# ---- Build stage ----
    FROM node:20-alpine AS build

    WORKDIR /app
    
    # Install dependencies
    COPY package*.json ./
    RUN npm install
    
    # Copy source code
    COPY . .
    
    # Build the app
    RUN npm run build
    
    # ---- Nginx stage ----
    FROM nginx:alpine
    
    # Copy build output to nginx html folder
    COPY --from=build /app/dist /usr/share/nginx/html
    
    # Expose app port
    EXPOSE 80
    
    CMD ["nginx", "-g", "daemon off;"]
    