const as = {
    login: "লগ ইন",
    signup: "ছাইন আপ",
    forgotPassword: "পাছৱৰ্ড পাহৰিলে নেকি?",
    welcome: "স্বাগতম, ব্যৱহাৰকাৰী!",
    logout: "লগ আউট",
    requiredField: "এইটো বাধ্যতামূলক।",
    invalidEmail: "অনুগ্ৰহ কৰি এটা বৈধ ইমেইল ঠিকনা লিখক।",
    name: "নাম",
    fullNamePlaceholder: "আপোনাৰ নাম লিখক",
    firstName: "প্ৰথম নাম",
    lastName: "উপাধি",
    mobileOrEmail: "ইমেইল আইডি বা মোবাইল নম্বৰ",
    firstNamePlaceHolder: "আপোনাৰ প্ৰথম নাম লিখক",
    lastNamePlaceHolder: "আপোনাৰ উপাধি লিখক",
    email: "ইমেইল",
    emailPlaceHolder: "আপোনাৰ ইমেইল লিখক",
    mobile: "মোবাইল নম্বৰ",
    mobilePlaceHolder: "আপোনাৰ মোবাইল নম্বৰ লিখক",
    receiveOTP: "আপুনি {0} ত এটা OTP লাভ কৰিব।",
    pleaseWait: "অনুগ্ৰহ কৰি অপেক্ষা কৰক...",
    fetchingDataFailedTitle: "অনুৰোধ কৰা তথ্য লাভ কৰিব পৰা নগ’ল।",
    failureMessage: "আপোনাৰ অনুৰোধ প্ৰক্ৰিয়াকৰণ কৰোঁতে আমি এটা ত্ৰুটিৰ সন্মুখীন হৈছোঁ।",
    technicalGlitch: "এয়া সাময়িক কাৰিকৰী বিজুতিৰ বাবে হ’ব পাৰে। কিছু সময়ৰ পিছত পুনৰ চেষ্টা কৰক।",
    contactSupport: "সহায়ৰ বাবে যোগাযোগ কৰক: <a href=\"{supportEmail}\" style=\"text-decoration:none; target=\"_blank\" rel=\"noopener noreferrer\" color: #27c0e0;\">{supportEmail}</a>।",
    register: "পঞ্জীয়ন কৰক",
    registering: "পঞ্জীয়ন হৈ আছে....",
    submitOTP: "OTP সত্যাপন কৰক",
    submittingOTP: "OTP সত্যাপন কৰা হৈছে....",
    otp: "OTP",
    otpPlaceholder: "OTP লিখক",
    enterOTP: "অনুগ্ৰহ কৰি ({value}) ত লাভ কৰা OTP টো লিখক।",
    signedUp: "আপুনি সফলতাৰে ছাইন আপ কৰিছে!",
    failedToSignUp: "ছাইন আপ কৰাত ব্যৰ্থ হৈছে।",
    loggedIn: "আপুনি সফলতাৰে লগ ইন কৰিছে!",
    failedToLogIn: "লগ ইন কৰাত ব্যৰ্থ হৈছে।",
    resendOTP: "OTP পুনৰ পঠিয়াওক",
    resendingOTP: "OTP পুনৰ পঠিয়াই থকা হৈছে....",
    password: "পাছৱৰ্ড",
    logingin: "লগ ইন হৈ আছে",
    passwordPlaceHolder: "আপোনাৰ পাছৱৰ্ড লিখক",
    otpChild1: "OTP ভুল হ’ব পাৰে",
    otpChild2: "OTP ৰ সময় উকলি যাব পাৰে।",
    otpChild3: "নেটৱৰ্কৰ সমস্যা হ’ব পাৰে।",
    otpChild4: "ছাৰ্ভাৰ ডাউন হ’ব পাৰে",
    passwordRequirementMsg: "আপোনাৰ একাউণ্ট সুৰক্ষিত কৰিবলৈ, অন্ততঃ আঠ (৮) টা আখৰৰ এটা পাছৱৰ্ড তৈয়াৰ কৰক, য’ত অন্তৰ্ভুক্ত থাকে:",
    passwordRequireMent: "পাছৱৰ্ডৰ প্ৰয়োজনীয়তাসমূহ",
    upperLowerCase: "বৰফলা আৰু সৰুফলা আখৰ",
    subHeadingIns: "শক্তিশালী পাছৱৰ্ডৰ বাবে, আপোনাৰ পাছৱৰ্ড নিম্নলিখিত চৰ্তসমূহৰ সৈতে সংগতিপূৰ্ণ হ’ব লাগে",
    minimum8Char: "অন্ততঃ ৮ টা আখৰ (বাধ্যতামূলক)",
    atLeastOneNumericals: "অন্ততঃ এটা সংখ্যা (বাধ্যতামূলক)",
    numericals: "সংখ্যা",
    specialChar: "বিশেষ চিহ্ন",
    oneUpperCase: "অন্ততঃ এটা বৰফলা আখৰ (বাধ্যতামূলক)",
    oneLowerCase: "অন্ততঃ এটা সৰুফলা আখৰ (বাধ্যতামূলক)",
    partnerCompanyName: "অংশীদাৰ কোম্পানীৰ নাম",
    atLeastOneSpecialChar: "অন্ততঃ এটা বিশেষ চিহ্ন (বাধ্যতামূলক)",
    skip: "এৰাই যাওক",
    confirmPassword: "পাছৱৰ্ড নিশ্চিত কৰক",
    setPassword: "পাছৱৰ্ড ছেট কৰক",
    accountInstruction: "একাউণ্টত প্ৰৱেশ কৰিবলৈ আৰু অৰ্ডাৰ পৰিচালনা কৰিবলৈ",
    aboutUs: "আমাৰ বিষয়ে",
    contactUs: "যোগাযোগ কৰক",
    profile: "প্ৰ’ফাইল",
    orders: "অৰ্ডাৰসমূহ",
    wishlist: "উইলিষ্ট",
    loginSignup: "লগ ইন/ছাইন আপ",
    welcome: "স্বাগতম",
    profileImgUpdated: "প্ৰ’ফাইল ছবি সফলতাৰে আপডেট কৰা হ’ল",
    save: "ছেভ কৰক",
    cancel: "বাতিল কৰক",
    adjustImage: "ছবি সঠিক কৰক",
    dragSqrToChangeImgSizePos: "আকাৰ আৰু স্থিতি সলনি কৰিবলৈ বৰ্গটো টানি আনক।",
    preview: "পূৰ্বদৰ্শন",
    imageCropped: "ক্ৰপ কৰা ছবি সফলতাৰে ছেভ কৰা হ’ল!",
    alternateMobile: "বিকল্প মোবাইল নম্বৰ",
    male: "পুৰুষ",
    female: "মহিলা",
    others: "অন্যান্য",
    genderLabel: "অনুগ্ৰহ কৰি আপোনাৰ লিংগ বাছনি কৰক:",
    dob: "জন্মৰ তাৰিখ",
    update: "আপডেট",
    changePassword: "পাছৱৰ্ড সলনি কৰক",
    updatePassword: "পাছৱৰ্ড আপডেট কৰক",
    updateProfile: "প্ৰ’ফাইল আপডেট কৰক",
    oldPassword: "পুৰণি পাছৱৰ্ড",
    confirmPasswordNotMatchPassword: "নিশ্চিত কৰা পাছৱৰ্ডটো পাছৱৰ্ডৰ সৈতে মিল খোৱা নাই।",
    passReqNotFulfil: "পাছৱৰ্ডৰ চৰ্তসমূহ পূৰণ হোৱা নাই।",
    passwordUpdated: "পাছৱৰ্ড সফলতাৰে আপডেট কৰা হ’ল!",
    profileUpdated: "প্ৰ’ফাইল সফলতাৰে আপডেট কৰা হ’ল!",
    pageNotFound: "পৃষ্ঠা পোৱা নগ’ল",
    brokenLinkMsg1: "আপুনি ক্লিক কৰা লিংকটো কাম নকৰা হ’ব পাৰে বা পৃষ্ঠাখন আঁতৰাই দিয়া হ’ব পাৰে।",
    brokenLinkMsg2: "মূল পৃষ্ঠালৈ যাওক বা সমস্যাটোৰ বিষয়ে আমাক জনাওক।",
    backToHome: "মূল পৃষ্ঠালৈ ঘূৰি যাওক",
    dashboard: "ডেশ্বব’ৰ্ড",
    pages: "পৃষ্ঠাসমূহ",
    inventory: "ইনভেণ্টৰী",
    customOrders: "কাষ্টম অৰ্ডাৰ",
    team: "টিম",
    customers: "গ্ৰাহকসকল",
    settings: "ছেটিংছ",
    messages: "মেছেজ",
    pendingOrders: "অসমাপ্ত অৰ্ডাৰ",
    completedOrders: "সম্পূৰ্ণ অৰ্ডাৰ",
    offers: "অফাৰসমূহ",
    id: "আইডি",
    brand: "ব্ৰেণ্ড",
    category: "শ্ৰেণী",
    price: "মূল্য",
    status: "স্থিতি",
    createdDate: "সৃষ্টিৰ তাৰিখ",
    updatedDate: "অন্তিম আপডেট",
    action: "কাৰ্য্য",
    productName: "সামগ্ৰীৰ নাম",
    size: "আকাৰ",
    color: "ৰং",
    sku: "SKU",
    stockQuantity: "পৰিমাণ",
    products: "সামগ্ৰীসমূহ",
    description: "বিৱৰণ",
    parent: "মূল (Parent)",
    namePlaceholder: "নাম লিখক",
    descriptionPlaceholder: "বিৱৰণ লিখক",
    categoryPlaceholder: "শ্ৰেণী বাছনি কৰক",
    categoryLevel: "শ্ৰেণী {0} স্তৰ ",
    at: "ত",
    modifiedOn: "পৰিৱৰ্তন কৰা হৈছে",
    today: "আজি",
    edit: "সম্পাদনা কৰক",
    delete: "ডিলিট কৰক",
    activated: "{entity} সক্ৰিয় কৰা হৈছে।",
    deactivated: "{entity} নিষ্ক্ৰিয় কৰা হৈছে।",
    yes: "হয়",
    no: "নহয়",
    confirm: "নিশ্চিত কৰক",
    deleteMsg: "আপুনি নিশ্চিতনে? আপুনি <b>{0}</b> {1} ডিলিট কৰিব বিচাৰে নেকি?",
    childrenOf: "ৰ সন্তানসকল ",
    page: "পৃষ্ঠা",
    add: "যোগ কৰক",
    deactivateFirst: "প্ৰথমে {entity} নিষ্ক্ৰিয় কৰক।",
    activeCantAction: "সক্ৰিয় {entity} ত {action} কৰিব নোৱাৰি।",
    entityIsActive: "<b>{0}</b> {entity} সক্ৰিয় হৈ আছে।",
    searchPlaceHolder: "{entity} সন্ধান কৰক...",
    copy: "কপি কৰক",
    deleted: "ডিলিট কৰা হ’ল",
    edited: "সম্পাদিত",
    product: "সামগ্ৰী",
    title: "শীৰ্ষক",
    titlePlaceholder: "শীৰ্ষক লিখক",
    image: "ছবি",
    material: "সামগ্ৰী (Material)",
    materialPlaceholder: "সামগ্ৰীৰ নাম লিখক",
    colorPlaceholder: "ৰং লিখক",
    skuPlaceholder: "এটা অনন্য SKU ক’ড লিখক",
    quantity: "পৰিমাণ",
    type: "প্ৰকাৰ",
    selectProductPlaceholder: "সামগ্ৰী বাছনি কৰক",
    sizeChart: "চাইজ চাৰ্ট",
    enterMeasure: "আপোনাৰ {0} জোখ লিখক",
    chest: "বুকু",
    hips: "কঁকালৰ তলৰ অংশ (Hips)",
    neck: " ডিঙি",
    sleeve: "হাত (Sleeve)",
    arm: "হাত",
    topLength: "ওপৰৰ দীঘ",
    shoulder: "কান্ধ",
    inseam: "ইনচিম",
    bottomLength: "তলৰ দীঘ",
    thigh: "উৰু",
    waist: "কঁকাল",
    topBody: "শৰীৰৰ ওপৰৰ অংশ",
    bottomBody: "শৰীৰৰ তলৰ অংশ",
    rank: "ৰেংক",
    sale: "বিক্ৰী",
    rental: "ভাড়া",
    selectRankPlaceholder: "ৰেংক বাছনি কৰক",
    mrp: "MRP",
    salePrice: "বিক্ৰী মূল্য",
    discount: "ৰেহাই",
    selectSizePlaceholder: "আকাৰ বাছনি কৰক",
    mrpPlaceholder: "MRP লিখক (₹)",
    salePricePlaceholder: "বিক্ৰী মূল্য লিখক (₹)",
    discountPlaceholder: "ৰেহাই লিখক (%)",
    quantityPlaceholder: "পৰিমাণ লিখক",
    saleOrRentPrice: "বিক্ৰী/ভাড়া মূল্য",
    security: "ছিউজৰিটি জমা (Security Deposit)",
    securityPlaceholder: "ঘূৰাই পোৱা ধন = জমা - (ভাড়াৰ মূল্য - ৰেহাই %)",
    size_Quant_Price: "আকাৰ - পৰিমাণ - বিক্ৰী মূল্য",
    view: "চাওক",
    webSettings: "ৱেব ছেটিংছ",
    siteUnderMaintenance: "ছাইট মেৰামতি চলি আছে",
    weWillGetbackShortly: "আমি অতি সোনকালে ঘূৰি আহিম। অনুগ্ৰহ কৰি কিছু সময় পিছত চেষ্টা কৰক।",
    reload: "ৰিলোড কৰক",
    enableWebsite: "ৱেবছাইট সক্ৰিয় বা নিষ্ক্ৰিয় কৰিবলৈ ক্লিক কৰক।",
    website: "ৱেবছাইট",
    switchOnOffWebsite: "ৱেবছাইট অন/অফ কৰক",
    webConfigs: "ৱেবছাইট কনফিগাৰেশ্যন",
    webTrendingBar: "ৱেবছাইট ট্ৰেণ্ডিং বাৰ",
    websiteId: "ৱেবছাইট আইডি",
    path: "পাথ (Path)",
    pathPlaceholder: "খুলিবলগীয়া পাথটো লিখক",
    homePage: "মূল পৃষ্ঠা",
    homePageCarousel: "মূল পৃষ্ঠাৰ কেৰুচেল",
    forPC: "PC ৰ বাবে:",
    forMobile: "মোবাইলৰ বাবে:",
    reset: "ৰিছেট কৰক",
    customFitting: "কাষ্টম ফিটিং",
    customDesigning: "কাষ্টম ডিজাইনিং",
    freeDelivery: "বিনামূলীয়া ডেলিভাৰী",
    assuredRefunds: "নিশ্চিত ৰিফাণ্ড",
    sizes: "আকাৰসমূহ",
    addresses: "ঠিকনাসমূহ",
    isTileVisible: "টাইল দৃশ্যমান হয়নে?",
    isTileVisibleGrid: "টাইল দৃশ্যমান",
    categories: "শ্ৰেণীসমূহ",
    mrpWithDots: "M.R.P",
    rtd: "পঠিয়াবলৈ সাজু",
    inclusiveTax: "সকলো কৰ অন্তৰ্ভুক্ত কৰি মূল্য",
    rentInclusiveTax: "সকলো কৰ অন্তৰ্ভুক্ত কৰি ভাড়া",
    purchase: "ক্ৰয় কৰক",
    rent: "ভাড়াত লওক",
    refundableSecurity: "ঘূৰাই পোৱা ছিকিউৰিটি জমা",
    securityDeposit: "ছিকিউৰিটি জমা",
    refundSecurity: "সামগ্ৰী ঘূৰাই দিয়াৰ পিছত, আপোনাৰ ছিকিউৰিটি জমা ঘূৰাই দিয়া হ’ব।",
    securityDepositDeduction: "আপুনি ডেলিভাৰী পোৱাৰ ৫ দিনৰ ভিতৰত সামগ্ৰী ঘূৰাই দিব পাৰে। তাৰ পিছত প্ৰতি ৫ দিনৰ বাবে আপোনাৰ ছিকিউৰিটি জমাৰ পৰা ভাড়াৰ পৰিমাণ কটা হ’ব।",
    sizeGuide: "চাইজ গাইড",
    customSize: "কাষ্টম চাইজ",
    loginToAddCustomSize: "কাষ্টম চাইজ যোগ কৰিবলৈ আৰু চাবলৈ লগ ইন/ছাইন আপ কৰক",
    yourCustomSizes: "আপোনাৰ কাষ্টম চাইজসমূহ",
    undoWishlistMsg: "আপুনি উইলিষ্টৰ পৰা <b>{name}</b> আঁতৰাইছে",
    undo: "পূৰ্বৰ অৱস্থালৈ যাওক (Undo)",
    textPlaceholder: "{0} লিখক",
    address: "ঠিকনা",
    fullName: "নাম",
    city: "চহৰ",
    country: "দেশ",
    pinCode: "পিন ক’ড",
    state: "ৰাজ্য",
    landmark: "লেণ্ডমাৰ্ক",
    streetAddress1: "ফ্লেট, ঘৰ নম্বৰ, বিল্ডিং, কোম্পানী, এপাৰ্টমেণ্ট",
    streetAddress2: "এৰিয়া, ৰাস্তা, ছেক্টৰ, গাঁও",
    defaultAddress: "ডিফল্ট ঠিকনা হিচাপে ছেট কৰক",
    setDefault: "ডিফল্ট হিচাপে ছেট কৰক",
    default: "ডিফল্ট",
    addToCart: "কাৰ্টত যোগ কৰক",
    buyNow: "এতিয়াই কিনক",
    total: "মুঠ",
    clearCart: "কাৰ্ট খালী কৰক",
    proceedToCheckout: "চেকআউটলৈ যাওক",
    shoppingCart: "শ্বপিং কাৰ্ট",
    loadingCart: "কাৰ্ট লোড হৈ আছে...",
    emptyCart: "আপোনাৰ কাৰ্ট খালী।",
    emptyWishlist: "আপোনাৰ উইলিষ্ট খালী।",
    deSelectAll: "সকলো বস্তু বাছনি বাতিল কৰক",
    invalidCoupon: "অবাস্তৱ কুপন ক’ড",
    couponApplied: "কুপন প্ৰয়োগ কৰা হ’ল: ",
    apply: "প্ৰয়োগ কৰক",
    freeCaps: "বিনামূলীয়া",
    deliveryCharges: "ডেলিভাৰী চাৰ্জ",
    subTotal: "উপ-মুঠ (SubTotal)",
    changeSize: "আকাৰ সলনি কৰক",
    moveToWishlist: "উইলিষ্টলৈ স্থানান্তৰ কৰক",
    share: "শ্বেয়াৰ কৰক",
    orderSummary: "অৰ্ডাৰ সাৰাংশ",
    coupon: "কুপন",
    itemsForPurchasing: "ক্ৰয়ৰ বাবে বাছনি কৰা সামগ্ৰী",
    itemsForRenting: "ভাড়াৰ বাবে বাছনি কৰা সামগ্ৰী",
    itemsSelected: "বাছনি কৰা সামগ্ৰী",
    applyCoupon: "কুপন প্ৰয়োগ কৰক",
    undoCartMsg: 'কাৰ্টৰ পৰা <strong>{name}</strong> আঁতৰোৱা হ’ল। ',
    itemRestored: "সামগ্ৰী কাৰ্টলৈ ঘূৰাই অনা হ’ল",
    selectAll: "সকলো বাছনি কৰক",
    itemMovedToWishlist: "সামগ্ৰী উইলিষ্টলৈ স্থানান্তৰ কৰা হ’ল।",
    itemRemoved: "সামগ্ৰী কাৰ্টৰ পৰা আঁতৰোৱা হ’ল",
    addedToCart: "সামগ্ৰী কাৰ্টত যোগ কৰা হ’ল",
    itemAddedToWishlist: "সামগ্ৰী উইলিষ্টত যোগ কৰা হ’ল",
    itemRemovedFromWishlist: "সামগ্ৰী উইলিষ্টৰ পৰা আঁতৰোৱা হ’ল",
    proceedToBuy: "ক্ৰয় কৰিবলৈ আগবাঢ়ক",
    change: "সলনি কৰক",
    checkout: "চেকআউট",
    deliverHere: "ইয়াত ডেলিভাৰী কৰক",
    selectDeliveryAddress: "ডেলিভাৰী ঠিকনা বাছনি কৰক",
    selectedDeliveryAddress: "বাছনি কৰা ডেলিভাৰী ঠিকনা",
    inventoryType: "ইনভেণ্টৰী প্ৰকাৰ",
    currentlyDefaultAddress: "ডিফল্ট ঠিকনা",
    chosenAddressUpdated: "বাছনি কৰা ঠিকনা সফলতাৰে আপডেট কৰা হ’ল।",
    draftUpdated: "অৰ্ডাৰৰ সবিশেষ সফলতাৰে আপডেট কৰা হ’ল।",
    proceedToCheckout: "চেকআউটলৈ আগবঢ়া হ’ল।",
    deliveringTo: "লৈ ডেলিভাৰী কৰা হৈছে",
    addNew: "নতুন যোগ কৰক",
    itemsInOrder: "অৰ্ডাৰত থকা সামগ্ৰী",
    shipTogether: "সকলো সামগ্ৰী একেলগে পঠিয়াওক",
    shipAsap: "প্ৰতিটো সামগ্ৰী প্ৰস্তুত হোৱাৰ লগে লগে পঠিয়াওক",
    shipItems: "আপুনি আপোনাৰ অৰ্ডাৰ কেতিয়া পঠিয়াব বিচাৰে?",
    shipItemsForOrder: "{user} এ অৰ্ডাৰটো কেতিয়া পঠিয়াব বিচাৰে?",
    orderPlacedTitle: "ধন্যবাদ, আপোনাৰ অৰ্ডাৰ সফলতাৰে গ্ৰহণ কৰা হৈছে!",
    orderConfirmationSent: "আপোনাৰ ইমেইললৈ এটা নিশ্চিতকৰণ বাৰ্তা পঠোৱা হৈছে।",
    orderId: "অৰ্ডাৰ আইডি",
    itemsInTheOrder: "অৰ্ডাৰত থকা সামগ্ৰী",
    viewOrders: "আপোনাৰ অৰ্ডাৰসমূহ চাওক",
    viewAllOrders: "সকলো অৰ্ডাৰ চাওক",
    continueShopping: "শ্বপিং অব্যাহত ৰাখক",
    orderDetails: "অৰ্ডাৰৰ সবিশেষ",
    appliedCoupon: "প্ৰয়োগ কৰা কুপন",
    orderPlacedOn: "অৰ্ডাৰ দিয়াৰ তাৰিখ",
    shipTo: "লৈ পঠিয়াওক",
    noOrdersFound: "কোনো অৰ্ডাৰ পোৱা নগ’ল",
    yourOrders: "আপোনাৰ অৰ্ডাৰসমূহ",
    paymentMode: "পেমেন্ট মোড",
    paymentMethod: "পেমেন্ট পদ্ধতি",
    all: "সকলো",
    pending: "অসমাপ্ত (Pending)",
    shipped: "পঠিওৱা হ’ল",
    delivered: "ডেলিভাৰী কৰা হ’ল",
    cancelled: "বাতিল কৰা হ’ল",
    allOrders: "সকলো অৰ্ডাৰ",
    newOrders: "নতুন অৰ্ডাৰ",
    statusMessages: {
      forOrder: {
        forManager: {
          draft: "অৰ্ডাৰটো ড্ৰাফ্ট অৱস্থাত আছে আৰু এতিয়ালৈকে প্লেচ কৰা হোৱা নাই।",
          pending: "পেমেন্ট বাকী আছে।",
          placed: "অৰ্ডাৰ প্লেচ কৰা হৈছে আৰু আপোনাৰ নিশ্চিতকৰণৰ বাবে অপেক্ষা কৰি আছে।",
          confirmed: "আপুনি অৰ্ডাৰটো নিশ্চিত কৰিছে।",
          payment_failed: "পেমেন্ট ব্যৰ্থ হৈছে।",
          in_process: "অৰ্ডাৰটো আপোনাৰ দ্বাৰা প্ৰক্ৰিয়াকৰণ কৰা হৈছে।",
          ready_to_dispatch: "অৰ্ডাৰটো পঠিয়াবলৈ সাজু।",
          shipped: "অৰ্ডাৰটো পঠিওৱা হৈছে।",
          in_transit: "অৰ্ডাৰটো বাটত আছে।",
          delivered: "অৰ্ডাৰটো ডেলিভাৰী কৰা হৈছে।",
          cancelled: "অৰ্ডাৰটো বাতিল কৰা হৈছে।",
          cancellation_requested: "ব্যৱহাৰকাৰীয়ে বাতিলৰ অনুৰোধ কৰিছে।",
          cancellation_rejected: "আপুনি বাতিলৰ অনুৰোধ প্ৰত্যাখ্যান কৰিছে।",
          cancellation_refunded: "অৰ্ডাৰটো বাতিল কৰা হৈছে আৰু ধন ঘূৰাই দিয়া হৈছে।",
          return_requested: "অৰ্ডাৰৰ বাবে ঘূৰাই দিয়াৰ অনুৰোধ।",
          return_rejected: "আপুনি ঘূৰাই দিয়াৰ অনুৰোধ প্ৰত্যাখ্যান কৰিছে।",
          returned: "অৰ্ডাৰটো ঘূৰাই দিয়া হৈছে।",
          return_refunded: "ঘূৰাই দিয়াৰ পিছত ধন ঘূৰাই দিয়া হৈছে।",
          refunded: "ধন ঘূৰাই দিয়া হৈছে।",
          rto_requested: "আপোনাৰ দ্বাৰা RTO অনুৰোধ কৰা হৈছে।",
          rto_rejected: "আপুনি RTO অনুৰোধ প্ৰত্যাখ্যান কৰিছে।",
          rto_approved: "আপুনি RTO অনুৰোধ অনুমোদন কৰিছে।",
          rto_in_progress: "RTO প্ৰক্ৰিয়াত আছে।",
          rto_delivered: "RTO ৰ দ্বাৰা অৰ্ডাৰটো আপোনাক ঘূৰাই দিয়া হৈছে।",
          rto_verified: "RTO সামগ্ৰীসমূহ আপোনাৰ দ্বাৰা পৰীক্ষা কৰা হৈছে।",
          rto_refunded: "RTO ৰ পিছত গ্ৰাহকক ধন ঘূৰাই দিয়া হৈছে।"
        },
        forUser: {
          draft: "আপোনাৰ অৰ্ডাৰ চেকআউটত আছে কিন্তু এতিয়ালৈকে প্লেচ কৰা হোৱা নাই।",
          pending: "পেমেন্ট বাকী আছে। অনুগ্ৰহ কৰি আপোনাৰ পেমেন্ট সম্পূৰ্ণ কৰক।",
          placed: "আপোনাৰ অৰ্ডাৰ প্লেচ কৰা হৈছে আৰু নিশ্চিতকৰণৰ বাবে অপেক্ষা কৰি আছে।",
          confirmed: "আপোনাৰ অৰ্ডাৰটো বিক্ৰেতাই নিশ্চিত কৰিছে।",
          payment_failed: "পেমেন্ট ব্যৰ্থ হৈছে। অনুগ্ৰহ কৰি পুনৰ চেষ্টা কৰক।",
          in_process: "আপোনাৰ অৰ্ডাৰটো বিক্ৰেতাৰ দ্বাৰা প্ৰক্ৰিয়াকৰণ কৰা হৈছে।",
          ready_to_dispatch: "আপোনাৰ অৰ্ডাৰটো পঠিয়াবলৈ সাজু।",
          shipped: "আপোনাৰ অৰ্ডাৰটো পঠিওৱা হৈছে।",
          in_transit: "আপোনাৰ অৰ্ডাৰটো বাটত আছে।",
          delivered: "আপোনাৰ অৰ্ডাৰটো ডেলিভাৰী কৰা হৈছে।",
          cancelled: "আপোনাৰ অৰ্ডাৰটো বাতিল কৰা হৈছে।",
          cancellation_requested: "আপুনি এই অৰ্ডাৰটো বাতিল কৰিবলৈ অনুৰোধ কৰিছে।",
          cancellation_rejected: "আপোনাৰ বাতিলৰ অনুৰোধ প্ৰত্যাখ্যান কৰা হৈছে।",
          cancellation_refunded: "আপোনাৰ বাতিল গ্ৰহণ কৰা হৈছে আৰু ধন ঘূৰাই দিয়া হৈছে।",
          return_requested: "আপোনাৰ অৰ্ডাৰৰ বাবে ঘূৰাই দিয়াৰ অনুৰোধ জমা দিয়া হৈছে।",
          return_rejected: "আপোনাৰ ঘূৰাই দিয়াৰ অনুৰোধ প্ৰত্যাখ্যান কৰা হৈছে।",
          returned: "আপোনাৰ অৰ্ডাৰটো ঘূৰাই দিয়া হৈছে।",
          return_refunded: "ঘূৰাই দিয়াৰ পিছত আপোনাৰ ধন ঘূৰাই দিয়া হৈছে।",
          refunded: "আপোনাৰ ধন ঘূৰাই দিয়া হৈছে।",
          rto_requested: "অৰ্ডাৰৰ বাবে আপুনি/বিক্ৰেতাই RTO অনুৰোধ কৰিছে।",
          rto_rejected: "বিক্ৰেতাই RTO অনুৰোধ প্ৰত্যাখ্যান কৰিছে।",
          rto_approved: "বিক্ৰেতাই এই অৰ্ডাৰৰ বাবে RTO অনুমোদন কৰিছে।",
          rto_in_progress: "আপোনাৰ অৰ্ডাৰটো RTO ৰ বাটত আছে।",
          rto_delivered: "RTO ৰ দ্বাৰা আপোনাৰ অৰ্ডাৰটো বিক্ৰেতাক ঘূৰাই দিয়া হৈছে।",
          rto_verified: "আপোনাৰ ঘূৰাই দিয়া অৰ্ডাৰটো বিক্ৰেতাই পৰীক্ষা কৰিছে।",
          rto_refunded: "RTO ৰ পিছত আপোনাক ধন ঘূৰাই দিয়া হৈছে।"
        }
      },
      forItem: {
        forManager: {
          draft: "সামগ্ৰীটো অৰ্ডাৰ ড্ৰাফ্টত যোগ কৰা হৈছে আৰু এতিয়ালৈকে প্লেচ কৰা হোৱা নাই।",
          pending: "এই সামগ্ৰীৰ বাবে পেমেন্ট বাকী আছে।",
          placed: "সামগ্ৰীটো প্লেচ কৰা হৈছে আৰু আপোনাৰ নিশ্চিতকৰণৰ বাবে অপেক্ষা কৰি আছে।",
          confirmed: "আপুনি এই সামগ্ৰীটো নিশ্চিত কৰিছে।",
          payment_failed: "এই সামগ্ৰীৰ বাবে পেমেন্ট ব্যৰ্থ হৈছে।",
          in_process: "সামগ্ৰীটো আপোনাৰ দ্বাৰা প্ৰক্ৰিয়াকৰণ কৰা হৈছে।",
          ready_to_dispatch: "সামগ্ৰীটো পঠিয়াবলৈ সাজু।",
          shipped: "সামগ্ৰীটো পঠিওৱা হৈছে।",
          in_transit: "সামগ্ৰীটো বাটত আছে।",
          delivered: "সামগ্ৰীটো ডেলিভাৰী কৰা হৈছে।",
          cancelled: "এই সামগ্ৰীটো বাতিল কৰা হৈছে।",
          cancellation_requested: "ব্যৱহাৰকাৰীয়ে এই সামগ্ৰীৰ বাবে বাতিলৰ অনুৰোধ কৰিছে।",
          cancellation_rejected: "আপুনি এই সামগ্ৰীৰ বাবে বাতিলৰ অনুৰোধ প্ৰত্যাখ্যান কৰিছে।",
          cancellation_refunded: "এই সামগ্ৰীটো বাতিল কৰা হৈছে আৰু ধন ঘূৰাই দিয়া হৈছে।",
          return_requested: "ব্যৱহাৰকাৰীয়ে এই সামগ্ৰীৰ বাবে ঘূৰাই দিয়াৰ অনুৰোধ কৰিছে।",
          return_rejected: "আপুনি এই সামগ্ৰীৰ বাবে ঘূৰাই দিয়াৰ অনুৰোধ প্ৰত্যাখ্যান কৰিছে।",
          returned: "সামগ্ৰীটো ঘূৰাই দিয়া হৈছে।",
          return_refunded: "এই ঘূৰাই দিয়া সামগ্ৰীৰ বাবে ধন ঘূৰাই দিয়া হৈছে।",
          refunded: "এই সামগ্ৰীৰ বাবে ধন ঘূৰাই দিয়া হৈছে।",
          rto_requested: "এই সামগ্ৰীৰ বাবে RTO অনুৰোধ কৰা হৈছে।",
          rto_rejected: "আপুনি এই সামগ্ৰীৰ বাবে RTO অনুৰোধ প্ৰত্যাখ্যান কৰিছে।",
          rto_approved: "আপুনি এই সামগ্ৰীৰ বাবে RTO অনুৰোধ অনুমোদন কৰিছে।",
          rto_in_progress: "এই সামগ্ৰীৰ বাবে RTO প্ৰক্ৰিয়াত আছে।",
          rto_delivered: "এই সামগ্ৰীটো আপোনাক ঘূৰাই দিয়া হৈছে।",
          rto_verified: "ঘূৰাই পোৱা এই সামগ্ৰীটো পৰীক্ষা কৰা হৈছে।",
          rto_refunded: "RTO ৰ পিছত এই সামগ্ৰীৰ বাবে ধন ঘূৰাই দিয়া হৈছে।"
        },
        forUser: {
          draft: "এই সামগ্ৰীটো চেকআউটত আছে কিন্তু এতিয়ালৈকে প্লেচ কৰা হোৱা নাই।",
          pending: "এই সামগ্ৰীৰ বাবে পেমেন্ট বাকী আছে। অনুগ্ৰহ কৰি আপোনাৰ পেমেন্ট সম্পূৰ্ণ কৰক।",
          placed: "এই সামগ্ৰীটো প্লেচ কৰা হৈছে আৰু নিশ্চিতকৰণৰ বাবে অপেক্ষা কৰি আছে।",
          confirmed: "এই সামগ্ৰীটো বিক্ৰেতাই নিশ্চিত কৰিছে।",
          payment_failed: "এই সামগ্ৰীৰ বাবে পেমেন্ট ব্যৰ্থ হৈছে। অনুগ্ৰহ কৰি পুনৰ চেষ্টা কৰক।",
          in_process: "এই সামগ্ৰীটো বিক্ৰেতাৰ দ্বাৰা প্ৰক্ৰিয়াকৰণ কৰা হৈছে।",
          ready_to_dispatch: "এই সামগ্ৰীটো পঠিয়াবলৈ সাজু।",
          shipped: "এই সামগ্ৰীটো পঠিওৱা হৈছে।",
          in_transit: "এই সামগ্ৰীটো বাটত আছে।",
          delivered: "এই সামগ্ৰীটো ডেলিভাৰী কৰা হৈছে।",
          cancelled: "এই সামগ্ৰীটো বাতিল কৰা হৈছে।",
          cancellation_requested: "আপুনি এই সামগ্ৰীটো বাতিল কৰিবলৈ অনুৰোধ কৰিছে।",
          cancellation_rejected: "এই সামগ্ৰীৰ বাবে আপোনাৰ বাতিলৰ অনুৰোধ প্ৰত্যাখ্যান কৰা হৈছে।",
          cancellation_refunded: "এই সামগ্ৰীৰ বাবে আপোনাৰ বাতিল গ্ৰহণ কৰা হৈছে আৰু ধন ঘূৰাই দিয়া হৈছে।",
          return_requested: "এই সামগ্ৰীৰ বাবে ঘূৰাই দিয়াৰ অনুৰোধ জমা দিয়া হৈছে।",
          return_rejected: "এই সামগ্ৰীৰ বাবে আপোনাৰ ঘূৰাই দিয়াৰ অনুৰোধ প্ৰত্যাখ্যান কৰা হৈছে।",
          returned: "এই সামগ্ৰীটো ঘূৰাই দিয়া হৈছে।",
          return_refunded: "এই সামগ্ৰীটো ঘূৰাই দিয়াৰ পিছত আপোনাৰ ধন ঘূৰাই দিয়া হৈছে।",
          refunded: "এই সামগ্ৰীৰ বাবে আপোনাৰ ধন ঘূৰাই দিয়া হৈছে।",
          rto_requested: "এই সামগ্ৰীৰ বাবে আপুনি/বিক্ৰেতাই RTO অনুৰোধ কৰিছে।",
          rto_rejected: "বিক্ৰেতাই এই সামগ্ৰীৰ বাবে RTO অনুৰোধ প্ৰত্যাখ্যান কৰিছে।",
          rto_approved: "বিক্ৰেতাই এই সামগ্ৰীৰ বাবে RTO অনুমোদন কৰিছে।",
          rto_in_progress: "এই সামগ্ৰীটো RTO হৈ আছে।",
          rto_delivered: "এই সামগ্ৰীটো বিক্ৰেতাক ঘূৰাই দিয়া হৈছে।",
          rto_verified: "ঘূৰাই অহা এই সামগ্ৰীটো বিক্ৰেতাই পৰীক্ষা কৰিছে।",
          rto_refunded: "RTO ৰ পিছত এই সামগ্ৰীৰ বাবে আপোনাক ধন ঘূৰাই দিয়া হৈছে।"
        }
      }
    },
    statusColors: {
      draft: "var(--secondarytext-color)",
      pending: "var(--warning-color)",
      placed: "var(--info-color)",
      confirmed: "var(--success-color)",
      payment_failed: "var(--danger-color)",
      in_process: "var(--infolight-color)",
      ready_to_dispatch: "purple",
      shipped: "blue",
      in_transit: "var(--primarylight-color)",
      delivered: "var(--successdark-color)",
      cancellation_requested: "orange",
      cancelled: "var(--dangerlight-color)",
      cancellation_rejected: "red",
      cancellation_refunded: "var(--success-color)",
      return_requested: "var(--secondary-color)",
      returned: "var(--dangerlight-color)",
      return_rejected: "var(--warning-color)",
      return_refunded: "var(--success-color)",
      refunded: "var(--success-color)",
      rto_requested: "var(--warningdark-color)",
      rto_rejected: "red",
      rto_approved: "var(--success-color)",
      rto_in_progress: "blueviolet",
      rto_delivered: "var(--info-color)",
      rto_verified: "var(--successdark-color)",
      rto_refunded: "var(--success-color)"
    },
    orderPages: {
      allOrders: {
        title: "সকলো অৰ্ডাৰ",
        statuses: ["ALL"]
      },
      pendingOrders: {
        title: "অসমাপ্ত অৰ্ডাৰ",
        statuses: ["PENDING"]
      },
      newOrders: {
        title: "নতুন অৰ্ডাৰ",
        statuses: ["PLACED"]
      },
      confirmedOrders: {
        title: "নিশ্চিত অৰ্ডাৰ",
        statuses: ["CONFIRMED"]
      },
      processingOrders: {
        title: "প্ৰক্ৰিয়াকৰণ হৈ থকা অৰ্ডাৰ",
        statuses: ["IN_PROCESS"]
      },
      readyToDispatchOrders: {
        title: "পঠিয়াবলৈ সাজু অৰ্ডাৰ",
        statuses: ["READY_TO_DISPATCH"]
      },
      onTheWayOrders: {
        title: "বাটত থকা অৰ্ডাৰ",
        statuses: ["SHIPPED", "IN_TRANSIT"]
      },
      deliveredOrders: {
        title: "ডেলিভাৰী কৰা অৰ্ডাৰ",
        statuses: ["DELIVERED"]
      },
      cancelled: {
        title: "বাতিল অৰ্ডাৰ",
        statuses: ["CANCELLED"]
      },
      returns: {
        title: "ৰিটৰ্নসমূহ",
        statuses: ["ALLRETURNS"],
        showOrderStatuses: false
      },
      cancellation_requested: {
        title: "বাতিলৰ অনুৰোধ কৰা অৰ্ডাৰ",
        statuses: ["CANCELLATION_REQUESTED"]
      },
      cancellation_rejected: {
        title: "বাতিল প্ৰত্যাখ্যান কৰা অৰ্ডাৰ",
        statuses: ["CANCELLATION_REJECTED"]
      },
      cancellation_refunded: {
        title: "বাতিল কৰি ৰিফাণ্ড দিয়া অৰ্ডাৰ",
        statuses: ["CANCELLATION_REFUNDED"]
      },
      return_requested: {
        title: "ঘূৰাই দিয়াৰ অনুৰোধ কৰা অৰ্ডাৰ",
        statuses: ["RETURN_REQUESTED"]
      },
      returned: {
        title: "ঘূৰাই দিয়া অৰ্ডাৰ",
        statuses: ["RETURNED"]
      },
      return_rejected: {
        title: "ঘূৰাই দিয়াৰ অনুৰোধ প্ৰত্যাখ্যান কৰা অৰ্ডাৰ",
        statuses: ["RETURN_REJECTED"]
      },
      return_refunded: {
        title: "ঘূৰাই দিয়াৰ বাবে ৰিফাণ্ড দিয়া অৰ্ডাৰ",
        statuses: ["RETURN_REFUNDED"]
      },
      rto_requested: {
        title: "RTO অনুৰোধ কৰা অৰ্ডাৰ",
        statuses: ["RTO_REQUESTED"]
      },
      rto_rejected: {
        title: "RTO প্ৰত্যাখ্যান কৰা অৰ্ডাৰ",
        statuses: ["RTO_REJECTED"]
      },
      rto_approved: {
        title: "RTO অনুমোদন কৰা অৰ্ডাৰ",
        statuses: ["RTO_APPROVED"]
      },
      rto_in_progress: {
        title: "RTO চলি থকা অৰ্ডাৰ",
        statuses: ["RTO_IN_PROGRESS"]
      },
      rto_delivered: {
        title: "RTO ডেলিভাৰী কৰা অৰ্ডাৰ",
        statuses: ["RTO_DELIVERED"]
      },
      rto_verified: {
        title: "RTO পৰীক্ষা কৰা অৰ্ডাৰ",
        statuses: ["RTO_VERIFIED"]
      },
      rto_refunded: {
        title: "RTO ৰিফাণ্ড দিয়া অৰ্ডাৰ",
        statuses: ["RTO_REFUNDED"]
      }
    },
    confirmedOrders: "নিশ্চিত অৰ্ডাৰ",
    processingOrders: "প্ৰক্ৰিয়াকৰণ হৈ থকা অৰ্ডাৰ",
    readyToDispatchOrders: "পঠিয়াবলৈ সাজু অৰ্ডাৰ",
    onTheWayOrders: "বাটত থকা অৰ্ডাৰ",
    deliveredOrders: "ডেলিভাৰী কৰা অৰ্ডাৰ",
    cancelled_orders: "বাতিল অৰ্ডাৰ",
    cancellation_requested_orders: "বাতিলৰ অনুৰোধ কৰা অৰ্ডাৰ",
    return_requested_orders: "ঘূৰাই দিয়াৰ অনুৰোধ কৰা অৰ্ডাৰ",
    return_refunded_orders: "ঘূৰাই দিয়াৰ বাবে ৰিফাণ্ড দিয়া অৰ্ডাৰ",
    returns: "ৰিটৰ্নসমূহ",
    returned_orders: "ঘূৰাই দিয়া অৰ্ডাৰ",
    return_rejected_orders: "ঘূৰাই দিয়াৰ অনুৰোধ প্ৰত্যাখ্যান কৰা অৰ্ডাৰ",
    cancellation_rejected_orders: "বাতিল প্ৰত্যাখ্যান কৰা অৰ্ডাৰ",
    cancellation_refunded_orders: "বাতিল কৰি ৰিফাণ্ড দিয়া অৰ্ডাৰ",
    rto_requested_orders: "RTO অনুৰোধ কৰা অৰ্ডাৰ",
    rto_rejected_orders: "RTO প্ৰত্যাখ্যান কৰা অৰ্ডাৰ",
    rto_approved_orders: "RTO অনুমোদন কৰা অৰ্ডাৰ",
    rto_in_progress_orders: "RTO চলি থকা অৰ্ডাৰ",
    rto_delivered_orders: "RTO ডেলিভাৰী কৰা অৰ্ডাৰ",
    rto_verified_orders: "RTO পৰীক্ষা কৰা অৰ্ডাৰ",
    rto_refunded_orders: "RTO ৰিফাণ্ড দিয়া অৰ্ডাৰ",
    moreOptions: "অধিক বিকল্প",
    details: "সবিশেষ",
    viewProductPage: "সামগ্ৰীৰ পৃষ্ঠা চাওক",
    viewSize: "আকাৰ চাওক",
    trackStatus: "স্থিতি ট্ৰেক কৰক",
    auditTrail: "অডিট ট্ৰেইল",
    changedFrom: "ৰ পৰা সলনি কৰা হৈছে",
    changedTo: "লৈ সলনি কৰা হৈছে",
    entityType: "এণ্টিটি প্ৰকাৰ",
    entityId: "এণ্টিটি আইডি",
    performedBy: "কোনে কৰিছে",
    timestamp: "সময়",
    trackingDetails: "ট্ৰেকিং সবিশেষ",
    noDetailsFound: "কোনো তথ্য পোৱা নগ’ল",
    userDetails: 'ব্যৱহাৰকাৰীৰ সবিশেষ',
    followUs: "আমাক ফলো কৰক",
    allRightsReserved: "সকলো অধিকাৰ সংৰক্ষিত",
    fastAndSecured: "দ্ৰুত আৰু সুৰক্ষিত পেমেন্ট বিকল্প",
    company: "কোম্পানী",
    myAccount: "মোৰ একাউণ্ট",
    home: "মূল পৃষ্ঠা",
    account: "একাউণ্ট",
    search: "সন্ধান কৰক",
    cart: "কাৰ্ট",
    language: "ভাষা",
    somethingWentWrong: "কিবা ভুল হ’ল!",
    note: "টোকা",
    notAllowed1: "আপোনাক এই এপ্লিকেশ্যনত লগ ইন কৰিবলৈ অনুমতি দিয়া হোৱা নাই",
    notAllowed2: "কেৱল এডমিন আৰু মেনেজাৰৰ এইটোত প্ৰৱেশাধিকাৰ আছে",
    notAllowed3: "যদি আপুনি তেওঁলোকৰ মাজৰ এজন আৰু তথাপিও প্ৰৱেশ কৰিব পৰা নাই তেন্তে এডমিনৰ সৈতে যোগাযোগ কৰক",
    logOutAndBackToHome: "লগ আউট কৰক আৰু মূল পৃষ্ঠালৈ যাওক",
    whatsAppUs: "আমাক হোৱাটছএপ কৰক",
    ourContactDetails: "আমাৰ যোগাযোগৰ ঠিকনা",
    workingHours: "কাম কৰাৰ সময়",
    instagram: "ইনষ্টাগ্ৰাম",
    facebook: "ফেচবুক",
    x: "X (টুইটাৰ)",
    threads: "থ্ৰেডছ",
    youtube: "ইউটিউব",
    pinterest: "পিন্টাৰেষ্ট",
    quotaUsage: "মেইল/SMS কোটা ব্যৱহাৰ",
    used: "ব্যৱহাৰ কৰা হ’ল",
    remaining: "বাকী আছে",
    totalQuota: "মুঠ কোটা",
    sms: "SMS",
    whatsapp: "হোৱাটছএপ",
    brevo: "ব্ৰেভো",
    count: "গণনা",
    date: "তাৰিখ",
    gmail: "জি-মেইল",
    quota: "কোটা",
    teamUsers: "টিম",
    member: "সদস্য",
    customer: "গ্ৰাহক",
    customers: "গ্ৰাহকসকল",
    profileImage: "প্ৰ’ফাইল ছবি",
    gender: "লিঙ্গ",
    role: "ভূমিকা (Role)",
    activatedText: "সক্ৰিয় কৰা হৈছে",
    selectRolePlaceholder: "ভূমিকা বাছনি কৰক",
    accountActiveLabel: "অনুগ্ৰহ কৰি বাছনি কৰক যে ব্যৱহাৰকাৰীৰ একাউণ্ট সক্ৰিয়/নিষ্ক্ৰিয় হ’ব লাগে নেকি:",
    user: "ব্যৱহাৰকাৰী",
    actions: "কাৰ্য্যসমূহ",
    setAsDiscontinued: "বন্ধ কৰা (Discontinued) বুলি ছেট কৰক",
    resetToDefaultPassword: "ডিফল্ট পাছৱৰ্ডলৈ ৰিছেট কৰক",
    confirmMsg: "আপুনি নিশ্চিতনে? আপুনি <b>{0}</b> {1} ক {2} কৰিব বিচাৰে নেকি?",
    discontinued: "বন্ধ কৰা হ’ল",
    base: "বেছ (Base)",
    setActive: "সক্ৰিয় বুলি ছেট কৰক",
    refresh: "ৰিফ্ৰেছ কৰক",
};

export default as;