const bn = {
    login: "লগ ইন করুন",
    signup: "সাইন আপ করুন",
    forgotPassword: "পাসওয়ার্ড ভুলে গেছেন?",
    welcomeUser: "স্বাগতম, ব্যবহারকারী!",
    logout: "লগ আউট",
    requiredField: "এই ক্ষেত্রটি আবশ্যক।",
    invalidEmail: "অনুগ্রহ করে একটি বৈধ ইমেল ঠিকানা লিখুন।",
    name: "নাম",
    fullNamePlaceholder: "আপনার নাম লিখুন",
    firstName: "প্রথম নাম",
    lastName: "শেষ নাম",
    mobileOrEmail: "ইমেল আইডি বা মোবাইল নম্বর",
    firstNamePlaceHolder: "আপনার প্রথম নাম লিখুন",
    lastNamePlaceHolder: "আপনার শেষ নাম লিখুন",
    email: "ইমেল",
    emailPlaceHolder: "আপনার ইমেল লিখুন",
    mobile: "মোবাইল নম্বর",
    mobilePlaceHolder: "আপনার মোবাইল নম্বর লিখুন",
    receiveOTP: "আপনি {0}-এ এই OTP পাবেন।",
    pleaseWait: "দয়া করে অপেক্ষা করুন...",
    fetchingDataFailedTitle: "অনুরোধ করা ডেটা পেতে অক্ষম।",
    failureMessage: "আমাদের অনুরোধ প্রক্রিয়া করার সময় একটি ত্রুটি ঘটেছে।",
    technicalGlitch: "এটি অস্থায়ী প্রযুক্তিগত ত্রুটির কারণে হতে পারে। কিছুক্ষণ পরে আবার চেষ্টা করুন।",
    contactSupport: "<a href=\"{supportEmail}\" style=\"text-decoration:none; target=\"_blank\" rel=\"noopener noreferrer\" color: #27c0e0;\">{supportEmail}</a>-এ যোগাযোগ করুন।",
    register: "নিবন্ধন করুন",
    registering: "নিবন্ধন করা হচ্ছে....",
    submitOTP: "OTP যাচাই করুন",
    submittingOTP: "OTP যাচাই করা হচ্ছে....",
    otp: "ওটিপি (OTP)",
    otpPlaceholder: "OTP লিখুন",
    enterOTP: "অনুগ্রহ করে OTP লিখুন যা আপনি ({value})-তে পেয়েছেন।",
    signedUp: "আপনি সফলভাবে সাইন আপ করেছেন!",
    failedToSignUp: "সাইন আপ করতে ব্যর্থ।",
    loggedIn: "আপনি সফলভাবে লগ ইন করেছেন!",
    failedToLogIn: "লগ ইন করতে ব্যর্থ।",
    resendOTP: "OTP পুনরায় পাঠান",
    resendingOTP: "OTP পুনরায় পাঠানো হচ্ছে....",
    password: "পাসওয়ার্ড",
    logingin: "লগ ইন হচ্ছে",
    passwordPlaceHolder: "আপনার পাসওয়ার্ড লিখুন",
    otpChild1: "OTP ভুল হতে পারে",
    otpChild2: "OTP-এর মেয়াদ শেষ হয়ে গেছে।",
    otpChild3: "নেটওয়ার্কে সমস্যা হতে পারে।",
    otpChild4: "সার্ভার ডাউন হতে পারে",
    passwordRequirementMsg: "আপনার অ্যাকাউন্টের সুরক্ষার জন্য, কমপক্ষে আট (8) অক্ষরের একটি পাসওয়ার্ড তৈরি করুন, যাতে অন্তর্ভুক্ত থাকবে",
    passwordRequireMent: "পাসওয়ার্ডের প্রয়োজনীয়তা",
    upperLowerCase: "বড় এবং ছোট হাতের অক্ষর",
    subHeadingIns: "শক্তিশালী পাসওয়ার্ডের জন্য, আপনার পাসওয়ার্ড নিম্নলিখিত পয়েন্টগুলি মেনে চলা উচিত",
    minimum8Char: "কমপক্ষে 8 অক্ষর (আবশ্যক)",
    atLeastOneNumericals: "কমপক্ষে একটি সংখ্যা (আবশ্যক)",
    numericals: "সংখ্যা",
    specialChar: "বিশেষ অক্ষর",
    oneUpperCase: "কমপক্ষে একটি বড় হাতের অক্ষর (আবশ্যক)",
    oneLowerCase: "কমপক্ষে একটি ছোট হাতের অক্ষর (আবশ্যক)",
    partnerCompanyName: "অংশীদার কোম্পানির নাম",
    atLeastOneSpecialChar: "কমপক্ষে একটি বিশেষ অক্ষর (আবশ্যক)",
    skip: "এড়িয়ে যান",
    confirmPassword: "পাসওয়ার্ড নিশ্চিত করুন",
    setPassword: "পাসওয়ার্ড সেট করুন",
    accountInstruction: "অ্যাকাউন্টে অ্যাক্সেস এবং অর্ডার ম্যানেজ করার জন্য",
    aboutUs: "আমাদের সম্পর্কে",
    contactUs: "যোগাযোগ করুন",
    profile: "প্রোফাইল",
    orders: "অর্ডার",
    wishlist: "উইশলিস্ট",
    loginSignup: "লগ ইন/সাইন আপ",
    welcome: "স্বাগতম",
    profileImgUpdated: "প্রোফাইল ছবি সফলভাবে আপডেট করা হয়েছে",
    save: "সংরক্ষণ করুন",
    cancel: "বাতিল করুন",
    adjustImage: "ছবি সামঞ্জস্য করুন",
    dragSqrToChangeImgSizePos: "আকার এবং অবস্থান পরিবর্তন করতে বর্গটি টানুন।",
    preview: "পূর্বরূপ",
    imageCropped: "ছবি সফলভাবে ক্রপ করা হয়েছে!",
    alternateMobile: "বিকল্প মোবাইল নম্বর",
    male: "পুরুষ",
    female: "মহিলা",
    others: "অন্যান্য",
    genderLabel: "অনুগ্রহ করে আপনার লিঙ্গ নির্বাচন করুন:",
    dob: "জন্ম তারিখ",
    update: "আপডেট করুন",
    changePassword: "পাসওয়ার্ড পরিবর্তন করুন",
    updatePassword: "পাসওয়ার্ড আপডেট করুন",
    updateProfile: "প্রোফাইল আপডেট করুন",
    oldPassword: "পুরানো পাসওয়ার্ড",
    confirmPasswordNotMatchPassword: "পাসওয়ার্ড নিশ্চিতকরণ মিলছে না।",
    passReqNotFulfil: "পাসওয়ার্ডের প্রয়োজনীয়তা পূরণ হয়নি।",
    passwordUpdated: "পাসওয়ার্ড সফলভাবে আপডেট হয়েছে!",
    profileUpdated: "প্রোফাইল সফলভাবে আপডেট হয়েছে!",
    pageNotFound: "পৃষ্ঠা পাওয়া যায়নি",
    brokenLinkMsg1: "আপনি যে লিঙ্কে ক্লিক করেছেন তা ভেঙে যেতে পারে বা পৃষ্ঠাটি সরানো হয়েছে।",
    brokenLinkMsg2: "হোম পেজে যান বা সমস্যা সম্পর্কে আমাদের সাথে যোগাযোগ করুন।",
    backToHome: "হোম পেজে ফিরে যান",
    dashboard: "ড্যাশবোর্ড",
    pages: "পৃষ্ঠা",
    inventory: "ইনভেন্টরি",
    customOrders: "কাস্টম অর্ডার",
    team: "টিম",
    customers: "গ্রাহক",
    settings: "সেটিংস",
    messages: "বার্তা",
    pendingOrders: "মুলতুবি অর্ডার",
    completedOrders: "সম্পন্ন অর্ডার",
    offers: "অফার",
    id: "আইডি",
    brand: "ব্র্যান্ড",
    category: "বিভাগ",
    price: "দাম",
    status: "স্ট্যাটাস",
    createdDate: "তৈরির তারিখ",
    updatedDate: "শেষ আপডেট",
    action: "অ্যাকশন",
    productName: "পণ্যের নাম",
    size: "আকার",
    color: "রঙ",
    stockQuantity: "পরিমাণ",
    products: "পণ্য",
    description: "বিবরণ",
    parent: "প্যারেন্ট",
    namePlaceholder: "নাম লিখুন",
    descriptionPlaceholder: "বিবরণ লিখুন",
    categoryPlaceholder: "বিভাগ নির্বাচন করুন",
    categoryLevel: "বিভাগ {0} স্তর",
    at: "এ",
    modifiedOn: "এ সংশোধিত",
    today: "আজ",
    edit: "সম্পাদনা করুন",
    delete: "মুছুন",
    activated: "{entity} সক্রিয় আছে।",
    deactivated: "{entity} নিষ্ক্রিয় আছে।",
    yes: "হ্যাঁ",
    no: "না",
    confirm: "নিশ্চিত করুন",
    deleteMsg: "আপনি কি নিশ্চিত যে আপনি <b>{0}</b> {1} মুছতে চান?",
    childrenOf: "এর চাইল্ড",
    page: "পৃষ্ঠা",
    add: "যোগ করুন",
    deactivateFirst: "প্রথমে {entity} নিষ্ক্রিয় করুন।",
    activeCantAction: "সক্রিয় {entity} কে {action} করা যাবে না।",
    entityIsActive: "<b>{0}</b> {entity} সক্রিয় আছে।",
    searchPlaceHolder: "{entity} খুঁজুন...",
    copy: "কপি করুন",
    deleted: "মুছে ফেলা হয়েছে",
    edited: "সম্পাদিত",
    product: "পণ্য",
    title: "শিরোনাম",
    titlePlaceholder: "শিরোনাম লিখুন",
    image: "ছবি",
    material: "উপাদান",
    materialPlaceholder: "উপাদান লিখুন",
    colorPlaceholder: "রঙ লিখুন",
    sku: "SKU কোড",
    skuPlaceholder: "অনন্য SKU কোড লিখুন",
    quantity: "পরিমাণ",
    type: "প্রকার",
    selectProductPlaceholder: "পণ্য নির্বাচন করুন",
    sizeChart: "সাইজ চার্ট",
    enterMeasure: "আপনার {0} মাপ লিখুন",
    chest: "বুক",
    hips: "কোমর (Hips)",
    neck: "ঘাড়",
    sleeve: "হাতা",
    arm: "বাহু",
    topLength: "উপরের দৈর্ঘ্য",
    shoulder: "কাঁধ",
    inseam: "ইনসিম",
    bottomLength: "নিচের দৈর্ঘ্য",
    thigh: "উরু",
    waist: "কোমর (Waist)",
    topBody: "উপরের শরীর",
    bottomBody: "নিচের শরীর",
    rank: "র‌্যাঙ্ক",
    sale: "বিক্রয়",
    rental: "ভাড়া",
    selectRankPlaceholder: "র‌্যাঙ্ক নির্বাচন করুন",
    mrp: "এমআরপি (MRP)",
    salePrice: "বিক্রয় মূল্য",
    discount: "ছাড়",
    selectSizePlaceholder: "আকার নির্বাচন করুন",
    mrpPlaceholder: "এমআরপি লিখুন (₹)",
    salePricePlaceholder: "বিক্রয় মূল্য লিখুন (₹)",
    discountPlaceholder: "ছাড় লিখুন (%)",
    quantityPlaceholder: "পরিমাণ লিখুন",
    saleOrRentPrice: "বিক্রয়/ভাড়া মূল্য",
    security: "নিরাপত্তা আমানত",
    securityPlaceholder: "ফেরত = আমানত - (ভাড়া মূল্য - ছাড় %)",
    size_Quant_Price: "আকার - পরিমাণ - বিক্রয় মূল্য",
    view: "দেখুন",
    webSettings: "ওয়েব সেটিংস",
    siteUnderMaintenance: "সাইট রক্ষণাবেক্ষণে আছে",
    weWillGetbackShortly: "আমরা শীঘ্রই ফিরে আসব। অনুগ্রহ করে পরে আবার চেক করুন।",
    reload: "রিলোড করুন",
    enableWebsite: "ওয়েবসাইট সক্ষম/অক্ষম করতে ক্লিক করুন।",
    website: "ওয়েবসাইট",
    switchOnOffWebsite: "ওয়েবসাইট চালু/বন্ধ করুন",
    webConfigs: "ওয়েবসাইট কনফিগারেশন",
    webTrendingBar: "ওয়েবসাইট ট্রেন্ডিং বার",
    websiteId: "ওয়েবসাইট আইডি",
    path: "পাথ",
    pathPlaceholder: "খোলার জন্য পাথ লিখুন",
    homePage: "হোম পেজ",
    PageCarousel: "হোম পেজ ক্যারোজেল",
    forPC: "পিসির জন্য:",
    forMobile: "মোবাইলের জন্য:",
    reset: "রিসেট করুন",
    customFitting: "কাস্টম ফিটিং",
    customDesigning: "কাস্টম ডিজাইনিং",
    freeDelivery: "ফ্রি ডেলিভারি",
    assuredRefunds: "নিশ্চিত রিফান্ড",
    sizes: "আকার",
    addresses: "ঠিকানা",
    isTileVisible: "টাইল কি দৃশ্যমান?",
    isTileVisibleGrid: "টাইল দৃশ্যমান",
    categories: "বিভাগসমূহ",
    mrpWithDots: "এম.আর.পি",
    rtd: "তাৎক্ষণিক ডেলিভারি",
    inclusiveTax: "সমস্ত কর সহ মূল্য",
    rentInclusiveTax: "ভাড়ায় কর অন্তর্ভুক্ত",
    purchase: "কিনুন",
    rent: "ভাড়া",
    refundableSecurity: "ফেরতযোগ্য নিরাপত্তা আমানত",
    securityDeposit: "নিরাপত্তা আমানত",
    refundSecurity: "পণ্য ফেরত দেওয়ার পরে আপনার নিরাপত্তা আমানত ফেরত দেওয়া হবে।",
    securityDepositDeduction: "আপনি ডেলিভারির 5 দিনের মধ্যে পণ্য ফেরত দিতে পারেন। এরপর প্রতি 5 দিনে ভাড়ার পরিমাণ নিরাপত্তা আমানত থেকে কাটা হবে।",
    sizeGuide: "সাইজ গাইড",
    customSize: "কাস্টম সাইজ",
    loginToAddCustomSize: "কাস্টম সাইজ যোগ এবং দেখতে লগইন/সাইন আপ করুন",
    yourCustomSizes: "আপনার কাস্টম সাইজ",
    undoWishlistMsg: "আপনি উইশলিস্ট থেকে <b>{name}</b> সরিয়ে ফেলেছেন",
    undo: "পূর্বাবস্থায় ফেরান (Undo)",
    textPlaceholder: "{0} লিখুন",
    address: "ঠিকানা",
    fullName: "নাম",
    city: "শহর",
    country: "দেশ",
    pinCode: "পিন কোড",
    state: "রাজ্য",
    landmark: "ল্যান্ডমার্ক",
    streetAddress1: "ফ্ল্যাট, বাড়ি নম্বর, বিল্ডিং, কোম্পানি, অ্যাপার্টমেন্ট",
    streetAddress2: "এলাকা, রাস্তা, সেক্টর, গ্রাম",
    defaultAddress: "ডিফল্ট ঠিকানা সেট করুন",
    setDefault: "ডিফল্ট সেট করুন",
    default: "ডিফল্ট",
    addToCart: "কার্টে যোগ করুন",
    buyNow: "এখনই কিনুন",
    total: "মোট",
    clearCart: "কার্ট সাফ করুন",
    proceedToCheckout: "চেকআউটে এগিয়ে যান",
    shoppingCart: "শপিং কার্ট",
    loadingCart: "কার্ট লোড হচ্ছে...",
    emptyCart: "আপনার কার্ট খালি।",
    emptyWishlist: "আপনার উইশলিস্ট খালি।",
    deSelectAll: "সব আইটেম আনচেক করুন",
    invalidCoupon: "অমান্য কুপন কোড",
    couponApplied: "কুপন প্রয়োগ করা হয়েছে: ",
    apply: "প্রয়োগ করুন",
    freeCaps: "ফ্রি",
    deliveryCharges: "ডেলিভারি চার্জ",
    subTotal: "উপ-মোট (Sub-Total)",
    changeSize: "আকার পরিবর্তন করুন",
    moveToWishlist: "উইশলিস্টে সরান",
    share: "শেয়ার করুন",
    orderSummary: "অর্ডার সারাংশ",
    coupon: "কুপন",
    itemsForPurchasing: "কেনার জন্য নির্বাচিত আইটেম",
    itemsForRenting: "ভাড়ার জন্য নির্বাচিত আইটেম",
    itemsSelected: "নির্বাচিত আইটেম",
    applyCoupon: "কুপন প্রয়োগ করুন",
    undoCartMsg: 'কার্ট থেকে <strong>{name}</strong> সরানো হয়েছে। ',
    itemRestored: "আইটেম কার্টে ফিরে এসেছে",
    selectAll: "সব নির্বাচন করুন",
    itemMovedToWishlist: "আইটেম উইশলিস্টে সরানো হয়েছে।",
    itemRemoved: "আইটেম সরানো হয়েছে",
    addedToCart: "আইটেম কার্টে যোগ করা হয়েছে",
    itemAddedToWishlist: "আইটেম উইশলিস্টে যোগ করা হয়েছে",
    itemRemovedFromWishlist: "আইটেম উইশলিস্ট থেকে সরানো হয়েছে",
    proceedToBuy: "কেনার জন্য এগিয়ে যান",
    change: "পরিবর্তন করুন",
    checkout: "চেকআউট",
    deliverHere: "এখানে ডেলিভার করুন",
    selectDeliveryAddress: "ডেলিভারি ঠিকানা নির্বাচন করুন",
    selectedDeliveryAddress: "নির্বাচিত ডেলিভারি ঠিকানা",
    inventoryType: "ইনভেন্টরি প্রকার",
    currentlyDefaultAddress: "ডিফল্ট ঠিকানা",
    chosenAddressUpdated: "নির্বাচিত ঠিকানা সফলভাবে আপডেট করা হয়েছে।",
    draftUpdated: "অর্ডার বিবরণ সফলভাবে আপডেট করা হয়েছে।",
    deliveringTo: "ডেলিভারি করা হচ্ছে",
    addNew: "নতুন যোগ করুন",
    itemsInOrder: "অর্ডারে থাকা আইটেম",
    shipTogether: "সব আইটেম একসাথে পাঠান",
    shipAsap: "প্রতিটি আইটেম প্রস্তুত হলে পাঠান",
    shipItems: "আপনি আপনার অর্ডারের আইটেম কখন পাঠাতে চান?",
    shipItemsForOrder: "{user} তার অর্ডারের আইটেম কখন পাঠাতে চান?",
    orderPlacedTitle: "ধন্যবাদ, আপনার অর্ডার সফলভাবে দেওয়া হয়েছে!",
    orderConfirmationSent: "আপনার ইমেলে একটি নিশ্চিতকরণ পাঠানো হয়েছে।",
    orderId: "অর্ডার আইডি",
    itemsInTheOrder: "অর্ডারে থাকা আইটেম",
    viewOrders: "আপনার অর্ডার দেখুন",
    viewAllOrders: "সব অর্ডার দেখুন",
    continueShopping: "কেনাকাটা চালিয়ে যান",
    orderDetails: "অর্ডারের বিবরণ",
    appliedCoupon: "প্রয়োগ করা কুপন",
    orderPlacedOn: "অর্ডার দেওয়া হয়েছে",
    shipTo: "শিপ করুন",
    noOrdersFound: "কোন অর্ডার পাওয়া যায়নি",
    yourOrders: "আপনার অর্ডার",
    paymentMode: "পেমেন্ট মোড",
    paymentMethod: "পেমেন্ট পদ্ধতি",
    all: "সব",
    pending: "মুলতুবি",
    shipped: "পাঠানো হয়েছে",
    delivered: "ডেলিভার করা হয়েছে",
    cancelled: "বাতিল করা হয়েছে",
    allOrders: "সব অর্ডার",
    newOrders: "নতুন অর্ডার",
    statusMessages: {
      forOrder: {
        forManager: {
          draft: "অর্ডার ড্রাফট স্ট্যাটাসে আছে এবং এখনও প্লেস করা হয়নি।",
          pending: "পেমেন্ট মুলতুবি আছে।",
          placed: "অর্ডার দেওয়া হয়েছে এবং আপনার নিশ্চিতকরণের অপেক্ষায় আছে।",
          confirmed: "আপনি অর্ডার নিশ্চিত করেছেন।",
          payment_failed: "পেমেন্ট ব্যর্থ হয়েছে।",
          in_process: "অর্ডার আপনার দ্বারা প্রসেস করা হচ্ছে।",
          ready_to_dispatch: "অর্ডার ডিসপ্যাচের জন্য প্রস্তুত।",
          shipped: "অর্ডার পাঠানো হয়েছে।",
          in_transit: "অর্ডার রাস্তায় আছে।",
          delivered: "অর্ডার ডেলিভার করা হয়েছে।",
          cancelled: "অর্ডার বাতিল করা হয়েছে।",
          cancellation_requested: "ব্যবহারকারী অর্ডার বাতিলের অনুরোধ করেছেন।",
          cancellation_rejected: "আপনি বাতিলের অনুরোধ প্রত্যাখ্যান করেছেন।",
          cancellation_refunded: "অর্ডার বাতিল করা হয়েছে এবং পেমেন্ট রিফান্ড করা হয়েছে।",
          return_requested: "রিটার্নের জন্য অনুরোধ করা হয়েছে।",
          return_rejected: "রিটার্ন অনুরোধ প্রত্যাখ্যান করা হয়েছে।",
          returned: "অর্ডার ফেরত দেওয়া হয়েছে।",
          return_refunded: "ফেরত দেওয়ার পর পেমেন্ট রিফান্ড করা হয়েছে।",
          refunded: "পেমেন্ট রিফান্ড করা হয়েছে।",
          rto_requested: "আপনার দ্বারা RTO-এর অনুরোধ করা হয়েছে।",
          rto_rejected: "আপনি RTO অনুরোধ প্রত্যাখ্যান করেছেন।",
          rto_approved: "আপনি RTO অনুরোধ অনুমোদন করেছেন।",
          rto_in_progress: "RTO প্রক্রিয়াধীন আছে।",
          rto_delivered: "RTO দ্বারা অর্ডার আপনাকে ফেরত পাঠানো হয়েছে।",
          rto_verified: "RTO আইটেম যাচাই করা হয়েছে।",
          rto_refunded: "RTO-এর পর পেমেন্ট রিফান্ড করা হয়েছে।"
        },
        forUser: {
          draft: "আপনার অর্ডার চেকআউটে আছে কিন্তু এখনও প্লেস করা হয়নি।",
          pending: "পেমেন্ট মুলতুবি আছে। অনুগ্রহ করে পেমেন্ট সম্পূর্ণ করুন।",
          placed: "আপনার অর্ডার প্লেস করা হয়েছে এবং নিশ্চিতকরণের অপেক্ষায় আছে।",
          confirmed: "আপনার অর্ডার বিক্রেতা দ্বারা নিশ্চিত করা হয়েছে।",
          payment_failed: "পেমেন্ট ব্যর্থ হয়েছে। অনুগ্রহ করে আবার চেষ্টা করুন।",
          in_process: "আপনার অর্ডার বিক্রেতা দ্বারা প্রসেস করা হচ্ছে।",
          ready_to_dispatch: "আপনার অর্ডার ডিসপ্যাচের জন্য প্রস্তুত।",
          shipped: "আপনার অর্ডার পাঠানো হয়েছে।",
          in_transit: "আপনার অর্ডার রাস্তায় আছে।",
          delivered: "আপনার অর্ডার ডেলিভার করা হয়েছে।",
          cancelled: "আপনার অর্ডার বাতিল করা হয়েছে।",
          cancellation_requested: "আপনি অর্ডার বাতিল করার অনুরোধ করেছেন।",
          cancellation_rejected: "আপনার বাতিলের অনুরোধ প্রত্যাখ্যান করা হয়েছে।",
          cancellation_refunded: "আপনার অর্ডার বাতিল করা হয়েছে এবং পেমেন্ট রিফান্ড করা হয়েছে।",
          return_requested: "আপনার অর্ডারের জন্য রিটার্ন অনুরোধ করা হয়েছে।",
          return_rejected: "রিটার্ন অনুরোধ প্রত্যাখ্যান করা হয়েছে।",
          returned: "আপনার অর্ডার ফেরত দেওয়া হয়েছে।",
          return_refunded: "ফেরত দেওয়ার পর আপনার পেমেন্ট রিফান্ড করা হয়েছে।",
          refunded: "পেমেন্ট রিফান্ড করা হয়েছে।",
          rto_requested: "আপনার অর্ডারের জন্য RTO অনুরোধ করা হয়েছে।",
          rto_rejected: "RTO অনুরোধ প্রত্যাখ্যান করা হয়েছে।",
          rto_approved: "RTO অনুরোধ অনুমোদিত হয়েছে।",
          rto_in_progress: "RTO প্রক্রিয়াধীন আছে।",
          rto_delivered: "RTO দ্বারা অর্ডার ফেরত পাঠানো হয়েছে।",
          rto_verified: "RTO আইটেম নিশ্চিত করা হয়েছে।",
          rto_refunded: "RTO-এর পর পেমেন্ট রিফান্ড করা হয়েছে।"
        }
      },
      forItem: {
        forManager: {
          draft: "আইটেম অর্ডার ড্রাফটে যোগ করা হয়েছে এবং এখনও প্লেস হয়নি।",
          pending: "এই আইটেমের পেমেন্ট মুলতুবি আছে।",
          placed: "আইটেম প্লেস করা হয়েছে এবং আপনার নিশ্চিতকরণের অপেক্ষায় আছে।",
          confirmed: "আপনি আইটেম নিশ্চিত করেছেন।",
          payment_failed: "এই আইটেমের পেমেন্ট ব্যর্থ হয়েছে।",
          in_process: "আইটেম প্রসেস করা হচ্ছে।",
          ready_to_dispatch: "আইটেম ডিসপ্যাচের জন্য প্রস্তুত।",
          shipped: "আইটেম পাঠানো হয়েছে।",
          in_transit: "আইটেম রাস্তায় আছে।",
          delivered: "আইটেম ডেলিভার করা হয়েছে।",
          cancelled: "আইটেম বাতিল করা হয়েছে।",
          cancellation_requested: "এই আইটেমের জন্য ব্যবহারকারী বাতিলের অনুরোধ করেছেন।",
          cancellation_rejected: "বাতিলের অনুরোধ প্রত্যাখ্যান করা হয়েছে।",
          cancellation_refunded: "পেমেন্ট রিফান্ড করা হয়েছে।",
          return_requested: "রিটার্ন অনুরোধ করা হয়েছে।",
          return_rejected: "রিটার্ন অনুরোধ প্রত্যাখ্যান করা হয়েছে।",
          returned: "আইটেম ফেরত দেওয়া হয়েছে।",
          return_refunded: "পেমেন্ট রিফান্ড করা হয়েছে।",
          refunded: "পেমেন্ট রিফান্ড করা হয়েছে।",
          rto_requested: "RTO-এর অনুরোধ করা হয়েছে।",
          rto_rejected: "RTO অনুরোধ প্রত্যাখ্যান করা হয়েছে।",
          rto_approved: "RTO অনুরোধ অনুমোদিত হয়েছে।",
          rto_in_progress: "RTO প্রক্রিয়াধীন আছে।",
          rto_delivered: "RTO দ্বারা আইটেম ফেরত পাঠানো হয়েছে।",
          rto_verified: "RTO আইটেম নিশ্চিত করা হয়েছে।",
          rto_refunded: "RTO-এর পর পেমেন্ট রিফান্ড করা হয়েছে।"
        },
        forUser: {
          draft: "এই আইটেমটি চেকআউটে আছে কিন্তু এখনও প্লেস হয়নি।",
          pending: "এই আইটেমের পেমেন্ট মুলতুবি আছে। অনুগ্রহ করে সম্পূর্ণ করুন।",
          placed: "এই আইটেম প্লেস করা হয়েছে এবং নিশ্চিতকরণের অপেক্ষায় আছে।",
          confirmed: "এই আইটেম বিক্রেতা দ্বারা নিশ্চিত করা হয়েছে।",
          payment_failed: "এই আইটেমের পেমেন্ট ব্যর্থ হয়েছে।",
          in_process: "আইটেম বিক্রেতা দ্বারা প্রসেস করা হচ্ছে।",
          ready_to_dispatch: "আইটেম ডিসপ্যাচের জন্য প্রস্তুত।",
          shipped: "আইটেম পাঠানো হয়েছে।",
          in_transit: "আইটেম রাস্তায় আছে।",
          delivered: "আইটেম ডেলিভার করা হয়েছে।",
          cancelled: "আইটেম বাতিল করা হয়েছে।",
          cancellation_requested: "আপনি এই আইটেম বাতিল করার অনুরোধ করেছেন।",
          cancellation_rejected: "বাতিলের অনুরোধ প্রত্যাখ্যান করা হয়েছে।",
          cancellation_refunded: "পেমেন্ট রিফান্ড করা হয়েছে।",
          return_requested: "রিটার্ন অনুরোধ করা হয়েছে।",
          return_rejected: "রিটার্ন অনুরোধ প্রত্যাখ্যান করা হয়েছে।",
          returned: "আইটেম ফেরত দেওয়া হয়েছে।",
          return_refunded: "পেমেন্ট রিফান্ড করা হয়েছে।",
          refunded: "পেমেন্ট রিফান্ড করা হয়েছে।",
          rto_requested: "RTO-এর অনুরোধ করা হয়েছে।",
          rto_rejected: "RTO অনুরোধ প্রত্যাখ্যান করা হয়েছে।",
          rto_approved: "RTO অনুরোধ অনুমোদিত হয়েছে।",
          rto_in_progress: "RTO প্রক্রিয়াধীন আছে।",
          rto_delivered: "RTO দ্বারা আইটেম ফেরত পাঠানো হয়েছে।",
          rto_verified: "RTO আইটেম নিশ্চিত করা হয়েছে।",
          rto_refunded: "RTO-এর পর পেমেন্ট রিফান্ড করা হয়েছে।"
        }
      }
    },
    statusColors: {
      draft: "var(--secondarytext-color)",
      pending: "var(--warning-color)",
      placed: "var(--info-color)",
      confirmed: "var(--success-color)",
      payment_failed: "var(--danger-color)",
      in_process: "var(--infolight-color)",
      ready_to_dispatch: "purple",
      shipped: "blue",
      in_transit: "var(--primarylight-color)",
      delivered: "var(--successdark-color)",
      cancellation_requested: "orange",
      cancelled: "var(--dangerlight-color)",
      cancellation_rejected: "red",
      cancellation_refunded: "var(--success-color)",
      return_requested: "var(--secondary-color)",
      returned: "var(--dangerlight-color)",
      return_rejected: "var(--warning-color)",
      return_refunded: "var(--success-color)",
      refunded: "var(--success-color)",
      rto_requested: "var(--warningdark-color)",
      rto_rejected: "red",
      rto_approved: "var(--success-color)",
      rto_in_progress: "blueviolet",
      rto_delivered: "var(--info-color)",
      rto_verified: "var(--successdark-color)",
      rto_refunded: "var(--success-color)"
    },
    orderPages: {
      allOrders: {
        title: "সব অর্ডার",
        statuses: ["ALL"]
      },
      pendingOrders: {
        title: "মুলতুবি অর্ডার",
        statuses: ["PENDING"]
      },
      newOrders: {
        title: "নতুন অর্ডার",
        statuses: ["PLACED"]
      },
      confirmedOrders: {
        title: "নিশ্চিত অর্ডার",
        statuses: ["CONFIRMED"]
      },
      processingOrders: {
        title: "প্রসেসিং অর্ডার",
        statuses: ["IN_PROCESS"]
      },
      readyToDispatchOrders: {
        title: "ডিসপ্যাচের জন্য প্রস্তুত",
        statuses: ["READY_TO_DISPATCH"]
      },
      onTheWayOrders: {
        title: "রাস্তায় থাকা অর্ডার",
        statuses: ["SHIPPED", "IN_TRANSIT"]
      },
      deliveredOrders: {
        title: "ডেলিভার করা অর্ডার",
        statuses: ["DELIVERED"]
      },
      cancelled: {
        title: "বাতিল অর্ডার",
        statuses: ["CANCELLED"]
      },
      returns: {
        title: "রিটার্নস",
        statuses: ["ALLRETURNS"],
        showOrderStatuses: false
      },
      cancellation_requested: {
        title: "বাতিল অনুরোধিত",
        statuses: ["CANCELLATION_REQUESTED"]
      },
      cancellation_rejected: {
        title: "বাতিল প্রত্যাখ্যাত",
        statuses: ["CANCELLATION_REJECTED"]
      },
      cancellation_refunded: {
        title: "বাতিল রিফান্ড",
        statuses: ["CANCELLATION_REFUNDED"]
      },
      return_requested: {
        title: "রিটার্ন অনুরোধিত",
        statuses: ["RETURN_REQUESTED"]
      },
      returned: {
        title: "ফেরত দেওয়া অর্ডার",
        statuses: ["RETURNED"]
      },
      return_rejected: {
        title: "রিটার্ন প্রত্যাখ্যাত",
        statuses: ["RETURN_REJECTED"]
      },
      return_refunded: {
        title: "রিটার্ন রিফান্ড",
        statuses: ["RETURN_REFUNDED"]
      },
      rto_requested: {
        title: "RTO অনুরোধিত",
        statuses: ["RTO_REQUESTED"]
      },
      rto_rejected: {
        title: "RTO প্রত্যাখ্যাত",
        statuses: ["RTO_REJECTED"]
      },
      rto_approved: {
        title: "RTO অনুমোদিত",
        statuses: ["RTO_APPROVED"]
      },
      rto_in_progress: {
        title: "RTO প্রক্রিয়াধীন",
        statuses: ["RTO_IN_PROGRESS"]
      },
      rto_delivered: {
        title: "RTO ডেলিভার",
        statuses: ["RTO_DELIVERED"]
      },
      rto_verified: {
        title: "RTO যাচাইকৃত",
        statuses: ["RTO_VERIFIED"]
      },
      rto_refunded: {
        title: "RTO রিফান্ড",
        statuses: ["RTO_REFUNDED"]
      }
    },
    confirmedOrders: "নিশ্চিত অর্ডার",
    processingOrders: "প্রসেসিং অর্ডার",
    readyToDispatchOrders: "ডিসপ্যাচের জন্য প্রস্তুত অর্ডার",
    onTheWayOrders: "রাস্তায় থাকা অর্ডার",
    deliveredOrders: "ডেলিভার করা অর্ডার",
    cancelled_orders: "বাতিল অর্ডার",
    cancellation_requested_orders: "বাতিল অনুরোধিত অর্ডার",
    return_requested_orders: "রিটার্ন অনুরোধিত অর্ডার",
    return_refunded_orders: "রিটার্ন রিফান্ড করা অর্ডার",
    returns: "রিটার্নস",
    returned_orders: "ফেরত দেওয়া অর্ডার",
    return_rejected_orders: "রিটার্ন প্রত্যাখ্যাত অর্ডার",
    cancellation_rejected_orders: "বাতিল প্রত্যাখ্যাত অর্ডার",
    cancellation_refunded_orders: "বাতিল রিফান্ড করা অর্ডার",
    rto_requested_orders: "RTO অনুরোধিত অর্ডার",
    rto_rejected_orders: "RTO প্রত্যাখ্যাত অর্ডার",
    rto_approved_orders: "RTO অনুমোদিত অর্ডার",
    rto_in_progress_orders: "RTO প্রক্রিয়াধীন অর্ডার",
    rto_delivered_orders: "RTO ডেলিভার করা অর্ডার",
    rto_verified_orders: "RTO যাচাইকৃত অর্ডার",
    rto_refunded_orders: "RTO রিফান্ড করা অর্ডার",
    moreOptions: "আরও বিকল্প",
    details: "বিবরণ",
    viewProductPage: "পণ্য পৃষ্ঠা দেখুন",
    viewSize: "আকার দেখুন",
    trackStatus: "স্ট্যাটাস ট্র্যাক করুন",
    auditTrail: "অডিট ট্রেইল",
    changedFrom: "থেকে পরিবর্তিত",
    changedTo: "এ পরিবর্তিত",
    entityType: "এনটিটি টাইপ",
    entityId: "এনটিটি আইডি",
    performedBy: "দ্বারা সম্পাদিত",
    timestamp: "টাইমস্ট্যাম্প",
    trackingDetails: "ট্র্যাকিং বিবরণ",
    noDetailsFound: "কোন বিবরণ পাওয়া যায়নি",
    userDetails: "ব্যবহারকারীর বিবরণ",
    followUs: "আমাদের অনুসরণ করুন",
    allRightsReserved: "সর্বস্বত্ব সংরক্ষিত",
    fastAndSecured: "দ্রুত এবং নিরাপদ পেমেন্ট বিকল্প",
    company: "কোম্পানি",
    myAccount: "আমার অ্যাকাউন্ট",
    home: "হোম পেজ",
    account: "অ্যাকাউন্ট",
    search: "অনুসন্ধান",
    cart: "কার্ট",
    language: "ভাষা",
    somethingWentWrong: "কিছু ভুল হয়েছে!",
    note: "নোট",
    notAllowed1: "আপনার এই অ্যাপ্লিকেশনে লগইন করার অনুমতি নেই",
    notAllowed2: "শুধুমাত্র অ্যাডমিন এবং ম্যানেজারের অ্যাক্সেস আছে",
    notAllowed3: "যদি আপনি এদের মধ্যে একজন হন এবং তবুও অ্যাক্সেস করতে না পারেন তবে অ্যাডমিনের সাথে যোগাযোগ করুন",
    logOutAndBackToHome: "লগ আউট করুন এবং হোমে ফিরে যান",
    whatsAppUs: "আমাদের হোয়াটসঅ্যাপ করুন",
    ourContactDetails: "আমাদের যোগাযোগের বিবরণ",
    workingHours: "কাজের সময়",
    instagram: "ইনস্টাগ্রাম",
    facebook: "ফেসবুক",
    x: "এক্স (টুইটার)",
    threads: "থ্রেডস",
    youtube: "ইউটিউব",
    pinterest: "পিন্টারেস্ট",
    quotaUsage: "মেল/এসএমএস কোটা ব্যবহার",
    used: "ব্যবহৃত",
    remaining: "অবশিষ্ট",
    totalQuota: "মোট কোটা",
    sms: "এসএমএস (SMS)",
    whatsapp: "হোয়াটসঅ্যাপ",
    brevo: "ব্রেভো",
    count: "গণনা",
    date: "তারিখ",
    gmail: "জিমেইল",
    quota: "কোটা",
    teamUsers: "টিম",
    member: "সদস্য",
    customer: "গ্রাহক",
    profileImage: "প্রোফাইল ছবি",
    gender: "লিঙ্গ",
    role: "ভূমিকা",
    activatedText: "সক্রিয়",
    selectRolePlaceholder: "ভূমিকা নির্বাচন করুন",
    accountActiveLabel: "অনুগ্রহ করে নির্বাচন করুন ব্যবহারকারীর অ্যাকাউন্ট সক্রিয়/নিষ্ক্রিয় হওয়া উচিত কিনা:",
    user: "ব্যবহারকারী",
    actions: "অ্যাকশন",
    setAsDiscontinued: "বন্ধ (Discontinued) হিসেবে সেট করুন",
    resetToDefaultPassword: "ডিফল্ট পাসওয়ার্ডে রিসেট করুন",
    confirmMsg: "আপনি কি নিশ্চিত? আপনি <b>{0}</b> {1} কে {2} করতে চান?",
    discontinued: "বন্ধ (Discontinued)",
    base: "বেস (Base)",
    setActive: "সক্রিয় (Active) করুন",
    refresh: "রিফ্রেশ"
  };

  export default bn;