const en = {
    login: "Log In",
    signup: "Sign Up",
    forgotPassword: "Forgot Password?",
    welcomeUser: "Welcome, User!",
    logout: "Log Out",
    requiredField: "This field is required.",
    invalidEmail: "Please enter a valid email address.",
    name: "Name",
    fullNamePlaceholder: "Enter your Name",
    firstName: "First Name",
    lastName: "Last Name",
    mobileOrEmail: "Email Id or Mobile no.",
    firstNamePlaceHolder: "Enter your First Name",
    lastNamePlaceHolder: "Enter your Last Name",
    email: "Email",
    emailPlaceHolder: "Enter your Email",
    mobile: "Mobile No.",
    mobilePlaceHolder: "Enter you Mobile no.",
    receiveOTP: "You will receive an OTP on this {0}.",
    pleaseWait: "Please Wait...",
    fetchingDataFailedTitle: "Unable to fetch the requested data.",
    failureMessage: "We faced an error while processing your request.",
    technicalGlitch: "This may be due to temporary glitch. Try again after some time.",
    contactSupport: "Contact Support at <a href=\"{supportEmail}\" style=\"text-decoration:none; target=\"_blank\" rel=\"noopener noreferrer\" color: #27c0e0;\">{supportEmail}</a>.",
    register: "Register",
    registering: "Registering....",
    submitOTP: "Verify OTP",
    submittingOTP: "Verifying OTP....",
    otp: "OTP",
    otpPlaceholder: "Enter the OTP",
    enterOTP: "Kindly Enter the OTP you have received on ({value}).",
    signedUp: "You have Signed Up Successfully!",
    failedToSignUp: "You have failed to sign up.",
    loggedIn: "You have Logged In Successfully!",
    failedToLogIn: "You have failed to log in.",
    resendOTP: "Resend OTP",
    resendingOTP: "Resending OTP....",
    password: "Password",
    logingin: "Logging In",
    passwordPlaceHolder: "Enter your Password",
    otpChild1: "OTP may be incorrect",
    otpChild2: "OTP may be expired.",
    otpChild3: "There might be network issue.",
    otpChild4: "Server may be down",
    passwordRequirementMsg: "To safeguard your account, create a password with a minimum of eight (8) characters, including",
    passwordRequireMent: "Password Requirements",
    upperLowerCase: "Upper & Lower Case",
    subHeadingIns: "For strong password, your password should comply to following points",
    minimum8Char: "Minimum 8 characters (mandatory)",
    atLeastOneNumericals: "Atleast one numerals (mandatory)",
    numericals: "Numerals",
    specialChar: "Special Characters",
    oneUpperCase: "Atleast one upper case character (mandatory)",
    oneLowerCase: "Atleast one lower case character (mandatory)",
    partnerCompanyName: "Partner's Company Name",
    atLeastOneSpecialChar: "Atleast one special character (mandatory)",
    skip: "Skip",
    confirmPassword: "Confirm Password",
    setPassword: "Set Password",
    accountInstruction: "To access account and manage orders",
    aboutUs: "About Us",
    contactUs: "Contact Us",
    profile: "Profile",
    orders: "Orders",
    wishlist: "Wishlist",
    loginSignup: "Log In/Sign Up",
    welcome: "Welcome",
    profileImgUpdated: "Profile Image Updated Successfully",
    save: "Save",
    cancel: "Cancel",
    adjustImage: "Adjust Image",
    dragSqrToChangeImgSizePos: "Drag the square to change the size and position.",
    preview: "Preview",
    imageCropped: "Cropped Image Saved Successfully!",
    alternateMobile: "Alternate Mobile No.",
    male: "Male",
    female: "Female",
    others: "Others",
    genderLabel: "Kindly select your gender:",
    dob: "Date of Birth",
    update: "Update",
    changePassword: "Change Password",
    updatePassword: "Update Password",
    updateProfile: "Update Profile",
    oldPassword: "Old Password",
    confirmPasswordNotMatchPassword: "Confirm Password did not match with Password.",
    passReqNotFulfil: "Password requirement not fulfilled.",
    passwordUpdated: "Password Updated Successfully!",
    profileUpdated: "Profile Updated Successfully!",
    pageNotFound: "Page Not Found",
    brokenLinkMsg1: "The link you clicked may be broken or the page may be removed.",
    brokenLinkMsg2: "Visit the Home page or contact us about the problem.",
    backToHome: "Back to Home Page",
    dashboard: "Dashboard",
    pages: "Pages",
    inventory: "Inventory",
    customOrders: "Custom Orders",
    team: "Team",
    customers: "Customers",
    settings: "Settings",
    messages: "Messages",
    pendingOrders: "Pending Orders",
    completedOrders: "Completed Orders",
    offers: "Offers",
    id: "Id",
    brand: "Brand",
    category: "Category",
    price: "Price",
    status: "Status",
    createdDate: "Creation Date",
    updatedDate: "Last Updated on",
    action: "Action",
    productName: "Product Name",
    size: "Size",
    color: "Color",
    stockQuantity: "Quantity",
    products: "Products",
    description: "Description",
    parent: "Parent",
    namePlaceholder: "Enter the Name",
    descriptionPlaceholder: "Enter the Description",
    categoryPlaceholder: "Select a Category",
    categoryLevel: "Category {0} Level ",
    at: "At",
    modifiedOn: "Modified on",
    today: "Today",
    edit: "Edit",
    delete: "Delete",
    activated: "{entity} is Activated.",
    deactivated: "{entity} is Deactivated.",
    yes: "Yes",
    no: "No",
    confirm: "Confirm",
    deleteMsg: "Are you Sure. You want to delete <b>{0}</b> {1}?",
    childrenOf: "Children of ",
    page: "Page",
    add: "Add",
    deactivateFirst: "Deactivate the {entity} first.",
    activeCantAction: "Active {entity} can't be {action}.",
    entityIsActive: "<b>{0}</b> {entity} is Active.",
    searchPlaceHolder: "Search for {entity}...",
    copy: "Copy",
    deleted: "Deleted",
    edited: "Edited",
    product: "Product",
    title: "Title",
    titlePlaceholder: "Enter the Title",
    image: "Image",
    material: "Material",
    materialPlaceholder: "Enter the Material",
    colorPlaceholder: "Enter the Color",
    sku: "SKU Code",
    skuPlaceholder: "Enter a unique SKU Code",
    quantity: "Quantity",
    type: "Type",
    selectProductPlaceholder: "Select the product",
    sizeChart: "Size Chart",
    enterMeasure: "Enter your {0} measure",
    chest: "Chest",
    hips: "Hips",
    neck: "Neck",
    sleeve: "Sleeve",
    arm: "Arm",
    topLength: "Top Length",
    shoulder: "Shoulder",
    inseam: "Inseam",
    bottomLength: "Bottom Length",
    thigh: "Thigh",
    waist: "Waist",
    topBody: "Top Body",
    bottomBody: "Bottom Body",
    rank: "Rank",
    sale: "Sale",
    rental: "Rental",
    selectRankPlaceholder: "Select the Rank",
    mrp: "MRP",
    salePrice: "Sale Price",
    discount: "Discount",
    selectSizePlaceholder: "Select Size",
    mrpPlaceholder: "Enter the MRP(₹)",
    salePricePlaceholder: "Enter Sale Price(₹)",
    discountPlaceholder: "Enter the discount(%)",
    quantityPlaceholder: "Enter the quantity",
    saleOrRentPrice: "Sale/Rental Price",
    security: "Security Deposit",
    securityPlaceholder: "Refundable = Deposit - (Rent Price - Discount %)",
    size_Quant_Price: "Size - Quantity - Sale Price",
    view: "View",
    webSettings: "Web Settings",
    siteUnderMaintenance: "Site Under Maintenance",
    weWillGetbackShortly: "We’ll be back shortly. Please check again later.",
    reload: "Reload",
    enableWebsite: "Click to enable or Disable the Website.",
    website: "Website",
    switchOnOffWebsite: "Switch On/Off Website",
    webConfigs: "Website Configurations",
    webTrendingBar: "Website Trending Bar",
    websiteId: "Website Id",
    path: "Path",
    pathPlaceholder: "Enter the path to be opened",
    homePage: "Home Page",
    homePageCarousel: "Home Page Carousel",
    forPC: "For PC:",
    forMobile: "For Mobile:",
    reset: "Reset",
    customFitting: "Custom Fitting",
    customDesigning: "Custom Designing",
    freeDelivery: "Free Delivery",
    assuredRefunds: "Assured Refunds",
    sizes: "Sizes",
    addresses: "Addresses",
    isTileVisible: "Is Tile Visible?",
    isTileVisibleGrid: "Is Tile Visible",
    categories: "Categories",
    mrpWithDots: "M.R.P",
    rtd: "Ready to Dispatch",
    inclusiveTax: "Price Inclusive Of All Taxes",
    rentInclusiveTax: "Rent Inclusive Of All Taxes",
    purchase: "Purchase",
    rent: "Rent",
    refundableSecurity: "Refundable Security Deposit",
    securityDeposit: "Security Deposit",
    refundSecurity: "After returning the item, your security deposit will be refunded.",
    securityDepositDeduction: " You can return the item within 5 days of delivery. After that rental amount will be deducted from your security deposit for each 5 days.",
    sizeGuide: "Size Guide",
    customSize: "Custom Size",
    loginToAddCustomSize: "Login/Sign Up, to add & view custom size",
    yourCustomSizes: "Your Custom Sizes",
    undoWishlistMsg: "You have removed <b>{name}</b> from wishlist",
    undo: "Undo",
    textPlaceholder: "Enter the {0}",
    address: "Address",
    fullName: "Name",
    city: "City",
    country: "Country",
    pinCode: "PIN Code",
    state: "State",
    landmark: "Landmark",
    streetAddress1: "Flat, House no., Building, Company, Apartment",
    streetAddress2: "Area, Street, Sector, Village",
    defaultAddress: "Set as default Address",
    setDefault: "Set as default",
    default: "Default",
    addToCart: "Add to Cart",
    buyNow: "Buy Now",
    total: "Total",
    clearCart: "Clear Cart",
    proceedToCheckout: "Proceed To Checkout",
    shoppingCart: "Shopping Cart",
    loadingCart: "Loading Cart...",
    emptyCart: "Your cart is empty.",
    emptyWishlist: "Your wishlist is empty.",
    deSelectAll: "Deselect All Items",
    invalidCoupon: "Invalid coupon code",
    couponApplied: "Coupon applied: ",
    apply: "Apply",
    freeCaps: "FREE",
    deliveryCharges: "Delivery Charges",
    subTotal: "SubTotal",
    changeSize: "Change Size",
    moveToWishlist: "Move to Wishlist",
    share: "Share",
    orderSummary: "Order Summary",
    coupon: "Coupon",
    itemsForPurchasing: "Items Selected for Purchasing",
    itemsForRenting: "Items Selected for Renting",
    itemsSelected: "Items Selected",
    applyCoupon: "Apply Coupon",
    undoCartMsg: 'Removed <strong>{name}</strong> from cart. ',
    itemRestored: "Item restored to cart",
    selectAll: "Select All",
    itemMovedToWishlist: "Item moved to wishlist.",
    itemRemoved: "Item Removed from cart",
    addedToCart: "Item Added to cart",
    itemAddedToWishlist: "Item Added to wishlist",
    itemRemovedFromWishlist: "Item Removed from wishlist",
    proceedToBuy: "Proceed to Buy",
    change: "Change",
    checkout: "Checkout",
    deliverHere: "Deliver here",
    selectDeliveryAddress: "Select Delivery Address",
    selectedDeliveryAddress: "Selected Delivery Address",
    inventoryType: "Inventory Type",
    currentlyDefaultAddress: "Default Address",
    chosenAddressUpdated: "Chosen Address Updated Successfully.",
    draftUpdated: "Order Details Updated Successfully.",
    deliveringTo: "Delivering to",
    addNew: "Add New",
    itemsInOrder: "Items in Order",
    shipTogether: "Ship all items together",
    shipAsap: "Ship each item as prepared",
    shipItems: "When do you want your order to be shipped?",
    shipItemsForOrder: "When do {user} want the order to be shipped?",
    orderPlacedTitle: "Thank you, your order has been placed!",
    orderConfirmationSent:  "A confirmation has been sent to your email.",
    orderId: "Order ID",
    itemsInTheOrder: "Items in the order",
    viewOrders: "View Your Orders",
    viewAllOrders: "View All Orders",
    continueShopping: "Continue Shopping",
    orderDetails: "Order Details",
    appliedCoupon: "Applied Coupon",
    orderPlacedOn: "Order Placed on",
    shipTo: "Ship to",
    noOrdersFound: "No orders found",
    yourOrders: "Your Orders",
    paymentMode: "Payment mode",
    paymentMethod: "Payment method",
    all: "All",
    pending: "Pending",
    shipped: "Shipped",
    delivered: "Delivered",
    cancelled: "Cancelled",
    allOrders: "All Orders",
    newOrders: "New Orders",
    statusMessages: {
      forOrder: {
        forManager: {
          draft: "Order is in draft state and not yet placed.",
          pending: "Payment is pending.",
          placed: "Order has been placed and is awaiting confirmation from your side.",
          confirmed: "You have confirmed the order.",
          payment_failed: "Payment failed.",
          in_process: "Order is being processed by you.",
          ready_to_dispatch: "Order is ready to be dispatched.",
          shipped: "Order has been shipped.",
          in_transit: "Order is on the way.",
          delivered: "Order has been delivered.",
          cancelled: "Order has been cancelled.",
          cancellation_requested: "User has requested cancellation.",
          cancellation_rejected: "You have rejected the cancellation request.",
          cancellation_refunded: "Order has been cancelled and payment refunded.",
          return_requested: "Return requests for the orders.",
          return_rejected: "You have rejected the return request.",
          returned: "Order has been returned.",
          return_refunded: "Payment has been refunded after return.",
          refunded: "Payment has been refunded.",
    
          // New RTO statuses
          rto_requested: "RTO has been requested by you.",
          rto_rejected: "You have rejected the RTO request.",
          rto_approved: "You have approved the RTO request.",
          rto_in_progress: "RTO is in progress.",
          rto_delivered: "Order is returned to you by RTO.",
          rto_verified: "RTO items has been verified by you.",
          rto_refunded: "Payment refunded to customer after RTO."
        },
        forUser: {
          draft: "Your order is in checkout but not placed yet.",
          pending: "Payment is pending. Please complete your payment.",
          placed: "Your order has been placed and is awaiting confirmation.",
          confirmed: "Your order has been confirmed by the seller.",
          payment_failed: "Payment failed. Please try again.",
          in_process: "Your order is being processed by the seller.",
          ready_to_dispatch: "Your order is ready to be dispatched.",
          shipped: "Your order has been shipped.",
          in_transit: "Your order is on the way.",
          delivered: "Your order has been delivered.",
          cancelled: "Your order has been cancelled.",
          cancellation_requested: "You have requested to cancel this order.",
          cancellation_rejected: "Your cancellation request has been rejected.",
          cancellation_refunded: "Your cancellation has been accepted and payment refunded.",
          return_requested: "A return request has been submitted for your order.",
          return_rejected: "Your return request has been rejected.",
          returned: "Your order has been returned.",
          return_refunded: "Your payment has been refunded after return.",
          refunded: "Your payment has been refunded.",
    
          // New RTO statuses
          rto_requested: "You/Seller has requested RTO for the order.",
          rto_rejected: "Seller has rejected the RTO request.",
          rto_approved: "Seller has approved the RTO for this order.",
          rto_in_progress: "Your order is on the way to RTO.",
          rto_delivered: "Your order has been returned to the seller by RTO.",
          rto_verified: "Your returned order has been verified by the seller.",
          rto_refunded: "You have been refunded after RTO."
        }
      },
      forItem: {
        forManager: {
          draft: "Item is added to the order draft and not yet placed.",
          pending: "Payment for this item is pending.",
          placed: "Item has been placed and is awaiting confirmation from your side.",
          confirmed: "You have confirmed this item.",
          payment_failed: "Payment for this item failed.",
          in_process: "Item is being processed by you.",
          ready_to_dispatch: "Item is ready to be dispatched.",
          shipped: "Item has been shipped.",
          in_transit: "Item is on the way.",
          delivered: "Item has been delivered.",
          cancelled: "This item has been cancelled.",
          cancellation_requested: "User has requested cancellation for this item.",
          cancellation_rejected: "You have rejected the cancellation request for this item.",
          cancellation_refunded: "This item has been cancelled and payment refunded.",
          return_requested: "User has requested a return for this item.",
          return_rejected: "You have rejected the return request for this item.",
          returned: "Item has been returned.",
          return_refunded: "Payment has been refunded for this returned item.",
          refunded: "Payment has been refunded for this item.",
    
          // New RTO statuses
          rto_requested: "RTO has been requested for this item.",
          rto_rejected: "You have rejected the RTO request for this item.",
          rto_approved: "You have approved the RTO request for this item.",
          rto_in_progress: "RTO for this item is in progress.",
          rto_delivered: "This item has been returned to you.",
          rto_verified: "This item returned to origin has been verified.",
          rto_refunded: "Payment has been refunded for this item after RTO."
        },
        forUser: {
          draft: "This item is in checkout but not placed yet.",
          pending: "Payment for this item is pending. Please complete your payment.",
          placed: "This item has been placed and is awaiting confirmation.",
          confirmed: "This item has been confirmed by the seller.",
          payment_failed: "Payment for this item failed. Please try again.",
          in_process: "This item is being processed by the seller.",
          ready_to_dispatch: "This item is ready to be dispatched.",
          shipped: "This item has been shipped.",
          in_transit: "This item is on the way.",
          delivered: "This item has been delivered.",
          cancelled: "This item has been cancelled.",
          cancellation_requested: "You have requested to cancel this item.",
          cancellation_rejected: "Your cancellation request for this item has been rejected.",
          cancellation_refunded: "Your cancellation for this item has been accepted and payment refunded.",
          return_requested: "A return request has been submitted for this item.",
          return_rejected: "Your return request for this item has been rejected.",
          returned: "This item has been returned.",
          return_refunded: "Your payment has been refunded after returning this item.",
          refunded: "Your payment has been refunded for this item.",
    
          // New RTO statuses
          rto_requested: "You/Seller has requested RTO for this item.",
          rto_rejected: "Seller has rejected the RTO request for this item.",
          rto_approved: "Seller has approved RTO for this item.",
          rto_in_progress: "This item is being RTO.",
          rto_delivered: "This item has been returned to the seller.",
          rto_verified: "This item returned to origin has been verified by the seller.",
          rto_refunded: "Your payment has been refunded for this item after RTO."
        }
      }
    },
    statusColors: {
      draft: "var(--secondarytext-color)",
      pending: "var(--warning-color)",
      placed: "var(--info-color)",
      confirmed: "var(--success-color)",
      payment_failed: "var(--danger-color)",
      in_process: "var(--infolight-color)",
      ready_to_dispatch: "purple",
      shipped: "blue",
      in_transit: "var(--primarylight-color)",
      delivered: "var(--successdark-color)",
    
      cancellation_requested: "orange",
      cancelled: "var(--dangerlight-color)",
      cancellation_rejected: "red",
      cancellation_refunded: "var(--success-color)",
    
      return_requested: "var(--secondary-color)",
      returned: "var(--dangerlight-color)",
      return_rejected: "var(--warning-color)",
      return_refunded: "var(--success-color)",
    
      refunded: "var(--success-color)",
    
      // New RTO statuses
      rto_requested: "var(--warningdark-color)",
      rto_rejected: "red",
      rto_approved: "var(--success-color)",
      rto_in_progress: "blueviolet",
      rto_delivered: "var(--info-color)",
      rto_verified: "var(--successdark-color)",
      rto_refunded: "var(--success-color)"
    },
    orderPages: {
      allOrders: {
        title: "allOrders",
        statuses: ["ALL"]
      },
      pendingOrders: {
        title: "pendingOrders",
        statuses: ["PENDING"]
      },
      newOrders: {
        title: "newOrders",
        statuses: ["PLACED"]
      },
      confirmedOrders: {
        title: "confirmedOrders",
        statuses: ["CONFIRMED"]
      },
      processingOrders: {
        title: "processingOrders",
        statuses: ["IN_PROCESS"]
      },
      readyToDispatchOrders: {
        title: "readyToDispatchOrders",
        statuses: ["READY_TO_DISPATCH"]
      },
      onTheWayOrders: {
        title: "onTheWayOrders",
        statuses: ["SHIPPED", "IN_TRANSIT"]
      },
      deliveredOrders: {
        title: "deliveredOrders",
        statuses: ["DELIVERED"]
      },
    
      // After-sale statuses
      cancelled: {
        title: "cancelled_orders",
        statuses: ["CANCELLED"]
      },
      returns: {
        title: "returns",
        statuses: ["ALLRETURNS"],
        showOrderStatuses: false
      },  
      cancellation_requested: {
        title: "cancellation_requested_orders",
        statuses: ["CANCELLATION_REQUESTED"]
      },
      cancellation_rejected: {
        title: "cancellation_rejected_orders",
        statuses: ["CANCELLATION_REJECTED"]
      },
      cancellation_refunded: {
        title: "cancellation_refunded_orders",
        statuses: ["CANCELLATION_REFUNDED"]
      },
      return_requested: {
        title: "return_requested_orders",
        statuses: ["RETURN_REQUESTED"]
      },
      returned: {
        title: "returned_orders",
        statuses: ["RETURNED"]
      },
      return_rejected: {
        title: "return_rejected_orders",
        statuses: ["RETURN_REJECTED"]
      },
      return_refunded: {
        title: "return_refunded_orders",
        statuses: ["RETURN_REFUNDED"]
      },
    
      // New RTO pages
      rto_requested: {
        title: "rto_requested_orders",
        statuses: ["RTO_REQUESTED"]
      },
      rto_rejected: {
        title: "rto_rejected_orders",
        statuses: ["RTO_REJECTED"]
      },
      rto_approved: {
        title: "rto_approved_orders",
        statuses: ["RTO_APPROVED"]
      },
      rto_in_progress: {
        title: "rto_in_progress_orders",
        statuses: ["RTO_IN_PROGRESS"]
      },
      rto_delivered: {
        title: "rto_delivered_orders",
        statuses: ["RTO_DELIVERED"]
      },
      rto_verified: {
        title: "rto_verified_orders",
        statuses: ["RTO_VERIFIED"]
      },
      rto_refunded: {
        title: "rto_refunded_orders",
        statuses: ["RTO_REFUNDED"]
      }
    },  
    confirmedOrders: "Confirmed Orders",
    processingOrders: "Processing Orders",
    readyToDispatchOrders: "Ready To Dispatch Orders",
    onTheWayOrders: "On the way Orders",
    deliveredOrders: "Delivered Orders",
    cancelled_orders: "Cancelled Orders",
    cancellation_requested_orders: "Cancellation Requested Orders",
    return_requested_orders: "Return Requested Orders",
    return_refunded_orders: "Return Refunded Orders",
    returns: "Returns",
    returned_orders: "Returned Orders",
    return_rejected_orders: "Return Rejected Orders",
    cancellation_rejected_orders: "Cancellation Rejected Orders",
    cancellation_refunded_orders: "Cancellation Refunded Orders",
    rto_requested_orders: "RTO Requested Orders",
    rto_rejected_orders: "RTO Rejected Orders",
    rto_approved_orders: "RTO Approved Orders",
    rto_in_progress_orders: "RTO In Progress Orders",
    rto_delivered_orders: "RTO Delivered Orders",
    rto_verified_orders: "RTO Verified Orders",
    rto_refunded_orders: "RTO Refunded Orders",
    moreOptions: "More options",
    details: "Details",
    viewProductPage: "View Product Page",
    viewSize: "View Size",
    trackStatus: "Track Status",
    auditTrail: "Audit Trail",
    changedFrom: "Changed from",
    changedTo: "Changed to",
    entityType: "Entity type",
    entityId: "Entity Id",
    performedBy: "Performed by",
    timestamp: "Timestamp",
    trackingDetails: "Tracking Details",
    noDetailsFound: "No Details Found",
    userDetails: 'User Details',
    followUs: "Follow Us",
    allRightsReserved: "All Rights Reserved",
    fastAndSecured: "Fast and Secured Payment Options",
    company: "Company",
    myAccount: "My Account",
    home: "Home",
    account: "Account",
    search: "Search",
    cart: "Cart",
    language: "Language",
    somethingWentWrong: "Something went wrong!",
    note: "Note",
    notAllowed1: "You are not allowed to login in this Application",
    notAllowed2: "Only Admin and manager have access to this",
    notAllowed3: "If you are one and still can't access contact admin",
    logOutAndBackToHome: "Log Out and go back to home",
    whatsAppUs: "WhatsApp Us",
    ourContactDetails: "Our Contact Details",
    workingHours: "Working Hours",
    instagram: "Instagram",
    facebook: "Facebook",
    x: "X (Twitter)",
    threads: "Threads",
    youtube: "Youtube",
    pinterest: "Pinterest",
    quotaUsage: "Mail/SMS Quota Usage",
    used: "Used",
    remaining: "Remaining",
    totalQuota: "Total Quota",
    sms: "SMS",
    whatsapp: "WhatsApp",
    brevo: "Brevo",
    count: "Count",
    date: "Date",
    gmail: "Gmail",
    quota: "Quota",
    teamUsers: "Team",
    member: "Member",
    customer: "Customer",
    profileImage: "Profile Image",
    gender: "Gender",
    role: "Role",
    activatedText: "Activated",
    selectRolePlaceholder: "Select the Role",
    accountActiveLabel: "Kindly select if user's account should be active/inactive:",
    user: "User",
    actions: "Actions",
    setAsDiscontinued: "Set as Discontinued",
    resetToDefaultPassword: "Reset to default Password",
    confirmMsg: "Are you Sure. You want <b>{0}</b> {1} to {2}?",
    discontinued: "Discontinued",
    base: "Base",
    setActive: "set Active",
    refresh: "Refresh",
    about: "About",
    resume: "Resume",
    portfolio: "Portfolio",
    services: "Services",
    contact: "Contact",
    contactMe: "Contact Me",
    birthday: "Birthday",
    age: "Age",
    degree: "Degree",
    freelance: "Freelance",
    available: "Available",
    education: "Education",
    projects: "Projects",
    languages: "Languages",
    // --- Sidebar / User Widget ---
    accountInstruction1: "Manage your details",

    // --- About Section ---
    aboutDesc: "Learn more about me",

    // --- Resume Section ---
    resumeDesc: "A timeline of my professional experience and education:",
    summary: "Summary",
    professionalExperience: "Professional Experience",

    // --- Services Section ---
    servicesDesc: "Technical solutions and services I provide:",
    
    // --- Skills Section ---
    skillsDesc: "My technical proficiency and toolset:",

    // --- Portfolio Section ---
    portfolioDesc: "A showcase of my recent projects and work:",
    app: "App",
    web: "Web",
    branding: "Branding",
    books: "Books",
    // Add any specific categories found in your Properties.json here
    
    // --- Contact Section ---
    contactDesc: "Feel free to reach out for collaborations or opportunities",
    callUs: "Call Us",
    emailUs: "Email Us",
    yourName: "Your Name",
    yourEmail: "Your Email",
    subject: "Subject",
    message: "Message",
    sendMessage: "Send Message",
    messageSent: "Your message has been sent. Thank you!",
    dobShort: "DOB",
    intellij: "IntelliJ IDEA",
    vscode: "VS Code",
    eclipse: "Eclipse",
    git: "Git",
    aws: "AWS",
    github: "GitHub",
    mysql: "MySQL",
    mongodb: "MongoDB",
    docker: "Docker",
    jenkins: "Jenkins",
    jira: "Jira",
    postman: "Postman",
    toolsTitle: "Tools and Technologies I use"
  };
  
  export default en;
  