const gu = {
    login: "લોગ ઇન",
    signup: "સાઇન અપ",
    forgotPassword: "પાસવર્ડ ભૂલી ગયા છો?",
    welcome: "સ્વાગત છે, વપરાશકર્તા!",
    logout: "લોગ આઉટ",
    requiredField: "આ ફીલ્ડ ફરજિયાત છે.",
    invalidEmail: "કૃપા કરીને માન્ય ઇમેઇલ સરનામું દાખલ કરો.",
    name: "નામ",
    fullNamePlaceholder: "તમારું નામ દાખલ કરો",
    firstName: "પ્રથમ નામ",
    lastName: "અટક",
    mobileOrEmail: "ઇમેઇલ આઈડી અથવા મોબાઈલ નંબર",
    firstNamePlaceHolder: "તમારું પ્રથમ નામ દાખલ કરો",
    lastNamePlaceHolder: "તમારી અટક દાખલ કરો",
    email: "ઇમેઇલ",
    emailPlaceHolder: "તમારો ઇમેઇલ દાખલ કરો",
    mobile: "મોબાઈલ નંબર",
    mobilePlaceHolder: "તમારો મોબાઈલ નંબર દાખલ કરો",
    receiveOTP: "તમને આ {0} પર OTP મળશે.",
    pleaseWait: "કૃપા કરીને રાહ જુઓ...",
    fetchingDataFailedTitle: "વિનંતી કરેલ ડેટા મેળવવામાં અસમર્થ.",
    failureMessage: "તમારી વિનંતી પર પ્રક્રિયા કરતી વખતે અમને ભૂલનો સામનો કરવો પડ્યો.",
    technicalGlitch: "આ કામચલાઉ ખામીને કારણે હોઈ શકે છે. થોડા સમય પછી ફરી પ્રયાસ કરો.",
    contactSupport: "<a href=\"{supportEmail}\" style=\"text-decoration:none; target=\"_blank\" rel=\"noopener noreferrer\" color: #27c0e0;\">{supportEmail}</a> પર સપોર્ટનો સંપર્ક કરો.",
    register: "રજીસ્ટર",
    registering: "રજીસ્ટર થઈ રહ્યું છે....",
    submitOTP: "OTP ચકાસો",
    submittingOTP: "OTP ચકાસાઈ રહ્યો છે....",
    otp: "OTP",
    otpPlaceholder: "OTP દાખલ કરો",
    enterOTP: "કૃપા કરીને ({value}) પર મળેલો OTP દાખલ કરો.",
    signedUp: "તમે સફળતાપૂર્વક સાઇન અપ કર્યું છે!",
    failedToSignUp: "સાઇન અપ કરવામાં નિષ્ફળ.",
    loggedIn: "તમે સફળતાપૂર્વક લોગ ઇન થયા છો!",
    failedToLogIn: "લોગ ઇન કરવામાં નિષ્ફળ.",
    resendOTP: "OTP ફરી મોકલો",
    resendingOTP: "OTP ફરી મોકલાઈ રહ્યો છે....",
    password: "પાસવર્ડ",
    logingin: "લોગ ઇન થઈ રહ્યું છે",
    passwordPlaceHolder: "તમારો પાસવર્ડ દાખલ કરો",
    otpChild1: "OTP ખોટો હોઈ શકે છે",
    otpChild2: "OTP ની મુદત પૂરી થઈ ગઈ હોઈ શકે છે.",
    otpChild3: "નેટવર્ક સમસ્યા હોઈ શકે છે.",
    otpChild4: "સર્વર ડાઉન હોઈ શકે છે",
    passwordRequirementMsg: "તમારા એકાઉન્ટને સુરક્ષિત રાખવા માટે, ઓછામાં ઓછા આઠ (8) અક્ષરોનો પાસવર્ડ બનાવો, જેમાં સામેલ હોય:",
    passwordRequireMent: "પાસવર્ડ જરૂરિયાતો",
    upperLowerCase: "અપર અને લોઅર કેસ (Upper & Lower Case)",
    subHeadingIns: "મજબૂત પાસવર્ડ માટે, તમારો પાસવર્ડ નીચેના મુદ્દાઓનું પાલન કરતો હોવો જોઈએ",
    minimum8Char: "ઓછામાં ઓછા 8 અક્ષરો (ફરજિયાત)",
    atLeastOneNumericals: "ઓછામાં ઓછો એક અંક (ફરજિયાત)",
    numericals: "અંકો",
    specialChar: "ખાસ અક્ષરો",
    oneUpperCase: "ઓછામાં ઓછો એક કેપિટલ અક્ષર (ફરજિયાત)",
    oneLowerCase: "ઓછામાં ઓછો એક સ્મોલ અક્ષર (ફરજિયાત)",
    partnerCompanyName: "ભાગીદાર કંપનીનું નામ",
    atLeastOneSpecialChar: "ઓછામાં ઓછો એક ખાસ અક્ષર (ફરજિયાત)",
    skip: "છોડો",
    confirmPassword: "પાસવર્ડની પુષ્ટિ કરો",
    setPassword: "પાસવર્ડ સેટ કરો",
    accountInstruction: "એકાઉન્ટ એક્સેસ કરવા અને ઓર્ડર મેનેજ કરવા માટે",
    aboutUs: "અમારા વિશે",
    contactUs: "સંપર્ક કરો",
    profile: "પ્રોફાઇલ",
    orders: "ઓર્ડર",
    wishlist: "વિશલિસ્ટ",
    loginSignup: "લોગ ઇન/સાઇન અપ",
    welcome: "સ્વાગત છે",
    profileImgUpdated: "પ્રોફાઇલ ઇમેજ સફળતાપૂર્વક અપડેટ થઈ",
    save: "સાચવો",
    cancel: "રદ કરો",
    adjustImage: "ઇમેજ એડજસ્ટ કરો",
    dragSqrToChangeImgSizePos: "સાઇઝ અને પોઝિશન બદલવા માટે ચોરસ ખેંચો.",
    preview: "પ્રિવ્યૂ",
    imageCropped: "ક્રોપ કરેલી ઇમેજ સફળતાપૂર્વક સેવ થઈ!",
    alternateMobile: "વૈકલ્પિક મોબાઈલ નંબર",
    male: "પુરુષ",
    female: "સ્ત્રી",
    others: "અન્ય",
    genderLabel: "કૃપા કરીને તમારું લિંગ પસંદ કરો:",
    dob: "જન્મ તારીખ",
    update: "અપડેટ",
    changePassword: "પાસવર્ડ બદલો",
    updatePassword: "પાસવર્ડ અપડેટ કરો",
    updateProfile: "પ્રોફાઇલ અપડેટ કરો",
    oldPassword: "જૂનો પાસવર્ડ",
    confirmPasswordNotMatchPassword: "કન્ફર્મ પાસવર્ડ પાસવર્ડ સાથે મેળ ખાતો નથી.",
    passReqNotFulfil: "પાસવર્ડની જરૂરિયાતો પૂરી થઈ નથી.",
    passwordUpdated: "પાસવર્ડ સફળતાપૂર્વક અપડેટ થયો!",
    profileUpdated: "પ્રોફાઇલ સફળતાપૂર્વક અપડેટ થઈ!",
    pageNotFound: "પેજ મળ્યું નથી",
    brokenLinkMsg1: "તમે ક્લિક કરેલી લિંક તૂટેલી હોઈ શકે છે અથવા પેજ દૂર કરવામાં આવ્યું હોઈ શકે છે.",
    brokenLinkMsg2: "હોમ પેજની મુલાકાત લો અથવા સમસ્યા વિશે અમારો સંપર્ક કરો.",
    backToHome: "હોમ પેજ પર પાછા જાઓ",
    dashboard: "ડેશબોર્ડ",
    pages: "પેજ",
    inventory: "ઇન્વેન્ટરી",
    customOrders: "કસ્ટમ ઓર્ડર",
    team: "ટીમ",
    customers: "ગ્રાહકો",
    settings: "સેટિંગ્સ",
    messages: "મેસેજ",
    pendingOrders: "બાકી ઓર્ડર",
    completedOrders: "પૂર્ણ થયેલા ઓર્ડર",
    offers: "ઓફર",
    id: "આઈડી",
    name: "નામ",
    brand: "બ્રાન્ડ",
    category: "કેટેગરી",
    price: "કિંમત",
    status: "સ્થિતિ",
    createdDate: "બનાવ્યાની તારીખ",
    updatedDate: "છેલ્લે અપડેટ કરેલ",
    action: "ક્રિયા",
    productName: "ઉત્પાદનનું નામ",
    size: "સાઇઝ",
    color: "રંગ",
    sku: "SKU",
    stockQuantity: "જથ્થો",
    products: "ઉત્પાદનો",
    description: "વર્ણન",
    parent: "પેરન્ટ",
    namePlaceholder: "નામ દાખલ કરો",
    descriptionPlaceholder: "વર્ણન દાખલ કરો",
    categoryPlaceholder: "કેટેગરી પસંદ કરો",
    categoryLevel: "કેટેગરી {0} સ્તર ",
    at: "પર",
    modifiedOn: "સુધારેલ તારીખ",
    today: "આજે",
    edit: "એડિટ કરો",
    delete: "ડિલીટ કરો",
    activated: "{entity} સક્રિય છે.",
    deactivated: "{entity} નિષ્ક્રિય છે.",
    yes: "હા",
    no: "ના",
    confirm: "પુષ્ટિ કરો",
    deleteMsg: "શું તમે ચોક્કસ છો? તમે <b>{0}</b> {1} ડિલીટ કરવા માંગો છો?",
    childrenOf: "ના સંતાનો ",
    page: "પેજ",
    add: "ઉમેરો",
    deactivateFirst: "પહેલા {entity} ને નિષ્ક્રિય કરો.",
    activeCantAction: "સક્રિય {entity} પર {action} કરી શકાતું નથી.",
    entityIsActive: "<b>{0}</b> {entity} સક્રિય છે.",
    searchPlaceHolder: "{entity} શોધો...",
    copy: "કોપી કરો",
    deleted: "ડિલીટ કરેલ",
    edited: "એડિટ કરેલ",
    product: "ઉત્પાદન",
    title: "શીર્ષક",
    titlePlaceholder: "શીર્ષક દાખલ કરો",
    image: "ઇમેજ",
    material: "મટિરિયલ",
    materialPlaceholder: "મટિરિયલ દાખલ કરો",
    colorPlaceholder: "રંગ દાખલ કરો",
    sku: "SKU કોડ",
    skuPlaceholder: "યુનિક SKU કોડ દાખલ કરો",
    quantity: "જથ્થો",
    type: "પ્રકાર",
    productName: "ઉત્પાદનનું નામ",
    selectProductPlaceholder: "ઉત્પાદન પસંદ કરો",
    sizeChart: "સાઇઝ ચાર્ટ",
    enterMeasure: "તમારું {0} માપ દાખલ કરો",
    chest: "છાતી",
    hips: "નિતંબ (Hips)",
    neck: "ગળું",
    sleeve: "બાંય (Sleeve)",
    arm: "હાથ",
    topLength: "ટોપની લંબાઈ",
    shoulder: "ખભો",
    inseam: "ઇનસીમ",
    bottomLength: "નીચેની લંબાઈ",
    thigh: "સાથળ",
    waist: "કમર",
    topBody: "શરીરનો ઉપરનો ભાગ",
    bottomBody: "શરીરનો નીચેનો ભાગ",
    rank: "રેન્ક",
    sale: "વેચાણ",
    rental: "ભાડે",
    selectRankPlaceholder: "રેન્ક પસંદ કરો",
    mrp: "MRP",
    salePrice: "વેચાણ કિંમત",
    discount: "ડિસ્કાઉન્ટ",
    selectSizePlaceholder: "સાઇઝ પસંદ કરો",
    mrpPlaceholder: "MRP દાખલ કરો (₹)",
    salePricePlaceholder: "વેચાણ કિંમત દાખલ કરો (₹)",
    discountPlaceholder: "ડિસ્કાઉન્ટ દાખલ કરો (%)",
    quantityPlaceholder: "જથ્થો દાખલ કરો",
    saleOrRentPrice: "વેચાણ/ભાડાની કિંમત",
    security: "સિક્યુરિટી ડિપોઝિટ",
    securityPlaceholder: "રિફન્ડેબલ = ડિપોઝિટ - (ભાડાની કિંમત - ડિસ્કાઉન્ટ %)",
    size_Quant_Price: "સાઇઝ - જથ્થો - વેચાણ કિંમત",
    view: "જુઓ",
    webSettings: "વેબ સેટિંગ્સ",
    siteUnderMaintenance: "સાઇટ મેન્ટેનન્સ હેઠળ છે",
    weWillGetbackShortly: "અમે ટૂંક સમયમાં પાછા આવીશું. કૃપા કરીને પછીથી ફરી તપાસો.",
    reload: "રીલોડ",
    enableWebsite: "વેબસાઇટ સક્ષમ અથવા અક્ષમ કરવા માટે ક્લિક કરો.",
    website: "વેબસાઇટ",
    switchOnOffWebsite: "વેબસાઇટ ચાલુ/બંધ કરો",
    webConfigs: "વેબસાઇટ કોન્ફિગરેશન",
    webTrendingBar: "વેબસાઇટ ટ્રેન્ડિંગ બાર",
    websiteId: "વેબસાઇટ આઈડી",
    path: "પાથ",
    pathPlaceholder: "ખોલવા માટેનો પાથ દાખલ કરો",
    homePage: "હોમ પેજ",
    homePageCarousel: "હોમ પેજ કેરોયુઝલ",
    forPC: "PC માટે:",
    forMobile: "મોબાઈલ માટે:",
    reset: "રીસેટ",
    customFitting: "કસ્ટમ ફિટિંગ",
    customDesigning: "કસ્ટમ ડિઝાઇનિંગ",
    freeDelivery: "ફ્રી ડિલિવરી",
    assuredRefunds: "ખાતરીપૂર્વકનું રિફન્ડ",
    sizes: "સાઇઝ",
    addresses: "સરનામાં",
    isTileVisible: "શું ટાઇલ દેખાય છે?",
    isTileVisibleGrid: "ટાઇલ દેખાય છે",
    categories: "કેટેગરીઝ",
    mrpWithDots: "M.R.P",
    rtd: "ડિસ્પેચ માટે તૈયાર",
    inclusiveTax: "તમામ ટેક્સ સહિતની કિંમત",
    rentInclusiveTax: "તમામ ટેક્સ સહિતનું ભાડું",
    purchase: "ખરીદો",
    rent: "ભાડે",
    refundableSecurity: "રિફન્ડેબલ સિક્યુરિટી ડિપોઝિટ",
    securityDeposit: "સિક્યુરિટી ડિપોઝિટ",
    refundSecurity: "વસ્તુ પરત કર્યા પછી, તમારી સિક્યુરિટી ડિપોઝિટ રિફન્ડ કરવામાં આવશે.",
    securityDepositDeduction: "તમે ડિલિવરીના 5 દિવસમાં વસ્તુ પરત કરી શકો છો. તે પછી દર 5 દિવસ માટે તમારી સિક્યુરિટી ડિપોઝિટમાંથી ભાડાની રકમ કાપવામાં આવશે.",
    sizeGuide: "સાઇઝ ગાઇડ",
    customSize: "કસ્ટમ સાઇઝ",
    loginToAddCustomSize: "કસ્ટમ સાઇઝ ઉમેરવા અને જોવા માટે લોગ ઇન/સાઇન અપ કરો",
    yourCustomSizes: "તમારી કસ્ટમ સાઇઝ",
    undoWishlistMsg: "તમે વિશલિસ્ટમાંથી <b>{name}</b> ને દૂર કર્યું છે",
    undo: "અનડૂ (Undo)",
    textPlaceholder: "{0} દાખલ કરો",
    address: "સરનામું",
    fullName: "નામ",
    city: "શહેર",
    country: "દેશ",
    pinCode: "પિન કોડ",
    state: "રાજ્ય",
    landmark: "લેન્ડમાર્ક",
    streetAddress1: "ફ્લેટ, હાઉસ નં., બિલ્ડિંગ, કંપની, એપાર્ટમેન્ટ",
    streetAddress2: "વિસ્તાર, શેરી, સેક્ટર, ગામ",
    defaultAddress: "ડિફોલ્ટ સરનામાં તરીકે સેટ કરો",
    setDefault: "ડિફોલ્ટ સેટ કરો",
    default: "ડિફોલ્ટ",
    addToCart: "કાર્ટમાં ઉમેરો",
    buyNow: "અત્યારે ખરીદો",
    total: "કુલ",
    clearCart: "કાર્ટ ખાલી કરો",
    proceedToCheckout: "ચેકઆઉટ પર જાઓ",
    shoppingCart: "શોપિંગ કાર્ટ",
    loadingCart: "કાર્ટ લોડ થઈ રહ્યું છે...",
    emptyCart: "તમારું કાર્ટ ખાલી છે.",
    emptyWishlist: "તમારી વિશલિસ્ટ ખાલી છે.",
    deSelectAll: "બધી વસ્તુઓ અનસિલેક્ટ કરો",
    invalidCoupon: "અમાન્ય કૂપન કોડ",
    couponApplied: "કૂપન લાગુ થયું: ",
    apply: "લાગુ કરો",
    freeCaps: "ફ્રી",
    deliveryCharges: "ડિલિવરી ચાર્જ",
    subTotal: "પેટા-કુલ (SubTotal)",
    changeSize: "સાઇઝ બદલો",
    moveToWishlist: "વિશલિસ્ટમાં ખસેડો",
    share: "શેર કરો",
    orderSummary: "ઓર્ડર સારાંશ",
    coupon: "કૂપન",
    itemsForPurchasing: "ખરીદી માટે પસંદ કરેલી વસ્તુઓ",
    itemsForRenting: "ભાડા માટે પસંદ કરેલી વસ્તુઓ",
    itemsSelected: "પસંદ કરેલી વસ્તુઓ",
    applyCoupon: "કૂપન લાગુ કરો",
    undoCartMsg: 'કાર્ટમાંથી <strong>{name}</strong> દૂર કર્યું. ',
    itemRestored: "વસ્તુ કાર્ટમાં પાછી આવી",
    selectAll: "બધું પસંદ કરો",
    itemMovedToWishlist: "વસ્તુ વિશલિસ્ટમાં ખસેડવામાં આવી.",
    itemRemoved: "વસ્તુ કાર્ટમાંથી દૂર કરવામાં આવી",
    addedToCart: "વસ્તુ કાર્ટમાં ઉમેરવામાં આવી",
    itemAddedToWishlist: "વસ્તુ વિશલિસ્ટમાં ઉમેરવામાં આવી",
    itemRemovedFromWishlist: "વસ્તુ વિશલિસ્ટમાંથી દૂર કરવામાં આવી",
    proceedToBuy: "ખરીદવા માટે આગળ વધો",
    change: "બદલો",
    checkout: "ચેકઆઉટ",
    deliverHere: "અહીં ડિલિવરી કરો",
    selectDeliveryAddress: "ડિલિવરી સરનામું પસંદ કરો",
    selectedDeliveryAddress: "પસંદ કરેલ ડિલિવરી સરનામું",
    inventoryType: "ઇન્વેન્ટરી પ્રકાર",
    currentlyDefaultAddress: "ડિફોલ્ટ સરનામું",
    chosenAddressUpdated: "પસંદ કરેલ સરનામું સફળતાપૂર્વક અપડેટ થયું.",
    draftUpdated: "ઓર્ડરની વિગતો સફળતાપૂર્વક અપડેટ થઈ.",
    proceedToCheckout: "ચેકઆઉટ પર આગળ વધ્યા.",
    deliveringTo: "અહીં ડિલિવરી થઈ રહી છે",
    addNew: "નવું ઉમેરો",
    itemsInOrder: "ઓર્ડરની વસ્તુઓ",
    shipTogether: "બધી વસ્તુઓ સાથે મોકલો",
    shipAsap: "દરેક વસ્તુ તૈયાર થાય કે તરત મોકલો",
    shipItems: "તમે તમારા ઓર્ડરનું શિપમેન્ટ ક્યારે ઈચ્છો છો?",
    shipItemsForOrder: "{user} ઓર્ડરનું શિપમેન્ટ ક્યારે ઈચ્છે છે?",
    orderPlacedTitle: "આભાર, તમારો ઓર્ડર આપી દેવામાં આવ્યો છે!",
    orderConfirmationSent: "તમારા ઇમેઇલ પર પુષ્ટિ મોકલવામાં આવી છે.",
    orderId: "ઓર્ડર આઈડી",
    itemsInTheOrder: "ઓર્ડરની વસ્તુઓ",
    viewOrders: "તમારા ઓર્ડર જુઓ",
    viewAllOrders: "બધા ઓર્ડર જુઓ",
    continueShopping: "ખરીદી ચાલુ રાખો",
    orderDetails: "ઓર્ડરની વિગતો",
    appliedCoupon: "લાગુ કરેલ કૂપન",
    orderPlacedOn: "ઓર્ડરની તારીખ",
    shipTo: "અહીં મોકલો",
    noOrdersFound: "કોઈ ઓર્ડર મળ્યા નથી",
    yourOrders: "તમારા ઓર્ડર",
    paymentMode: "પેમેન્ટ મોડ",
    paymentMethod: "પેમેન્ટ પદ્ધતિ",
    all: "બધા",
    pending: "બાકી",
    shipped: "મોકલી દીધેલ",
    delivered: "ડિલિવર થયેલ",
    cancelled: "રદ કરેલ",
    allOrders: "બધા ઓર્ડર",
    newOrders: "નવા ઓર્ડર",
    statusMessages: {
        forOrder: {
            forManager: {
                draft: "ઓર્ડર ડ્રાફ્ટમાં છે અને હજુ અપાયો નથી.",
                pending: "પેમેન્ટ બાકી છે.",
                placed: "ઓર્ડર અપાઈ ગયો છે અને તમારી પુષ્ટિની રાહ જોઈ રહ્યો છે.",
                confirmed: "તમે ઓર્ડરની પુષ્ટિ કરી છે.",
                payment_failed: "પેમેન્ટ નિષ્ફળ રહ્યું.",
                in_process: "ઓર્ડર પર પ્રક્રિયા થઈ રહી છે.",
                ready_to_dispatch: "ઓર્ડર રવાના કરવા માટે તૈયાર છે.",
                shipped: "ઓર્ડર મોકલી દેવામાં આવ્યો છે.",
                in_transit: "ઓર્ડર રસ્તામાં છે.",
                delivered: "ઓર્ડર ડિલિવર થઈ ગયો છે.",
                cancelled: "ઓર્ડર રદ કરવામાં આવ્યો છે.",
                cancellation_requested: "વપરાશકર્તાએ રદ કરવાની વિનંતી કરી છે.",
                cancellation_rejected: "તમે રદ કરવાની વિનંતી નકારી છે.",
                cancellation_refunded: "ઓર્ડર રદ થયો અને પેમેન્ટ રિફન્ડ થયું.",
                return_requested: "ઓર્ડર માટે પરત કરવાની વિનંતીઓ.",
                return_rejected: "તમે પરત કરવાની વિનંતી નકારી છે.",
                returned: "ઓર્ડર પરત મળ્યો છે.",
                return_refunded: "પરત મળ્યા પછી પેમેન્ટ રિફન્ડ થયું.",
                refunded: "પેમેન્ટ રિફન્ડ કરવામાં આવ્યું છે.",
                rto_requested: "તમારા દ્વારા RTO ની વિનંતી કરવામાં આવી છે.",
                rto_rejected: "તમે RTO વિનંતી નકારી છે.",
                rto_approved: "તમે RTO વિનંતી મંજૂર કરી છે.",
                rto_in_progress: "RTO પ્રક્રિયામાં છે.",
                rto_delivered: "ઓર્ડર RTO દ્વારા તમને પરત મળ્યો છે.",
                rto_verified: "RTO વસ્તુઓની તમારા દ્વારા ચકાસણી કરવામાં આવી છે.",
                rto_refunded: "RTO પછી ગ્રાહકને પેમેન્ટ રિફન્ડ થયું."
            },
            forUser: {
                draft: "તમારો ઓર્ડર ચેકઆઉટમાં છે પણ હજુ અપાયો નથી.",
                pending: "પેમેન્ટ બાકી છે. કૃપા કરીને તમારું પેમેન્ટ પૂર્ણ કરો.",
                placed: "તમારો ઓર્ડર અપાઈ ગયો છે અને પુષ્ટિની રાહ જોવાઈ રહી છે.",
                confirmed: "વિક્રેતા દ્વારા તમારા ઓર્ડરની પુષ્ટિ કરવામાં આવી છે.",
                payment_failed: "પેમેન્ટ નિષ્ફળ ગયું. કૃપા કરીને ફરી પ્રયાસ કરો.",
                in_process: "વિક્રેતા દ્વારા તમારા ઓર્ડર પર પ્રક્રિયા થઈ રહી છે.",
                ready_to_dispatch: "તમારો ઓર્ડર રવાના કરવા માટે તૈયાર છે.",
                shipped: "તમારો ઓર્ડર મોકલી દેવામાં આવ્યો છે.",
                in_transit: "તમારો ઓર્ડર રસ્તામાં છે.",
                delivered: "તમારો ઓર્ડર ડિલિવર થઈ ગયો છે.",
                cancelled: "તમારો ઓર્ડર રદ કરવામાં આવ્યો છે.",
                cancellation_requested: "તમે આ ઓર્ડર રદ કરવાની વિનંતી કરી છે.",
                cancellation_rejected: "તમારી રદ કરવાની વિનંતી નકારવામાં આવી છે.",
                cancellation_refunded: "તમારી રદ કરવાની વિનંતી સ્વીકારાઈ અને પેમેન્ટ રિફન્ડ થયું.",
                return_requested: "તમારા ઓર્ડર માટે પરત કરવાની વિનંતી સબમિટ કરવામાં આવી છે.",
                return_rejected: "તમારી પરત કરવાની વિનંતી નકારવામાં આવી છે.",
                returned: "તમારો ઓર્ડર પરત કરી દેવામાં આવ્યો છે.",
                return_refunded: "પરત કર્યા પછી તમારું પેમેન્ટ રિફન્ડ થઈ ગયું છે.",
                refunded: "તમારું પેમેન્ટ રિફન્ડ થઈ ગયું છે.",
                rto_requested: "ઓર્ડર માટે RTO ની વિનંતી કરવામાં આવી છે.",
                rto_rejected: "વિક્રેતાએ RTO વિનંતી નકારી છે.",
                rto_approved: "વિક્રેતાએ આ ઓર્ડર માટે RTO મંજૂર કર્યું છે.",
                rto_in_progress: "તમારો ઓર્ડર RTO ના રસ્તે છે.",
                rto_delivered: "તમારો ઓર્ડર RTO દ્વારા વિક્રેતાને પરત મળ્યો છે.",
                rto_verified: "તમારા પરત કરેલા ઓર્ડરની વિક્રેતા દ્વારા ચકાસણી કરવામાં આવી છે.",
                rto_refunded: "RTO પછી તમને રિફન્ડ મળી ગયું છે."
            }
        },
        forItem: {
            forManager: {
                draft: "વસ્તુ ઓર્ડર ડ્રાફ્ટમાં ઉમેરાઈ છે અને હજુ અપાઈ નથી.",
                pending: "આ વસ્તુનું પેમેન્ટ બાકી છે.",
                placed: "વસ્તુનો ઓર્ડર અપાઈ ગયો છે અને તમારી પુષ્ટિની રાહ જોવાઈ રહી છે.",
                confirmed: "તમે આ વસ્તુની પુષ્ટિ કરી છે.",
                payment_failed: "આ વસ્તુનું પેમેન્ટ નિષ્ફળ રહ્યું.",
                in_process: "વસ્તુ પર પ્રક્રિયા થઈ રહી છે.",
                ready_to_dispatch: "વસ્તુ રવાના કરવા માટે તૈયાર છે.",
                shipped: "વસ્તુ મોકલી દેવામાં આવી છે.",
                in_transit: "વસ્તુ રસ્તામાં છે.",
                delivered: "વસ્તુ ડિલિવર થઈ ગઈ છે.",
                cancelled: "આ વસ્તુ રદ કરવામાં આવી છે.",
                cancellation_requested: "વપરાશકર્તાએ આ વસ્તુ રદ કરવાની વિનંતી કરી છે.",
                cancellation_rejected: "તમે આ વસ્તુ રદ કરવાની વિનંતી નકારી છે.",
                cancellation_refunded: "આ વસ્તુ રદ થઈ અને પેમેન્ટ રિફન્ડ થયું.",
                return_requested: "વપરાશકર્તાએ આ વસ્તુ પરત કરવાની વિનંતી કરી છે.",
                return_rejected: "તમે આ વસ્તુ પરત કરવાની વિનંતી નકારી છે.",
                returned: "વસ્તુ પરત મળી છે.",
                return_refunded: "પરત મળેલ વસ્તુનું પેમેન્ટ રિફન્ડ થયું.",
                refunded: "આ વસ્તુનું પેમેન્ટ રિફન્ડ કરવામાં આવ્યું છે.",
                rto_requested: "આ વસ્તુ માટે RTO ની વિનંતી કરવામાં આવી છે.",
                rto_rejected: "તમે આ વસ્તુ માટે RTO વિનંતી નકારી છે.",
                rto_approved: "તમે આ વસ્તુ માટે RTO વિનંતી મંજૂર કરી છે.",
                rto_in_progress: "આ વસ્તુ માટે RTO પ્રક્રિયામાં છે.",
                rto_delivered: "આ વસ્તુ તમને પરત મળી છે.",
                rto_verified: "આ પરત આવેલી વસ્તુ ચકાસવામાં આવી છે.",
                rto_refunded: "RTO પછી આ વસ્તુનું પેમેન્ટ રિફન્ડ થયું."
            },
            forUser: {
                draft: "આ વસ્તુ ચેકઆઉટમાં છે પણ હજુ અપાઈ નથી.",
                pending: "આ વસ્તુનું પેમેન્ટ બાકી છે. કૃપા કરીને તમારું પેમેન્ટ પૂર્ણ કરો.",
                placed: "આ વસ્તુનો ઓર્ડર અપાઈ ગયો છે અને પુષ્ટિની રાહ જોવાઈ રહી છે.",
                confirmed: "વિક્રેતા દ્વારા આ વસ્તુની પુષ્ટિ કરવામાં આવી છે.",
                payment_failed: "આ વસ્તુનું પેમેન્ટ નિષ્ફળ ગયું. કૃપા કરીને ફરી પ્રયાસ કરો.",
                in_process: "વિક્રેતા દ્વારા આ વસ્તુ પર પ્રક્રિયા થઈ રહી છે.",
                ready_to_dispatch: "આ વસ્તુ રવાના કરવા માટે તૈયાર છે.",
                shipped: "આ વસ્તુ મોકલી દેવામાં આવી છે.",
                in_transit: "આ વસ્તુ રસ્તામાં છે.",
                delivered: "આ વસ્તુ ડિલિવર થઈ ગઈ છે.",
                cancelled: "આ વસ્તુ રદ કરવામાં આવી છે.",
                cancellation_requested: "તમે આ વસ્તુ રદ કરવાની વિનંતી કરી છે.",
                cancellation_rejected: "આ વસ્તુ માટે તમારી રદ કરવાની વિનંતી નકારવામાં આવી છે.",
                cancellation_refunded: "આ વસ્તુ માટે તમારી રદ કરવાની વિનંતી સ્વીકારાઈ અને પેમેન્ટ રિફન્ડ થયું.",
                return_requested: "આ વસ્તુ માટે પરત કરવાની વિનંતી સબમિટ કરવામાં આવી છે.",
                return_rejected: "આ વસ્તુ માટે તમારી પરત કરવાની વિનંતી નકારવામાં આવી છે.",
                returned: "આ વસ્તુ પરત કરી દેવામાં આવી છે.",
                return_refunded: "આ વસ્તુ પરત કર્યા પછી તમારું પેમેન્ટ રિફન્ડ થઈ ગયું છે.",
                refunded: "આ વસ્તુ માટે તમારું પેમેન્ટ રિફન્ડ થઈ ગયું છે.",
                rto_requested: "આ વસ્તુ માટે તમે/વિક્રેતાએ RTO ની વિનંતી કરી છે.",
                rto_rejected: "વિક્રેતાએ આ વસ્તુ માટે RTO વિનંતી નકારી છે.",
                rto_approved: "વિક્રેતાએ આ વસ્તુ માટે RTO મંજૂર કર્યું છે.",
                rto_in_progress: "આ વસ્તુ RTO ના રસ્તે છે.",
                rto_delivered: "આ વસ્તુ વિક્રેતાને પરત મળી છે.",
                rto_verified: "તમે પરત કરેલી વસ્તુ વિક્રેતા દ્વારા ચકાસવામાં આવી છે.",
                rto_refunded: "RTO પછી આ વસ્તુનું તમને રિફન્ડ મળી ગયું છે."
            }
        }
    },
    statusColors: {
        draft: "var(--secondarytext-color)",
        pending: "var(--warning-color)",
        placed: "var(--info-color)",
        confirmed: "var(--success-color)",
        payment_failed: "var(--danger-color)",
        in_process: "var(--infolight-color)",
        ready_to_dispatch: "purple",
        shipped: "blue",
        in_transit: "var(--primarylight-color)",
        delivered: "var(--successdark-color)",
        cancellation_requested: "orange",
        cancelled: "var(--dangerlight-color)",
        cancellation_rejected: "red",
        cancellation_refunded: "var(--success-color)",
        return_requested: "var(--secondary-color)",
        returned: "var(--dangerlight-color)",
        return_rejected: "var(--warning-color)",
        return_refunded: "var(--success-color)",
        refunded: "var(--success-color)",
        rto_requested: "var(--warningdark-color)",
        rto_rejected: "red",
        rto_approved: "var(--success-color)",
        rto_in_progress: "blueviolet",
        rto_delivered: "var(--info-color)",
        rto_verified: "var(--successdark-color)",
        rto_refunded: "var(--success-color)"
    },
    orderPages: {
        allOrders: {
            title: "બધા ઓર્ડર",
            statuses: ["ALL"]
        },
        pendingOrders: {
            title: "બાકી ઓર્ડર",
            statuses: ["PENDING"]
        },
        newOrders: {
            title: "નવા ઓર્ડર",
            statuses: ["PLACED"]
        },
        confirmedOrders: {
            title: "પુષ્ટિ થયેલ ઓર્ડર",
            statuses: ["CONFIRMED"]
        },
        processingOrders: {
            title: "પ્રોસેસિંગ ઓર્ડર",
            statuses: ["IN_PROCESS"]
        },
        readyToDispatchOrders: {
            title: "રવાના કરવા માટે તૈયાર ઓર્ડર",
            statuses: ["READY_TO_DISPATCH"]
        },
        onTheWayOrders: {
            title: "રસ્તામાં હોય તેવા ઓર્ડર",
            statuses: ["SHIPPED", "IN_TRANSIT"]
        },
        deliveredOrders: {
            title: "ડિલિવર થયેલ ઓર્ડર",
            statuses: ["DELIVERED"]
        },
        cancelled: {
            title: "રદ થયેલ ઓર્ડર",
            statuses: ["CANCELLED"]
        },
        returns: {
            title: "રિટર્ન્સ",
            statuses: ["ALLRETURNS"],
            showOrderStatuses: false
        },
        cancellation_requested: {
            title: "રદ કરવા વિનંતી કરેલ ઓર્ડર",
            statuses: ["CANCELLATION_REQUESTED"]
        },
        cancellation_rejected: {
            title: "રદ કરવાની વિનંતી નકારેલ ઓર્ડર",
            statuses: ["CANCELLATION_REJECTED"]
        },
        cancellation_refunded: {
            title: "રદ કરી રિફન્ડ આપેલ ઓર્ડર",
            statuses: ["CANCELLATION_REFUNDED"]
        },
        return_requested: {
            title: "પરત કરવા વિનંતી કરેલ ઓર્ડર",
            statuses: ["RETURN_REQUESTED"]
        },
        returned: {
            title: "પરત મળેલ ઓર્ડર",
            statuses: ["RETURNED"]
        },
        return_rejected: {
            title: "પરત કરવાની વિનંતી નકારેલ ઓર્ડર",
            statuses: ["RETURN_REJECTED"]
        },
        return_refunded: {
            title: "પરત કરી રિફન્ડ આપેલ ઓર્ડર",
            statuses: ["RETURN_REFUNDED"]
        },
        rto_requested: {
            title: "RTO વિનંતી કરેલ ઓર્ડર",
            statuses: ["RTO_REQUESTED"]
        },
        rto_rejected: {
            title: "RTO વિનંતી નકારેલ ઓર્ડર",
            statuses: ["RTO_REJECTED"]
        },
        rto_approved: {
            title: "RTO મંજૂર કરેલ ઓર્ડર",
            statuses: ["RTO_APPROVED"]
        },
        rto_in_progress: {
            title: "RTO પ્રક્રિયામાં હોય તેવા ઓર્ડર",
            statuses: ["RTO_IN_PROGRESS"]
        },
        rto_delivered: {
            title: "RTO ડિલિવર થયેલ ઓર્ડર",
            statuses: ["RTO_DELIVERED"]
        },
        rto_verified: {
            title: "RTO ચકાસાયેલ ઓર્ડર",
            statuses: ["RTO_VERIFIED"]
        },
        rto_refunded: {
            title: "RTO રિફન્ડ આપેલ ઓર્ડર",
            statuses: ["RTO_REFUNDED"]
        }
    },
    confirmedOrders: "પુષ્ટિ થયેલ ઓર્ડર",
    processingOrders: "પ્રોસેસિંગ ઓર્ડર",
    readyToDispatchOrders: "રવાના કરવા માટે તૈયાર ઓર્ડર",
    onTheWayOrders: "રસ્તામાં હોય તેવા ઓર્ડર",
    deliveredOrders: "ડિલિવર થયેલ ઓર્ડર",
    cancelled_orders: "રદ થયેલ ઓર્ડર",
    cancellation_requested_orders: "રદ કરવા વિનંતી કરેલ ઓર્ડર",
    return_requested_orders: "પરત કરવા વિનંતી કરેલ ઓર્ડર",
    return_refunded_orders: "પરત કરી રિફન્ડ આપેલ ઓર્ડર",
    returns: "રિટર્ન્સ",
    returned_orders: "પરત મળેલ ઓર્ડર",
    return_rejected_orders: "પરત કરવાની વિનંતી નકારેલ ઓર્ડર",
    cancellation_rejected_orders: "રદ કરવાની વિનંતી નકારેલ ઓર્ડર",
    cancellation_refunded_orders: "રદ કરી રિફન્ડ આપેલ ઓર્ડર",
    rto_requested_orders: "RTO વિનંતી કરેલ ઓર્ડર",
    rto_rejected_orders: "RTO વિનંતી નકારેલ ઓર્ડર",
    rto_approved_orders: "RTO મંજૂર કરેલ ઓર્ડર",
    rto_in_progress_orders: "RTO પ્રક્રિયામાં હોય તેવા ઓર્ડર",
    rto_delivered_orders: "RTO ડિલિવર થયેલ ઓર્ડર",
    rto_verified_orders: "RTO ચકાસાયેલ ઓર્ડર",
    rto_refunded_orders: "RTO રિફન્ડ આપેલ ઓર્ડર",
    moreOptions: "વધુ વિકલ્પો",
    details: "વિગતો",
    viewProductPage: "પ્રોડક્ટ પેજ જુઓ",
    viewSize: "સાઇઝ જુઓ",
    trackStatus: "સ્ટેટસ ટ્રેક કરો",
    auditTrail: "ઓડિટ ટ્રેઇલ",
    changedFrom: "થી બદલાયું",
    changedTo: "માં બદલાયું",
    entityType: "એન્ટિટી પ્રકાર",
    entityId: "એન્ટિટી આઈડી",
    performedBy: "દ્વારા કરવામાં આવ્યું",
    timestamp: "સમય",
    trackingDetails: "ટ્રેકિંગ વિગતો",
    noDetailsFound: "કોઈ વિગતો મળી નથી",
    userDetails: 'વપરાશકર્તા વિગતો',
    followUs: "અમને ફોલો કરો",
    allRightsReserved: "તમામ હકો સુરક્ષિત",
    fastAndSecured: "ઝડપી અને સુરક્ષિત પેમેન્ટ વિકલ્પો",
    company: "કંપની",
    myAccount: "મારું એકાઉન્ટ",
    home: "હોમ",
    account: "એકાઉન્ટ",
    search: "શોધો",
    cart: "કાર્ટ",
    language: "ભાષા",
    somethingWentWrong: "કંઈક ખોટું થયું!",
    note: "નોંધ",
    notAllowed1: "તમને આ એપ્લિકેશનમાં લોગ ઇન કરવાની મંજૂરી નથી",
    notAllowed2: "માત્ર એડમિન અને મેનેજરને જ આનો એક્સેસ છે",
    notAllowed3: "જો તમે તેમાંથી એક હોવ અને તેમ છતાં એક્સેસ ન કરી શકતા હોવ તો એડમિનનો સંપર્ક કરો",
    logOutAndBackToHome: "લોગ આઉટ કરો અને હોમ પર પાછા જાઓ",
    whatsAppUs: "અમને વોટ્સએપ કરો",
    ourContactDetails: "અમારી સંપર્ક વિગતો",
    workingHours: "કામકાજના કલાકો",
    instagram: "ઇન્સ્ટાગ્રામ",
    facebook: "ફેસબુક",
    x: "X (Twitter)",
    threads: "થ્રેડ્સ",
    youtube: "યુટ્યુબ",
    pinterest: "પિનટ્રેસ્ટ",
    quotaUsage: "મેઇલ/SMS ક્વોટા વપરાશ",
    used: "વપરાયેલ",
    remaining: "બાકી",
    totalQuota: "કુલ ક્વોટા",
    sms: "SMS",
    whatsapp: "વોટ્સએપ",
    brevo: "Brevo",
    count: "ગણતરી",
    date: "તારીખ",
    gmail: "જીમેઇલ",
    quota: "ક્વોટા",
    teamUsers: "ટીમ",
    member: "સભ્ય",
    customer: "ગ્રાહક",
    customers: "ગ્રાહકો",
    profileImage: "પ્રોફાઇલ ઇમેજ",
    gender: "લિંગ",
    role: "ભૂમિકા",
    activatedText: "સક્રિય",
    selectRolePlaceholder: "ભૂમિકા પસંદ કરો",
    accountActiveLabel: "કૃપા કરીને પસંદ કરો કે વપરાશકર્તાનું એકાઉન્ટ સક્રિય/નિષ્ક્રિય હોવું જોઈએ:",
    user: "વપરાશકર્તા",
    actions: "ક્રિયાઓ",
    setAsDiscontinued: "બંધ (Discontinued) તરીકે સેટ કરો",
    resetToDefaultPassword: "ડિફોલ્ટ પાસવર્ડ પર રીસેટ કરો",
    confirmMsg: "શું તમે ચોક્કસ છો? તમે <b>{0}</b> {1} ને {2} કરવા માંગો છો?",
    discontinued: "બંધ કરેલ",
    base: "બેઝ",
    setActive: "સક્રિય કરો",
    refresh: "રિફ્રેશ",
};

export default gu;