const hi = {
  login: "लॉग इन करें",
  signup: "साइन अप करें",
  forgotPassword: "पासवर्ड भूल गए?",
  welcome: "स्वागत है, उपयोगकर्ता!",
  logout: "लॉग आउट",
  requiredField: "यह फ़ील्ड आवश्यक है।",
  invalidEmail: "कृपया वैध ईमेल पता दर्ज करें।",
  name: "नाम",
  fullNamePlaceholder: "अपना नाम दर्ज करें",
  firstName: "पहला नाम",
  lastName: "अंतिम नाम",
  mobileOrEmail: "ईमेल आईडी या मोबाइल नंबर",
  firstNamePlaceHolder: "अपना पहला नाम दर्ज करें",
  lastNamePlaceHolder: "अपना अंतिम नाम दर्ज करें",
  email: "ईमेल",
  emailPlaceHolder: "अपना ईमेल दर्ज करें",
  mobile: "मोबाइल नंबर",
  mobilePlaceHolder: "अपना मोबाइल नंबर दर्ज करें",
  receiveOTP: "आपको यह OTP प्राप्त होगा {0} पर।",
  pleaseWait: "कृपया प्रतीक्षा करें...",
  fetchingDataFailedTitle: "अनुरोधित डेटा प्राप्त करने में असमर्थ।",
  failureMessage: "हमारे अनुरोध को संसाधित करते समय त्रुटि हुई।",
  technicalGlitch: "यह अस्थायी गड़बड़ी के कारण हो सकता है। कुछ समय बाद पुनः प्रयास करें।",
  contactSupport: "संपर्क करें <a href=\"{supportEmail}\" style=\"text-decoration:none; target=\"_blank\" rel=\"noopener noreferrer\" color: #27c0e0;\">{supportEmail}</a> पर।",
  register: "रजिस्टर करें",
  registering: "रजिस्टर किया जा रहा है....",
  submitOTP: "OTP सत्यापित करें",
  submittingOTP: "OTP सत्यापित किया जा रहा है....",
  otp: "ओटीपी",
  otpPlaceholder: "OTP दर्ज करें",
  enterOTP: "कृपया OTP दर्ज करें जो आपको ({value}) पर मिला है।",
  signedUp: "आप सफलतापूर्वक साइन अप हो गए हैं!",
  failedToSignUp: "साइन अप करने में विफल।",
  loggedIn: "आप सफलतापूर्वक लॉग इन हो गए हैं!",
  failedToLogIn: "लॉग इन करने में विफल।",
  resendOTP: "OTP पुनः भेजें",
  resendingOTP: "OTP पुनः भेजा जा रहा है....",
  password: "पासवर्ड",
  logingin: "लॉग इन हो रहा है",
  passwordPlaceHolder: "अपना पासवर्ड दर्ज करें",
  otpChild1: "OTP गलत हो सकता है",
  otpChild2: "OTP की अवधि समाप्त हो गई है।",
  otpChild3: "नेटवर्क में समस्या हो सकती है।",
  otpChild4: "सर्वर डाउन हो सकता है",
  passwordRequirementMsg: "अपने खाते की सुरक्षा के लिए, कम से कम आठ (8) अक्षरों का पासवर्ड बनाएं, जिसमें शामिल हैं",
  passwordRequireMent: "पासवर्ड आवश्यकताएँ",
  upperLowerCase: "बड़ा और छोटा अक्षर",
  subHeadingIns: "मजबूत पासवर्ड के लिए, आपका पासवर्ड निम्नलिखित बिंदुओं का पालन करना चाहिए",
  minimum8Char: "कम से कम 8 अक्षर (अनिवार्य)",
  atLeastOneNumericals: "कम से कम एक अंक (अनिवार्य)",
  numericals: "अंक",
  specialChar: "विशेष वर्ण",
  oneUpperCase: "कम से कम एक बड़ा अक्षर (अनिवार्य)",
  oneLowerCase: "कम से कम एक छोटा अक्षर (अनिवार्य)",
  partnerCompanyName: "साझेदार कंपनी का नाम",
  atLeastOneSpecialChar: "कम से कम एक विशेष वर्ण (अनिवार्य)",
  skip: "छोड़ें",
  confirmPassword: "पासवर्ड की पुष्टि करें",
  setPassword: "पासवर्ड सेट करें",
  accountInstruction: "खाते तक पहुँचने और ऑर्डर प्रबंधित करने के लिए",
  aboutUs: "हमारे बारे में",
  contactUs: "संपर्क करें",
  profile: "प्रोफ़ाइल",
  orders: "ऑर्डर",
  wishlist: "विशलिस्ट",
  loginSignup: "लॉग इन/साइन अप",
  welcome: "स्वागत है",
  profileImgUpdated: "प्रोफ़ाइल छवि सफलतापूर्वक अपडेट हुई",
  save: "सहेजें",
  cancel: "रद्द करें",
  adjustImage: "छवि समायोजित करें",
  dragSqrToChangeImgSizePos: "आकार और स्थिति बदलने के लिए वर्ग को खींचें।",
  preview: "पूर्वावलोकन",
  imageCropped: "छवि सफलतापूर्वक सेव हुई!",
  alternateMobile: "वैकल्पिक मोबाइल नंबर",
  male: "पुरुष",
  female: "महिला",
  others: "अन्य",
  genderLabel: "कृपया अपनी लिंग का चयन करें:",
  dob: "जन्म तिथि",
  update: "अपडेट करें",
  changePassword: "पासवर्ड बदलें",
  updatePassword: "पासवर्ड अपडेट करें",
  updateProfile: "प्रोफ़ाइल अपडेट करें",
  oldPassword: "पुराना पासवर्ड",
  confirmPasswordNotMatchPassword: "पासवर्ड पुष्टि मेल नहीं खाती।",
  passReqNotFulfil: "पासवर्ड आवश्यकताएँ पूरी नहीं हुईं।",
  passwordUpdated: "पासवर्ड सफलतापूर्वक अपडेट हुआ!",
  profileUpdated: "प्रोफ़ाइल सफलतापूर्वक अपडेट हुई!",
  pageNotFound: "पृष्ठ नहीं मिला",
  brokenLinkMsg1: "आपके द्वारा क्लिक किया गया लिंक टूट सकता है या पृष्ठ हटा दिया गया है।",
  brokenLinkMsg2: "होम पेज पर जाएँ या समस्या के बारे में हमसे संपर्क करें।",
  backToHome: "होम पेज पर वापस जाएँ",
  dashboard: "डैशबोर्ड",
  pages: "पृष्ठ",
  inventory: "इन्वेंटरी",
  customOrders: "कस्टम ऑर्डर",
  team: "टीम",
  customers: "ग्राहक",
  settings: "सेटिंग्स",
  messages: "संदेश",
  pendingOrders: "लंबित ऑर्डर",
  completedOrders: "पूरा हुआ ऑर्डर",
  offers: "ऑफ़र",
  id: "आईडी",
  name: "नाम",
  brand: "ब्रांड",
  category: "श्रेणी",
  price: "मूल्य",
  status: "स्थिति",
  createdDate: "निर्माण तिथि",
  updatedDate: "अंतिम अपडेट",
  action: "क्रिया",
  productName: "उत्पाद का नाम",
  size: "आकार",
  color: "रंग",
  sku: "SKU",
  stockQuantity: "मात्रा",
  products: "उत्पाद",
  description: "विवरण",
  parent: "मूल",
  namePlaceholder: "नाम दर्ज करें",
  descriptionPlaceholder: "विवरण दर्ज करें",
  categoryPlaceholder: "श्रेणी चुनें",
  categoryLevel: "श्रेणी {0} स्तर",
  at: "पर",
  modifiedOn: "पर संशोधित",
  today: "आज",
  edit: "संपादित करें",
  delete: "हटाएँ",
  activated: "{entity} सक्रिय है।",
  deactivated: "{entity} निष्क्रिय है।",
  yes: "हाँ",
  no: "नहीं",
  confirm: "पुष्टि करें",
  deleteMsg: "क्या आप निश्चित हैं कि आप <b>{0}</b> {1} हटाना चाहते हैं?",
  childrenOf: "के बच्चे",
  page: "पृष्ठ",
  add: "जोड़ें",
  deactivateFirst: "{entity} पहले निष्क्रिय करें।",
  activeCantAction: "सक्रिय {entity} को {action} नहीं किया जा सकता।",
  entityIsActive: "<b>{0}</b> {entity} सक्रिय है।",
  searchPlaceHolder: "{entity} खोजें...",
  copy: "कॉपी करें",
  deleted: "हटा दिया गया",
  edited: "संपादित",
  product: "उत्पाद",
  title: "शीर्षक",
  titlePlaceholder: "शीर्षक दर्ज करें",
  image: "छवि",
  material: "सामग्री",
  materialPlaceholder: "सामग्री दर्ज करें",
  colorPlaceholder: "रंग दर्ज करें",
  sku: "SKU कोड",
  skuPlaceholder: "अद्वितीय SKU कोड दर्ज करें",
  quantity: "मात्रा",
  type: "प्रकार",
  selectProductPlaceholder: "उत्पाद चुनें",
  sizeChart: "साइज़ चार्ट",
  enterMeasure: "अपना {0} माप दर्ज करें",
  chest: "छाती",
  hips: "कूल्हे",
  neck: "गरदन",
  sleeve: "आस्तीन",
  arm: "भुजा",
  topLength: "ऊपरी लंबाई",
  shoulder: "कंधा",
  inseam: "इनसीम",
  bottomLength: "नीचे लंबाई",
  thigh: "जांघ",
  waist: "कमर",
  topBody: "ऊपरी शरीर",
  bottomBody: "निचला शरीर",
  rank: "रैंक",
  sale: "बिक्री",
  rental: "किराया",
  selectRankPlaceholder: "रैंक चुनें",
  mrp: "एमआरपी",
  salePrice: "बिक्री मूल्य",
  discount: "छूट",
  selectSizePlaceholder: "आकार चुनें",
  mrpPlaceholder: "एमआरपी दर्ज करें (₹)",
  salePricePlaceholder: "बिक्री मूल्य दर्ज करें (₹)",
  discountPlaceholder: "छूट दर्ज करें (%)",
  quantityPlaceholder: "मात्रा दर्ज करें",
  saleOrRentPrice: "बिक्री/किराया मूल्य",
  security: "सुरक्षा जमा",
  securityPlaceholder: "रिफंड = जमा - (किराया मूल्य - छूट %)",
  size_Quant_Price: "आकार - मात्रा - बिक्री मूल्य",
  view: "देखें",
  webSettings: "वेब सेटिंग्स",
  siteUnderMaintenance: "साइट रखरखाव में",
  weWillGetbackShortly: "हम थोड़ी देर में वापस आएँगे। कृपया बाद में पुनः जाँच करें।",
  reload: "पुनः लोड करें",
  enableWebsite: "वेबसाइट सक्षम/अक्षम करने के लिए क्लिक करें।",
  website: "वेबसाइट",
  switchOnOffWebsite: "वेबसाइट ऑन/ऑफ करें",
  webConfigs: "वेबसाइट कॉन्फ़िगरेशन",
  webTrendingBar: "वेबसाइट ट्रेंडिंग बार",
  websiteId: "वेबसाइट आईडी",
  path: "पथ",
  pathPlaceholder: "खुलने के लिए पथ दर्ज करें",
  homePage: "होम पेज",
  PageCarousel: "होम पेज कैरोसेल",
  forPC: "पीसी के लिए:",
  forMobile: "मोबाइल के लिए:",
  reset: "रीसेट",
  customFitting: "कस्टम फिटिंग",
  customDesigning: "कस्टम डिजाइनिंग",
  freeDelivery: "फ्री डिलीवरी",
  assuredRefunds: "सुनिश्चित रिफंड",
  sizes: "आकार",
  addresses: "पते",
  isTileVisible: "क्या टाइल दिखाई दे रही है?",
  isTileVisibleGrid: "टाइल दिखाई दे रही है",
  categories: "श्रेणियाँ",
  mrpWithDots: "एम.आर.पी",
  rtd: "तत्काल डिलीवरी",
  inclusiveTax: "सभी करों सहित मूल्य",
  rentInclusiveTax: "किराए में कर शामिल",
  purchase: "खरीदें",
  rent: "किराया",
  refundableSecurity: "रिफंडेबल सुरक्षा जमा",
  securityDeposit: "सुरक्षा जमा",
  refundSecurity: "सामान लौटाने के बाद आपका सुरक्षा जमा वापस कर दिया जाएगा।",
  securityDepositDeduction: "आप सामान डिलीवरी के 5 दिनों के भीतर लौटा सकते हैं। इसके बाद प्रत्येक 5 दिन पर किराए की राशि सुरक्षा जमा से घटाई जाएगी।",
  sizeGuide: "आकार गाइड",
  customSize: "कस्टम आकार",
  loginToAddCustomSize: "कस्टम आकार जोड़ने और देखने के लिए लॉगिन/साइन अप करें",
  yourCustomSizes: "आपके कस्टम आकार",
  undoWishlistMsg: "आपने <b>{name}</b> को विशलिस्ट से हटा दिया है",
  undo: "पूर्ववत करें",
  textPlaceholder: "{0} दर्ज करें",
  address: "पता",
  fullName: "नाम",
  city: "शहर",
  country: "देश",
  pinCode: "पिन कोड",
  state: "राज्य",
  landmark: "लैंडमार्क",
  streetAddress1: "फ़्लैट, हाउस नंबर, बिल्डिंग, कंपनी, अपार्टमेंट",
  streetAddress2: "एरिया, स्ट्रीट, सेक्टर, गाँव",
  defaultAddress: "डिफ़ॉल्ट पता सेट करें",
  setDefault: "डिफ़ॉल्ट सेट करें",
  default: "डिफ़ॉल्ट",
  addToCart: "कार्ट में जोड़ें",
  buyNow: "अभी खरीदें",
  total: "कुल",
  clearCart: "कार्ट साफ़ करें",
  proceedToCheckout: "चेकआउट के लिए आगे बढ़ें",
  shoppingCart: "शॉपिंग कार्ट",
  loadingCart: "कार्ट लोड हो रहा है...",
  emptyCart: "आपका कार्ट खाली है।",
  emptyWishlist: "आपकी विशलिस्ट खाली है।",
  deSelectAll: "सभी आइटम अनचेक करें",
  invalidCoupon: "अमान्य कूपन कोड",
  couponApplied: "कूपन लागू हुआ: ",
  apply: "लागू करें",
  freeCaps: "फ्री",
  deliveryCharges: "डिलीवरी शुल्क",
  subTotal: "उप-योग",
  changeSize: "आकार बदलें",
  moveToWishlist: "विशलिस्ट में स्थानांतरित करें",
  share: "साझा करें",
  orderSummary: "ऑर्डर सारांश",
  coupon: "कूपन",
  itemsForPurchasing: "खरीदारी के लिए चयनित आइटम",
  itemsForRenting: "किराए के लिए चयनित आइटम",
  itemsSelected: "चयनित आइटम",
  applyCoupon: "कूपन लागू करें",
  undoCartMsg: 'कार्ट से <strong>{name}</strong> हटा दिया गया। ',
  itemRestored: "आइटम कार्ट में वापस आ गया",
  selectAll: "सभी का चयन करें",
  itemMovedToWishlist: "आइटम विशलिस्ट में स्थानांतरित किया गया।",
  itemRemoved: "आइटम हटा दिया गया",
  addedToCart: "आइटम कार्ट में जोड़ा गया",
  itemAddedToWishlist: "आइटम विशलिस्ट में जोड़ा गया",
  itemRemovedFromWishlist: "आइटम विशलिस्ट से हटा दिया गया",
  proceedToBuy: "खरीदारी के लिए आगे बढ़ें",
  change: "बदलें",
  checkout: "चेकआउट",
  deliverHere: "यहाँ डिलीवर करें",
  selectDeliveryAddress: "डिलीवरी पता चुनें",
  selectedDeliveryAddress: "चयनित डिलीवरी पता",
  inventoryType: "इन्वेंटरी प्रकार",
  currentlyDefaultAddress: "डिफ़ॉल्ट पता",
  chosenAddressUpdated: "चयनित पता सफलतापूर्वक अपडेट हुआ।",
  draftUpdated: "ऑर्डर विवरण सफलतापूर्वक अपडेट हुआ।",
  proceedToCheckout: "चेकआउट के लिए आगे बढ़ा।",
  deliveringTo: "डिलीवरी के लिए",
  addNew: "नया जोड़ें",
  itemsInOrder: "ऑर्डर में आइटम",
  shipTogether: "सभी आइटम एक साथ भेजें",
  shipAsap: "प्रत्येक आइटम तैयार होने पर भेजें",
  shipItems: "आप अपने ऑर्डर के आइटम कब भेजना चाहते हैं?",
  shipItemsForOrder: "{user} अपने ऑर्डर के आइटम कब भेजना चाहता है?",
  orderPlacedTitle: "धन्यवाद, आपका ऑर्डर सफलतापूर्वक दिया गया!",
  orderConfirmationSent: "एक पुष्टि आपके ईमेल पर भेज दी गई है।",
  orderId: "ऑर्डर आईडी",
  itemsInTheOrder: "ऑर्डर में आइटम",
  viewOrders: "अपने ऑर्डर देखें",
  viewAllOrders: "सभी ऑर्डर देखें",
  continueShopping: "खरीदारी जारी रखें",
  orderDetails: "ऑर्डर विवरण",
  appliedCoupon: "लागू कूपन",
  orderPlacedOn: "ऑर्डर दिया गया",
  shipTo: "शिप करें",
  noOrdersFound: "कोई ऑर्डर नहीं मिली",
  yourOrders: "आपके ऑर्डर",
  paymentMode: "भुगतान मोड",
  paymentMethod: "भुगतान विधि",
  all: "सभी",
  pending: "लंबित",
  shipped: "भेजा गया",
  delivered: "डिलीवर किया गया",
  cancelled: "रद्द किया गया",
  allOrders: "सभी ऑर्डर",
  newOrders: "नए ऑर्डर",
  statusMessages: {
    forOrder: {
      forManager: {
        draft: "ऑर्डर ड्राफ्ट स्थिति में है और अभी तक प्लेस नहीं किया गया है।",
        pending: "भुगतान लंबित है।",
        placed: "ऑर्डर दिया गया है और आपकी पुष्टि का इंतजार है।",
        confirmed: "आपने ऑर्डर की पुष्टि कर दी है।",
        payment_failed: "भुगतान विफल हुआ।",
        in_process: "ऑर्डर आपके द्वारा प्रोसेस किया जा रहा है।",
        ready_to_dispatch: "ऑर्डर डिस्पैच के लिए तैयार है।",
        shipped: "ऑर्डर भेज दिया गया है।",
        in_transit: "ऑर्डर रास्ते में है।",
        delivered: "ऑर्डर डिलीवर कर दिया गया है।",
        cancelled: "ऑर्डर रद्द कर दिया गया है।",
        cancellation_requested: "यूज़र ने ऑर्डर रद्द करने का अनुरोध किया है।",
        cancellation_rejected: "आपने रद्द करने के अनुरोध को अस्वीकार किया है।",
        cancellation_refunded: "ऑर्डर रद्द कर दिया गया और भुगतान रिफंड किया गया।",
        return_requested: "रिटर्न के लिए अनुरोध किया गया है।",
        return_rejected: "रिटर्न का अनुरोध अस्वीकार किया गया।",
        returned: "ऑर्डर लौटाया गया है।",
        return_refunded: "रिटर्न के बाद भुगतान रिफंड किया गया।",
        refunded: "भुगतान रिफंड कर दिया गया।",
        rto_requested: "आपके द्वारा RTO का अनुरोध किया गया।",
        rto_rejected: "आपने RTO अनुरोध अस्वीकार किया।",
        rto_approved: "आपने RTO अनुरोध को स्वीकृत किया।",
        rto_in_progress: "RTO प्रक्रिया में है।",
        rto_delivered: "RTO द्वारा ऑर्डर आपको वापस भेज दिया गया।",
        rto_verified: "RTO आइटम की सत्यापन किया गया।",
        rto_refunded: "RTO के बाद भुगतान रिफंड कर दिया गया।"
      },
      forUser: {
        draft: "आपका ऑर्डर चेकआउट में है लेकिन अभी तक प्लेस नहीं किया गया।",
        pending: "भुगतान लंबित है। कृपया भुगतान पूरा करें।",
        placed: "आपका ऑर्डर प्लेस कर दिया गया है और पुष्टि का इंतजार है।",
        confirmed: "आपका ऑर्डर विक्रेता द्वारा पुष्टि किया गया।",
        payment_failed: "भुगतान विफल हुआ। कृपया पुनः प्रयास करें।",
        in_process: "आपका ऑर्डर विक्रेता द्वारा प्रोसेस किया जा रहा है।",
        ready_to_dispatch: "आपका ऑर्डर डिस्पैच के लिए तैयार है।",
        shipped: "आपका ऑर्डर भेज दिया गया है।",
        in_transit: "आपका ऑर्डर रास्ते में है।",
        delivered: "आपका ऑर्डर डिलीवर कर दिया गया है।",
        cancelled: "आपका ऑर्डर रद्द कर दिया गया है।",
        cancellation_requested: "आपने ऑर्डर रद्द करने का अनुरोध किया।",
        cancellation_rejected: "आपका रद्द करने का अनुरोध अस्वीकार किया गया।",
        cancellation_refunded: "आपका ऑर्डर रद्द कर दिया गया और भुगतान रिफंड किया गया।",
        return_requested: "आपके ऑर्डर के लिए रिटर्न का अनुरोध किया गया।",
        return_rejected: "रिटर्न का अनुरोध अस्वीकार किया गया।",
        returned: "आपका ऑर्डर लौटाया गया।",
        return_refunded: "रिटर्न के बाद आपका भुगतान रिफंड किया गया।",
        refunded: "भुगतान रिफंड कर दिया गया।",
        rto_requested: "आपके ऑर्डर के लिए RTO का अनुरोध किया गया।",
        rto_rejected: "RTO अनुरोध अस्वीकार किया गया।",
        rto_approved: "RTO अनुरोध स्वीकृत किया गया।",
        rto_in_progress: "RTO प्रक्रिया में है।",
        rto_delivered: "RTO द्वारा ऑर्डर वापस भेज दिया गया।",
        rto_verified: "RTO आइटम की पुष्टि की गई।",
        rto_refunded: "RTO के बाद भुगतान रिफंड कर दिया गया।"
      }
    },
    forItem: {
      forManager: {
        draft: "आइटम ऑर्डर ड्राफ्ट में जोड़ा गया है और अभी तक प्लेस नहीं हुआ।",
        pending: "इस आइटम का भुगतान लंबित है।",
        placed: "आइटम प्लेस किया गया है और आपकी पुष्टि का इंतजार है।",
        confirmed: "आपने आइटम की पुष्टि कर दी है।",
        payment_failed: "इस आइटम का भुगतान विफल हुआ।",
        in_process: "आइटम प्रोसेस किया जा रहा है।",
        ready_to_dispatch: "आइटम डिस्पैच के लिए तैयार है।",
        shipped: "आइटम भेज दिया गया।",
        in_transit: "आइटम रास्ते में है।",
        delivered: "आइटम डिलीवर कर दिया गया।",
        cancelled: "आइटम रद्द कर दिया गया।",
        cancellation_requested: "इस आइटम के लिए यूज़र ने रद्द करने का अनुरोध किया।",
        cancellation_rejected: "रद्द करने का अनुरोध अस्वीकार किया गया।",
        cancellation_refunded: "भुगतान रिफंड कर दिया गया।",
        return_requested: "रिटर्न का अनुरोध किया गया।",
        return_rejected: "रिटर्न का अनुरोध अस्वीकार किया गया।",
        returned: "आइटम लौटाया गया।",
        return_refunded: "भुगतान रिफंड कर दिया गया।",
        refunded: "भुगतान रिफंड कर दिया गया।",
        rto_requested: "RTO का अनुरोध किया गया।",
        rto_rejected: "RTO अनुरोध अस्वीकार किया गया।",
        rto_approved: "RTO अनुरोध स्वीकृत किया गया।",
        rto_in_progress: "RTO प्रक्रिया में है।",
        rto_delivered: "RTO द्वारा आइटम वापस भेज दिया गया।",
        rto_verified: "RTO आइटम की पुष्टि की गई।",
        rto_refunded: "RTO के बाद भुगतान रिफंड कर दिया गया।"
      },
      forUser: {
        draft: "यह आइटम चेकआउट में है लेकिन अभी तक प्लेस नहीं हुआ।",
        pending: "इस आइटम का भुगतान लंबित है। कृपया पूरा करें।",
        placed: "यह आइटम प्लेस किया गया है और पुष्टि का इंतजार है।",
        confirmed: "यह आइटम विक्रेता द्वारा पुष्टि किया गया।",
        payment_failed: "इस आइटम का भुगतान विफल हुआ।",
        in_process: "आइटम विक्रेता द्वारा प्रोसेस किया जा रहा है।",
        ready_to_dispatch: "आइटम डिस्पैच के लिए तैयार है।",
        shipped: "आइटम भेज दिया गया।",
        in_transit: "आइटम रास्ते में है।",
        delivered: "आइटम डिलीवर कर दिया गया।",
        cancelled: "आइटम रद्द कर दिया गया।",
        cancellation_requested: "आपने इस आइटम को रद्द करने का अनुरोध किया।",
        cancellation_rejected: "रद्द करने का अनुरोध अस्वीकार किया गया।",
        cancellation_refunded: "भुगतान रिफंड कर दिया गया।",
        return_requested: "रिटर्न का अनुरोध किया गया।",
        return_rejected: "रिटर्न का अनुरोध अस्वीकार किया गया।",
        returned: "आइटम लौटाया गया।",
        return_refunded: "भुगतान रिफंड कर दिया गया।",
        refunded: "भुगतान रिफंड कर दिया गया।",
        rto_requested: "RTO का अनुरोध किया गया।",
        rto_rejected: "RTO अनुरोध अस्वीकार किया गया।",
        rto_approved: "RTO अनुरोध स्वीकृत किया गया।",
        rto_in_progress: "RTO प्रक्रिया में है।",
        rto_delivered: "RTO द्वारा आइटम वापस भेज दिया गया।",
        rto_verified: "RTO आइटम की पुष्टि की गई।",
        rto_refunded: "RTO के बाद भुगतान रिफंड कर दिया गया।"
      }
    }
  },
  statusColors: {
    draft: "var(--secondarytext-color)",
    pending: "var(--warning-color)",
    placed: "var(--info-color)",
    confirmed: "var(--success-color)",
    payment_failed: "var(--danger-color)",
    in_process: "var(--infolight-color)",
    ready_to_dispatch: "purple",
    shipped: "blue",
    in_transit: "var(--primarylight-color)",
    delivered: "var(--successdark-color)",
    cancellation_requested: "orange",
    cancelled: "var(--dangerlight-color)",
    cancellation_rejected: "red",
    cancellation_refunded: "var(--success-color)",
    return_requested: "var(--secondary-color)",
    returned: "var(--dangerlight-color)",
    return_rejected: "var(--warning-color)",
    return_refunded: "var(--success-color)",
    refunded: "var(--success-color)",
    rto_requested: "var(--warningdark-color)",
    rto_rejected: "red",
    rto_approved: "var(--success-color)",
    rto_in_progress: "blueviolet",
    rto_delivered: "var(--info-color)",
    rto_verified: "var(--successdark-color)",
    rto_refunded: "var(--success-color)"
  },
  orderPages: {
    allOrders: {
      title: "सभी ऑर्डर",
      statuses: ["ALL"]
    },
    pendingOrders: {
      title: "लंबित ऑर्डर",
      statuses: ["PENDING"]
    },
    newOrders: {
      title: "नए ऑर्डर",
      statuses: ["PLACED"]
    },
    confirmedOrders: {
      title: "पुष्ट ऑर्डर",
      statuses: ["CONFIRMED"]
    },
    processingOrders: {
      title: "प्रोसेसिंग ऑर्डर",
      statuses: ["IN_PROCESS"]
    },
    readyToDispatchOrders: {
      title: "डिस्पैच के लिए तैयार",
      statuses: ["READY_TO_DISPATCH"]
    },
    onTheWayOrders: {
      title: "रास्ते में ऑर्डर",
      statuses: ["SHIPPED", "IN_TRANSIT"]
    },
    deliveredOrders: {
      title: "डिलीवर ऑर्डर",
      statuses: ["DELIVERED"]
    },
    cancelled: {
      title: "रद्द ऑर्डर",
      statuses: ["CANCELLED"]
    },
    returns: {
      title: "रिटर्न्स",
      statuses: ["ALLRETURNS"],
      showOrderStatuses: false
    },
    cancellation_requested: {
      title: "रद्दीकरण अनुरोधित",
      statuses: ["CANCELLATION_REQUESTED"]
    },
    cancellation_rejected: {
      title: "रद्दीकरण अस्वीकार",
      statuses: ["CANCELLATION_REJECTED"]
    },
    cancellation_refunded: {
      title: "रद्दीकरण रिफंड",
      statuses: ["CANCELLATION_REFUNDED"]
    },
    return_requested: {
      title: "रिटर्न अनुरोधित",
      statuses: ["RETURN_REQUESTED"]
    },
    returned: {
      title: "रिटर्न किए गए ऑर्डर",
      statuses: ["RETURNED"]
    },
    return_rejected: {
      title: "रिटर्न अस्वीकार",
      statuses: ["RETURN_REJECTED"]
    },
    return_refunded: {
      title: "रिटर्न रिफंड",
      statuses: ["RETURN_REFUNDED"]
    },
    rto_requested: {
      title: "RTO अनुरोधित",
      statuses: ["RTO_REQUESTED"]
    },
    rto_rejected: {
      title: "RTO अस्वीकार",
      statuses: ["RTO_REJECTED"]
    },
    rto_approved: {
      title: "RTO स्वीकृत",
      statuses: ["RTO_APPROVED"]
    },
    rto_in_progress: {
      title: "RTO प्रक्रिया में",
      statuses: ["RTO_IN_PROGRESS"]
    },
    rto_delivered: {
      title: "RTO डिलीवर",
      statuses: ["RTO_DELIVERED"]
    },
    rto_verified: {
      title: "RTO सत्यापित",
      statuses: ["RTO_VERIFIED"]
    },
    rto_refunded: {
      title: "RTO रिफंड",
      statuses: ["RTO_REFUNDED"]
    }
  },
  confirmedOrders: "पुष्ट ऑर्डर",
  processingOrders: "प्रोसेसिंग ऑर्डर",
  readyToDispatchOrders: "डिस्पैच के लिए तैयार ऑर्डर",
  onTheWayOrders: "रास्ते में ऑर्डर",
  deliveredOrders: "डिलीवर किए गए ऑर्डर",
  cancelled_orders: "रद्द ऑर्डर",
  cancellation_requested_orders: "रद्दीकरण अनुरोधित ऑर्डर",
  return_requested_orders: "रिटर्न अनुरोधित ऑर्डर",
  return_refunded_orders: "रिटर्न रिफंड किए गए ऑर्डर",
  returns: "रिटर्न्स",
  returned_orders: "रिटर्न किए गए ऑर्डर",
  return_rejected_orders: "रिटर्न अस्वीकार किए गए ऑर्डर",
  cancellation_rejected_orders: "रद्दीकरण अस्वीकार किए गए ऑर्डर",
  cancellation_refunded_orders: "रद्दीकरण रिफंड किए गए ऑर्डर",
  rto_requested_orders: "RTO अनुरोधित ऑर्डर",
  rto_rejected_orders: "RTO अस्वीकार किए गए ऑर्डर",
  rto_approved_orders: "RTO स्वीकृत ऑर्डर",
  rto_in_progress_orders: "RTO प्रक्रिया में ऑर्डर",
  rto_delivered_orders: "RTO डिलीवर किए गए ऑर्डर",
  rto_verified_orders: "RTO सत्यापित ऑर्डर",
  rto_refunded_orders: "RTO रिफंड किए गए ऑर्डर",
  moreOptions: "अधिक विकल्प",
  details: "विवरण",
  viewProductPage: "प्रोडक्ट पेज देखें",
  viewSize: "आकार देखें",
  trackStatus: "स्थिति ट्रैक करें",
  auditTrail: "ऑडिट ट्रेल",
  changedFrom: "से बदलें",
  changedTo: "तक बदलें",
  entityType: "इकाई प्रकार",
  entityId: "इकाई आईडी",
  performedBy: "द्वारा किया गया",
  timestamp: "समय-सीमा",
  trackingDetails: "ट्रैकिंग विवरण",
  noDetailsFound: "कोई विवरण नहीं मिला",
  userDetails: "उपयोगकर्ता विवरण",
  followUs: "हमें फॉलो करें",
  allRightsReserved: "सभी अधिकार सुरक्षित हैं",
  fastAndSecured: "तेज़ और सुरक्षित भुगतान विकल्प",
  company: "कंपनी",
  myAccount: "मेरा खाता",
  home: "मुख्य पृष्ठ",
  account: "खाता",
  search: "खोजें",
  cart: "कार्ट",
  language: "भाषा",
  somethingWentWrong: "कुछ गलत हो गया!",
  note: "नोट",
  notAllowed1: "आपको इस एप्लिकेशन में लॉगिन करने की अनुमति नहीं है",
  notAllowed2: "केवल एडमिन और मैनेजर को ही इसकी पहुँच है",
  notAllowed3: "यदि आप इनमें से एक हैं और फिर भी एक्सेस नहीं कर पा रहे हैं तो एडमिन से संपर्क करें",
  logOutAndBackToHome: "लॉग आउट करें और होम पर वापस जाएँ",
  whatsAppUs: "हमें व्हाट्सऐप करें",
  ourContactDetails: "हमारे संपर्क विवरण",
  workingHours: "कार्य समय",
  instagram: "इंस्टाग्राम",
  facebook: "फेसबुक",
  x: "एक्स (ट्विटर)",
  threads: "थ्रेड्स",
  youtube: "यूट्यूब",
  pinterest: "पिनटेरेस्ट",
  quotaUsage: "मेल/एसएमएस कोटा उपयोग",
  used: "उपयोग किया गया",
  remaining: "शेष",
  totalQuota: "कुल कोटा",
  sms: "एसएमएस",
  whatsapp: "व्हाट्सएप",
  brevo: "ब्रेवो",
  count: "गिनती",
  date: "दिनांक",
  gmail: "जीमेल",
  quota: "कोटा",
  teamUsers: "टीम",
  member: "सदस्य",
  customer: "ग्राहक",
  customers: "ग्राहक",
  profileImage: "प्रोफ़ाइल छवि",
  gender: "लिंग",
  role: "भूमिका",
  activatedText: "सक्रिय",
  selectRolePlaceholder: "भूमिका चुनें",
  accountActiveLabel: "कृपया चुनें कि उपयोगकर्ता का खाता सक्रिय/निष्क्रिय होना चाहिए:",
  user: "उपयोगकर्ता",
  actions: "क्रियाएं",
  setAsDiscontinued: "बंद (Discontinued) के रूप में सेट करें",
  resetToDefaultPassword: "डिफ़ॉल्ट पासवर्ड पर रीसेट करें",
  confirmMsg: "क्या आप निश्चित हैं? आप <b>{0}</b> {1} को {2} करना चाहते हैं?",
  discontinued: "बंद (Discontinued)",
  base: "आधार (Base)",
  setActive: "सक्रिय (Active) करें",
  refresh: "रिफ्रेश"
};
  
  export default hi;
  
  
  