const kn = {
    login: "ಲಾಗಿನ್",
    signup: "ಸೈನ್ ಅಪ್",
    forgotPassword: "ಪಾಸ್‌ವರ್ಡ್ ಮರೆತಿದ್ದೀರಾ?",
    welcome: "ಸ್ವಾಗತ, ಬಳಕೆದಾರರೇ!",
    logout: "ಲಾಗ್ ಔಟ್",
    requiredField: "ಈ ಕ್ಷೇತ್ರವು ಕಡ್ಡಾಯವಾಗಿದೆ.",
    invalidEmail: "ದಯವಿಟ್ಟು ಮಾನ್ಯ ಇಮೇಲ್ ವಿಳಾಸವನ್ನು ನಮೂದಿಸಿ.",
    name: "ಹೆಸರು",
    fullNamePlaceholder: "ನಿಮ್ಮ ಹೆಸರನ್ನು ನಮೂದಿಸಿ",
    firstName: "ಮೊದಲ ಹೆಸರು",
    lastName: "ಕೊನೆಯ ಹೆಸರು",
    mobileOrEmail: "ಇಮೇಲ್ ಐಡಿ ಅಥವಾ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ",
    firstNamePlaceHolder: "ನಿಮ್ಮ ಮೊದಲ ಹೆಸರನ್ನು ನಮೂದಿಸಿ",
    lastNamePlaceHolder: "ನಿಮ್ಮ ಕೊನೆಯ ಹೆಸರನ್ನು ನಮೂದಿಸಿ",
    email: "ಇಮೇಲ್",
    emailPlaceHolder: "ನಿಮ್ಮ ಇಮೇಲ್ ನಮೂದಿಸಿ",
    mobile: "ಮೊಬೈಲ್ ಸಂಖ್ಯೆ",
    mobilePlaceHolder: "ನಿಮ್ಮ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ ನಮೂದಿಸಿ",
    receiveOTP: "ನೀವು {0} ನಲ್ಲಿ OTP ಸ್ವೀಕರಿಸುತ್ತೀರಿ.",
    pleaseWait: "ದಯವಿಟ್ಟು ನಿರೀಕ್ಷಿಸಿ...",
    fetchingDataFailedTitle: "ವಿನಂತಿಸಿದ ಡೇಟಾವನ್ನು ಪಡೆಯಲು ಸಾಧ್ಯವಾಗುತ್ತಿಲ್ಲ.",
    failureMessage: "ನಿಮ್ಮ ವಿನಂತಿಯನ್ನು ಪ್ರಕ್ರಿಯೆಗೊಳಿಸುವಾಗ ನಮಗೆ ದೋಷ ಎದುರಾಗಿದೆ.",
    technicalGlitch: "ಇದು ತಾತ್ಕಾಲಿಕ ತಾಂತ್ರಿಕ ಸಮಸ್ಯೆಯಿಂದ ಇರಬಹುದು. ಸ್ವಲ್ಪ ಸಮಯದ ನಂತರ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
    contactSupport: "ಸಹಾಯಕ್ಕಾಗಿ ಇಲ್ಲಿ ಸಂಪರ್ಕಿಸಿ: <a href=\"{supportEmail}\" style=\"text-decoration:none; target=\"_blank\" rel=\"noopener noreferrer\" color: #27c0e0;\">{supportEmail}</a>.",
    register: "ನೋಂದಾಯಿಸಿ",
    registering: "ನೋಂದಾಯಿಸಲಾಗುತ್ತಿದೆ....",
    submitOTP: "OTP ಪರಿಶೀಲಿಸಿ",
    submittingOTP: "OTP ಪರಿಶೀಲಿಸಲಾಗುತ್ತಿದೆ....",
    otp: "OTP",
    otpPlaceholder: "OTP ನಮೂದಿಸಿ",
    enterOTP: "ದಯವಿಟ್ಟು ({value}) ಗೆ ಬಂದಿರುವ OTP ಯನ್ನು ನಮೂದಿಸಿ.",
    signedUp: "ನೀವು ಯಶಸ್ವಿಯಾಗಿ ಸೈನ್ ಅಪ್ ಆಗಿದ್ದೀರಿ!",
    failedToSignUp: "ಸೈನ್ ಅಪ್ ಮಾಡಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ.",
    loggedIn: "ನೀವು ಯಶಸ್ವಿಯಾಗಿ ಲಾಗಿನ್ ಆಗಿದ್ದೀರಿ!",
    failedToLogIn: "ಲಾಗಿನ್ ಮಾಡಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ.",
    resendOTP: "OTP ಮತ್ತೆ ಕಳುಹಿಸಿ",
    resendingOTP: "OTP ಮತ್ತೆ ಕಳುಹಿಸಲಾಗುತ್ತಿದೆ....",
    password: "ಪಾಸ್‌ವರ್ಡ್",
    logingin: "ಲಾಗಿನ್ ಆಗುತ್ತಿದೆ",
    passwordPlaceHolder: "ನಿಮ್ಮ ಪಾಸ್‌ವರ್ಡ್ ನಮೂದಿಸಿ",
    otpChild1: "OTP ತಪ್ಪಿರಬಹುದು",
    otpChild2: "OTP ಅವಧಿ ಮುಗಿದಿರಬಹುದು.",
    otpChild3: "ನೆಟ್‌ವರ್ಕ್ ಸಮಸ್ಯೆ ಇರಬಹುದು.",
    otpChild4: "ಸರ್ವರ್ ಡೌನ್ ಆಗಿರಬಹುದು",
    passwordRequirementMsg: "ನಿಮ್ಮ ಖಾತೆಯನ್ನು ರಕ್ಷಿಸಲು, ಕನಿಷ್ಠ ಎಂಟು (8) ಅಕ್ಷರಗಳ ಪಾಸ್‌ವರ್ಡ್ ರಚಿಸಿ, ಅದರಲ್ಲಿ ಇವುಗಳನ್ನು ಒಳಗೊಂಡಿರಲಿ:",
    passwordRequireMent: "ಪಾಸ್‌ವರ್ಡ್ ಅಗತ್ಯತೆಗಳು",
    upperLowerCase: "ದೊಡ್ಡ ಮತ್ತು ಸಣ್ಣ ಅಕ್ಷರಗಳು",
    subHeadingIns: "ಬಲವಾದ ಪಾಸ್‌ವರ್ಡ್‌ಗಾಗಿ, ನಿಮ್ಮ ಪಾಸ್‌ವರ್ಡ್ ಈ ಅಂಶಗಳನ್ನು ಪಾಲಿಸಬೇಕು",
    minimum8Char: "ಕನಿಷ್ಠ 8 ಅಕ್ಷರಗಳು (ಕಡ್ಡಾಯ)",
    atLeastOneNumericals: "ಕನಿಷ್ಠ ಒಂದು ಅಂಕೆ (ಕಡ್ಡಾಯ)",
    numericals: "ಅಂಕೆಗಳು",
    specialChar: "ವಿಶೇಷ ಅಕ್ಷರಗಳು",
    oneUpperCase: "ಕನಿಷ್ಠ ಒಂದು ದೊಡ್ಡ ಅಕ್ಷರ (ಕಡ್ಡಾಯ)",
    oneLowerCase: "ಕನಿಷ್ಠ ಒಂದು ಸಣ್ಣ ಅಕ್ಷರ (ಕಡ್ಡಾಯ)",
    partnerCompanyName: "ಪಾಲುದಾರ ಕಂಪನಿಯ ಹೆಸರು",
    atLeastOneSpecialChar: "ಕನಿಷ್ಠ ಒಂದು ವಿಶೇಷ ಅಕ್ಷರ (ಕಡ್ಡಾಯ)",
    skip: "ಬಿಟ್ಟುಬಿಡಿ",
    confirmPassword: "ಪಾಸ್‌ವರ್ಡ್ ದೃಢೀಕರಿಸಿ",
    setPassword: "ಪಾಸ್‌ವರ್ಡ್ ಹೊಂದಿಸಿ",
    accountInstruction: "ಖಾತೆಯನ್ನು ಪ್ರವೇಶಿಸಲು ಮತ್ತು ಆರ್ಡರ್‌ಗಳನ್ನು ನಿರ್ವಹಿಸಲು",
    aboutUs: "ನಮ್ಮ ಬಗ್ಗೆ",
    contactUs: "ನಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸಿ",
    profile: "ಪ್ರೊಫೈಲ್",
    orders: "ಆರ್ಡರ್‌ಗಳು",
    wishlist: "ವಿಶ್‌ಲಿಸ್ಟ್",
    loginSignup: "ಲಾಗಿನ್/ಸೈನ್ ಅಪ್",
    welcome: "ಸ್ವಾಗತ",
    profileImgUpdated: "ಪ್ರೊಫೈಲ್ ಚಿತ್ರ ಯಶಸ್ವಿಯಾಗಿ ನವೀಕರಿಸಲಾಗಿದೆ",
    save: "ಉಳಿಸಿ",
    cancel: "ರದ್ದುಮಾಡಿ",
    adjustImage: "ಚಿತ್ರವನ್ನು ಹೊಂದಿಸಿ",
    dragSqrToChangeImgSizePos: "ಗಾತ್ರ ಮತ್ತು ಸ್ಥಾನವನ್ನು ಬದಲಾಯಿಸಲು ಚೌಕವನ್ನು ಎಳೆಯಿರಿ.",
    preview: "ಮುನ್ನೋಟ",
    imageCropped: "ಕತ್ತರಿಸಿದ ಚಿತ್ರವನ್ನು ಯಶಸ್ವಿಯಾಗಿ ಉಳಿಸಲಾಗಿದೆ!",
    alternateMobile: "ಪರ್ಯಾಯ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ",
    male: "ಪುರುಷ",
    female: "ಮಹಿಳೆ",
    others: "ಇತರರು",
    genderLabel: "ದಯವಿಟ್ಟು ನಿಮ್ಮ ಲಿಂಗವನ್ನು ಆಯ್ಕೆಮಾಡಿ:",
    dob: "ಹುಟ್ಟಿದ ದಿನಾಂಕ",
    update: "ನವೀಕರಿಸಿ",
    changePassword: "ಪಾಸ್‌ವರ್ಡ್ ಬದಲಾಯಿಸಿ",
    updatePassword: "ಪಾಸ್‌ವರ್ಡ್ ನವೀಕರಿಸಿ",
    updateProfile: "ಪ್ರೊಫೈಲ್ ನವೀಕರಿಸಿ",
    oldPassword: "ಹಳೆಯ ಪಾಸ್‌ವರ್ಡ್",
    confirmPasswordNotMatchPassword: "ದೃಢೀಕರಣ ಪಾಸ್‌ವರ್ಡ್ ಮತ್ತು ಪಾಸ್‌ವರ್ಡ್ ತಾಳೆಯಾಗುತ್ತಿಲ್ಲ.",
    passReqNotFulfil: "ಪಾಸ್‌ವರ್ಡ್ ಅಗತ್ಯತೆಗಳನ್ನು ಪೂರೈಸಲಾಗಿಲ್ಲ.",
    passwordUpdated: "ಪಾಸ್‌ವರ್ಡ್ ಯಶಸ್ವಿಯಾಗಿ ನವೀಕರಿಸಲಾಗಿದೆ!",
    profileUpdated: "ಪ್ರೊಫೈಲ್ ಯಶಸ್ವಿಯಾಗಿ ನವೀಕರಿಸಲಾಗಿದೆ!",
    pageNotFound: "ಪುಟ ಕಂಡುಬಂದಿಲ್ಲ",
    brokenLinkMsg1: "ನೀವು ಕ್ಲಿಕ್ ಮಾಡಿದ ಲಿಂಕ್ ಮುರಿದಿರಬಹುದು ಅಥವಾ ಪುಟವನ್ನು ತೆಗೆದುಹಾಕಿರಬಹುದು.",
    brokenLinkMsg2: "ಮುಖಪುಟಕ್ಕೆ ಭೇಟಿ ನೀಡಿ ಅಥವಾ ಸಮಸ್ಯೆಯ ಬಗ್ಗೆ ನಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸಿ.",
    backToHome: "ಮುಖಪುಟಕ್ಕೆ ಹಿಂತಿರುಗಿ",
    dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    pages: "ಪುಟಗಳು",
    inventory: "ಇನ್ವೆಂಟರಿ",
    customOrders: "ಕಸ್ಟಮ್ ಆರ್ಡರ್‌ಗಳು",
    team: "ತಂಡ",
    customers: "ಗ್ರಾಹಕರು",
    settings: "ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
    messages: "ಸಂದೇಶಗಳು",
    pendingOrders: "ಬಾಕಿ ಉಳಿದ ಆರ್ಡರ್‌ಗಳು",
    completedOrders: "ಪೂರ್ಣಗೊಂಡ ಆರ್ಡರ್‌ಗಳು",
    offers: "ಕೊಡುಗೆಗಳು",
    id: "ID",
    name: "ಹೆಸರು",
    brand: "ಬ್ರ್ಯಾಂಡ್",
    category: "ವರ್ಗ",
    price: "ಬೆಲೆ",
    status: "ಸ್ಥಿತಿ",
    createdDate: "ರಚಿಸಿದ ದಿನಾಂಕ",
    updatedDate: "ಕೊನೆಯದಾಗಿ ನವೀಕರಿಸಿದ್ದು",
    action: "ಕ್ರಮ",
    productName: "ಉತ್ಪನ್ನದ ಹೆಸರು",
    size: "ಗಾತ್ರ",
    color: "ಬಣ್ಣ",
    sku: "SKU",
    stockQuantity: "ಪ್ರಮಾಣ",
    products: "ಉತ್ಪನ್ನಗಳು",
    description: "ವಿವರಣೆ",
    parent: "ಪೋಷಕ (Parent)",
    namePlaceholder: "ಹೆಸರನ್ನು ನಮೂದಿಸಿ",
    descriptionPlaceholder: "ವಿವರಣೆಯನ್ನು ನಮೂದಿಸಿ",
    categoryPlaceholder: "ವರ್ಗವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    categoryLevel: "ವರ್ಗ {0} ಮಟ್ಟ ",
    at: "ನಲ್ಲಿ",
    modifiedOn: "ಪರಿಷ್ಕರಿಸಿದ ದಿನಾಂಕ",
    today: "ಇಂದು",
    edit: "ತಿದ್ದುಪಡಿ",
    delete: "ಅಳಿಸಿ",
    activated: "{entity} ಸಕ್ರಿಯಗೊಳಿಸಲಾಗಿದೆ.",
    deactivated: "{entity} ನಿಷ್ಕ್ರಿಯಗೊಳಿಸಲಾಗಿದೆ.",
    yes: "ಹೌದು",
    no: "ಇಲ್ಲ",
    confirm: "ದೃಢೀಕರಿಸಿ",
    deleteMsg: "ನೀವು ಖಚಿತವಾಗಿ <b>{0}</b> {1} ಅನ್ನು ಅಳಿಸಲು ಬಯಸುವಿರಾ?",
    childrenOf: "ನ ಮಕ್ಕಳು ",
    page: "ಪುಟ",
    add: "ಸೇರಿಸಿ",
    deactivateFirst: "ಮೊದಲು {entity} ಅನ್ನು ನಿಷ್ಕ್ರಿಯಗೊಳಿಸಿ.",
    activeCantAction: "ಸಕ್ರಿಯ {entity} ಮೇಲೆ {action} ಮಾಡಲು ಸಾಧ್ಯವಿಲ್ಲ.",
    entityIsActive: "<b>{0}</b> {entity} ಸಕ್ರಿಯವಾಗಿದೆ.",
    searchPlaceHolder: "{entity} ಗಾಗಿ ಹುಡುಕಿ...",
    copy: "ನಕಲಿಸಿ",
    deleted: "ಅಳಿಸಲಾಗಿದೆ",
    edited: "ತಿದ್ದುಪಡಿ ಮಾಡಲಾಗಿದೆ",
    product: "ಉತ್ಪನ್ನ",
    title: "ಶೀರ್ಷಿಕೆ",
    titlePlaceholder: "ಶೀರ್ಷಿಕೆಯನ್ನು ನಮೂದಿಸಿ",
    image: "ಚಿತ್ರ",
    material: "ವಸ್ತು (Material)",
    materialPlaceholder: "ವಸ್ತುವನ್ನು ನಮೂದಿಸಿ",
    colorPlaceholder: "ಬಣ್ಣವನ್ನು ನಮೂದಿಸಿ",
    sku: "SKU ಕೋಡ್",
    skuPlaceholder: "ವಿಶಿಷ್ಟ SKU ಕೋಡ್ ನಮೂದಿಸಿ",
    quantity: "ಪ್ರಮಾಣ",
    type: "ಪ್ರಕಾರ",
    selectProductPlaceholder: "ಉತ್ಪನ್ನವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    sizeChart: "ಗಾತ್ರದ ಚಾರ್ಟ್",
    enterMeasure: "ನಿಮ್ಮ {0} ಅಳತೆಯನ್ನು ನಮೂದಿಸಿ",
    chest: "ಎದೆ",
    hips: "ಸೊಂಟದ ಕೆಳಭಾಗ (Hips)",
    neck: "ಕುತ್ತಿಗೆ",
    sleeve: "ತೋಳು (Sleeve)",
    arm: "ತೋಳು",
    topLength: "ಮೇಲ್ಭಾಗದ ಉದ್ದ",
    shoulder: "ಭುಜ",
    inseam: "ಇನ್ಸೀಮ್",
    bottomLength: "ಕೆಳಭಾಗದ ಉದ್ದ",
    thigh: "ತೊಡೆ",
    waist: "ಸೊಂಟ",
    topBody: "ಮೇಲಿನ ದೇಹ",
    bottomBody: "ಕೆಳಗಿನ ದೇಹ",
    rank: "ಶ್ರೇಣಿ (Rank)",
    sale: "ಮಾರಾಟ",
    rental: "ಬಾಡಿಗೆ",
    selectRankPlaceholder: "ಶ್ರೇಣಿಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    mrp: "MRP",
    salePrice: "ಮಾರಾಟದ ಬೆಲೆ",
    discount: "ರಿಯಾಯಿತಿ",
    selectSizePlaceholder: "ಗಾತ್ರವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    mrpPlaceholder: "MRP ನಮೂದಿಸಿ (₹)",
    salePricePlaceholder: "ಮಾರಾಟದ ಬೆಲೆ ನಮೂದಿಸಿ (₹)",
    discountPlaceholder: "ರಿಯಾಯಿತಿಯನ್ನು ನಮೂದಿಸಿ (%)",
    quantityPlaceholder: "ಪ್ರಮಾಣವನ್ನು ನಮೂದಿಸಿ",
    saleOrRentPrice: "ಮಾರಾಟ/ಬಾಡಿಗೆ ಬೆಲೆ",
    security: "ಭದ್ರತಾ ಠೇವಣಿ",
    securityPlaceholder: "ಹಿಂತಿರುಗಿಸಬಹುದಾದ = ಠೇವಣಿ - (ಬಾಡಿಗೆ ಬೆಲೆ - ರಿಯಾಯಿತಿ %)",
    size_Quant_Price: "ಗಾತ್ರ - ಪ್ರಮಾಣ - ಮಾರಾಟದ ಬೆಲೆ",
    view: "ನೋಡಿ",
    webSettings: "ವೆಬ್ ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
    siteUnderMaintenance: "ಸೈಟ್ ನಿರ್ವಹಣೆಯಲ್ಲಿದೆ",
    weWillGetbackShortly: "ನಾವು ಶೀಘ್ರದಲ್ಲೇ ಹಿಂತಿರುಗುತ್ತೇವೆ. ದಯವಿಟ್ಟು ನಂತರ ಮತ್ತೆ ಪರಿಶೀಲಿಸಿ.",
    reload: "ಮತ್ತೆ ಲೋಡ್ ಮಾಡಿ",
    enableWebsite: "ವೆಬ್‌ಸೈಟ್ ಸಕ್ರಿಯಗೊಳಿಸಲು ಅಥವಾ ನಿಷ್ಕ್ರಿಯಗೊಳಿಸಲು ಕ್ಲಿಕ್ ಮಾಡಿ.",
    website: "ವೆಬ್‌ಸೈಟ್",
    switchOnOffWebsite: "ವೆಬ್‌ಸೈಟ್ ಆನ್/ಆಫ್ ಮಾಡಿ",
    webConfigs: "ವೆಬ್‌ಸೈಟ್ ಸಂರಚನೆಗಳು",
    webTrendingBar: "ವೆಬ್‌ಸೈಟ್ ಟ್ರೆಂಡಿಂಗ್ ಬಾರ್",
    websiteId: "ವೆಬ್‌ಸೈಟ್ ಐಡಿ",
    path: "ಪಥ (Path)",
    pathPlaceholder: "ತೆರೆಯಬೇಕಾದ ಪಥವನ್ನು ನಮೂದಿಸಿ",
    homePage: "ಮುಖಪುಟ",
    homePageCarousel: "ಮುಖಪುಟದ ಕ್ಯಾರೋಸೆಲ್",
    forPC: "PC ಗಾಗಿ:",
    forMobile: "ಮೊಬೈಲ್‌ಗಾಗಿ:",
    reset: "ಮರುಹೊಂದಿಸಿ",
    customFitting: "ಕಸ್ಟಮ್ ಫಿಟ್ಟಿಂಗ್",
    customDesigning: "ಕಸ್ಟಮ್ ಡಿಸೈನಿಂಗ್",
    freeDelivery: "ಉಚಿತ ಡೆಲಿವರಿ",
    assuredRefunds: "ಖಚಿತವಾದ ಮರುಪಾವತಿ",
    sizes: "ಗಾತ್ರಗಳು",
    addresses: "ವಿಳಾಸಗಳು",
    isTileVisible: "ಟೈಲ್ ಕಾಣಿಸುತ್ತಿದೆಯೇ?",
    isTileVisibleGrid: "ಟೈಲ್ ಕಾಣಿಸುತ್ತಿದೆ",
    categories: "ವರ್ಗಗಳು",
    mrpWithDots: "M.R.P",
    rtd: "ರವಾನಿಸಲು ಸಿದ್ಧವಾಗಿದೆ",
    inclusiveTax: "ಎಲ್ಲಾ ತೆರಿಗೆಗಳನ್ನು ಒಳಗೊಂಡ ಬೆಲೆ",
    rentInclusiveTax: "ಎಲ್ಲಾ ತೆರಿಗೆಗಳನ್ನು ಒಳಗೊಂಡ ಬಾಡಿಗೆ",
    purchase: "ಖರೀದಿ",
    rent: "ಬಾಡಿಗೆ",
    refundableSecurity: "ಹಿಂತಿರುಗಿಸಬಹುದಾದ ಭದ್ರತಾ ಠೇವಣಿ",
    securityDeposit: "ಭದ್ರತಾ ಠೇವಣಿ",
    refundSecurity: "ವಸ್ತುವನ್ನು ಹಿಂತಿರುಗಿಸಿದ ನಂತರ, ನಿಮ್ಮ ಭದ್ರತಾ ಠೇವಣಿಯನ್ನು ಮರುಪಾವತಿಸಲಾಗುತ್ತದೆ.",
    securityDepositDeduction: " ಡೆಲಿವರಿ ಆದ 5 ದಿನಗಳಲ್ಲಿ ನೀವು ವಸ್ತುವನ್ನು ಹಿಂತಿರುಗಿಸಬಹುದು. ಅದರ ನಂತರ ಪ್ರತಿ 5 ದಿನಗಳಿಗೊಮ್ಮೆ ನಿಮ್ಮ ಭದ್ರತಾ ಠೇವಣಿಯಿಂದ ಬಾಡಿಗೆ ಮೊತ್ತವನ್ನು ಕಡಿತಗೊಳಿಸಲಾಗುತ್ತದೆ.",
    sizeGuide: "ಗಾತ್ರದ ಮಾರ್ಗದರ್ಶಿ",
    customSize: "ಕಸ್ಟಮ್ ಗಾತ್ರ",
    loginToAddCustomSize: "ಕಸ್ಟಮ್ ಗಾತ್ರವನ್ನು ಸೇರಿಸಲು ಮತ್ತು ನೋಡಲು ಲಾಗಿನ್/ಸೈನ್ ಅಪ್ ಮಾಡಿ",
    yourCustomSizes: "ನಿಮ್ಮ ಕಸ್ಟಮ್ ಗಾತ್ರಗಳು",
    undoWishlistMsg: "ನೀವು <b>{name}</b> ಅನ್ನು ವಿಶ್‌ಲಿಸ್ಟ್‌ನಿಂದ ತೆಗೆದುಹಾಕಿದ್ದೀರಿ",
    undo: "ಹಿಂದಕ್ಕೆ (Undo)",
    textPlaceholder: "{0} ಅನ್ನು ನಮೂದಿಸಿ",
    address: "ವಿಳಾಸ",
    fullName: "ಹೆಸರು",
    city: "ನಗರ",
    country: "ದೇಶ",
    pinCode: "ಪಿನ್ ಕೋಡ್",
    state: "ರಾಜ್ಯ",
    landmark: "ಗುರುತು (Landmark)",
    streetAddress1: "ಫ್ಲಾಟ್, ಮನೆ ಸಂಖ್ಯೆ, ಕಟ್ಟಡ, ಕಂಪನಿ, ಅಪಾರ್ಟ್‌ಮೆಂಟ್",
    streetAddress2: "ಪ್ರದೇಶ, ರಸ್ತೆ, ಸೆಕ್ಟರ್, ಹಳ್ಳಿ",
    defaultAddress: "ಡೀಫಾಲ್ಟ್ ವಿಳಾಸವಾಗಿ ಹೊಂದಿಸಿ",
    setDefault: "ಡೀಫಾಲ್ಟ್ ಆಗಿ ಹೊಂದಿಸಿ",
    default: "ಡೀಫಾಲ್ಟ್",
    addToCart: "ಕಾರ್ಟ್‌ಗೆ ಸೇರಿಸಿ",
    buyNow: "ಈಗಲೇ ಖರೀದಿಸಿ",
    total: "ಒಟ್ಟು",
    clearCart: "ಕಾರ್ಟ್ ಖಾಲಿ ಮಾಡಿ",
    proceedToCheckout: "ಚೆಕ್ಔಟ್‌ಗೆ ಮುಂದುವರಿಯಿರಿ",
    shoppingCart: "ಶಾಪಿಂಗ್ ಕಾರ್ಟ್",
    loadingCart: "ಕಾರ್ಟ್ ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
    emptyCart: "ನಿಮ್ಮ ಕಾರ್ಟ್ ಖಾಲಿಯಾಗಿದೆ.",
    emptyWishlist: "ನಿಮ್ಮ ವಿಶ್‌ಲಿಸ್ಟ್ ಖಾಲಿಯಾಗಿದೆ.",
    deSelectAll: "ಎಲ್ಲವನ್ನೂ ಆಯ್ಕೆ ರದ್ದುಮಾಡಿ",
    invalidCoupon: "ಅಮಾನ್ಯವಾದ ಕೂಪನ್ ಕೋಡ್",
    couponApplied: "ಕೂಪನ್ ಅನ್ವಯಿಸಲಾಗಿದೆ: ",
    apply: "ಅನ್ವಯಿಸು",
    freeCaps: "ಉಚಿತ",
    deliveryCharges: "ಡೆಲಿವರಿ ಶುಲ್ಕಗಳು",
    subTotal: "ಒಟ್ಟು ಮೊತ್ತ (SubTotal)",
    changeSize: "ಗಾತ್ರ ಬದಲಿಸಿ",
    moveToWishlist: "ವಿಶ್‌ಲಿಸ್ಟ್‌ಗೆ ಸ್ಥಳಾಂತರಿಸಿ",
    share: "ಹಂಚಿಕೊಳ್ಳಿ",
    orderSummary: "ಆರ್ಡರ್ ಸಾರಾಂಶ",
    coupon: "ಕೂಪನ್",
    itemsForPurchasing: "ಖರೀದಿಸಲು ಆಯ್ಕೆಮಾಡಿದ ವಸ್ತುಗಳು",
    itemsForRenting: "ಬಾಡಿಗೆಗೆ ಆಯ್ಕೆಮಾಡಿದ ವಸ್ತುಗಳು",
    itemsSelected: "ಆಯ್ಕೆಮಾಡಿದ ವಸ್ತುಗಳು",
    applyCoupon: "ಕೂಪನ್ ಅನ್ವಯಿಸಿ",
    undoCartMsg: 'ಕಾರ್ಟ್‌ನಿಂದ <strong>{name}</strong> ತೆಗೆದುಹಾಕಲಾಗಿದೆ. ',
    itemRestored: "ವಸ್ತುವನ್ನು ಕಾರ್ಟ್‌ಗೆ ಮರುಸ್ಥಾಪಿಸಲಾಗಿದೆ",
    selectAll: "ಎಲ್ಲವನ್ನೂ ಆಯ್ಕೆಮಾಡಿ",
    itemMovedToWishlist: "ವಸ್ತುವನ್ನು ವಿಶ್‌ಲಿಸ್ಟ್‌ಗೆ ಸ್ಥಳಾಂತರಿಸಲಾಗಿದೆ.",
    itemRemoved: "ವಸ್ತುವನ್ನು ಕಾರ್ಟ್‌ನಿಂದ ತೆಗೆದುಹಾಕಲಾಗಿದೆ",
    addedToCart: "ವಸ್ತುವನ್ನು ಕಾರ್ಟ್‌ಗೆ ಸೇರಿಸಲಾಗಿದೆ",
    itemAddedToWishlist: "ವಸ್ತುವನ್ನು ವಿಶ್‌ಲಿಸ್ಟ್‌ಗೆ ಸೇರಿಸಲಾಗಿದೆ",
    itemRemovedFromWishlist: "ವಸ್ತುವನ್ನು ವಿಶ್‌ಲಿಸ್ಟ್‌ನಿಂದ ತೆಗೆದುಹಾಕಲಾಗಿದೆ",
    proceedToBuy: "ಖರೀದಿಸಲು ಮುಂದುವರಿಯಿರಿ",
    change: "ಬದಲಿಸಿ",
    checkout: "ಚೆಕ್ಔಟ್",
    deliverHere: "ಇಲ್ಲಿಗೆ ಡೆಲಿವರಿ ಮಾಡಿ",
    selectDeliveryAddress: "ಡೆಲಿವರಿ ವಿಳಾಸವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    selectedDeliveryAddress: "ಆಯ್ಕೆ ಮಾಡಿದ ಡೆಲಿವರಿ ವಿಳಾಸ",
    inventoryType: "ಇನ್ವೆಂಟರಿ ಪ್ರಕಾರ",
    currentlyDefaultAddress: "ಡೀಫಾಲ್ಟ್ ವಿಳಾಸ",
    chosenAddressUpdated: "ಆಯ್ಕೆ ಮಾಡಿದ ವಿಳಾಸ ಯಶಸ್ವಿಯಾಗಿ ನವೀಕರಿಸಲಾಗಿದೆ.",
    draftUpdated: "ಆರ್ಡರ್ ವಿವರಗಳು ಯಶಸ್ವಿಯಾಗಿ ನವೀಕರಿಸಲ್ಪಟ್ಟಿವೆ.",
    proceedToCheckout: "ಚೆಕ್ಔಟ್‌ಗೆ ಮುಂದುವರಿಯಲಾಗಿದೆ.",
    deliveringTo: "ಡೆಲಿವರಿ ಮಾಡಲಾಗುತ್ತಿದೆ",
    addNew: "ಹೊಸದನ್ನು ಸೇರಿಸಿ",
    itemsInOrder: "ಆರ್ಡರ್‌ನಲ್ಲಿರುವ ವಸ್ತುಗಳು",
    shipTogether: "ಎಲ್ಲಾ ವಸ್ತುಗಳನ್ನು ಒಟ್ಟಿಗೆ ಕಳುಹಿಸಿ",
    shipAsap: "ಸಿದ್ಧವಾದಂತೆ ಪ್ರತಿ ವಸ್ತುವನ್ನು ಕಳುಹಿಸಿ",
    shipItems: "ನಿಮ್ಮ ಆರ್ಡರ್ ಅನ್ನು ಯಾವಾಗ ಕಳುಹಿಸಬೇಕೆಂದು ನೀವು ಬಯಸುತ್ತೀರಿ?",
    shipItemsForOrder: "{user} ಆರ್ಡರ್ ಅನ್ನು ಯಾವಾಗ ಕಳುಹಿಸಬೇಕೆಂದು ಬಯಸುತ್ತಾರೆ?",
    orderPlacedTitle: "ಧನ್ಯವಾದಗಳು, ನಿಮ್ಮ ಆರ್ಡರ್ ಸಲ್ಲಿಕೆಯಾಗಿದೆ!",
    orderConfirmationSent: "ನಿಮ್ಮ ಇಮೇಲ್‌ಗೆ ದೃಢೀಕರಣ ಸಂದೇಶವನ್ನು ಕಳುಹಿಸಲಾಗಿದೆ.",
    orderId: "ಆರ್ಡರ್ ID",
    itemsInTheOrder: "ಆರ್ಡರ್‌ನಲ್ಲಿರುವ ವಸ್ತುಗಳು",
    viewOrders: "ನಿಮ್ಮ ಆರ್ಡರ್‌ಗಳನ್ನು ನೋಡಿ",
    viewAllOrders: "ಎಲ್ಲಾ ಆರ್ಡರ್‌ಗಳನ್ನು ನೋಡಿ",
    continueShopping: "ಶಾಪಿಂಗ್ ಮುಂದುವರಿಸಿ",
    orderDetails: "ಆರ್ಡರ್ ವಿವರಗಳು",
    appliedCoupon: "ಅನ್ವಯಿಸಿದ ಕೂಪನ್",
    orderPlacedOn: "ಆರ್ಡರ್ ಮಾಡಿದ ದಿನಾಂಕ",
    shipTo: "ಇಲ್ಲಿಗೆ ಕಳುಹಿಸಿ",
    noOrdersFound: "ಯಾವುದೇ ಆರ್ಡರ್‌ಗಳು ಕಂಡುಬಂದಿಲ್ಲ",
    yourOrders: "ನಿಮ್ಮ ಆರ್ಡರ್‌ಗಳು",
    paymentMode: "ಪಾವತಿ ವಿಧಾನ",
    paymentMethod: "ಪಾವತಿ ರೀತಿ",
    all: "ಎಲ್ಲಾ",
    pending: "ಬಾಕಿ (Pending)",
    shipped: "ರವಾನಿಸಲಾಗಿದೆ",
    delivered: "ಡೆಲಿವರಿ ಮಾಡಲಾಗಿದೆ",
    cancelled: "ರದ್ದುಗೊಳಿಸಲಾಗಿದೆ",
    allOrders: "ಎಲ್ಲಾ ಆರ್ಡರ್‌ಗಳು",
    newOrders: "ಹೊಸ ಆರ್ಡರ್‌ಗಳು",
    statusMessages: {
      forOrder: {
        forManager: {
          draft: "ಆರ್ಡರ್ ಡ್ರಾಫ್ಟ್‌ನಲ್ಲಿದೆ ಮತ್ತು ಇನ್ನೂ ಸಲ್ಲಿಕೆಯಾಗಿಲ್ಲ.",
          pending: "ಪಾವತಿ ಬಾಕಿ ಇದೆ.",
          placed: "ಆರ್ಡರ್ ಸಲ್ಲಿಕೆಯಾಗಿದೆ ಮತ್ತು ನಿಮ್ಮ ಕಡೆಯಿಂದ ದೃಢೀಕರಣಕ್ಕಾಗಿ ಕಾಯುತ್ತಿದೆ.",
          confirmed: "ನೀವು ಆರ್ಡರ್ ಅನ್ನು ದೃಢೀಕರಿಸಿದ್ದೀರಿ.",
          payment_failed: "ಪಾವತಿ ವಿಫಲವಾಗಿದೆ.",
          in_process: "ಆರ್ಡರ್ ಪ್ರಕ್ರಿಯೆಯಲ್ಲಿದೆ.",
          ready_to_dispatch: "ಆರ್ಡರ್ ರವಾನಿಸಲು ಸಿದ್ಧವಾಗಿದೆ.",
          shipped: "ಆರ್ಡರ್ ರವಾನಿಸಲಾಗಿದೆ.",
          in_transit: "ಆರ್ಡರ್ ಮಾರ್ಗದಲ್ಲಿದೆ.",
          delivered: "ಆರ್ಡರ್ ಡೆಲಿವರಿ ಮಾಡಲಾಗಿದೆ.",
          cancelled: "ಆರ್ಡರ್ ರದ್ದುಗೊಳಿಸಲಾಗಿದೆ.",
          cancellation_requested: "ಬಳಕೆದಾರರು ರದ್ದತಿಗಾಗಿ ವಿನಂತಿಸಿದ್ದಾರೆ.",
          cancellation_rejected: "ನೀವು ರದ್ದತಿ ವಿನಂತಿಯನ್ನು ತಿರಸ್ಕರಿಸಿದ್ದೀರಿ.",
          cancellation_refunded: "ಆರ್ಡರ್ ರದ್ದುಗೊಳಿಸಲಾಗಿದೆ ಮತ್ತು ಪಾವತಿಯನ್ನು ಮರುಪಾವತಿಸಲಾಗಿದೆ.",
          return_requested: "ಆರ್ಡರ್‌ಗಳಿಗಾಗಿ ರಿಟರ್ನ್ ವಿನಂತಿಗಳು.",
          return_rejected: "ನೀವು ರಿಟರ್ನ್ ವಿನಂತಿಯನ್ನು ತಿರಸ್ಕರಿಸಿದ್ದೀರಿ.",
          returned: "ಆರ್ಡರ್ ಹಿಂತಿರುಗಿಸಲಾಗಿದೆ.",
          return_refunded: "ಹಿಂತಿರುಗಿಸಿದ ನಂತರ ಪಾವತಿಯನ್ನು ಮರುಪಾವತಿಸಲಾಗಿದೆ.",
          refunded: "ಪಾವತಿಯನ್ನು ಮರುಪಾವತಿಸಲಾಗಿದೆ.",
          rto_requested: "ನಿಮ್ಮಿಂದ RTO ಗಾಗಿ ವಿನಂತಿಸಲಾಗಿದೆ.",
          rto_rejected: "ನೀವು RTO ವಿನಂತಿಯನ್ನು ತಿರಸ್ಕರಿಸಿದ್ದೀರಿ.",
          rto_approved: "ನೀವು RTO ವಿನಂತಿಯನ್ನು ಅನುಮೋದಿಸಿದ್ದೀರಿ.",
          rto_in_progress: "RTO ಪ್ರಕ್ರಿಯೆಯಲ್ಲಿದೆ.",
          rto_delivered: "ಆರ್ಡರ್ RTO ಮೂಲಕ ನಿಮಗೆ ಮರಳಿದೆ.",
          rto_verified: "RTO ವಸ್ತುಗಳನ್ನು ನೀವು ದೃಢೀಕರಿಸಿದ್ದೀರಿ.",
          rto_refunded: "RTO ನಂತರ ಗ್ರಾಹಕರಿಗೆ ಪಾವತಿ ಮರುಪಾವತಿಸಲಾಗಿದೆ."
        },
        forUser: {
          draft: "ನಿಮ್ಮ ಆರ್ಡರ್ ಚೆಕ್ಔಟ್‌ನಲ್ಲಿದೆ ಆದರೆ ಇನ್ನೂ ಸಲ್ಲಿಕೆಯಾಗಿಲ್ಲ.",
          pending: "ಪಾವತಿ ಬಾಕಿ ಇದೆ. ದಯವಿಟ್ಟು ನಿಮ್ಮ ಪಾವತಿಯನ್ನು ಪೂರ್ಣಗೊಳಿಸಿ.",
          placed: "ನಿಮ್ಮ ಆರ್ಡರ್ ಸಲ್ಲಿಕೆಯಾಗಿದೆ ಮತ್ತು ದೃಢೀಕರಣಕ್ಕಾಗಿ ಕಾಯುತ್ತಿದೆ.",
          confirmed: "ನಿಮ್ಮ ಆರ್ಡರ್ ಅನ್ನು ಮಾರಾಟಗಾರರು ದೃಢೀಕರಿಸಿದ್ದಾರೆ.",
          payment_failed: "ಪಾವತಿ ವಿಫಲವಾಗಿದೆ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
          in_process: "ನಿಮ್ಮ ಆರ್ಡರ್ ಅನ್ನು ಮಾರಾಟಗಾರರು ಪ್ರಕ್ರಿಯೆಗೊಳಿಸುತ್ತಿದ್ದಾರೆ.",
          ready_to_dispatch: "ನಿಮ್ಮ ಆರ್ಡರ್ ರವಾನಿಸಲು ಸಿದ್ಧವಾಗಿದೆ.",
          shipped: "ನಿಮ್ಮ ಆರ್ಡರ್ ರವಾನಿಸಲಾಗಿದೆ.",
          in_transit: "ನಿಮ್ಮ ಆರ್ಡರ್ ಮಾರ್ಗದಲ್ಲಿದೆ.",
          delivered: "ನಿಮ್ಮ ಆರ್ಡರ್ ಡೆಲಿವರಿ ಮಾಡಲಾಗಿದೆ.",
          cancelled: "ನಿಮ್ಮ ಆರ್ಡರ್ ರದ್ದುಗೊಂಡಿದೆ.",
          cancellation_requested: "ಈ ಆರ್ಡರ್ ಅನ್ನು ರದ್ದುಗೊಳಿಸಲು ನೀವು ವಿನಂತಿಸಿದ್ದೀರಿ.",
          cancellation_rejected: "ನಿಮ್ಮ ರದ್ದತಿ ವಿನಂತಿಯನ್ನು ತಿರಸ್ಕರಿಸಲಾಗಿದೆ.",
          cancellation_refunded: "ನಿಮ್ಮ ರದ್ದತಿಯನ್ನು ಸ್ವೀಕರಿಸಲಾಗಿದೆ ಮತ್ತು ಪಾವತಿಯನ್ನು ಮರುಪಾವತಿಸಲಾಗಿದೆ.",
          return_requested: "ನಿಮ್ಮ ಆರ್ಡರ್‌ಗಾಗಿ ರಿಟರ್ನ್ ವಿನಂತಿಯನ್ನು ಸಲ್ಲಿಸಲಾಗಿದೆ.",
          return_rejected: "ನಿಮ್ಮ ರಿಟರ್ನ್ ವಿನಂತಿಯನ್ನು ತಿರಸ್ಕರಿಸಲಾಗಿದೆ.",
          returned: "ನಿಮ್ಮ ಆರ್ಡರ್ ಅನ್ನು ಹಿಂತಿರುಗಿಸಲಾಗಿದೆ.",
          return_refunded: "ಹಿಂತಿರುಗಿಸಿದ ನಂತರ ನಿಮ್ಮ ಪಾವತಿಯನ್ನು ಮರುಪಾವತಿಸಲಾಗಿದೆ.",
          refunded: "ನಿಮ್ಮ ಪಾವತಿಯನ್ನು ಮರುಪಾವತಿಸಲಾಗಿದೆ.",
          rto_requested: "ಆರ್ಡರ್‌ಗಾಗಿ RTO ವಿನಂತಿಸಲಾಗಿದೆ.",
          rto_rejected: "ಮಾರಾಟಗಾರರು RTO ವಿನಂತಿಯನ್ನು ತಿರಸ್ಕರಿಸಿದ್ದಾರೆ.",
          rto_approved: "ಮಾರಾಟಗಾರರು ಈ ಆರ್ಡರ್‌ಗೆ RTO ಅನ್ನು ಅನುಮೋದಿಸಿದ್ದಾರೆ.",
          rto_in_progress: "ನಿಮ್ಮ ಆರ್ಡರ್ RTO ಮಾರ್ಗದಲ್ಲಿದೆ.",
          rto_delivered: "ನಿಮ್ಮ ಆರ್ಡರ್ RTO ಮೂಲಕ ಮಾರಾಟಗಾರರಿಗೆ ಮರಳಿದೆ.",
          rto_verified: "ನೀವು ಹಿಂತಿರುಗಿಸಿದ ಆರ್ಡರ್ ಅನ್ನು ಮಾರಾಟಗಾರರು ದೃಢೀಕರಿಸಿದ್ದಾರೆ.",
          rto_refunded: "RTO ನಂತರ ನಿಮಗೆ ಮರುಪಾವತಿ ಮಾಡಲಾಗಿದೆ."
        }
      }
    },
    statusColors: {
      draft: "var(--secondarytext-color)",
      pending: "var(--warning-color)",
      placed: "var(--info-color)",
      confirmed: "var(--success-color)",
      payment_failed: "var(--danger-color)",
      in_process: "var(--infolight-color)",
      ready_to_dispatch: "purple",
      shipped: "blue",
      in_transit: "var(--primarylight-color)",
      delivered: "var(--successdark-color)",
      cancellation_requested: "orange",
      cancelled: "var(--dangerlight-color)",
      cancellation_rejected: "red",
      cancellation_refunded: "var(--success-color)",
      return_requested: "var(--secondary-color)",
      returned: "var(--dangerlight-color)",
      return_rejected: "var(--warning-color)",
      return_refunded: "var(--success-color)",
      refunded: "var(--success-color)",
      rto_requested: "var(--warningdark-color)",
      rto_rejected: "red",
      rto_approved: "var(--success-color)",
      rto_in_progress: "blueviolet",
      rto_delivered: "var(--info-color)",
      rto_verified: "var(--successdark-color)",
      rto_refunded: "var(--success-color)"
    },
    orderPages: {
      allOrders: { title: "ಎಲ್ಲಾ ಆರ್ಡರ್‌ಗಳು", statuses: ["ALL"] },
      pendingOrders: { title: "ಬಾಕಿ ಆರ್ಡರ್‌ಗಳು", statuses: ["PENDING"] },
      newOrders: { title: "ಹೊಸ ಆರ್ಡರ್‌ಗಳು", statuses: ["PLACED"] },
      confirmedOrders: { title: "ದೃಢೀಕರಿಸಿದ ಆರ್ಡರ್‌ಗಳು", statuses: ["CONFIRMED"] },
      processingOrders: { title: "ಪ್ರಕ್ರಿಯೆಯಲ್ಲಿರುವ ಆರ್ಡರ್‌ಗಳು", statuses: ["IN_PROCESS"] },
      readyToDispatchOrders: { title: "ರವಾನಿಸಲು ಸಿದ್ಧವಿರುವ ಆರ್ಡರ್‌ಗಳು", statuses: ["READY_TO_DISPATCH"] },
      onTheWayOrders: { title: "ಮಾರ್ಗದಲ್ಲಿರುವ ಆರ್ಡರ್‌ಗಳು", statuses: ["SHIPPED", "IN_TRANSIT"] },
      deliveredOrders: { title: "ಡೆಲಿವರಿ ಆದ ಆರ್ಡರ್‌ಗಳು", statuses: ["DELIVERED"] },
      cancelled: { title: "ರದ್ದುಗೊಂಡ ಆರ್ಡರ್‌ಗಳು", statuses: ["CANCELLED"] },
      returns: { title: "ರಿಟರ್ನ್ಸ್", statuses: ["ALLRETURNS"], showOrderStatuses: false },
      cancellation_requested: { title: "ರದ್ದತಿಗೆ ವಿನಂತಿಸಿದ ಆರ್ಡರ್‌ಗಳು", statuses: ["CANCELLATION_REQUESTED"] },
      cancellation_rejected: { title: "ರದ್ದತಿ ತಿರಸ್ಕರಿಸಿದ ಆರ್ಡರ್‌ಗಳು", statuses: ["CANCELLATION_REJECTED"] },
      cancellation_refunded: { title: "ರದ್ದತಿ ಮರುಪಾವತಿ ಆದ ಆರ್ಡರ್‌ಗಳು", statuses: ["CANCELLATION_REFUNDED"] },
      return_requested: { title: "ರಿಟರ್ನ್‌ಗೆ ವಿನಂತಿಸಿದ ಆರ್ಡರ್‌ಗಳು", statuses: ["RETURN_REQUESTED"] },
      returned: { title: "ಹಿಂತಿರುಗಿದ ಆರ್ಡರ್‌ಗಳು", statuses: ["RETURNED"] },
      return_rejected: { title: "ರಿಟರ್ನ್ ತಿರಸ್ಕರಿಸಿದ ಆರ್ಡರ್‌ಗಳು", statuses: ["RETURN_REJECTED"] },
      return_refunded: { title: "ರಿಟರ್ನ್ ಮರುಪಾವತಿ ಆದ ಆರ್ಡರ್‌ಗಳು", statuses: ["RETURN_REFUNDED"] },
      rto_requested: { title: "RTO ವಿನಂತಿಸಿದ ಆರ್ಡರ್‌ಗಳು", statuses: ["RTO_REQUESTED"] },
      rto_rejected: { title: "RTO ತಿರಸ್ಕರಿಸಿದ ಆರ್ಡರ್‌ಗಳು", statuses: ["RTO_REJECTED"] },
      rto_approved: { title: "RTO ಅನುಮೋದಿಸಿದ ಆರ್ಡರ್‌ಗಳು", statuses: ["RTO_APPROVED"] },
      rto_in_progress: { title: "RTO ಪ್ರಕ್ರಿಯೆಯಲ್ಲಿರುವ ಆರ್ಡರ್‌ಗಳು", statuses: ["RTO_IN_PROGRESS"] },
      rto_delivered: { title: "RTO ಡೆಲಿವರಿ ಆದ ಆರ್ಡರ್‌ಗಳು", statuses: ["RTO_DELIVERED"] },
      rto_verified: { title: "RTO ದೃಢೀಕರಿಸಿದ ಆರ್ಡರ್‌ಗಳು", statuses: ["RTO_VERIFIED"] },
      rto_refunded: { title: "RTO ಮರುಪಾವತಿ ಆದ ಆರ್ಡರ್‌ಗಳು", statuses: ["RTO_REFUNDED"] }
    },
    confirmedOrders: "ದೃಢೀಕರಿಸಿದ ಆರ್ಡರ್‌ಗಳು",
    processingOrders: "ಪ್ರಕ್ರಿಯೆಯಲ್ಲಿರುವ ಆರ್ಡರ್‌ಗಳು",
    readyToDispatchOrders: "ರವಾನಿಸಲು ಸಿದ್ಧವಿರುವ ಆರ್ಡರ್‌ಗಳು",
    onTheWayOrders: "ಮಾರ್ಗದಲ್ಲಿರುವ ಆರ್ಡರ್‌ಗಳು",
    deliveredOrders: "ಡೆಲಿವರಿ ಆದ ಆರ್ಡರ್‌ಗಳು",
    cancelled_orders: "ರದ್ದುಗೊಂಡ ಆರ್ಡರ್‌ಗಳು",
    cancellation_requested_orders: "ರದ್ದತಿಗೆ ವಿನಂತಿಸಿದ ಆರ್ಡರ್‌ಗಳು",
    return_requested_orders: "ರಿಟರ್ನ್‌ಗೆ ವಿನಂತಿಸಿದ ಆರ್ಡರ್‌ಗಳು",
    return_refunded_orders: "ರಿಟರ್ನ್ ಮರುಪಾವತಿ ಆದ ಆರ್ಡರ್‌ಗಳು",
    returns: "ರಿಟರ್ನ್ಸ್",
    returned_orders: "ಹಿಂತಿರುಗಿದ ಆರ್ಡರ್‌ಗಳು",
    return_rejected_orders: "ರಿಟರ್ನ್ ತಿರಸ್ಕರಿಸಿದ ಆರ್ಡರ್‌ಗಳು",
    cancellation_rejected_orders: "ರದ್ದತಿ ತಿರಸ್ಕರಿಸಿದ ಆರ್ಡರ್‌ಗಳು",
    cancellation_refunded_orders: "ರದ್ದತಿ ಮರುಪಾವತಿ ಆದ ಆರ್ಡರ್‌ಗಳು",
    rto_requested_orders: "RTO ವಿನಂತಿಸಿದ ಆರ್ಡರ್‌ಗಳು",
    rto_rejected_orders: "RTO ತಿರಸ್ಕರಿಸಿದ ಆರ್ಡರ್‌ಗಳು",
    rto_approved_orders: "RTO ಅನುಮೋದಿಸಿದ ಆರ್ಡರ್‌ಗಳು",
    rto_in_progress_orders: "RTO ಪ್ರಕ್ರಿಯೆಯಲ್ಲಿರುವ ಆರ್ಡರ್‌ಗಳು",
    rto_delivered_orders: "RTO ಡೆಲಿವರಿ ಆದ ಆರ್ಡರ್‌ಗಳು",
    rto_verified_orders: "RTO ದೃಢೀಕರಿಸಿದ ಆರ್ಡರ್‌ಗಳು",
    rto_refunded_orders: "RTO ಮರುಪಾವತಿ ಆದ ಆರ್ಡರ್‌ಗಳು",
    moreOptions: "ಹೆಚ್ಚಿನ ಆಯ್ಕೆಗಳು",
    details: "ವಿವರಗಳು",
    viewProductPage: "ಉತ್ಪನ್ನದ ಪುಟ ನೋಡಿ",
    viewSize: "ಗಾತ್ರ ನೋಡಿ",
    trackStatus: "ಸ್ಥಿತಿ ಟ್ರ್ಯಾಕ್ ಮಾಡಿ",
    auditTrail: "ಆಡಿಟ್ ಟ್ರಯಲ್",
    changedFrom: "ನಿಂದ ಬದಲಾಗಿದೆ",
    changedTo: "ಗೆ ಬದಲಾಗಿದೆ",
    entityType: "ಎಂಟಿಟಿ ಪ್ರಕಾರ",
    entityId: "ಎಂಟಿಟಿ ID",
    performedBy: "ಮಾಡಿದವರು",
    timestamp: "ಸಮಯ",
    trackingDetails: "ಟ್ರ್ಯಾಕಿಂಗ್ ವಿವರಗಳು",
    noDetailsFound: "ಯಾವುದೇ ವಿವರಗಳು ಕಂಡುಬಂದಿಲ್ಲ",
    userDetails: 'ಬಳಕೆದಾರರ ವಿವರಗಳು',
    followUs: "ನಮ್ಮನ್ನು ಅನುಸರಿಸಿ",
    allRightsReserved: "ಎಲ್ಲಾ ಹಕ್ಕುಗಳನ್ನು ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ",
    fastAndSecured: "ವೇಗವಾದ ಮತ್ತು ಸುರಕ್ಷಿತ ಪಾವತಿ ಆಯ್ಕೆಗಳು",
    company: "ಕಂಪನಿ",
    myAccount: "ನನ್ನ ಖಾತೆ",
    home: "ಮುಖಪುಟ",
    account: "ಖಾತೆ",
    search: "ಹುಡುಕು",
    cart: "ಕಾರ್ಟ್",
    language: "ಭಾಷೆ",
    somethingWentWrong: "ಏನೋ ತಪ್ಪಾಗಿದೆ!",
    note: "ಸೂಚನೆ",
    notAllowed1: "ಈ ಅಪ್ಲಿಕೇಶನ್‌ಗೆ ಲಾಗಿನ್ ಮಾಡಲು ನಿಮಗೆ ಅನುಮತಿಯಿಲ್ಲ",
    notAllowed2: "ಕೇವಲ ಅಡ್ಮಿನ್ ಮತ್ತು ಮ್ಯಾನೇಜರ್‌ಗೆ ಮಾತ್ರ ಇದಕ್ಕೆ ಪ್ರವೇಶವಿದೆ",
    notAllowed3: "ನೀವು ಅವರಲ್ಲಿ ಒಬ್ಬರಾಗಿದ್ದು ಇನ್ನೂ ಪ್ರವೇಶಿಸಲು ಸಾಧ್ಯವಾಗದಿದ್ದರೆ ಅಡ್ಮಿನ್ ಅನ್ನು ಸಂಪರ್ಕಿಸಿ",
    logOutAndBackToHome: "ಲಾಗ್ ಔಟ್ ಮಾಡಿ ಮತ್ತು ಮುಖಪುಟಕ್ಕೆ ಹೋಗಿ",
    whatsAppUs: "ನಮಗೆ ವಾಟ್ಸಾಪ್ ಮಾಡಿ",
    ourContactDetails: "ನಮ್ಮ ಸಂಪರ್ಕ ವಿವರಗಳು",
    workingHours: "ಕೆಲಸದ ಸಮಯ",
    instagram: "ಇನ್‌ಸ್ಟಾಗ್ರಾಮ್",
    facebook: "ಫೇಸ್‌ಬುಕ್",
    x: "X (ಟ್ವಿಟರ್)",
    threads: "ಥ್ರೆಡ್ಸ್",
    youtube: "ಯೂಟ್ಯೂಬ್",
    pinterest: "ಪಿಂಟ್ರೆಸ್ಟ್",
    quotaUsage: "ಮೇಲ್/SMS ಕೋಟಾ ಬಳಕೆ",
    used: "ಬಳಸಲಾಗಿದೆ",
    remaining: "ಬಾಕಿ",
    totalQuota: "ಒಟ್ಟು ಕೋಟಾ",
    sms: "SMS",
    whatsapp: "ವಾಟ್ಸಾಪ್",
    brevo: "Brevo",
    count: "ಸಂಖ್ಯೆ",
    date: "ದಿನಾಂಕ",
    gmail: "Gmail",
    quota: "ಕೋಟಾ",
    teamUsers: "ತಂಡ",
    member: "ಸದಸ್ಯ",
    customer: "ಗ್ರಾಹಕ",
    customers: "ಗ್ರಾಹಕರು",
    profileImage: "ಪ್ರೊಫೈಲ್ ಚಿತ್ರ",
    gender: "ಲಿಂಗ",
    role: "ಪಾತ್ರ (Role)",
    activatedText: "ಸಕ್ರಿಯಗೊಳಿಸಲಾಗಿದೆ",
    selectRolePlaceholder: "ಪಾತ್ರವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    accountActiveLabel: "ಬಳಕೆದಾರರ ಖಾತೆ ಸಕ್ರಿಯ/ನಿಷ್ಕ್ರಿಯವಾಗಿರಬೇಕೆ ಎಂದು ಆಯ್ಕೆಮಾಡಿ:",
    user: "ಬಳಕೆದಾರ",
    actions: "ಕ್ರಮಗಳು",
    setAsDiscontinued: "ಸ್ಥಗಿತಗೊಂಡಿದೆ ಎಂದು ಹೊಂದಿಸಿ",
    resetToDefaultPassword: "ಡೀಫಾಲ್ಟ್ ಪಾಸ್‌ವರ್ಡ್‌ಗೆ ಮರುಹೊಂದಿಸಿ",
    confirmMsg: "ನೀವು ಖಚಿತವಾಗಿ <b>{0}</b> {1} ಅನ್ನು {2} ಮಾಡಲು ಬಯಸುವಿರಾ?",
    discontinued: "ಸ್ಥಗಿತಗೊಳಿಸಲಾಗಿದೆ",
    base: "ಬೇಸ್",
    setActive: "ಸಕ್ರಿಯಗೊಳಿಸಿ",
    refresh: "ರಿಫ್ರೆಶ್",
};

export default kn;