const ml = {
    login: "ലോഗിൻ",
    signup: "സൈൻ അപ്പ്",
    forgotPassword: "പാസ്‌വേഡ് മറന്നോ?",
    welcome: "സ്വാഗതം, ഉപയോക്താവേ!",
    logout: "ലോഗ് ഔട്ട്",
    requiredField: "ഈ ഫീൽഡ് നിർബന്ധമാണ്.",
    invalidEmail: "സാധുവായ ഒരു ഇമെയിൽ വിലാസം നൽകുക.",
    name: "പേര്",
    fullNamePlaceholder: "നിങ്ങളുടെ പേര് നൽകുക",
    firstName: "ആദ്യനാമം",
    lastName: "അവസാനനാമം",
    mobileOrEmail: "ഇമെയിൽ ഐഡി അല്ലെങ്കിൽ മൊബൈൽ നമ്പർ",
    firstNamePlaceHolder: "നിങ്ങളുടെ ആദ്യനാമം നൽകുക",
    lastNamePlaceHolder: "നിങ്ങളുടെ അവസാനനാമം നൽകുക",
    email: "ഇമെയിൽ",
    emailPlaceHolder: "നിങ്ങളുടെ ഇമെയിൽ നൽകുക",
    mobile: "മൊബൈൽ നമ്പർ",
    mobilePlaceHolder: "നിങ്ങളുടെ മൊബൈൽ നമ്പർ നൽകുക",
    receiveOTP: "നിങ്ങൾക്ക് {0}-ൽ ഒരു OTP ലഭിക്കും.",
    pleaseWait: "ദയവായി കാത്തിരിക്കൂ...",
    fetchingDataFailedTitle: "അഭ്യർത്ഥിച്ച ഡാറ്റ ലഭ്യമാക്കാൻ കഴിഞ്ഞില്ല.",
    failureMessage: "നിങ്ങളുടെ അഭ്യർത്ഥന പ്രോസസ്സ് ചെയ്യുന്നതിൽ ഒരു പിശക് സംഭവിച്ചു.",
    technicalGlitch: "ഇത് താൽക്കാലിക സാങ്കേതിക തകരാർ കാരണമാകാം. കുറച്ച് കഴിഞ്ഞ് വീണ്ടും ശ്രമിക്കുക.",
    contactSupport: "സപ്പോർട്ടുമായി ബന്ധപ്പെടുക: <a href=\"{supportEmail}\" style=\"text-decoration:none; target=\"_blank\" rel=\"noopener noreferrer\" color: #27c0e0;\">{supportEmail}</a>.",
    register: "രജിസ്റ്റർ ചെയ്യുക",
    registering: "രജിസ്റ്റർ ചെയ്യുന്നു....",
    submitOTP: "OTP പരിശോധിക്കുക",
    submittingOTP: "OTP പരിശോധിക്കുന്നു....",
    otp: "OTP",
    otpPlaceholder: "OTP നൽകുക",
    enterOTP: "({value}) എന്നതിൽ നിങ്ങൾക്ക് ലഭിച്ച OTP ദയവായി നൽകുക.",
    signedUp: "നിങ്ങൾ വിജയകരമായി സൈൻ അപ്പ് ചെയ്തു!",
    failedToSignUp: "സൈൻ അപ്പ് ചെയ്യുന്നതിൽ പരാജയപ്പെട്ടു.",
    loggedIn: "നിങ്ങൾ വിജയകരമായി ലോഗിൻ ചെയ്തു!",
    failedToLogIn: "ലോഗിൻ ചെയ്യുന്നതിൽ പരാജയപ്പെട്ടു.",
    resendOTP: "OTP വീണ്ടും അയക്കുക",
    resendingOTP: "OTP വീണ്ടും അയക്കുന്നു....",
    password: "പാസ്‌വേഡ്",
    logingin: "ലോഗിൻ ചെയ്യുന്നു",
    passwordPlaceHolder: "നിങ്ങളുടെ പാസ്‌വേഡ് നൽകുക",
    otpChild1: "OTP തെറ്റായിരിക്കാം",
    otpChild2: "OTP കാലാവധി കഴിഞ്ഞിരിക്കാം.",
    otpChild3: "നെറ്റ്‌വർക്ക് പ്രശ്‌നമുണ്ടാകാം.",
    otpChild4: "സെർവർ തകരാറിലായിരിക്കാം",
    passwordRequirementMsg: "നിങ്ങളുടെ അക്കൗണ്ട് സുരക്ഷിതമാക്കാൻ, താഴെ പറയുന്നവ ഉൾപ്പെടെ കുറഞ്ഞത് എട്ട് (8) അക്ഷരങ്ങളുള്ള ഒരു പാസ്‌വേഡ് സൃഷ്ടിക്കുക:",
    passwordRequireMent: "പാസ്‌വേഡ് നിബന്ധനകൾ",
    upperLowerCase: "വലിയ അക്ഷരങ്ങളും ചെറിയ അക്ഷരങ്ങളും",
    subHeadingIns: "ശക്തമായ പാസ്‌വേഡിനായി, നിങ്ങളുടെ പാസ്‌വേഡ് താഴെ പറയുന്ന കാര്യങ്ങൾ പാലിക്കണം",
    minimum8Char: "കുറഞ്ഞത് 8 അക്ഷരങ്ങൾ (നിർബന്ധം)",
    atLeastOneNumericals: "കുറഞ്ഞത് ഒരു അക്കം (നിർബന്ധം)",
    numericals: "അക്കങ്ങൾ",
    specialChar: "പ്രത്യേക അക്ഷരങ്ങൾ",
    oneUpperCase: "കുറഞ്ഞത് ഒരു വലിയ അക്ഷരം (നിർബന്ധം)",
    oneLowerCase: "കുറഞ്ഞത് ഒരു ചെറിയ അക്ഷരം (നിർബന്ധം)",
    partnerCompanyName: "പങ്കാളി കമ്പനിയുടെ പേര്",
    atLeastOneSpecialChar: "കുറഞ്ഞത് ഒരു പ്രത്യേക അക്ഷരം (നിർബന്ധം)",
    skip: "ഒഴിവാക്കുക",
    confirmPassword: "പാസ്‌വേഡ് സ്ഥിരീകരിക്കുക",
    setPassword: "പാസ്‌വേഡ് സജ്ജമാക്കുക",
    accountInstruction: "അക്കൗണ്ട് ആക്സസ് ചെയ്യാനും ഓർഡറുകൾ നിയന്ത്രിക്കാനും",
    aboutUs: "ഞങ്ങളെക്കുറിച്ച്",
    contactUs: "ഞങ്ങളെ ബന്ധപ്പെടുക",
    profile: "പ്രൊഫൈൽ",
    orders: "ഓർഡറുകൾ",
    wishlist: "വിഷ് ലിസ്റ്റ്",
    loginSignup: "ലോഗിൻ/സൈൻ അപ്പ്",
    welcome: "സ്വാഗതം",
    profileImgUpdated: "പ്രൊഫൈൽ ചിത്രം വിജയകരമായി അപ്‌ഡേറ്റ് ചെയ്തു",
    save: "സേവ് ചെയ്യുക",
    cancel: "റദ്ദാക്കുക",
    adjustImage: "ചിത്രം ക്രമീകരിക്കുക",
    dragSqrToChangeImgSizePos: "വലുപ്പവും സ്ഥാനവും മാറ്റാൻ ചതുരം വലിച്ചിടുക.",
    preview: "പ്രിവ്യൂ",
    imageCropped: "ക്രോപ്പ് ചെയ്ത ചിത്രം വിജയകരമായി സേവ് ചെയ്തു!",
    alternateMobile: "മറ്റൊരു മൊബൈൽ നമ്പർ",
    male: "പുരുഷൻ",
    female: "സ്ത്രീ",
    others: "മറ്റുള്ളവർ",
    genderLabel: "നിങ്ങളുടെ ലിംഗഭേദം തിരഞ്ഞെടുക്കുക:",
    dob: "ജനനതീയതി",
    update: "അപ്‌ഡേറ്റ് ചെയ്യുക",
    changePassword: "പാസ്‌വേഡ് മാറ്റുക",
    updatePassword: "പാസ്‌വേഡ് അപ്‌ഡേറ്റ് ചെയ്യുക",
    updateProfile: "പ്രൊഫൈൽ അപ്‌ഡേറ്റ് ചെയ്യുക",
    oldPassword: "പഴയ പാസ്‌വേഡ്",
    confirmPasswordNotMatchPassword: "സ്ഥിരീകരണ പാസ്‌വേഡും പാസ്‌വേഡും തമ്മിൽ പൊരുത്തപ്പെടുന്നില്ല.",
    passReqNotFulfil: "പാസ്‌വേഡ് നിബന്ധനകൾ പാലിച്ചിട്ടില്ല.",
    passwordUpdated: "പാസ്‌വേഡ് വിജയകരമായി അപ്‌ഡേറ്റ് ചെയ്തു!",
    profileUpdated: "പ്രൊഫൈൽ വിജയകരമായി അപ്‌ഡേറ്റ് ചെയ്തു!",
    pageNotFound: "പേജ് കണ്ടെത്തിയില്ല",
    brokenLinkMsg1: "നിങ്ങൾ ക്ലിക്ക് ചെയ്ത ലിങ്ക് തെറ്റായിരിക്കാം അല്ലെങ്കിൽ പേജ് നീക്കം ചെയ്തിരിക്കാം.",
    brokenLinkMsg2: "ഹോം പേജ് സന്ദർശിക്കുക അല്ലെങ്കിൽ പ്രശ്നത്തെക്കുറിച്ച് ഞങ്ങളെ അറിയിക്കുക.",
    backToHome: "ഹോം പേജിലേക്ക് മടങ്ങുക",
    dashboard: "ഡാഷ്‌ബോർഡ്",
    pages: "പേജുകൾ",
    inventory: "ഇൻവെന്ററി",
    customOrders: "കസ്റ്റം ഓർഡറുകൾ",
    team: "ടീം",
    customers: "ഉപഭോക്താക്കൾ",
    settings: "ക്രമീകരണങ്ങൾ",
    messages: "സന്ദേശങ്ങൾ",
    pendingOrders: "Pending ഓർഡറുകൾ",
    completedOrders: "പൂർത്തിയാക്കിയ ഓർഡറുകൾ",
    offers: "ഓഫറുകൾ",
    id: "ID",
    name: "പേര്",
    brand: "ബ്രാൻഡ്",
    category: "കാറ്റഗറി",
    price: "വില",
    status: "നില",
    createdDate: "സൃഷ്ടിച്ച തീയതി",
    updatedDate: "അവസാനം പുതുക്കിയത്",
    action: "നടപടി",
    productName: "ഉൽപ്പന്നത്തിന്റെ പേര്",
    size: "വലിപ്പം",
    color: "നിറം",
    sku: "SKU",
    stockQuantity: "അളവ്",
    products: "ഉൽപ്പന്നങ്ങൾ",
    description: "വിവരണം",
    parent: "പാരന്റ്",
    namePlaceholder: "പേര് നൽകുക",
    descriptionPlaceholder: "വിവരണം നൽകുക",
    categoryPlaceholder: "കാറ്റഗറി തിരഞ്ഞെടുക്കുക",
    categoryLevel: "കാറ്റഗറി {0} ലെവൽ ",
    at: "At",
    modifiedOn: "പുതുക്കിയ തീയതി",
    today: "ഇന്ന്",
    edit: "തിരുത്തുക",
    delete: "നീക്കം ചെയ്യുക",
    activated: "{entity} സജീവമാക്കി.",
    deactivated: "{entity} നിഷ്ക്രിയമാക്കി.",
    yes: "അതെ",
    no: "അല്ല",
    confirm: "സ്ഥിരീകരിക്കുക",
    deleteMsg: "ഉറപ്പാണോ? <b>{0}</b> {1} നീക്കം ചെയ്യണോ?",
    childrenOf: "Children of ",
    page: "പേജ്",
    add: "ചേർക്കുക",
    deactivateFirst: "ആദ്യം {entity} നിഷ്ക്രിയമാക്കുക.",
    activeCantAction: "സജീവമായ {entity}-ൽ {action} ചെയ്യാൻ കഴിയില്ല.",
    entityIsActive: "<b>{0}</b> {entity} സജീവമാണ്.",
    searchPlaceHolder: "{entity}-നായി തിരയുക...",
    copy: "കോപ്പി ചെയ്യുക",
    deleted: "നീക്കം ചെയ്തു",
    edited: "തിരുത്തി",
    product: "ഉൽപ്പന്നം",
    title: "ശീർഷകം",
    titlePlaceholder: "ശീർഷകം നൽകുക",
    image: "ചിത്രം",
    material: "മെറ്റീരിയൽ",
    materialPlaceholder: "മെറ്റീരിയൽ നൽകുക",
    colorPlaceholder: "നിറം നൽകുക",
    sku: "SKU കോഡ്",
    skuPlaceholder: "യൂണിക് SKU കോഡ് നൽകുക",
    quantity: "അളവ്",
    type: "തരം",
    productName: "ഉൽപ്പന്നത്തിന്റെ പേര്",
    selectProductPlaceholder: "ഉൽപ്പന്നം തിരഞ്ഞെടുക്കുക",
    sizeChart: "സൈസ് ചാർട്ട്",
    enterMeasure: "നിങ്ങളുടെ {0} അളവ് നൽകുക",
    chest: "നെഞ്ച്",
    hips: "ഇടുപ്പ്",
    neck: "കഴുത്ത്",
    sleeve: "കൈ (Sleeve)",
    arm: "കൈ",
    topLength: "മുകൾ ഭാഗം നീളം",
    shoulder: "തോൾ",
    inseam: "ഇൻസീം",
    bottomLength: "താഴത്തെ നീളം",
    thigh: "തുട",
    waist: "അരക്കെട്ട്",
    topBody: "ശരീരത്തിന്റെ മുകൾ ഭാഗം",
    bottomBody: "ശരീരത്തിന്റെ താഴത്തെ ഭാഗം",
    rank: "റാങ്ക്",
    sale: "വിൽപ്പന",
    rental: "വാടക",
    selectRankPlaceholder: "റാങ്ക് തിരഞ്ഞെടുക്കുക",
    mrp: "MRP",
    salePrice: "വിൽപ്പന വില",
    discount: "ഡിസ്കൗണ്ട്",
    selectSizePlaceholder: "സൈസ് തിരഞ്ഞെടുക്കുക",
    mrpPlaceholder: "MRP നൽകുക (₹)",
    salePricePlaceholder: "വിൽപ്പന വില നൽകുക (₹)",
    discountPlaceholder: "ഡിസ്കൗണ്ട് നൽകുക (%)",
    quantityPlaceholder: "അളവ് നൽകുക",
    saleOrRentPrice: "വിൽപ്പന/വാടക വില",
    security: "സെക്യൂരിറ്റി ഡെപ്പോസിറ്റ്",
    securityPlaceholder: "റീഫണ്ട് = ഡെപ്പോസിറ്റ് - (വാടക വില - ഡിസ്കൗണ്ട് %)",
    size_Quant_Price: "സൈസ് - അളവ് - വിൽപ്പന വില",
    view: "കാണുക",
    webSettings: "വെബ് ക്രമീകരണങ്ങൾ",
    siteUnderMaintenance: "സൈറ്റ് അറ്റകുറ്റപ്പണിയിലാണ്",
    weWillGetbackShortly: "ഞങ്ങൾ ഉടൻ തിരിച്ചെത്തും. ദയവായി പിന്നീട് പരിശോധിക്കുക.",
    reload: "റീലോഡ് ചെയ്യുക",
    enableWebsite: "വെബ്‌സൈറ്റ് പ്രവർത്തനക്ഷമമാക്കാനോ നിർത്താനോ ക്ലിക്ക് ചെയ്യുക.",
    website: "വെബ്‌സൈറ്റ്",
    switchOnOffWebsite: "വെബ്‌സൈറ്റ് ഓൺ/ഓഫ് ചെയ്യുക",
    webConfigs: "വെബ്‌സൈറ്റ് കോൺഫിഗറേഷനുകൾ",
    webTrendingBar: "വെബ്‌സൈറ്റ് ട്രെൻഡിംഗ് ബാർ",
    websiteId: "വെബ്‌സൈറ്റ് ഐഡി",
    path: "പാത്ത്",
    pathPlaceholder: "തുറക്കേണ്ട പാത്ത് നൽകുക",
    homePage: "ഹോം പേജ്",
    homePageCarousel: "ഹോം പേജ് കറൗസൽ",
    forPC: "PC-ക്കായി:",
    forMobile: "മൊബൈലിനായി:",
    reset: "റീസെറ്റ്",
    customFitting: "കസ്റ്റം ഫിറ്റിംഗ്",
    customDesigning: "കസ്റ്റം ഡിസൈനിംഗ്",
    freeDelivery: "സൗജന്യ ഡെലിവറി",
    assuredRefunds: "ഉറപ്പായ റീഫണ്ട്",
    sizes: "സൈസുകൾ",
    addresses: "വിലാസങ്ങൾ",
    isTileVisible: "ടൈൽ ദൃശ്യമാണോ?",
    isTileVisibleGrid: "ടൈൽ ദൃശ്യമാണ്",
    categories: "കാറ്റഗറികൾ",
    mrpWithDots: "M.R.P",
    rtd: "അയക്കാൻ തയ്യാറാണ്",
    inclusiveTax: "എല്ലാ നികുതികളും ഉൾപ്പെടെയുള്ള വില",
    rentInclusiveTax: "എല്ലാ നികുതികളും ഉൾപ്പെടെയുള്ള വാടക",
    purchase: "വാങ്ങുക",
    rent: "വാടകയ്ക്ക് എടുക്കുക",
    refundableSecurity: "തിരികെ ലഭിക്കുന്ന സെക്യൂരിറ്റി ഡെപ്പോസിറ്റ്",
    securityDeposit: "സെക്യൂരിറ്റി ഡെപ്പോസിറ്റ്",
    refundSecurity: "ഉൽപ്പന്നം തിരികെ നൽകിയ ശേഷം, നിങ്ങളുടെ സെക്യൂരിറ്റി ഡെപ്പോസിറ്റ് റീഫണ്ട് ചെയ്യുന്നതാണ്.",
    securityDepositDeduction: "ഡെലിവറി കഴിഞ്ഞ് 5 ദിവസത്തിനുള്ളിൽ നിങ്ങൾക്ക് ഉൽപ്പന്നം തിരികെ നൽകാം. അതിനുശേഷം ഓരോ 5 ദിവസത്തേക്കും നിങ്ങളുടെ സെക്യൂരിറ്റി ഡെപ്പോസിറ്റിൽ നിന്ന് വാടക തുക കുറയ്ക്കുന്നതാണ്.",
    sizeGuide: "സൈസ് ഗൈഡ്",
    customSize: "കസ്റ്റം സൈസ്",
    loginToAddCustomSize: "കസ്റ്റം സൈസ് ചേർക്കാനും കാണാനും ലോഗിൻ/സൈൻ അപ്പ് ചെയ്യുക",
    yourCustomSizes: "നിങ്ങളുടെ കസ്റ്റം സൈസുകൾ",
    undoWishlistMsg: "നിങ്ങൾ വിഷ് ലിസ്റ്റിൽ നിന്ന് <b>{name}</b> നീക്കം ചെയ്തു",
    undo: "Undo",
    textPlaceholder: "{0} നൽകുക",
    address: "വിലാസം",
    fullName: "പേര്",
    city: "നഗരം",
    country: "രാജ്യം",
    pinCode: "പിൻ കോഡ്",
    state: "സംസ്ഥാനം",
    landmark: "ലാൻഡ്‌മാർക്ക്",
    streetAddress1: "ഫ്ലാറ്റ്, വീട്ടു നമ്പർ, ബിൽഡിംഗ്, കമ്പനി, അപ്പാർട്ട്മെന്റ്",
    streetAddress2: "ഏരിയ, സ്ട്രീറ്റ്, സെക്ടർ, ഗ്രാമം",
    defaultAddress: "സ്ഥിരം വിലാസമായി സജ്ജമാക്കുക",
    setDefault: "സ്ഥിരമായി സജ്ജമാക്കുക",
    default: "ഡിഫോൾട്ട്",
    addToCart: "കാർട്ടിലേക്ക് ചേർക്കുക",
    buyNow: "ഇപ്പോൾ വാങ്ങുക",
    total: "ആകെ",
    clearCart: "കാർട്ട് കാലിയാക്കുക",
    proceedToCheckout: "ചെക്ക്ഔട്ടിലേക്ക് പോകുക",
    shoppingCart: "ഷോപ്പിംഗ് കാർട്ട്",
    loadingCart: "കാർട്ട് ലോഡ് ചെയ്യുന്നു...",
    emptyCart: "നിങ്ങളുടെ കാർട്ട് കാലിയാണ്.",
    emptyWishlist: "നിങ്ങളുടെ വിഷ് ലിസ്റ്റ് കാലിയാണ്.",
    deSelectAll: "എല്ലാം ഒഴിവാക്കുക",
    invalidCoupon: "അസാധുവായ കൂപ്പൺ കോഡ്",
    couponApplied: "കൂപ്പൺ ഉപയോഗിച്ചു: ",
    apply: "Apply",
    freeCaps: "സൗജന്യം",
    deliveryCharges: "ഡെലിവറി ചാർജ്",
    subTotal: "സബ് ടോട്ടൽ",
    changeSize: "സൈസ് മാറ്റുക",
    moveToWishlist: "വിഷ് ലിസ്റ്റിലേക്ക് മാറ്റുക",
    share: "ഷെയർ ചെയ്യുക",
    orderSummary: "ഓർഡർ സംഗ്രഹം",
    coupon: "കൂപ്പൺ",
    itemsForPurchasing: "വാങ്ങുന്നതിനായി തിരഞ്ഞെടുത്തവ",
    itemsForRenting: "വാടകയ്ക്കായി തിരഞ്ഞെടുത്തവ",
    itemsSelected: "തിരഞ്ഞെടുത്തവ",
    applyCoupon: "കൂപ്പൺ ചേർക്കുക",
    undoCartMsg: 'കാർട്ടിൽ നിന്ന് <strong>{name}</strong> നീക്കം ചെയ്തു. ',
    itemRestored: "ഉൽപ്പന്നം കാർട്ടിലേക്ക് തിരികെ ചേർത്തു",
    selectAll: "എല്ലാം തിരഞ്ഞെടുക്കുക",
    itemMovedToWishlist: "വിഷ് ലിസ്റ്റിലേക്ക് മാറ്റി.",
    itemRemoved: "കാർട്ടിൽ നിന്ന് നീക്കം ചെയ്തു",
    addedToCart: "കാർട്ടിലേക്ക് ചേർത്തു",
    itemAddedToWishlist: "വിഷ് ലിസ്റ്റിലേക്ക് ചേർത്തു",
    itemRemovedFromWishlist: "വിഷ് ലിസ്റ്റിൽ നിന്ന് നീക്കം ചെയ്തു",
    proceedToBuy: "വാങ്ങാൻ തുടരുക",
    change: "മാറ്റുക",
    checkout: "ചെക്ക്ഔട്ട്",
    deliverHere: "ഇവിടെ ഡെലിവർ ചെയ്യുക",
    selectDeliveryAddress: "ഡെലിവറി വിലാസം തിരഞ്ഞെടുക്കുക",
    selectedDeliveryAddress: "തിരഞ്ഞെടുത്ത ഡെലിവറി വിലാസം",
    inventoryType: "ഇൻവെന്ററി തരം",
    currentlyDefaultAddress: "ഡിഫോൾട്ട് വിലാസം",
    chosenAddressUpdated: "തിരഞ്ഞെടുത്ത വിലാസം വിജയകരമായി അപ്‌ഡേറ്റ് ചെയ്തു.",
    draftUpdated: "ഓർഡർ വിവരങ്ങൾ വിജയകരമായി അപ്‌ഡേറ്റ് ചെയ്തു.",
    proceedToCheckout: "ചെക്ക്ഔട്ടിലേക്ക് നീങ്ങി.",
    deliveringTo: "ഡെലിവറി ചെയ്യുന്നത്",
    addNew: "പുതിയത് ചേർക്കുക",
    itemsInOrder: "ഓർഡറിലെ ഉൽപ്പന്നങ്ങൾ",
    shipTogether: "എല്ലാ ഉൽപ്പന്നങ്ങളും ഒരുമിച്ച് അയക്കുക",
    shipAsap: "ഓരോന്നും തയ്യാറാകുമ്പോൾ ഉടൻ അയക്കുക",
    shipItems: "നിങ്ങളുടെ ഓർഡർ എപ്പോൾ അയക്കണം?",
    shipItemsForOrder: "{user}-ന്റെ ഓർഡർ എപ്പോൾ അയക്കണം?",
    orderPlacedTitle: "നന്ദി, നിങ്ങളുടെ ഓർഡർ നൽകിയിരിക്കുന്നു!",
    orderConfirmationSent: "നിങ്ങളുടെ ഇമെയിലിലേക്ക് ഒരു സ്ഥിരീകരണ സന്ദേശം അയച്ചിട്ടുണ്ട്.",
    orderId: "ഓർഡർ ID",
    itemsInTheOrder: "ഓർഡറിലെ ഉൽപ്പന്നങ്ങൾ",
    viewOrders: "നിങ്ങളുടെ ഓർഡറുകൾ കാണുക",
    viewAllOrders: "എല്ലാ ഓർഡറുകളും കാണുക",
    continueShopping: "ഷോപ്പിംഗ് തുടരുക",
    orderDetails: "ഓർഡർ വിവരങ്ങൾ",
    appliedCoupon: "ഉപയോഗിച്ച കൂപ്പൺ",
    orderPlacedOn: "ഓർഡർ നൽകിയ തീയതി",
    shipTo: "അയക്കേണ്ട വിലാസം",
    noOrdersFound: "ഓർഡറുകളൊന്നും കണ്ടെത്തിയില്ല",
    yourOrders: "നിങ്ങളുടെ ഓർഡറുകൾ",
    paymentMode: "പേയ്‌മെന്റ് മോഡ്",
    paymentMethod: "പേയ്‌മെന്റ് രീതി",
    all: "എല്ലാം",
    pending: "ബാക്കി",
    shipped: "അയച്ചു",
    delivered: "ഡെലിവർ ചെയ്തു",
    cancelled: "റദ്ദാക്കി",
    allOrders: "എല്ലാ ഓർഡറുകളും",
    newOrders: "പുതിയ ഓർഡറുകൾ",
    statusMessages: {
      forOrder: {
        forManager: {
          draft: "ഓർഡർ ഡ്രാഫ്റ്റ് ഘട്ടത്തിലാണ്, ഇതുവരെ നൽകിയിട്ടില്ല.",
          pending: "പേയ്‌മെന്റ് ബാക്കിയാണ്.",
          placed: "ഓർഡർ നൽകി, നിങ്ങളുടെ സ്ഥിരീകരണത്തിനായി കാത്തിരിക്കുന്നു.",
          confirmed: "നിങ്ങൾ ഓർഡർ സ്ഥിരീകരിച്ചു.",
          payment_failed: "പേയ്‌മെന്റ് പരാജയപ്പെട്ടു.",
          in_process: "ഓർഡർ പ്രോസസ്സ് ചെയ്യുന്നു.",
          ready_to_dispatch: "ഓർഡർ അയക്കാൻ തയ്യാറാണ്.",
          shipped: "ഓർഡർ അയച്ചു.",
          in_transit: "ഓർഡർ വഴിയിലാണ്.",
          delivered: "ഓർഡർ ഡെലിവർ ചെയ്തു.",
          cancelled: "ഓർഡർ റദ്ദാക്കി.",
          cancellation_requested: "ഉപഭോക്താവ് ഓർഡർ റദ്ദാക്കാൻ അഭ്യർത്ഥിച്ചു.",
          cancellation_rejected: "നിങ്ങൾ റദ്ദാക്കൽ അഭ്യർത്ഥന നിരസിച്ചു.",
          cancellation_refunded: "ഓർഡർ റദ്ദാക്കി പണം തിരികെ നൽകി.",
          return_requested: "തിരികെ നൽകാനുള്ള അഭ്യർത്ഥനകൾ.",
          return_rejected: "നിങ്ങൾ റിട്ടേൺ അഭ്യർത്ഥന നിരസിച്ചു.",
          returned: "ഓർഡർ തിരികെ ലഭിച്ചു.",
          return_refunded: "തിരികെ ലഭിച്ച ശേഷം പണം നൽകി.",
          refunded: "പണം തിരികെ നൽകി.",
          rto_requested: "നിങ്ങൾ RTO അഭ്യർത്ഥിച്ചു.",
          rto_rejected: "നിങ്ങൾ RTO അഭ്യർത്ഥന നിരസിച്ചു.",
          rto_approved: "നിങ്ങൾ RTO അഭ്യർത്ഥന അംഗീകരിച്ചു.",
          rto_in_progress: "RTO നടന്നുക്കൊണ്ടിരിക്കുന്നു.",
          rto_delivered: "RTO വഴി ഓർഡർ നിങ്ങൾക്ക് തിരികെ ലഭിച്ചു.",
          rto_verified: "RTO ഇനങ്ങൾ നിങ്ങൾ പരിശോധിച്ചു.",
          rto_refunded: "RTO-യ്ക്ക് ശേഷം ഉപഭോക്താവിന് പണം നൽകി."
        },
        forUser: {
          draft: "നിങ്ങളുടെ ഓർഡർ ചെക്ക്ഔട്ടിലാണ്, ഇതുവരെ നൽകിയിട്ടില്ല.",
          pending: "പേയ്‌മെന്റ് ബാക്കിയാണ്. ദയവായി പേയ്‌മെന്റ് പൂർത്തിയാക്കുക.",
          placed: "നിങ്ങളുടെ ഓർഡർ നൽകി, സ്ഥിരീകരണത്തിനായി കാത്തിരിക്കുന്നു.",
          confirmed: "നിങ്ങളുടെ ഓർഡർ സെല്ലർ സ്ഥിരീകരിച്ചു.",
          payment_failed: "പേയ്‌മെന്റ് പരാജയപ്പെട്ടു. ദയവായി വീണ്ടും ശ്രമിക്കുക.",
          in_process: "നിങ്ങളുടെ ഓർഡർ സെല്ലർ പ്രോസസ്സ് ചെയ്യുന്നു.",
          ready_to_dispatch: "നിങ്ങളുടെ ഓർഡർ അയക്കാൻ തയ്യാറാണ്.",
          shipped: "നിങ്ങളുടെ ഓർഡർ അയച്ചു.",
          in_transit: "നിങ്ങളുടെ ഓർഡർ വഴിയിലാണ്.",
          delivered: "നിങ്ങളുടെ ഓർഡർ ഡെലിവർ ചെയ്തു.",
          cancelled: "നിങ്ങളുടെ ഓർഡർ റദ്ദാക്കി.",
          cancellation_requested: "നിങ്ങൾ ഓർഡർ റദ്ദാക്കാൻ അഭ്യർത്ഥിച്ചു.",
          cancellation_rejected: "നിങ്ങളുടെ റദ്ദാക്കൽ അഭ്യർത്ഥന നിരസിക്കപ്പെട്ടു.",
          cancellation_refunded: "റദ്ദാക്കൽ അംഗീകരിച്ചു പണം തിരികെ നൽകി.",
          return_requested: "ഓർഡർ തിരികെ നൽകാനുള്ള അഭ്യർത്ഥന നൽകി.",
          return_rejected: "നിങ്ങളുടെ റിട്ടേൺ അഭ്യർത്ഥന നിരസിക്കപ്പെട്ടു.",
          returned: "നിങ്ങളുടെ ഓർഡർ തിരികെ നൽകി.",
          return_refunded: "തിരികെ നൽകിയ ശേഷം പണം റീഫണ്ട് ചെയ്തു.",
          refunded: "പണം റീഫണ്ട് ചെയ്തു.",
          rto_requested: "ഓർഡറിനായി RTO അഭ്യർത്ഥിച്ചു.",
          rto_rejected: "സെല്ലർ RTO അഭ്യർത്ഥന നിരസിച്ചു.",
          rto_approved: "സെല്ലർ RTO അംഗീകരിച്ചു.",
          rto_in_progress: "നിങ്ങളുടെ ഓർഡർ RTO വഴിയിലാണ്.",
          rto_delivered: "നിങ്ങളുടെ ഓർഡർ സെല്ലർക്ക് തിരികെ ലഭിച്ചു.",
          rto_verified: "നിങ്ങൾ തിരികെ നൽകിയ ഓർഡർ സെല്ലർ പരിശോധിച്ചു.",
          rto_refunded: "RTO-യ്ക്ക് ശേഷം നിങ്ങൾക്ക് പണം തിരികെ ലഭിച്ചു."
        }
      },
      forItem: {
        forManager: {
          draft: "ഇനം ഓർഡർ ഡ്രാഫ്റ്റിൽ ചേർത്തു, ഇതുവരെ നൽകിയിട്ടില്ല.",
          pending: "ഈ ഇനത്തിനായുള്ള പേയ്‌മെന്റ് ബാക്കിയാണ്.",
          placed: "ഇനം നൽകി, നിങ്ങളുടെ സ്ഥിരീകരണത്തിനായി കാത്തിരിക്കുന്നു.",
          confirmed: "നിങ്ങൾ ഈ ഇനം സ്ഥിരീകരിച്ചു.",
          payment_failed: "ഈ ഇനത്തിനായുള്ള പേയ്‌മെന്റ് പരാജയപ്പെട്ടു.",
          in_process: "ഇനം പ്രോസസ്സ് ചെയ്യുന്നു.",
          ready_to_dispatch: "ഇനം അയക്കാൻ തയ്യാറാണ്.",
          shipped: "ഇനം അയച്ചു.",
          in_transit: "ഇനം വഴിയിലാണ്.",
          delivered: "ഇനം ഡെലിവർ ചെയ്തു.",
          cancelled: "ഈ ഇനം റദ്ദാക്കി.",
          cancellation_requested: "ഉപഭോക്താവ് ഈ ഇനം റദ്ദാക്കാൻ അഭ്യർത്ഥിച്ചു.",
          cancellation_rejected: "നിങ്ങൾ ഈ ഇനത്തിനായുള്ള റദ്ദാക്കൽ അഭ്യർത്ഥന നിരസിച്ചു.",
          cancellation_refunded: "ഈ ഇനം റദ്ദാക്കി പണം തിരികെ നൽകി.",
          return_requested: "ഉപഭോക്താവ് ഈ ഇനം തിരികെ നൽകാൻ അഭ്യർത്ഥിച്ചു.",
          return_rejected: "നിങ്ങൾ ഈ ഇനത്തിനായുള്ള റിട്ടേൺ അഭ്യർത്ഥന നിരസിച്ചു.",
          returned: "ഇനം തിരികെ ലഭിച്ചു.",
          return_refunded: "തിരികെ നൽകിയ ഇനത്തിന് പണം തിരികെ നൽകി.",
          refunded: "ഈ ഇനത്തിന് പണം തിരികെ നൽകി.",
          rto_requested: "ഈ ഇനത്തിന് RTO അഭ്യർത്ഥിച്ചു.",
          rto_rejected: "നിങ്ങൾ ഈ ഇനത്തിനായുള്ള RTO അഭ്യർത്ഥന നിരസിച്ചു.",
          rto_approved: "നിങ്ങൾ ഈ ഇനത്തിനായുള്ള RTO അഭ്യർത്ഥന അംഗീകരിച്ചു.",
          rto_in_progress: "ഈ ഇനത്തിന് RTO നടന്നുക്കൊണ്ടിരിക്കുന്നു.",
          rto_delivered: "ഈ ഇനം നിങ്ങൾക്ക് തിരികെ ലഭിച്ചു.",
          rto_verified: "തിരികെ ലഭിച്ച ഇനം പരിശോധിച്ചു.",
          rto_refunded: "RTO-യ്ക്ക് ശേഷം ഈ ഇനത്തിന് പണം തിരികെ നൽകി."
        },
        forUser: {
          draft: "ഈ ഇനം ചെക്ക്ഔട്ടിലാണ്, ഇതുവരെ നൽകിയിട്ടില്ല.",
          pending: "ഈ ഇനത്തിനായുള്ള പേയ്‌മെന്റ് ബാക്കിയാണ്. ദയവായി പേയ്‌മെന്റ് പൂർത്തിയാക്കുക.",
          placed: "ഈ ഇനം നൽകി, സ്ഥിരീകരണത്തിനായി കാത്തിരിക്കുന്നു.",
          confirmed: "ഈ ഇനം സെല്ലർ സ്ഥിരീകരിച്ചു.",
          payment_failed: "ഈ ഇനത്തിനായുള്ള പേയ്‌മെന്റ് പരാജയപ്പെട്ടു. ദയവായി വീണ്ടും ശ്രമിക്കുക.",
          in_process: "ഈ ഇനം സെല്ലർ പ്രോസസ്സ് ചെയ്യുന്നു.",
          ready_to_dispatch: "ഈ ഇനം അയക്കാൻ തയ്യാറാണ്.",
          shipped: "ഈ ഇനം അയച്ചു.",
          in_transit: "ഈ ഇനം വഴിയിലാണ്.",
          delivered: "ഈ ഇനം ഡെലിവർ ചെയ്തു.",
          cancelled: "ഈ ഇനം റദ്ദാക്കി.",
          cancellation_requested: "നിങ്ങൾ ഈ ഇനം റദ്ദാക്കാൻ അഭ്യർത്ഥിച്ചു.",
          cancellation_rejected: "ഈ ഇനത്തിനായുള്ള നിങ്ങളുടെ റദ്ദാക്കൽ അഭ്യർത്ഥന നിരസിക്കപ്പെട്ടു.",
          cancellation_refunded: "ഈ ഇനത്തിനായുള്ള നിങ്ങളുടെ റദ്ദാക്കൽ അംഗീകരിച്ചു പണം തിരികെ നൽകി.",
          return_requested: "ഈ ഇനത്തിന് തിരികെ നൽകാനുള്ള അഭ്യർത്ഥന നൽകി.",
          return_rejected: "ഈ ഇനത്തിനായുള്ള നിങ്ങളുടെ റിട്ടേൺ അഭ്യർത്ഥന നിരസിക്കപ്പെട്ടു.",
          returned: "ഈ ഇനം തിരികെ നൽകി.",
          return_refunded: "ഈ ഇനം തിരികെ നൽകിയ ശേഷം പണം റീഫണ്ട് ചെയ്തു.",
          refunded: "ഈ ഇനത്തിന് പണം റീഫണ്ട് ചെയ്തു.",
          rto_requested: "ഈ ഇനത്തിന് നിങ്ങൾ/സെല്ലർ RTO അഭ്യർത്ഥിച്ചു.",
          rto_rejected: "സെല്ലർ ഈ ഇനത്തിനായുള്ള RTO അഭ്യർത്ഥന നിരസിച്ചു.",
          rto_approved: "സെല്ലർ ഈ ഇനത്തിനായുള്ള RTO അംഗീകരിച്ചു.",
          rto_in_progress: "ഈ ഇനം RTO വഴിയിലാണ്.",
          rto_delivered: "ഈ ഇനം സെല്ലർക്ക് തിരികെ ലഭിച്ചു.",
          rto_verified: "നിങ്ങൾ തിരികെ നൽകിയ ഇനം സെല്ലർ പരിശോധിച്ചു.",
          rto_refunded: "RTO-യ്ക്ക് ശേഷം ഈ ഇനത്തിന് പണം തിരികെ ലഭിച്ചു."
        }
      }
    },
    statusColors: {
      draft: "var(--secondarytext-color)",
      pending: "var(--warning-color)",
      placed: "var(--info-color)",
      confirmed: "var(--success-color)",
      payment_failed: "var(--danger-color)",
      in_process: "var(--infolight-color)",
      ready_to_dispatch: "purple",
      shipped: "blue",
      in_transit: "var(--primarylight-color)",
      delivered: "var(--successdark-color)",
    
      cancellation_requested: "orange",
      cancelled: "var(--dangerlight-color)",
      cancellation_rejected: "red",
      cancellation_refunded: "var(--success-color)",
    
      return_requested: "var(--secondary-color)",
      returned: "var(--dangerlight-color)",
      return_rejected: "var(--warning-color)",
      return_refunded: "var(--success-color)",
    
      refunded: "var(--success-color)",
    
      // New RTO statuses
      rto_requested: "var(--warningdark-color)",
      rto_rejected: "red",
      rto_approved: "var(--success-color)",
      rto_in_progress: "blueviolet",
      rto_delivered: "var(--info-color)",
      rto_verified: "var(--successdark-color)",
      rto_refunded: "var(--success-color)"
    },
    orderPages: {
      allOrders: {
        title: "എല്ലാ ഓർഡറുകളും",
        statuses: ["ALL"]
      },
      pendingOrders: {
        title: "Pending ഓർഡറുകൾ",
        statuses: ["PENDING"]
      },
      newOrders: {
        title: "പുതിയ ഓർഡറുകൾ",
        statuses: ["PLACED"]
      },
      confirmedOrders: {
        title: "സ്ഥിരീകരിച്ചവ",
        statuses: ["CONFIRMED"]
      },
      processingOrders: {
        title: "പ്രോസസ്സിംഗിലുള്ളവ",
        statuses: ["IN_PROCESS"]
      },
      readyToDispatchOrders: {
        title: "അയക്കാൻ തയ്യാറായവ",
        statuses: ["READY_TO_DISPATCH"]
      },
      onTheWayOrders: {
        title: "വഴിയിലുള്ളവ",
        statuses: ["SHIPPED", "IN_TRANSIT"]
      },
      deliveredOrders: {
        title: "ലഭിച്ച ഓർഡറുകൾ",
        statuses: ["DELIVERED"]
      },
    
      // After-sale statuses
      cancelled: {
        title: "റദ്ദാക്കിയവ",
        statuses: ["CANCELLED"]
      },
      returns: {
        title: "റിട്ടേണുകൾ",
        statuses: ["ALLRETURNS"],
        showOrderStatuses: false
      },  
      cancellation_requested: {
        title: "റദ്ദാക്കാൻ ആവശ്യപ്പെട്ടവ",
        statuses: ["CANCELLATION_REQUESTED"]
      },
      cancellation_rejected: {
        title: "റദ്ദാക്കൽ നിരസിച്ചവ",
        statuses: ["CANCELLATION_REJECTED"]
      },
      cancellation_refunded: {
        title: "റദ്ദാക്കി പണം നൽകിയവ",
        statuses: ["CANCELLATION_REFUNDED"]
      },
      return_requested: {
        title: "തിരികെ നൽകാൻ ആവശ്യപ്പെട്ടവ",
        statuses: ["RETURN_REQUESTED"]
      },
      returned: {
        title: "തിരികെ നൽകിയവ",
        statuses: ["RETURNED"]
      },
      return_rejected: {
        title: "റിട്ടേൺ നിരസിച്ചവ",
        statuses: ["RETURN_REJECTED"]
      },
      return_refunded: {
        title: "റിട്ടേൺ റീഫണ്ട് നൽകിയവ",
        statuses: ["RETURN_REFUNDED"]
      },
    
      // New RTO pages
      rto_requested: {
        title: "RTO ആവശ്യപ്പെട്ടവ",
        statuses: ["RTO_REQUESTED"]
      },
      rto_rejected: {
        title: "RTO നിരസിച്ചവ",
        statuses: ["RTO_REJECTED"]
      },
      rto_approved: {
        title: "RTO അംഗീകരിച്ചവ",
        statuses: ["RTO_APPROVED"]
      },
      rto_in_progress: {
        title: "RTO നടന്നുകൊണ്ടിരിക്കുന്നവ",
        statuses: ["RTO_IN_PROGRESS"]
      },
      rto_delivered: {
        title: "RTO പൂർത്തിയായവ",
        statuses: ["RTO_DELIVERED"]
      },
      rto_verified: {
        title: "RTO പരിശോധിച്ചവ",
        statuses: ["RTO_VERIFIED"]
      },
      rto_refunded: {
        title: "RTO റീഫണ്ട് നൽകിയവ",
        statuses: ["RTO_REFUNDED"]
      }
    },  
    confirmedOrders: "സ്ഥിരീകരിച്ച ഓർഡറുകൾ",
    processingOrders: "പ്രോസസ്സിംഗിലുള്ള ഓർഡറുകൾ",
    readyToDispatchOrders: "അയക്കാൻ തയ്യാറായ ഓർഡറുകൾ",
    onTheWayOrders: "വഴിയിലുള്ള ഓർഡറുകൾ",
    deliveredOrders: "ലഭിച്ച ഓർഡറുകൾ",
    cancelled_orders: "റദ്ദാക്കിയ ഓർഡറുകൾ",
    cancellation_requested_orders: "റദ്ദാക്കാൻ ആവശ്യപ്പെട്ട ഓർഡറുകൾ",
    return_requested_orders: "തിരികെ നൽകാൻ ആവശ്യപ്പെട്ട ഓർഡറുകൾ",
    return_refunded_orders: "റിട്ടേൺ റീഫണ്ട് നൽകിയ ഓർഡറുകൾ",
    returns: "റിട്ടേണുകൾ",
    returned_orders: "തിരികെ നൽകിയ ഓർഡറുകൾ",
    return_rejected_orders: "റിട്ടേൺ നിരസിച്ച ഓർഡറുകൾ",
    cancellation_rejected_orders: "റദ്ദാക്കൽ നിരസിച്ച ഓർഡറുകൾ",
    cancellation_refunded_orders: "റദ്ദാക്കി പണം നൽകിയ ഓർഡറുകൾ",
    rto_requested_orders: "RTO ആവശ്യപ്പെട്ട ഓർഡറുകൾ",
    rto_rejected_orders: "RTO നിരസിച്ച ഓർഡറുകൾ",
    rto_approved_orders: "RTO അംഗീകരിച്ച ഓർഡറുകൾ",
    rto_in_progress_orders: "RTO നടന്നുകൊണ്ടിരിക്കുന്ന ഓർഡറുകൾ",
    rto_delivered_orders: "RTO പൂർത്തിയായ ഓർഡറുകൾ",
    rto_verified_orders: "RTO പരിശോധിച്ച ഓർഡറുകൾ",
    rto_refunded_orders: "RTO റീഫണ്ട് നൽകിയ ഓർഡറുകൾ",
    moreOptions: "കൂടുതൽ ഓപ്ഷനുകൾ",
    details: "വിവരങ്ങൾ",
    viewProductPage: "ഉൽപ്പന്ന പേജ് കാണുക",
    viewSize: "സൈസ് കാണുക",
    trackStatus: "നില പരിശോധിക്കുക",
    auditTrail: "Audit Trail",
    changedFrom: "ഇതിൽ നിന്ന് മാറ്റി",
    changedTo: "ഇതിലേക്ക് മാറ്റി",
    entityType: "Entity type",
    entityId: "Entity Id",
    performedBy: "ചെയ്തത്",
    timestamp: "സമയം",
    trackingDetails: "ട്രാക്കിംഗ് വിവരങ്ങൾ",
    noDetailsFound: "വിവരങ്ങളൊന്നും കണ്ടെത്തിയില്ല",
    userDetails: 'ഉപയോക്താവിന്റെ വിവരങ്ങൾ',
    followUs: "ഞങ്ങളെ ഫോളോ ചെയ്യുക",
    allRightsReserved: "എല്ലാ അവകാശങ്ങളും നിക്ഷിപ്തം",
    fastAndSecured: "വേഗതയേറിയതും സുരക്ഷിതവുമായ പേയ്‌മെന്റ് ഓപ്ഷനുകൾ",
    company: "കമ്പനി",
    myAccount: "എന്റെ അക്കൗണ്ട്",
    home: "ഹോം",
    account: "അക്കൗണ്ട്",
    search: "തിരയുക",
    cart: "കാർട്ട്",
    language: "ഭാഷ",
    somethingWentWrong: "എന്തോ പിശക് സംഭവിച്ചു!",
    note: "കുറിപ്പ്",
    notAllowed1: "നിങ്ങൾക്ക് ഈ ആപ്ലിക്കേഷനിൽ ലോഗിൻ ചെയ്യാൻ അനുമതിയില്ല",
    notAllowed2: "അഡ്മിനും മാനേജർക്കും മാത്രമേ ഇതിലേക്ക് പ്രവേശനമുള്ളൂ",
    notAllowed3: "നിങ്ങൾ ഇവരിൽ ഒരാളായിട്ടും പ്രവേശിക്കാൻ കഴിയുന്നില്ലെങ്കിൽ അഡ്മിനെ ബന്ധപ്പെടുക",
    logOutAndBackToHome: "ലോഗ് ഔട്ട് ചെയ്ത് ഹോമിലേക്ക് പോകുക",
    whatsAppUs: "വാട്സാപ്പ് ചെയ്യുക",
    ourContactDetails: "ബന്ധപ്പെടാനുള്ള വിവരങ്ങൾ",
    workingHours: "പ്രവൃത്തി സമയം",
    instagram: "ഇൻസ്റ്റാഗ്രാം",
    facebook: "ഫേസ്ബുക്ക്",
    x: "X (Twitter)",
    threads: "Threads",
    youtube: "യൂട്യൂബ്",
    pinterest: "Pinterest",
    quotaUsage: "Mail/SMS ക്വാട്ട ഉപയോഗം",
    used: "ഉപയോഗിച്ചത്",
    remaining: "ബാക്കി",
    totalQuota: "ആകെ ക്വാട്ട",
    sms: "SMS",
    whatsapp: "WhatsApp",
    brevo: "Brevo",
    count: "എണ്ണം",
    date: "തീയതി",
    gmail: "Gmail",
    quota: "ക്വാട്ട",
    teamUsers: "ടീം",
    member: "അംഗം",
    customer: "ഉപഭോക്താവ്",
    customers: "ഉപഭോക്താക്കൾ",
    profileImage: "പ്രൊഫൈൽ ചിത്രം",
    gender: "ലിംഗം",
    role: "റോൾ",
    activatedText: "സജീവമാക്കി",
    selectRolePlaceholder: "റോൾ തിരഞ്ഞെടുക്കുക",
    accountActiveLabel: "അക്കൗണ്ട് സജീവമാണോ അല്ലയോ എന്ന് തിരഞ്ഞെടുക്കുക:",
    user: "ഉപയോക്താവ്",
    actions: "നടപടികൾ",
    setAsDiscontinued: "Discontinued ആയി സജ്ജമാക്കുക",
    resetToDefaultPassword: "പാസ്‌വേഡ് റീസെറ്റ് ചെയ്യുക",
    confirmMsg: "ഉറപ്പാണോ? <b>{0}</b> {1}-നെ {2} ചെയ്യണോ?",
    discontinued: "നിർത്തലാക്കി",
    base: "ബേസ്",
    setActive: "സജീവമാക്കുക",
    refresh: "റിഫ്രഷ് ചെയ്യുക",
};

export default ml;