const mr = {
    login: "लॉग इन करा",
    signup: "साइन अप करा",
    forgotPassword: "पासवर्ड विसरलात?",
    welcomeUser: "स्वागत आहे, वापरकर्ता!",
    logout: "लॉग आउट",
    requiredField: "हे फील्ड आवश्यक आहे.",
    invalidEmail: "कृपया वैध ईमेल पत्ता प्रविष्ट करा.",
    name: "नाव",
    fullNamePlaceholder: "तुमचे नाव प्रविष्ट करा",
    firstName: "पहिले नाव",
    lastName: "आडनाव",
    mobileOrEmail: "ईमेल आयडी किंवा मोबाईल नंबर",
    firstNamePlaceHolder: "तुमचे पहिले नाव प्रविष्ट करा",
    lastNamePlaceHolder: "तुमचे आडनाव प्रविष्ट करा",
    email: "ईमेल",
    emailPlaceHolder: "तुमचा ईमेल प्रविष्ट करा",
    mobile: "मोबाईल नंबर",
    mobilePlaceHolder: "तुमचा मोबाईल नंबर प्रविष्ट करा",
    receiveOTP: "तुम्हाला {0} वर OTP प्राप्त होईल.",
    pleaseWait: "कृपया प्रतीक्षा करा...",
    fetchingDataFailedTitle: "विनंती केलेला डेटा प्राप्त करण्यात अक्षम.",
    failureMessage: "तुमची विनंती पूर्ण करताना आम्हाला त्रुटी आली.",
    technicalGlitch: "हे तांत्रिक बिघाडामुळे असू शकते. काही वेळानंतर पुन्हा प्रयत्न करा.",
    contactSupport: "येथे सपोर्टशी संपर्क साधा: <a href=\"{supportEmail}\" style=\"text-decoration:none; target=\"_blank\" rel=\"noopener noreferrer\" color: #27c0e0;\">{supportEmail}</a>.",
    register: "नोंदणी करा",
    registering: "नोंदणी होत आहे....",
    submitOTP: "OTP सत्यापित करा",
    submittingOTP: "OTP सत्यापित केला जात आहे....",
    otp: "OTP",
    otpPlaceholder: "OTP प्रविष्ट करा",
    enterOTP: "कृपया ({value}) वर प्राप्त झालेला OTP प्रविष्ट करा.",
    signedUp: "तुमची नोंदणी यशस्वी झाली आहे!",
    failedToSignUp: "नोंदणी करण्यात अपयश आले.",
    loggedIn: "तुम्ही यशस्वीरित्या लॉग इन झाले आहात!",
    failedToLogIn: "लॉग इन करण्यात अपयश आले.",
    resendOTP: "OTP पुन्हा पाठवा",
    resendingOTP: "OTP पुन्हा पाठवला जात आहे....",
    password: "पासवर्ड",
    logingin: "लॉग इन होत आहे",
    passwordPlaceHolder: "तुमचा पासवर्ड प्रविष्ट करा",
    otpChild1: "OTP चुकीचा असू शकतो",
    otpChild2: "OTP ची मुदत संपली असावी.",
    otpChild3: "नेटवर्कमध्ये समस्या असू शकते.",
    otpChild4: "सर्व्हर डाऊन असू शकतो",
    passwordRequirementMsg: "तुमच्या खात्याच्या सुरक्षिततेसाठी, किमान आठ (8) अक्षरांचा पासवर्ड तयार करा, ज्यामध्ये समाविष्ट आहे",
    passwordRequireMent: "पासवर्ड आवश्यकता",
    upperLowerCase: "मोठी आणि लहान अक्षरे",
    subHeadingIns: "मजबूत पासवर्डसाठी, तुमचा पासवर्ड खालील मुद्द्यांचे पालन करणारा असावा",
    minimum8Char: "किमान 8 अक्षरे (अनिवार्य)",
    atLeastOneNumericals: "किमान एक अंक (अनिवार्य)",
    numericals: "अंक",
    specialChar: "विशेष वर्ण",
    oneUpperCase: "किमान एक मोठे अक्षर (अनिवार्य)",
    oneLowerCase: "किमान एक लहान अक्षर (अनिवार्य)",
    partnerCompanyName: "भागीदार कंपनीचे नाव",
    atLeastOneSpecialChar: "किमान एक विशेष वर्ण (अनिवार्य)",
    skip: "वगळा",
    confirmPassword: "पासवर्डची पुष्टी करा",
    setPassword: "पासवर्ड सेट करा",
    accountInstruction: "खात्यात प्रवेश करण्यासाठी आणि ऑर्डर्स व्यवस्थापित करण्यासाठी",
    aboutUs: "आमच्याबद्दल",
    contactUs: "आमच्याशी संपर्क साधा",
    profile: "प्रोफाइल",
    orders: "ऑर्डर्स",
    wishlist: "विशलिस्ट",
    loginSignup: "लॉग इन/साइन अप",
    welcome: "स्वागत आहे",
    profileImgUpdated: "प्रोफाइल प्रतिमा यशस्वीरित्या अपडेट केली",
    save: "जतन करा",
    cancel: "रद्द करा",
    adjustImage: "प्रतिमा समायोजित करा",
    dragSqrToChangeImgSizePos: "आकार आणि स्थिती बदलण्यासाठी चौरस ओढा.",
    preview: "पूर्वावलोकन",
    imageCropped: "क्रॉप केलेली प्रतिमा यशस्वीरित्या जतन केली!",
    alternateMobile: "पर्यायी मोबाईल नंबर",
    male: "पुरुष",
    female: "महिला",
    others: "इतर",
    genderLabel: "कृपया तुमचे लिंग निवडा:",
    dob: "जन्म तारीख",
    update: "अपडेट",
    changePassword: "पासवर्ड बदला",
    updatePassword: "पासवर्ड अपडेट करा",
    updateProfile: "प्रोफाइल अपडेट करा",
    oldPassword: "जुना पासवर्ड",
    confirmPasswordNotMatchPassword: "पासवर्ड पुष्टी पासवर्डशी जुळली नाही.",
    passReqNotFulfil: "पासवर्ड आवश्यकता पूर्ण झाली नाही.",
    passwordUpdated: "पासवर्ड यशस्वीरित्या अपडेट केला!",
    profileUpdated: "प्रोफाइल यशस्वीरित्या अपडेट केली!",
    pageNotFound: "पृष्ठ सापडले नाही",
    brokenLinkMsg1: "तुम्ही क्लिक केलेली लिंक तुटलेली असू शकते किंवा पृष्ठ काढून टाकले असावे.",
    brokenLinkMsg2: "मुख्य पृष्ठाला भेट द्या किंवा समस्येबद्दल आमच्याशी संपर्क साधा.",
    backToHome: "मुख्य पृष्ठावर परत जा",
    dashboard: "डॅशबोर्ड",
    pages: "पृष्ठे",
    inventory: "इन्व्हेंटरी",
    customOrders: "कस्टम ऑर्डर्स",
    team: "टीम",
    customers: "ग्राहक",
    settings: "सेटिंग्ज",
    messages: "संदेश",
    pendingOrders: "प्रलंबित ऑर्डर्स",
    completedOrders: "पूर्ण झालेल्या ऑर्डर्स",
    offers: "ऑफर्स",
    id: "आयडी",
    brand: "ब्रँड",
    category: "श्रेणी",
    price: "किंमत",
    status: "स्थिती",
    createdDate: "निर्मिती तारीख",
    updatedDate: "शेवटचे अपडेट",
    action: "कृती",
    productName: "उत्पादनाचे नाव",
    size: "आकार",
    color: "रंग",
    stockQuantity: "प्रमाण",
    products: "उत्पादने",
    description: "वर्णन",
    parent: "मूळ",
    namePlaceholder: "नाव प्रविष्ट करा",
    descriptionPlaceholder: "वर्णन प्रविष्ट करा",
    categoryPlaceholder: "श्रेणी निवडा",
    categoryLevel: "श्रेणी {0} स्तर ",
    at: "ला",
    modifiedOn: "वर सुधारित",
    today: "आज",
    edit: "संपादित करा",
    delete: "हटवा",
    activated: "{entity} सक्रिय झाले आहे.",
    deactivated: "{entity} निष्क्रिय झाले आहे.",
    yes: "हो",
    no: "नाही",
    confirm: "पुष्टी",
    deleteMsg: "तुम्हाला खात्री आहे का? तुम्ही <b>{0}</b> {1} हटवू इच्छिता?",
    childrenOf: "चे उपघटक ",
    page: "पृष्ठ",
    add: "जोडा",
    deactivateFirst: "{entity} आधी निष्क्रिय करा.",
    activeCantAction: "सक्रिय {entity} वर {action} करता येत नाही.",
    entityIsActive: "<b>{0}</b> {entity} सक्रिय आहे.",
    searchPlaceHolder: "{entity} शोधा...",
    copy: "कॉपी",
    deleted: "हटवले",
    edited: "संपादित",
    product: "उत्पादन",
    title: "शीर्षक",
    titlePlaceholder: "शीर्षक प्रविष्ट करा",
    image: "प्रतिमा",
    material: "साहित्य",
    materialPlaceholder: "साहित्य प्रविष्ट करा",
    colorPlaceholder: "रंग प्रविष्ट करा",
    skuPlaceholder: "युनिक SKU कोड प्रविष्ट करा",
    quantity: "प्रमाण",
    type: "प्रकार",
    selectProductPlaceholder: "उत्पादन निवडा",
    sizeChart: "साईज चार्ट",
    enterMeasure: "तुमचे {0} मोजमाप प्रविष्ट करा",
    chest: "छाती",
    hips: "कमर (खालील भाग)",
    neck: "मान",
    sleeve: "बाही",
    arm: "हात",
    topLength: "वरची लांबी",
    shoulder: "खांदा",
    inseam: "इनसीम",
    bottomLength: "खालची लांबी",
    thigh: "मांडी",
    waist: "कंबर",
    topBody: "वरचा भाग",
    bottomBody: "खालचा भाग",
    rank: "रँक",
    sale: "विक्री",
    rental: "भाडे",
    selectRankPlaceholder: "रँक निवडा",
    mrp: "एमआरपी",
    salePrice: "विक्री किंमत",
    discount: "सवलत",
    selectSizePlaceholder: "आकार निवडा",
    mrpPlaceholder: "एमआरपी प्रविष्ट करा (₹)",
    salePricePlaceholder: "विक्री किंमत प्रविष्ट करा (₹)",
    discountPlaceholder: "सवलत प्रविष्ट करा (%)",
    quantityPlaceholder: "प्रमाण प्रविष्ट करा",
    saleOrRentPrice: "विक्री/भाडे किंमत",
    security: "सुरक्षा अनामत",
    securityPlaceholder: "रिफंडेबल = अनामत - (भाडे किंमत - सवलत %)",
    size_Quant_Price: "आकार - प्रमाण - विक्री किंमत",
    view: "पहा",
    webSettings: "वेब सेटिंग्ज",
    siteUnderMaintenance: "साइट देखरेखीखाली आहे",
    weWillGetbackShortly: "आम्ही लवकरच परत येऊ. कृपया नंतर पुन्हा तपासा.",
    reload: "रीलोड",
    enableWebsite: "वेबसाइट सक्षम किंवा अक्षम करण्यासाठी क्लिक करा.",
    website: "वेबसाइट",
    switchOnOffWebsite: "वेबसाइट सुरू/बंद करा",
    webConfigs: "वेबसाइट कॉन्फिगरेशन",
    webTrendingBar: "वेबसाइट ट्रेंडिंग बार",
    websiteId: "वेबसाइट आयडी",
    path: "पाथ",
    pathPlaceholder: "उघडण्यासाठी पाथ प्रविष्ट करा",
    homePage: "होम पेज",
    homePageCarousel: "होम पेज कॅरोसेल",
    forPC: "पीसी साठी:",
    forMobile: "मोबाईलसाठी:",
    reset: "रीसेट",
    customFitting: "कस्टम फिटिंग",
    customDesigning: "कस्टम डिझायनिंग",
    freeDelivery: "मोफत डिलिव्हरी",
    assuredRefunds: "खात्रीशीर रिफंड",
    sizes: "आकार",
    addresses: "पत्ते",
    isTileVisible: "टाईल दृश्यमान आहे का?",
    isTileVisibleGrid: "टाईल दृश्यमान आहे",
    categories: "श्रेण्या",
    mrpWithDots: "एम.आर.पी",
    rtd: "पाठवण्यासाठी तयार",
    inclusiveTax: "किंमत सर्व करांसह",
    rentInclusiveTax: "भाडे सर्व करांसह",
    purchase: "खरेदी",
    rent: "भाड्याने",
    refundableSecurity: "परतावा पात्र सुरक्षा अनामत",
    securityDeposit: "सुरक्षा अनामत",
    refundSecurity: "वस्तू परत केल्यानंतर, तुमची सुरक्षा अनामत परत केली जाईल.",
    securityDepositDeduction: " तुम्ही वस्तू डिलिव्हरीच्या ५ दिवसांच्या आत परत करू शकता. त्यानंतर दर ५ दिवसांसाठी सुरक्षा अनामत रकमेतून भाडे कापले जाईल.",
    sizeGuide: "साईज गाईड",
    customSize: "कस्टम आकार",
    loginToAddCustomSize: "कस्टम आकार जोडण्यासाठी आणि पाहण्यासाठी लॉग इन/साइन अप करा",
    yourCustomSizes: "तुमचे कस्टम आकार",
    undoWishlistMsg: "तुम्ही <b>{name}</b> ला विशलिस्ट मधून हटवले आहे",
    undo: "पूर्ववत करा",
    textPlaceholder: "{0} प्रविष्ट करा",
    address: "पत्ता",
    fullName: "नाव",
    city: "शहर",
    country: "देश",
    pinCode: "पिन कोड",
    state: "राज्य",
    landmark: "लँडमार्क",
    streetAddress1: "फ्लॅट, हाऊस नं, बिल्डिंग, कंपनी, अपार्टमेंट",
    streetAddress2: "परिसर, रस्ता, सेक्टर, गाव",
    defaultAddress: "डिफॉल्ट पत्ता म्हणून सेट करा",
    setDefault: "डिफॉल्ट सेट करा",
    default: "डिफॉल्ट",
    addToCart: "कार्टमध्ये जोडा",
    buyNow: "आत्ता खरेदी करा",
    total: "एकूण",
    clearCart: "कार्ट रिकामे करा",
    proceedToCheckout: "चेकआउटवर जा",
    shoppingCart: "शॉपिंग कार्ट",
    loadingCart: "कार्ट लोड होत आहे...",
    emptyCart: "तुमचे कार्ट रिकामे आहे.",
    emptyWishlist: "तुमची विशलिस्ट रिकामी आहे.",
    deSelectAll: "सर्व निवडी रद्द करा",
    invalidCoupon: "अवैध कूपन कोड",
    couponApplied: "कूपन लागू झाले: ",
    apply: "लागू करा",
    freeCaps: "मोफत",
    deliveryCharges: "डिलिव्हरी चार्जेस",
    subTotal: "उप-एकूण",
    changeSize: "आकार बदला",
    moveToWishlist: "विशलिस्टमध्ये हलवा",
    share: "शेअर करा",
    orderSummary: "ऑर्डर सारांश",
    coupon: "कूपन",
    itemsForPurchasing: "खरेदीसाठी निवडलेल्या वस्तू",
    itemsForRenting: "भाड्यासाठी निवडलेल्या वस्तू",
    itemsSelected: "निवडलेल्या वस्तू",
    applyCoupon: "कूपन लागू करा",
    undoCartMsg: 'कार्ट मधून <strong>{name}</strong> हटवले. ',
    itemRestored: "आयटम कार्टमध्ये परत आणला",
    selectAll: "सर्व निवडा",
    itemMovedToWishlist: "आयटम विशलिस्टमध्ये हलवला.",
    itemRemoved: "आयटम कार्टमधून हटवला",
    addedToCart: "आयटम कार्टमध्ये जोडला",
    itemAddedToWishlist: "आयटम विशलिस्टमध्ये जोडला",
    itemRemovedFromWishlist: "आयटम विशलिस्ट मधून हटवला",
    proceedToBuy: "खरेदीसाठी पुढे जा",
    change: "बदला",
    checkout: "चेकआउट",
    deliverHere: "येथे डिलिव्हर करा",
    selectDeliveryAddress: "डिलिव्हरी पत्ता निवडा",
    selectedDeliveryAddress: "निवडलेला डिलिव्हरी पत्ता",
    inventoryType: "इन्व्हेंटरी प्रकार",
    currentlyDefaultAddress: "डिफॉल्ट पत्ता",
    chosenAddressUpdated: "निवडलेला पत्ता यशस्वीरित्या अपडेट केला.",
    draftUpdated: "ऑर्डर तपशील यशस्वीरित्या अपडेट केले.",
    deliveringTo: "येथे डिलिव्हर होत आहे",
    addNew: "नवीन जोडा",
    itemsInOrder: "ऑर्डरमधील वस्तू",
    shipTogether: "सर्व वस्तू एकत्र पाठवा",
    shipAsap: "प्रत्येक वस्तू तयार होताच पाठवा",
    shipItems: "तुम्हाला तुमची ऑर्डर कधी पाठवायची आहे?",
    shipItemsForOrder: "{user} ला ऑर्डर कधी पाठवायची आहे?",
    orderPlacedTitle: "धन्यवाद, तुमची ऑर्डर यशस्वीरित्या नोंदवली गेली आहे!",
    orderConfirmationSent: "तुमच्या ईमेलवर एक पुष्टीकरण पाठवले गेले आहे.",
    orderId: "ऑर्डर आयडी",
    itemsInTheOrder: "ऑर्डरमधील वस्तू",
    viewOrders: "तुमच्या ऑर्डर्स पहा",
    viewAllOrders: "सर्व ऑर्डर्स पहा",
    continueShopping: "खरेदी सुरू ठेवा",
    orderDetails: "ऑर्डर तपशील",
    appliedCoupon: "लागू केलेले कूपन",
    orderPlacedOn: "ऑर्डर नोंदवली गेली",
    shipTo: "येथे पाठवा",
    noOrdersFound: "कोणतीही ऑर्डर सापडली नाही",
    yourOrders: "तुमच्या ऑर्डर्स",
    paymentMode: "पेमेंट मोड",
    paymentMethod: "पेमेंट पद्धत",
    all: "सर्व",
    pending: "प्रलंबित",
    shipped: "पाठवले",
    delivered: "डिलिव्हर केले",
    cancelled: "रद्द केले",
    allOrders: "सर्व ऑर्डर्स",
    newOrders: "नवीन ऑर्डर्स",
    statusMessages: {
      forOrder: {
        forManager: {
          draft: "ऑर्डर ड्राफ्ट स्वरूपात आहे आणि अजून नोंदवलेली नाही.",
          pending: "पेमेंट प्रलंबित आहे.",
          placed: "ऑर्डर नोंदवली गेली आहे आणि तुमच्या बाजूने पुष्टीकरणाची प्रतीक्षा आहे.",
          confirmed: "तुम्ही ऑर्डरची पुष्टी केली आहे.",
          payment_failed: "पेमेंट अयशस्वी झाले.",
          in_process: "ऑर्डर तुमच्याद्वारे प्रोसेस केली जात आहे.",
          ready_to_dispatch: "ऑर्डर पाठवण्यासाठी तयार आहे.",
          shipped: "ऑर्डर पाठवली गेली आहे.",
          in_transit: "ऑर्डर मार्गावर आहे.",
          delivered: "ऑर्डर डिलिव्हर झाली आहे.",
          cancelled: "ऑर्डर रद्द करण्यात आली आहे.",
          cancellation_requested: "वापरकर्त्याने रद्दीकरणाची विनंती केली आहे.",
          cancellation_rejected: "तुम्ही रद्दीकरण विनंती नाकारली आहे.",
          cancellation_refunded: "ऑर्डर रद्द करण्यात आली आहे आणि पेमेंट रिफंड केले आहे.",
          return_requested: "ऑर्डर्ससाठी रिटर्न विनंत्या.",
          return_rejected: "तुम्ही रिटर्न विनंती नाकारली आहे.",
          returned: "ऑर्डर परत मिळाली आहे.",
          return_refunded: "परत मिळाल्यानंतर पेमेंट रिफंड केले आहे.",
          refunded: "पेमेंट रिफंड केले आहे.",
          rto_requested: "तुमच्याद्वारे RTO विनंती केली गेली आहे.",
          rto_rejected: "तुम्ही RTO विनंती नाकारली आहे.",
          rto_approved: "तुम्ही RTO विनंती मंजूर केली आहे.",
          rto_in_progress: "RTO प्रक्रियेत आहे.",
          rto_delivered: "RTO द्वारे ऑर्डर तुम्हाला परत मिळाली आहे.",
          rto_verified: "RTO वस्तू तुमच्याद्वारे सत्यापित केल्या आहेत.",
          rto_refunded: "RTO नंतर ग्राहकाला पेमेंट रिफंड केले."
        },
        forUser: {
          draft: "तुमची ऑर्डर चेकआउटमध्ये आहे पण अजून नोंदवलेली नाही.",
          pending: "पेमेंट प्रलंबित आहे. कृपया तुमचे पेमेंट पूर्ण करा.",
          placed: "तुमची ऑर्डर नोंदवली गेली आहे आणि पुष्टीकरणाची प्रतीक्षा आहे.",
          confirmed: "तुमच्या ऑर्डरची विक्रेत्याद्वारे पुष्टी करण्यात आली आहे.",
          payment_failed: "पेमेंट अयशस्वी. कृपया पुन्हा प्रयत्न करा.",
          in_process: "तुमची ऑर्डर विक्रेत्याद्वारे प्रोसेस केली जात आहे.",
          ready_to_dispatch: "तुमची ऑर्डर पाठवण्यासाठी तयार आहे.",
          shipped: "तुमची ऑर्डर पाठवली गेली आहे.",
          in_transit: "तुमची ऑर्डर मार्गावर आहे.",
          delivered: "तुमची ऑर्डर डिलिव्हर झाली आहे.",
          cancelled: "तुमची ऑर्डर रद्द करण्यात आली आहे.",
          cancellation_requested: "तुम्ही ही ऑर्डर रद्द करण्याची विनंती केली आहे.",
          cancellation_rejected: "तुमची रद्दीकरण विनंती नाकारण्यात आली आहे.",
          cancellation_refunded: "तुमची रद्दीकरण विनंती स्वीकारली गेली आणि पेमेंट रिफंड केले.",
          return_requested: "तुमच्या ऑर्डरसाठी रिटर्न विनंती सबमिट केली गेली आहे.",
          return_rejected: "तुमची रिटर्न विनंती नाकारण्यात आली आहे.",
          returned: "तुमची ऑर्डर परत केली गेली आहे.",
          return_refunded: "परत केल्यानंतर तुमचे पेमेंट रिफंड झाले आहे.",
          refunded: "तुमचे पेमेंट रिफंड झाले आहे.",
          rto_requested: "तुम्ही/विक्रेत्याने ऑर्डरसाठी RTO विनंती केली आहे.",
          rto_rejected: "विक्रेत्याने RTO विनंती नाकारली आहे.",
          rto_approved: "विक्रेत्याने या ऑर्डरसाठी RTO मंजूर केले आहे.",
          rto_in_progress: "तुमची ऑर्डर RTO मार्गावर आहे.",
          rto_delivered: "तुमची ऑर्डर RTO द्वारे विक्रेत्याला परत मिळाली आहे.",
          rto_verified: "तुमची परत केलेली ऑर्डर विक्रेत्याद्वारे सत्यापित केली गेली आहे.",
          rto_refunded: "RTO नंतर तुम्हाला रिफंड मिळाले आहे."
        }
      },
      forItem: {
        forManager: {
          draft: "वस्तू ऑर्डर ड्राफ्टमध्ये जोडली आहे आणि अजून नोंदवलेली नाही.",
          pending: "या वस्तूचे पेमेंट प्रलंबित आहे.",
          placed: "वस्तू नोंदवली गेली आहे आणि तुमच्या बाजूने पुष्टीकरणाची प्रतीक्षा आहे.",
          confirmed: "तुम्ही या वस्तूची पुष्टी केली आहे.",
          payment_failed: "या वस्तूचे पेमेंट अयशस्वी झाले.",
          in_process: "वस्तू तुमच्याद्वारे प्रोसेस केली जात आहे.",
          ready_to_dispatch: "वस्तू पाठवण्यासाठी तयार आहे.",
          shipped: "वस्तू पाठवली गेली आहे.",
          in_transit: "वस्तू मार्गावर आहे.",
          delivered: "वस्तू डिलिव्हर झाली आहे.",
          cancelled: "ही वस्तू रद्द करण्यात आली आहे.",
          cancellation_requested: "वापरकर्त्याने या वस्तूसाठी रद्दीकरणाची विनंती केली आहे.",
          cancellation_rejected: "तुम्ही या वस्तूसाठी रद्दीकरण विनंती नाकारली आहे.",
          cancellation_refunded: "ही वस्तू रद्द करण्यात आली आहे आणि पेमेंट रिफंड केले आहे.",
          return_requested: "वापरकर्त्याने या वस्तूसाठी रिटर्नची विनंती केली आहे.",
          return_rejected: "तुम्ही या वस्तूसाठी रिटर्न विनंती नाकारली आहे.",
          returned: "वस्तू परत मिळाली आहे.",
          return_refunded: "परत केलेल्या वस्तूसाठी पेमेंट रिफंड केले आहे.",
          refunded: "या वस्तूचे पेमेंट रिफंड केले आहे.",
          rto_requested: "या वस्तूसाठी RTO विनंती केली गेली आहे.",
          rto_rejected: "तुम्ही या वस्तूसाठी RTO विनंती नाकारली आहे.",
          rto_approved: "तुम्ही या वस्तूसाठी RTO विनंती मंजूर केली आहे.",
          rto_in_progress: "या वस्तूसाठी RTO प्रक्रियेत आहे.",
          rto_delivered: "ही वस्तू तुम्हाला परत मिळाली आहे.",
          rto_verified: "परत आलेली ही वस्तू सत्यापित केली गेली आहे.",
          rto_refunded: "RTO नंतर या वस्तूसाठी पेमेंट रिफंड केले आहे."
        },
        forUser: {
          draft: "ही वस्तू चेकआउटमध्ये आहे पण अजून नोंदवलेली नाही.",
          pending: "या वस्तूचे पेमेंट प्रलंबित आहे. कृपया तुमचे पेमेंट पूर्ण करा.",
          placed: "ही वस्तू नोंदवली गेली आहे आणि पुष्टीकरणाची प्रतीक्षा आहे.",
          confirmed: "ही वस्तू विक्रेत्याद्वारे पुष्टी करण्यात आली आहे.",
          payment_failed: "या वस्तूचे पेमेंट अयशस्वी. कृपया पुन्हा प्रयत्न करा.",
          in_process: "ही वस्तू विक्रेत्याद्वारे प्रोसेस केली जात आहे.",
          ready_to_dispatch: "ही वस्तू पाठवण्यासाठी तयार आहे.",
          shipped: "ही वस्तू पाठवली गेली आहे.",
          in_transit: "ही वस्तू मार्गावर आहे.",
          delivered: "ही वस्तू डिलिव्हर झाली आहे.",
          cancelled: "ही वस्तू रद्द करण्यात आली आहे.",
          cancellation_requested: "तुम्ही ही वस्तू रद्द करण्याची विनंती केली आहे.",
          cancellation_rejected: "या वस्तूसाठी तुमची रद्दीकरण विनंती नाकारण्यात आली आहे.",
          cancellation_refunded: "या वस्तूसाठी तुमचे रद्दीकरण स्वीकारले गेले आणि पेमेंट रिफंड झाले.",
          return_requested: "या वस्तूसाठी रिटर्न विनंती सबमिट केली गेली आहे.",
          return_rejected: "या वस्तूसाठी तुमची रिटर्न विनंती नाकारण्यात आली आहे.",
          returned: "ही वस्तू परत केली गेली आहे.",
          return_refunded: "ही वस्तू परत केल्यानंतर तुमचे पेमेंट रिफंड झाले आहे.",
          refunded: "या वस्तूसाठी तुमचे पेमेंट रिफंड झाले आहे.",
          rto_requested: "तुम्ही/विक्रेत्याने या वस्तूसाठी RTO विनंती केली आहे.",
          rto_rejected: "विक्रेत्याने या वस्तूसाठी RTO विनंती नाकारली आहे.",
          rto_approved: "विक्रेत्याने या वस्तूसाठी RTO मंजूर केले आहे.",
          rto_in_progress: "ही वस्तू RTO मार्गावर आहे.",
          rto_delivered: "ही वस्तू विक्रेत्याला परत मिळाली आहे.",
          rto_verified: "परत मिळालेली ही वस्तू विक्रेत्याद्वारे सत्यापित केली गेली आहे.",
          rto_refunded: "RTO नंतर या वस्तूसाठी तुम्हाला रिफंड मिळाले आहे."
        }
      }
    },
    statusColors: {
      draft: "var(--secondarytext-color)",
      pending: "var(--warning-color)",
      placed: "var(--info-color)",
      confirmed: "var(--success-color)",
      payment_failed: "var(--danger-color)",
      in_process: "var(--infolight-color)",
      ready_to_dispatch: "purple",
      shipped: "blue",
      in_transit: "var(--primarylight-color)",
      delivered: "var(--successdark-color)",
      cancellation_requested: "orange",
      cancelled: "var(--dangerlight-color)",
      cancellation_rejected: "red",
      cancellation_refunded: "var(--success-color)",
      return_requested: "var(--secondary-color)",
      returned: "var(--dangerlight-color)",
      return_rejected: "var(--warning-color)",
      return_refunded: "var(--success-color)",
      refunded: "var(--success-color)",
      rto_requested: "var(--warningdark-color)",
      rto_rejected: "red",
      rto_approved: "var(--success-color)",
      rto_in_progress: "blueviolet",
      rto_delivered: "var(--info-color)",
      rto_verified: "var(--successdark-color)",
      rto_refunded: "var(--success-color)"
    },
    orderPages: {
      allOrders: {
        title: "सर्व ऑर्डर्स",
        statuses: ["ALL"]
      },
      pendingOrders: {
        title: "प्रलंबित ऑर्डर्स",
        statuses: ["PENDING"]
      },
      newOrders: {
        title: "नवीन ऑर्डर्स",
        statuses: ["PLACED"]
      },
      confirmedOrders: {
        title: "पुष्टी केलेल्या ऑर्डर्स",
        statuses: ["CONFIRMED"]
      },
      processingOrders: {
        title: "प्रोसेसिंग ऑर्डर्स",
        statuses: ["IN_PROCESS"]
      },
      readyToDispatchOrders: {
        title: "पाठवण्यासाठी तयार ऑर्डर्स",
        statuses: ["READY_TO_DISPATCH"]
      },
      onTheWayOrders: {
        title: "मार्गावर असलेल्या ऑर्डर्स",
        statuses: ["SHIPPED", "IN_TRANSIT"]
      },
      deliveredOrders: {
        title: "डिलिव्हर केलेल्या ऑर्डर्स",
        statuses: ["DELIVERED"]
      },
      cancelled: {
        title: "रद्द केलेल्या ऑर्डर्स",
        statuses: ["CANCELLED"]
      },
      returns: {
        title: "रिटर्न्स",
        statuses: ["ALLRETURNS"],
        showOrderStatuses: false
      },
      cancellation_requested: {
        title: "रद्दीकरण विनंती केलेल्या ऑर्डर्स",
        statuses: ["CANCELLATION_REQUESTED"]
      },
      cancellation_rejected: {
        title: "रद्दीकरण नाकारलेल्या ऑर्डर्स",
        statuses: ["CANCELLATION_REJECTED"]
      },
      cancellation_refunded: {
        title: "रद्दीकरण रिफंड केलेल्या ऑर्डर्स",
        statuses: ["CANCELLATION_REFUNDED"]
      },
      return_requested: {
        title: "रिटर्न विनंती केलेल्या ऑर्डर्स",
        statuses: ["RETURN_REQUESTED"]
      },
      returned: {
        title: "परत केलेल्या ऑर्डर्स",
        statuses: ["RETURNED"]
      },
      return_rejected: {
        title: "रिटर्न नाकारलेल्या ऑर्डर्स",
        statuses: ["RETURN_REJECTED"]
      },
      return_refunded: {
        title: "रिटर्न रिफंड केलेल्या ऑर्डर्स",
        statuses: ["RETURN_REFUNDED"]
      },
      rto_requested: {
        title: "RTO विनंती केलेल्या ऑर्डर्स",
        statuses: ["RTO_REQUESTED"]
      },
      rto_rejected: {
        title: "RTO नाकारलेल्या ऑर्डर्स",
        statuses: ["RTO_REJECTED"]
      },
      rto_approved: {
        title: "RTO मंजूर ऑर्डर्स",
        statuses: ["RTO_APPROVED"]
      },
      rto_in_progress: {
        title: "RTO प्रक्रियेत असलेल्या ऑर्डर्स",
        statuses: ["RTO_IN_PROGRESS"]
      },
      rto_delivered: {
        title: "RTO डिलिव्हर ऑर्डर्स",
        statuses: ["RTO_DELIVERED"]
      },
      rto_verified: {
        title: "RTO सत्यापित ऑर्डर्स",
        statuses: ["RTO_VERIFIED"]
      },
      rto_refunded: {
        title: "RTO रिफंड केलेल्या ऑर्डर्स",
        statuses: ["RTO_REFUNDED"]
      }
    },
    confirmedOrders: "पुष्टी केलेल्या ऑर्डर्स",
    processingOrders: "प्रोसेसिंग ऑर्डर्स",
    readyToDispatchOrders: "पाठवण्यासाठी तयार ऑर्डर्स",
    onTheWayOrders: "मार्गावर असलेल्या ऑर्डर्स",
    deliveredOrders: "डिलिव्हर केलेल्या ऑर्डर्स",
    cancelled_orders: "रद्द केलेल्या ऑर्डर्स",
    cancellation_requested_orders: "रद्दीकरण विनंती केलेल्या ऑर्डर्स",
    return_requested_orders: "रिटर्न विनंती केलेल्या ऑर्डर्स",
    return_refunded_orders: "रिटर्न रिफंड केलेल्या ऑर्डर्स",
    returns: "रिटर्न्स",
    returned_orders: "परत केलेल्या ऑर्डर्स",
    return_rejected_orders: "रिटर्न नाकारलेल्या ऑर्डर्स",
    cancellation_rejected_orders: "रद्दीकरण नाकारलेल्या ऑर्डर्स",
    cancellation_refunded_orders: "रद्दीकरण रिफंड केलेल्या ऑर्डर्स",
    rto_requested_orders: "RTO विनंती केलेल्या ऑर्डर्स",
    rto_rejected_orders: "RTO नाकारलेल्या ऑर्डर्स",
    rto_approved_orders: "RTO मंजूर ऑर्डर्स",
    rto_in_progress_orders: "RTO प्रक्रियेत असलेल्या ऑर्डर्स",
    rto_delivered_orders: "RTO डिलिव्हर ऑर्डर्स",
    rto_verified_orders: "RTO सत्यापित ऑर्डर्स",
    rto_refunded_orders: "RTO रिफंड केलेल्या ऑर्डर्स",
    moreOptions: "अधिक पर्याय",
    details: "तपशील",
    viewProductPage: "उत्पादन पृष्ठ पहा",
    viewSize: "आकार पहा",
    trackStatus: "स्थिती ट्रॅक करा",
    auditTrail: "ऑडिट ट्रेल",
    changedFrom: "येथून बदलले",
    changedTo: "येथे बदलले",
    entityType: "घटक प्रकार",
    entityId: "घटक आयडी",
    performedBy: "द्वारे केले",
    timestamp: "टाइमस्टॅम्प",
    trackingDetails: "ट्रॅकिंग तपशील",
    noDetailsFound: "तपशील सापडले नाहीत",
    userDetails: 'वापरकर्ता तपशील',
    followUs: "आम्हाला फॉलो करा",
    allRightsReserved: "सर्व हक्क राखीव",
    fastAndSecured: "जलद आणि सुरक्षित पेमेंट पर्याय",
    company: "कंपनी",
    myAccount: "माझे खाते",
    home: "मुख्य",
    account: "खाते",
    search: "शोधा",
    cart: "कार्ट",
    language: "भाषा",
    somethingWentWrong: "काहीतरी चुकले!",
    note: "टीप",
    notAllowed1: "तुम्हाला या ॲप्लिकेशनमध्ये लॉग इन करण्याची परवानगी नाही",
    notAllowed2: "फक्त ॲडमिन आणि मॅनेजरला याचा एक्सेस आहे",
    notAllowed3: "जर तुम्ही त्यापैकी एक असाल आणि तरीही एक्सेस करू शकत नसाल तर ॲडमिनशी संपर्क साधा",
    logOutAndBackToHome: "लॉग आउट करा आणि मुख्य पृष्ठावर जा",
    whatsAppUs: "आम्हाला व्हॉट्सॲप करा",
    ourContactDetails: "आमचे संपर्क तपशील",
    workingHours: "कामकाजाचे तास",
    instagram: "इंस्टाग्राम",
    facebook: "फेसबुक",
    x: "X (ट्विटर)",
    threads: "थ्रेड्स",
    youtube: "यूट्यूब",
    pinterest: "पिनटेरेस्ट",
    quotaUsage: "मेल/SMS कोटा वापर",
    used: "वापरलेले",
    remaining: "उर्वरित",
    totalQuota: "एकूण कोटा",
    sms: "SMS",
    whatsapp: "व्हॉट्सॲप",
    brevo: "ब्रेवो",
    count: "संख्या",
    date: "तारीख",
    gmail: "जीमेल",
    quota: "कोटा",
    teamUsers: "टीम",
    member: "सदस्य",
    customer: "ग्राहक",
    profileImage: "प्रोफाइल प्रतिमा",
    gender: "लिंग",
    role: "भूमिका",
    activatedText: "सक्रिय",
    selectRolePlaceholder: "भूमिका निवडा",
    accountActiveLabel: "वापरकर्त्याचे खाते सक्रिय/निष्क्रिय असावे का ते निवडा:",
    user: "वापरकर्ता",
    actions: "कृती",
    setAsDiscontinued: "बंद (Discontinued) म्हणून सेट करा",
    resetToDefaultPassword: "डिफॉल्ट पासवर्डवर रीसेट करा",
    confirmMsg: "तुम्हाला खात्री आहे का? तुम्हाला <b>{0}</b> {1} ला {2} करायचे आहे?",
    discontinued: "बंद",
    base: "बेस",
    setActive: "सक्रिय करा",
    refresh: "रिफ्रेश",
    about: "माझ्याबद्दल",
    resume: "रेझ्युमे",
    portfolio: "पोर्टफोलिओ",
    services: "सेवा",
    contact: "संपर्क",
    contactMe: "माझ्याशी संपर्क साधा",
    birthday: "वाढदिवस",
    age: "वय",
    degree: "पदवी",
    freelance: "फ्रीलान्स",
    available: "उपलब्ध",
    education: "शिक्षण",
    projects: "प्रकल्प",
    languages: "भाषा",
    accountInstruction1: "आपली माहिती व्यवस्थापित करा",
    aboutDesc: "माझ्याबद्दल अधिक जाणून घ्या",
    resumeDesc: "माझ्या व्यावसायिक अनुभव आणि शिक्षणाची वेळरेषा:",
    summary: "सारांश",
    professionalExperience: "व्यावसायिक अनुभव",
    servicesDesc: "मी प्रदान करत असलेल्या तांत्रिक सेवा:",
    skillsDesc: "माझी तांत्रिक कौशल्ये:",
    portfolioDesc: "माझ्या अलीकडील प्रकल्पांचे प्रदर्शन:",
    app: "अ‍ॅप",
    web: "वेब",
    branding: "ब्रँडिंग",
    books: "पुस्तके",
    contactDesc: "सहकार्य किंवा संधींसाठी संपर्क करा",
    callUs: "आम्हाला कॉल करा",
    emailUs: "आम्हाला ईमेल करा",
    yourName: "आपले नाव",
    yourEmail: "आपला ईमेल",
    subject: "विषय",
    message: "संदेश",
    sendMessage: "संदेश पाठवा",
    messageSent: "आपला संदेश पाठवला गेला आहे. धन्यवाद!",
    dobShort: "जन्मतारीख",
    toolsTitle: "मी वापरत असलेली साधने आणि तंत्रज्ञान",
    iM: "मी आहे",
    viewDetails: "तपशील पहा",
    zoom: "झूम",
    sendingMessage: "संदेश पाठवला जात आहे...",
    messageFailed: "संदेश पाठवण्यात अयशस्वी. कृपया नंतर पुन्हा प्रयत्न करा.",
    networkError: "नेटवर्क त्रुटी आली. कृपया आपले कनेक्शन तपासा.",
    sending: "पाठवले जात आहे..."
  
};

export default mr;