const or = {
    login: "ଲଗ୍ ଇନ୍ କରନ୍ତୁ",
    signup: "ସାଇନ୍ ଅପ୍ କରନ୍ତୁ",
    forgotPassword: "ପାସୱାର୍ଡ ଭୁଲିଗଲେ କି?",
    welcomeUser: "ସ୍ୱାଗତ, ଉପଭୋକ୍ତା!",
    logout: "ଲଗ୍ ଆଉଟ୍",
    requiredField: "ଏହି ଫିଲ୍ଡଟି ଆବଶ୍ୟକ।",
    invalidEmail: "ଦୟାକରି ଏକ ବୈଧ ଇମେଲ୍ ଠିକଣା ଦିଅନ୍ତୁ।",
    name: "ନାମ",
    fullNamePlaceholder: "ଆପଣଙ୍କ ନାମ ଦିଅନ୍ତୁ",
    firstName: "ପ୍ରଥମ ନାମ",
    lastName: "ଶେଷ ନାମ",
    mobileOrEmail: "ଇମେଲ୍ ଆଇଡି କିମ୍ବା ମୋବାଇଲ୍ ନମ୍ବର",
    firstNamePlaceHolder: "ଆପଣଙ୍କ ପ୍ରଥମ ନାମ ଦିଅନ୍ତୁ",
    lastNamePlaceHolder: "ଆପଣଙ୍କ ଶେଷ ନାମ ଦିଅନ୍ତୁ",
    email: "ଇମେଲ୍",
    emailPlaceHolder: "ଆପଣଙ୍କ ଇମେଲ୍ ଦିଅନ୍ତୁ",
    mobile: "ମୋବାଇଲ୍ ନମ୍ବର",
    mobilePlaceHolder: "ଆପଣଙ୍କ ମୋବାଇଲ୍ ନମ୍ବର ଦିଅନ୍ତୁ",
    receiveOTP: "ଆପଣ {0} ରେ ଏକ OTP ପାଇବେ।",
    pleaseWait: "ଦୟାକରି ଅପେକ୍ଷା କରନ୍ତୁ...",
    fetchingDataFailedTitle: "ଅନୁରୋଧିତ ତଥ୍ୟ ଆଣିବାରେ ଅସମର୍ଥ।",
    failureMessage: "ଆପଣଙ୍କ ଅନୁରୋଧ ପ୍ରକ୍ରିୟାକରଣ କରିବା ସମୟରେ ଏକ ତ୍ରୁଟି ଘଟିଲା।",
    technicalGlitch: "ଏହା ସାମୟିକ ବୈଷୟିକ ତ୍ରୁଟି ଯୋଗୁଁ ହୋଇଥାଇପାରେ। କିଛି ସମୟ ପରେ ପୁଣି ଚେଷ୍ଟା କରନ୍ତୁ।",
    contactSupport: "ସହାୟତା ପାଇଁ ଯୋଗାଯୋଗ କରନ୍ତୁ <a href=\"{supportEmail}\" style=\"text-decoration:none; target=\"_blank\" rel=\"noopener noreferrer\" color: #27c0e0;\">{supportEmail}</a> ରେ।",
    register: "ପଞ୍ଜିକରଣ କରନ୍ତୁ",
    registering: "ପଞ୍ଜିକରଣ କରାଯାଉଛି....",
    submitOTP: "OTP ଯାଞ୍ଚ କରନ୍ତୁ",
    submittingOTP: "OTP ଯାଞ୍ଚ କରାଯାଉଛି....",
    otp: "OTP",
    otpPlaceholder: "OTP ଦିଅନ୍ତୁ",
    enterOTP: "ଦୟାକରି ({value}) ରେ ପାଇଥିବା OTP ଦିଅନ୍ତୁ।",
    signedUp: "ଆପଣ ସଫଳତାର ସହ ସାଇନ୍ ଅପ୍ କରିଛନ୍ତି!",
    failedToSignUp: "ସାଇନ୍ ଅପ୍ କରିବାରେ ବିଫଳ ହେଲେ।",
    loggedIn: "ଆପଣ ସଫଳତାର ସହ ଲଗ୍ ଇନ୍ ହୋଇଛନ୍ତି!",
    failedToLogIn: "ଲଗ୍ ଇନ୍ କରିବାରେ ବିଫଳ ହେଲେ।",
    resendOTP: "OTP ପୁଣି ପଠାନ୍ତୁ",
    resendingOTP: "OTP ପୁଣି ପଠାଯାଉଛି....",
    password: "ପାସୱାର୍ଡ",
    logingin: "ଲଗ୍ ଇନ୍ ହେଉଛି",
    passwordPlaceHolder: "ଆପଣଙ୍କ ପାସୱାର୍ଡ ଦିଅନ୍ତୁ",
    otpChild1: "OTP ଭୁଲ୍ ହୋଇପାରେ",
    otpChild2: "OTP ର ସମୟ ସୀମା ଶେଷ ହୋଇଥାଇପାରେ।",
    otpChild3: "ନେଟୱାର୍କ ସମସ୍ୟା ଥାଇପାରେ।",
    otpChild4: "ସର୍ଭର ଡାଉନ୍ ଥାଇପାରେ",
    passwordRequirementMsg: "ଆପଣଙ୍କ ଆକାଉଣ୍ଟକୁ ସୁରକ୍ଷିତ ରଖିବା ପାଇଁ, ଅତି କମରେ ଆଠ (୮) ଅକ୍ଷର ବିଶିଷ୍ଟ ଏକ ପାସୱାର୍ଡ ପ୍ରସ୍ତୁତ କରନ୍ତୁ, ଯେଉଁଥିରେ ଅନ୍ତର୍ଭୁକ୍ତ ଥିବ",
    passwordRequireMent: "ପାସୱାର୍ଡ ଆବଶ୍ୟକତା",
    upperLowerCase: "ବଡ଼ ଏବଂ ସାନ ଅକ୍ଷର",
    subHeadingIns: "ଶକ୍ତିଶାଳୀ ପାସୱାର୍ଡ ପାଇଁ, ଆପଣଙ୍କ ପାସୱାର୍ଡ ନିମ୍ନଲିଖିତ ବିନ୍ଦୁଗୁଡିକ ପାଳନ କରିବା ଉଚିତ୍",
    minimum8Char: "ଅତିକମରେ ୮ଟି ଅକ୍ଷର (ବାଧ୍ୟତାମୂଳକ)",
    atLeastOneNumericals: "ଅତିକମରେ ଗୋଟିଏ ସଂଖ୍ୟା (ବାଧ୍ୟତାମୂଳକ)",
    numericals: "ସଂଖ୍ୟା",
    specialChar: "ବିଶେଷ ଅକ୍ଷର",
    oneUpperCase: "ଅତିକମରେ ଗୋଟିଏ ବଡ଼ ଅକ୍ଷର (ବାଧ୍ୟତାମୂଳକ)",
    oneLowerCase: "ଅତିକମରେ ଗୋଟିଏ ସାନ ଅକ୍ଷର (ବାଧ୍ୟତାମୂଳକ)",
    partnerCompanyName: "ଅଂଶୀଦାର କମ୍ପାନୀର ନାମ",
    atLeastOneSpecialChar: "ଅତିକମରେ ଗୋଟିଏ ବିଶେଷ ଅକ୍ଷର (ବାଧ୍ୟତାମୂଳକ)",
    skip: "ଏଡ଼ାଇ ଦିଅନ୍ତୁ",
    confirmPassword: "ପାସୱାର୍ଡ ନିଶ୍ଚିତ କରନ୍ତୁ",
    setPassword: "ପାସୱାର୍ଡ ସେଟ୍ କରନ୍ତୁ",
    accountInstruction: "ଆକାଉଣ୍ଟ୍ ଆକ୍ସେସ୍ କରିବା ଏବଂ ଅର୍ଡର ପରିଚାଳନା କରିବା ପାଇଁ",
    aboutUs: "ଆମ ବିଷୟରେ",
    contactUs: "ଯୋଗାଯୋଗ କରନ୍ତୁ",
    profile: "ପ୍ରୋଫାଇଲ୍",
    orders: "ଅର୍ଡରଗୁଡିକ",
    wishlist: "ୱିଶଲିଷ୍ଟ",
    loginSignup: "ଲଗ୍ ଇନ୍/ସାଇନ୍ ଅପ୍",
    welcome: "ସ୍ୱାଗତ",
    profileImgUpdated: "ପ୍ରୋଫାଇଲ୍ ଛବି ସଫଳତାର ସହ ଅପଡେଟ୍ ହୋଇଛି",
    save: "ସଂରକ୍ଷଣ କରନ୍ତୁ",
    cancel: "ବାତିଲ କରନ୍ତୁ",
    adjustImage: "ଛବି ସଜାଡନ୍ତୁ",
    dragSqrToChangeImgSizePos: "ଆକାର ଏବଂ ସ୍ଥିତି ପରିବର୍ତ୍ତନ କରିବାକୁ ବର୍ଗକୁ ଟାଣନ୍ତୁ।",
    preview: "ପୂର୍ବାବଲୋକନ",
    imageCropped: "କ୍ରପ୍ ହୋଇଥିବା ଛବି ସଫଳତାର ସହ ସଂରକ୍ଷିତ ହୋଇଛି!",
    alternateMobile: "ବିକଳ୍ପ ମୋବାଇଲ୍ ନମ୍ବର",
    male: "ପୁରୁଷ",
    female: "ମହିଳା",
    others: "ଅନ୍ୟାନ୍ୟ",
    genderLabel: "ଦୟାକରି ଆପଣଙ୍କ ଲିଙ୍ଗ ଚୟନ କରନ୍ତୁ:",
    dob: "ଜନ୍ମ ତାରିଖ",
    update: "ଅପଡେଟ୍ କରନ୍ତୁ",
    changePassword: "ପାସୱାର୍ଡ ପରିବର୍ତ୍ତନ କରନ୍ତୁ",
    updatePassword: "ପାସୱାର୍ଡ ଅପଡେଟ୍ କରନ୍ତୁ",
    updateProfile: "ପ୍ରୋଫାଇଲ୍ ଅପଡେଟ୍ କରନ୍ତୁ",
    oldPassword: "ପୁରୁଣା ପାସୱାର୍ଡ",
    confirmPasswordNotMatchPassword: "ନିଶ୍ଚିତ ପାସୱାର୍ଡ ପାସୱାର୍ଡ ସହିତ ମେଳ ଖାଉ ନାହିଁ।",
    passReqNotFulfil: "ପାସୱାର୍ଡ ଆବଶ୍ୟକତା ପୂରଣ ହୋଇନାହିଁ।",
    passwordUpdated: "ପାସୱାର୍ଡ ସଫଳତାର ସହ ଅପଡେଟ୍ ହୋଇଛି!",
    profileUpdated: "ପ୍ରୋଫାଇଲ୍ ସଫଳତାର ସହ ଅପଡେଟ୍ ହୋଇଛି!",
    pageNotFound: "ପୃଷ୍ଠା ମିଳିଲା ନାହିଁ",
    brokenLinkMsg1: "ଆପଣ କ୍ଲିକ୍ କରିଥିବା ଲିଙ୍କ୍ ଟି ଭାଙ୍ଗି ଯାଇଥାଇପାରେ କିମ୍ବା ପୃଷ୍ଠାଟି ବାହାର କରି ଦିଆଯାଇଥାଇପାରେ।",
    brokenLinkMsg2: "ହୋମ୍ ପେଜ୍ ପରିଦର୍ଶନ କରନ୍ତୁ କିମ୍ବା ସମସ୍ୟା ବିଷୟରେ ଆମ ସହିତ ଯୋଗାଯୋଗ କରନ୍ତୁ।",
    backToHome: "ହୋମ୍ ପେଜ୍ କୁ ଫେରିଯାଆନ୍ତୁ",
    dashboard: "ଡ୍ୟାସବୋର୍ଡ",
    pages: "ପୃଷ୍ଠାଗୁଡ଼ିକ",
    inventory: "ଇନଭେଣ୍ଟୋରୀ",
    customOrders: "କଷ୍ଟମ୍ ଅର୍ଡର",
    team: "ଟିମ୍",
    customers: "ଗ୍ରାହକମାନେ",
    settings: "ସେଟିଂସ",
    messages: "ମେସେଜ୍",
    pendingOrders: "ବାକି ଥିବା ଅର୍ଡର",
    completedOrders: "ସମ୍ପୂର୍ଣ୍ଣ ହୋଇଥିବା ଅର୍ଡର",
    offers: "ଅଫର୍",
    id: "ଆଇଡି",
    brand: "ବ୍ରାଣ୍ଡ",
    category: "ଶ୍ରେଣୀ",
    price: "ମୂଲ୍ୟ",
    status: "ସ୍ଥିତି",
    createdDate: "ତିଆରି ତାରିଖ",
    updatedDate: "ଶେଷ ଅପଡେଟ୍",
    action: "କାର୍ଯ୍ୟାନୁଷ୍ଠାନ",
    productName: "ଉତ୍ପାଦର ନାମ",
    size: "ଆକାର",
    color: "ରଙ୍ଗ",
    stockQuantity: "ପରିମାଣ",
    products: "ଉତ୍ପାଦଗୁଡ଼ିକ",
    description: "ବର୍ଣ୍ଣନା",
    parent: "ମୂଳ (Parent)",
    namePlaceholder: "ନାମ ଦିଅନ୍ତୁ",
    descriptionPlaceholder: "ବର୍ଣ୍ଣନା ଦିଅନ୍ତୁ",
    categoryPlaceholder: "ଶ୍ରେଣୀ ବାଛନ୍ତୁ",
    categoryLevel: "ଶ୍ରେଣୀ {0} ସ୍ତର ",
    at: "ଠାରେ",
    modifiedOn: "ସଂଶୋଧିତ ତାରିଖ",
    today: "ଆଜି",
    edit: "ସମ୍ପାଦନ କରନ୍ତୁ",
    delete: "ଡିଲିଟ୍ କରନ୍ତୁ",
    activated: "{entity} ସକ୍ରିୟ ଅଛି।",
    deactivated: "{entity} ନିଷ୍କ୍ରିୟ ଅଛି।",
    yes: "ହଁ",
    no: "ନାହିଁ",
    confirm: "ନିଶ୍ଚିତ କରନ୍ତୁ",
    deleteMsg: "ଆପଣ ନିଶ୍ଚିତ କି? ଆପଣ <b>{0}</b> {1} କୁ ଡିଲିଟ୍ କରିବାକୁ ଚାହୁଁଛନ୍ତି କି?",
    childrenOf: "ର ସନ୍ତାନଗଣ ",
    page: "ପୃଷ୍ଠା",
    add: "ଯୋଡନ୍ତୁ",
    deactivateFirst: "ପ୍ରଥମେ {entity} କୁ ନିଷ୍କ୍ରିୟ କରନ୍ତୁ।",
    activeCantAction: "ସକ୍ରିୟ {entity} ଉପରେ {action} କରାଯାଇପାରିବ ନାହିଁ।",
    entityIsActive: "<b>{0}</b> {entity} ସକ୍ରିୟ ଅଛି।",
    searchPlaceHolder: "{entity} ଖୋଜନ୍ତୁ...",
    copy: "କପି କରନ୍ତୁ",
    deleted: "ଡିଲିଟ୍ ହୋଇଛି",
    edited: "ସମ୍ପାଦିତ",
    product: "ଉତ୍ପାଦ",
    title: "ଶୀର୍ଷକ",
    titlePlaceholder: "ଶୀର୍ଷକ ଦିଅନ୍ତୁ",
    image: "ଛବି",
    material: "ସାମଗ୍ରୀ",
    materialPlaceholder: "ସାମଗ୍ରୀ ଦିଅନ୍ତୁ",
    colorPlaceholder: "ରଙ୍ଗ ଦିଅନ୍ତୁ",
    sku: "SKU କୋଡ୍",
    skuPlaceholder: "ଏକ ଅନନ୍ୟ SKU କୋଡ୍ ଦିଅନ୍ତୁ",
    quantity: "ପରିମାଣ",
    type: "ପ୍ରକାର",
    selectProductPlaceholder: "ଉତ୍ପାଦ ବାଛନ୍ତୁ",
    sizeChart: "ସାଇଜ୍ ଚାର୍ଟ",
    enterMeasure: "ଆପଣଙ୍କର {0} ମାପ ଦିଅନ୍ତୁ",
    chest: "ଛାତି",
    hips: "ହିପ୍ସ",
    neck: "ବେକ",
    sleeve: "ହାତ (Sleeve)",
    arm: "ବାହୁ",
    topLength: "ଉପର ଲମ୍ବ",
    shoulder: "କାନ୍ଧ",
    inseam: "ଇନସିମ୍",
    bottomLength: "ତଳ ଲମ୍ବ",
    thigh: "ଜଙ୍ଘ",
    waist: "କମର",
    topBody: "ଉପର ଶରୀର",
    bottomBody: "ତଳ ଶରୀର",
    rank: "ରାଙ୍କ",
    sale: "ବିକ୍ରୟ",
    rental: "ଭଡ଼ା",
    selectRankPlaceholder: "ରାଙ୍କ ବାଛନ୍ତୁ",
    mrp: "MRP",
    salePrice: "ବିକ୍ରୟ ମୂଲ୍ୟ",
    discount: "ରିହାତି",
    selectSizePlaceholder: "ଆକାର ବାଛନ୍ତୁ",
    mrpPlaceholder: "MRP ଦିଅନ୍ତୁ (₹)",
    salePricePlaceholder: "ବିକ୍ରୟ ମୂଲ୍ୟ ଦିଅନ୍ତୁ (₹)",
    discountPlaceholder: "ରିହାତି ଦିଅନ୍ତୁ (%)",
    quantityPlaceholder: "ପରିମାଣ ଦିଅନ୍ତୁ",
    saleOrRentPrice: "ବିକ୍ରୟ/ଭଡ଼ା ମୂଲ୍ୟ",
    security: "ସୁରକ୍ଷା ଜମା",
    securityPlaceholder: "ଫେରସ୍ତଯୋଗ୍ୟ = ଜମା - (ଭଡ଼ା ମୂଲ୍ୟ - ରିହାତି %)",
    size_Quant_Price: "ଆକାର - ପରିମାଣ - ବିକ୍ରୟ ମୂଲ୍ୟ",
    view: "ଦେଖନ୍ତୁ",
    webSettings: "ୱେବ୍ ସେଟିଂସ",
    siteUnderMaintenance: "ସାଇଟ୍ ରକ୍ଷଣାବେକ୍ଷଣ ଅଧୀନରେ ଅଛି",
    weWillGetbackShortly: "ଆମେ ଶୀଘ୍ର ଫେରିବୁ। ଦୟାକରି କିଛି ସମୟ ପରେ ପୁଣି ଯାଞ୍ଚ କରନ୍ତୁ।",
    reload: "ପୁନର୍ବାର ଲୋଡ୍ କରନ୍ତୁ",
    enableWebsite: "ୱେବସାଇଟ୍ ସକ୍ଷମ କିମ୍ବା ଅକ୍ଷମ କରିବାକୁ କ୍ଲିକ୍ କରନ୍ତୁ।",
    website: "ୱେବସାଇଟ୍",
    switchOnOffWebsite: "ୱେବସାଇଟ୍ ଅନ୍/ଅଫ୍ କରନ୍ତୁ",
    webConfigs: "ୱେବସାଇଟ୍ ବିନ୍ୟାସ (Configurations)",
    webTrendingBar: "ୱେବସାଇଟ୍ ଟ୍ରେଣ୍ଡିଂ ବାର୍",
    websiteId: "ୱେବସାଇଟ୍ ଆଇଡି",
    path: "ପଥ (Path)",
    pathPlaceholder: "ଖୋଲାଯିବାକୁ ଥିବା ପଥ ଦିଅନ୍ତୁ",
    homePage: "ହୋମ୍ ପେଜ୍",
    homePageCarousel: "ହୋମ୍ ପେଜ୍ କ୍ୟାରୋସେଲ୍",
    forPC: "PC ପାଇଁ:",
    forMobile: "ମୋବାଇଲ୍ ପାଇଁ:",
    reset: "ରିସେଟ୍",
    customFitting: "କଷ୍ଟମ୍ ଫିଟିଂ",
    customDesigning: "କଷ୍ଟମ୍ ଡିଜାଇନିଂ",
    freeDelivery: "ମାଗଣା ବିତରଣ",
    assuredRefunds: "ନିଶ୍ଚିତ ଫେରସ୍ତ (Refunds)",
    sizes: "ଆକାରଗୁଡ଼ିକ",
    addresses: "ଠିକଣାଗୁଡ଼ିକ",
    isTileVisible: "ଟାଇଲ୍ ଦୃଶ୍ୟମାନ କି?",
    isTileVisibleGrid: "ଟାଇଲ୍ ଦୃଶ୍ୟମାନ ଅଛି",
    categories: "ଶ୍ରେଣୀଗୁଡ଼ିକ",
    mrpWithDots: "M.R.P",
    rtd: "ପଠାଇବା ପାଇଁ ପ୍ରସ୍ତୁତ",
    inclusiveTax: "ସମସ୍ତ ଟ୍ୟାକ୍ସ ଅନ୍ତର୍ଭୁକ୍ତ ମୂଲ୍ୟ",
    rentInclusiveTax: "ସମସ୍ତ ଟ୍ୟାକ୍ସ ଅନ୍ତର୍ଭୁକ୍ତ ଭଡ଼ା",
    purchase: "କ୍ରୟ କରନ୍ତୁ",
    rent: "ଭଡ଼ାରେ ନିଅନ୍ତୁ",
    refundableSecurity: "ଫେରସ୍ତଯୋଗ୍ୟ ସୁରକ୍ଷା ଜମା",
    securityDeposit: "ସୁରକ୍ଷା ଜମା",
    refundSecurity: "ଆଇଟମଟି ଫେରସ୍ତ କରିବା ପରେ, ଆପଣଙ୍କର ସୁରକ୍ଷା ଜମା ଫେରସ୍ତ କରାଯିବ।",
    securityDepositDeduction: " ଆପଣ ବିତରଣର ୫ ଦିନ ମଧ୍ୟରେ ଆଇଟମଟି ଫେରସ୍ତ କରିପାରିବେ। ତା’ପରେ ପ୍ରତ୍ୟେକ ୫ ଦିନ ପାଇଁ ଆପଣଙ୍କ ସୁରକ୍ଷା ଜମାରୁ ଭଡ଼ା ରାଶି କଟାଯିବ।",
    sizeGuide: "ସାଇଜ୍ ଗାଇଡ୍",
    customSize: "କଷ୍ଟମ୍ ସାଇଜ୍",
    loginToAddCustomSize: "କଷ୍ଟମ୍ ସାଇଜ୍ ଯୋଡିବା ଏବଂ ଦେଖିବା ପାଇଁ ଲଗ୍ ଇନ୍/ସାଇନ୍ ଅପ୍ କରନ୍ତୁ",
    yourCustomSizes: "ଆପଣଙ୍କର କଷ୍ଟମ୍ ସାଇଜ୍ ସମୂହ",
    undoWishlistMsg: "ଆପଣ ୱିଶଲିଷ୍ଟରୁ <b>{name}</b> କୁ ବାହାର କରିଛନ୍ତି",
    undo: "ପୂର୍ବବତ୍ (Undo)",
    textPlaceholder: "{0} ଦିଅନ୍ତୁ",
    address: "ଠିକଣା",
    fullName: "ନାମ",
    city: "ସହର",
    country: "ଦେଶ",
    pinCode: "ପିନ୍ କୋଡ୍",
    state: "ରାଜ୍ୟ",
    landmark: "ଲ୍ୟାଣ୍ଡମାର୍କ",
    streetAddress1: "ଫ୍ଲାଟ୍, ଘର ନମ୍ବର, ବିଲଡିଂ, କମ୍ପାନୀ, ଆପାର୍ଟମେଣ୍ଟ",
    streetAddress2: "ଅଞ୍ଚଳ, ରାସ୍ତା, ସେକ୍ଟର, ଗାଁ",
    defaultAddress: "ଡିଫଲ୍ଟ ଠିକଣା ଭାବରେ ସେଟ୍ କରନ୍ତୁ",
    setDefault: "ଡିଫଲ୍ଟ ଭାବରେ ସେଟ୍ କରନ୍ତୁ",
    default: "ଡିଫଲ୍ଟ",
    addToCart: "କାର୍ଟରେ ଯୋଡନ୍ତୁ",
    buyNow: "ବର୍ତ୍ତମାନ କିଣନ୍ତୁ",
    total: "ମୋଟ",
    clearCart: "କାର୍ଟ ସଫା କରନ୍ତୁ",
    proceedToCheckout: "ଚେକ୍-ଆଉଟ୍ ପାଇଁ ଆଗକୁ ବଢ଼ନ୍ତୁ",
    shoppingCart: "ଶପିଂ କାର୍ଟ",
    loadingCart: "କାର୍ଟ ଲୋଡ୍ ହେଉଛି...",
    emptyCart: "ଆପଣଙ୍କ କାର୍ଟ ଖାଲି ଅଛି।",
    emptyWishlist: "ଆପଣଙ୍କ ୱିଶଲିଷ୍ଟ ଖାଲି ଅଛି।",
    deSelectAll: "ସମସ୍ତ ଆଇଟମର ଚୟନ ବାତିଲ କରନ୍ତୁ",
    invalidCoupon: "ଅବୈଧ କୁପନ୍ କୋଡ୍",
    couponApplied: "କୁପନ୍ ପ୍ରୟୋଗ ହେଲା: ",
    apply: "ପ୍ରୟୋଗ କରନ୍ତୁ",
    freeCaps: "ମାଗଣା",
    deliveryCharges: "ବିତରଣ ଶୁଳ୍କ",
    subTotal: "ସବ୍-ଟୋଟାଲ୍",
    changeSize: "ଆକାର ବଦଳାନ୍ତୁ",
    moveToWishlist: "ୱିଶଲିଷ୍ଟକୁ ସ୍ଥାନାନ୍ତର କରନ୍ତୁ",
    share: "ସେୟାର କରନ୍ତୁ",
    orderSummary: "ଅର୍ଡର ସାରାଂଶ",
    coupon: "କୁପନ୍",
    itemsForPurchasing: "କିଣିବା ପାଇଁ ମନୋନୀତ ଆଇଟମଗୁଡ଼ିକ",
    itemsForRenting: "ଭଡ଼ା ପାଇଁ ମନୋନୀତ ଆଇଟମଗୁଡ଼ିକ",
    itemsSelected: "ମନୋନୀତ ଆଇଟମଗୁଡ଼ିକ",
    applyCoupon: "କୁପନ୍ ପ୍ରୟୋଗ କରନ୍ତୁ",
    undoCartMsg: 'କାର୍ଟରୁ <strong>{name}</strong> କୁ ବାହାର କରାଗଲା। ',
    itemRestored: "ଆଇଟମଟି କାର୍ଟକୁ ଫେରିଆସିଲା",
    selectAll: "ସବୁ ଚୟନ କରନ୍ତୁ",
    itemMovedToWishlist: "ଆଇଟମଟି ୱିଶଲିଷ୍ଟକୁ ସ୍ଥାନାନ୍ତରିତ ହେଲା।",
    itemRemoved: "କାର୍ଟରୁ ଆଇଟମଟି ବାହାର କରାଗଲା",
    addedToCart: "କାର୍ଟରେ ଆଇଟମଟି ଯୋଡାଗଲା",
    itemAddedToWishlist: "ୱିଶଲିଷ୍ଟରେ ଆଇଟମଟି ଯୋଡାଗଲା",
    itemRemovedFromWishlist: "ୱିଶଲିଷ୍ଟରୁ ଆଇଟମଟି ବାହାର କରାଗଲା",
    proceedToBuy: "କିଣିବା ପାଇଁ ଆଗକୁ ବଢ଼ନ୍ତୁ",
    change: "ପରିବର୍ତ୍ତନ କରନ୍ତୁ",
    checkout: "ଚେକ୍-ଆଉଟ୍",
    deliverHere: "ଏଠାରେ ବିତରଣ କରନ୍ତୁ",
    selectDeliveryAddress: "ବିତରଣ ଠିକଣା ଚୟନ କରନ୍ତୁ",
    selectedDeliveryAddress: "ମନୋନୀତ ବିତରଣ ଠିକଣା",
    inventoryType: "ଇନଭେଣ୍ଟୋରୀ ପ୍ରକାର",
    currentlyDefaultAddress: "ଡିଫଲ୍ଟ ଠିକଣା",
    chosenAddressUpdated: "ମନୋନୀତ ଠିକଣା ସଫଳତାର ସହ ଅପଡେଟ୍ ହୋଇଛି।",
    draftUpdated: "ଅର୍ଡର ବିବରଣୀ ସଫଳତାର ସହ ଅପଡେଟ୍ ହୋଇଛି।",
    deliveringTo: "ବିତରଣ କରାଯାଉଛି",
    addNew: "ନୂଆ ଯୋଡନ୍ତୁ",
    itemsInOrder: "ଅର୍ଡରରେ ଥିବା ଆଇଟମଗୁଡ଼ିକ",
    shipTogether: "ସମସ୍ତ ଆଇଟମକୁ ଏକାଠି ପଠାନ୍ତୁ",
    shipAsap: "ପ୍ରତ୍ୟେକ ଆଇଟମ ପ୍ରସ୍ତୁତ ହେବା ମାତ୍ରେ ପଠାନ୍ତୁ",
    shipItems: "ଆପଣ ଆପଣଙ୍କର ଅର୍ଡର କେବେ ପଠାଯାଉ ବୋଲି ଚାହାଁନ୍ତି?",
    shipItemsForOrder: "{user} ଅର୍ଡରଟି କେବେ ପଠାଯାଉ ବୋଲି ଚାହାଁନ୍ତି?",
    orderPlacedTitle: "ଧନ୍ୟବାଦ, ଆପଣଙ୍କ ଅର୍ଡର ସଫଳତାର ସହ ଗ୍ରହଣ କରାଯାଇଛି!",
    orderConfirmationSent: "ଆପଣଙ୍କ ଇମେଲକୁ ଏକ ନିଶ୍ଚିତକରଣ ବାର୍ତ୍ତା ପଠାଯାଇଛି।",
    orderId: "ଅର୍ଡର ଆଇଡି",
    itemsInTheOrder: "ଅର୍ଡରରେ ଥିବା ଆଇଟମଗୁଡ଼ିକ",
    viewOrders: "ଆପଣଙ୍କର ଅର୍ଡରଗୁଡ଼ିକ ଦେଖନ୍ତୁ",
    viewAllOrders: "ସମସ୍ତ ଅର୍ଡର ଦେଖନ୍ତୁ",
    continueShopping: "ଶପିଂ ଜାରି ରଖନ୍ତୁ",
    orderDetails: "ଅର୍ଡର ବିବରଣୀ",
    appliedCoupon: "ପ୍ରୟୋଗ କରାଯାଇଥିବା କୁପନ୍",
    orderPlacedOn: "ଅର୍ଡର ଦିଆଯାଇଥିବା ତାରିଖ",
    shipTo: "ଏଠାକୁ ପଠାନ୍ତୁ",
    noOrdersFound: "କୌଣସି ଅର୍ଡର ମିଳିଲା ନାହିଁ",
    yourOrders: "ଆପଣଙ୍କର ଅର୍ଡରଗୁଡ଼ିକ",
    paymentMode: "ପେମେଣ୍ଟ ମୋଡ୍",
    paymentMethod: "ପେମେଣ୍ଟ ପଦ୍ଧତି",
    all: "ସମସ୍ତ",
    pending: "ବାକି ଅଛି",
    shipped: "ପଠାଯାଇଛି",
    delivered: "ବିତରଣ ହୋଇଛି",
    cancelled: "ବାତିଲ ହୋଇଛି",
    allOrders: "ସମସ୍ତ ଅର୍ଡର",
    newOrders: "ନୂଆ ଅର୍ଡର",
    statusMessages: {
      forOrder: {
        forManager: {
          draft: "ଅର୍ଡରଟି ଡ୍ରାଫ୍ଟ ଅବସ୍ଥାରେ ଅଛି ଏବଂ ଏପର୍ଯ୍ୟନ୍ତ ଦିଆଯାଇ ନାହିଁ।",
          pending: "ପେମେଣ୍ଟ ବାକି ଅଛି।",
          placed: "ଅର୍ଡର ଦିଆଯାଇଛି ଏବଂ ଆପଣଙ୍କ ପକ୍ଷରୁ ନିଶ୍ଚିତକରଣକୁ ଅପେକ୍ଷା କରିଛି।",
          confirmed: "ଆପଣ ଅର୍ଡରଟିକୁ ନିଶ୍ଚିତ କରିଛନ୍ତି।",
          payment_failed: "ପେମେଣ୍ଟ ବିଫଳ ହୋଇଛି।",
          in_process: "ଅର୍ଡରଟି ଆପଣଙ୍କ ଦ୍ୱାରା ପ୍ରକ୍ରିୟାକରଣ କରାଯାଉଛି।",
          ready_to_dispatch: "ଅର୍ଡରଟି ପଠାଯିବା ପାଇଁ ପ୍ରସ୍ତୁତ ଅଛି।",
          shipped: "ଅର୍ଡରଟି ପଠାଯାଇଛି।",
          in_transit: "ଅର୍ଡରଟି ବାଟରେ ଅଛି।",
          delivered: "ଅର୍ଡରଟି ବିତରଣ କରାଯାଇଛି।",
          cancelled: "ଅର୍ଡରଟି ବାତିଲ କରାଯାଇଛି।",
          cancellation_requested: "ଉପଭୋକ୍ତା ବାତିଲ ପାଇଁ ଅନୁରୋଧ କରିଛନ୍ତି।",
          cancellation_rejected: "ଆପଣ ବାତିଲ ଅନୁରୋଧକୁ ପ୍ରତ୍ୟାଖ୍ୟାନ କରିଛନ୍ତି।",
          cancellation_refunded: "ଅର୍ଡରଟି ବାତିଲ ହୋଇଛି ଏବଂ ପେମେଣ୍ଟ ଫେରସ୍ତ କରାଯାଇଛି।",
          return_requested: "ଅର୍ଡରଗୁଡ଼ିକ ପାଇଁ ରିଟର୍ଣ୍ଣ ଅନୁରୋଧ।",
          return_rejected: "ଆପଣ ରିଟର୍ଣ୍ଣ ଅନୁରୋଧକୁ ପ୍ରତ୍ୟାଖ୍ୟାନ କରିଛନ୍ତି।",
          returned: "ଅର୍ଡରଟି ଫେରସ୍ତ କରାଯାଇଛି।",
          return_refunded: "ଫେରସ୍ତ ପରେ ପେମେଣ୍ଟ ଫେରସ୍ତ କରାଯାଇଛି।",
          refunded: "ପେମେଣ୍ଟ ଫେରସ୍ତ କରାଯାଇଛି।",
    
          // New RTO statuses
          rto_requested: "ଆପଣଙ୍କ ଦ୍ୱାରା RTO ପାଇଁ ଅନୁରୋଧ କରାଯାଇଛି।",
          rto_rejected: "ଆପଣ RTO ଅନୁରୋଧକୁ ପ୍ରତ୍ୟାଖ୍ୟାନ କରିଛନ୍ତି।",
          rto_approved: "ଆପଣ RTO ଅନୁରୋଧକୁ ଅନୁମୋଦନ କରିଛନ୍ତି।",
          rto_in_progress: "RTO ପ୍ରକ୍ରିୟା ଚାଲିଛି।",
          rto_delivered: "RTO ମାଧ୍ୟମରେ ଅର୍ଡରଟି ଆପଣଙ୍କୁ ଫେରସ୍ତ କରାଯାଇଛି।",
          rto_verified: "RTO ଆଇଟମଗୁଡ଼ିକ ଆପଣଙ୍କ ଦ୍ୱାରା ଯାଞ୍ଚ କରାଯାଇଛି।",
          rto_refunded: "RTO ପରେ ଗ୍ରାହକଙ୍କୁ ପେମେଣ୍ଟ ଫେରସ୍ତ କରାଯାଇଛି।"
        },
        forUser: {
          draft: "ଆପଣଙ୍କ ଅର୍ଡର ଚେକ୍-ଆଉଟ୍ ରେ ଅଛି କିନ୍ତୁ ଏପର୍ଯ୍ୟନ୍ତ ଦିଆଯାଇ ନାହିଁ।",
          pending: "ପେମେଣ୍ଟ ବାକି ଅଛି। ଦୟାକରି ଆପଣଙ୍କର ପେମେଣ୍ଟ ସମ୍ପୂର୍ଣ୍ଣ କରନ୍ତୁ।",
          placed: "ଆପଣଙ୍କ ଅର୍ଡର ଦିଆଯାଇଛି ଏବଂ ନିଶ୍ଚିତକରଣକୁ ଅପେକ୍ଷା କରିଛି।",
          confirmed: "ଆପଣଙ୍କ ଅର୍ଡର ବିକ୍ରେତାଙ୍କ ଦ୍ୱାରା ନିଶ୍ଚିତ କରାଯାଇଛି।",
          payment_failed: "ପେମେଣ୍ଟ ବିଫଳ ହୋଇଛି। ଦୟାକରି ପୁଣି ଚେଷ୍ଟା କରନ୍ତୁ।",
          in_process: "ଆପଣଙ୍କ ଅର୍ଡର ବିକ୍ରେତାଙ୍କ ଦ୍ୱାରା ପ୍ରକ୍ରିୟାକରଣ କରାଯାଉଛି।",
          ready_to_dispatch: "ଆପଣଙ୍କ ଅର୍ଡର ପଠାଯିବା ପାଇଁ ପ୍ରସ୍ତୁତ ଅଛି।",
          shipped: "ଆପଣଙ୍କ ଅର୍ଡର ପଠାଯାଇଛି।",
          in_transit: "ଆପଣଙ୍କ ଅର୍ଡର ବାଟରେ ଅଛି।",
          delivered: "ଆପଣଙ୍କ ଅର୍ଡର ବିତରଣ କରାଯାଇଛି।",
          cancelled: "ଆପଣଙ୍କ ଅର୍ଡର ବାତିଲ କରାଯାଇଛି।",
          cancellation_requested: "ଆପଣ ଏହି ଅର୍ଡରଟିକୁ ବାତିଲ କରିବାକୁ ଅନୁରୋଧ କରିଛନ୍ତି।",
          cancellation_rejected: "ଆପଣଙ୍କର ବାତିଲ ଅନୁରୋଧ ପ୍ରତ୍ୟାଖ୍ୟାନ କରାଯାଇଛି।",
          cancellation_refunded: "ଆପଣଙ୍କର ବାତିଲ ଗ୍ରହଣ କରାଯାଇଛି ଏବଂ ପେମେଣ୍ଟ ଫେରସ୍ତ କରାଯାଇଛି।",
          return_requested: "ଆପଣଙ୍କ ଅର୍ଡର ପାଇଁ ଏକ ରିଟର୍ଣ୍ଣ ଅନୁରୋଧ ଦାଖଲ କରାଯାଇଛି।",
          return_rejected: "ଆପଣଙ୍କର ରିଟର୍ଣ୍ଣ ଅନୁରୋଧ ପ୍ରତ୍ୟାଖ୍ୟାନ କରାଯାଇଛି।",
          returned: "ଆପଣଙ୍କ ଅର୍ଡର ଫେରସ୍ତ କରାଯାଇଛି।",
          return_refunded: "ଫେରସ୍ତ ପରେ ଆପଣଙ୍କର ପେମେଣ୍ଟ ଫେରସ୍ତ କରାଯାଇଛି।",
          refunded: "ଆପଣଙ୍କର ପେମେଣ୍ଟ ଫେରସ୍ତ କରାଯାଇଛି।",
    
          // New RTO statuses
          rto_requested: "ଅର୍ଡର ପାଇଁ RTO ଅନୁରୋଧ କରାଯାଇଛି।",
          rto_rejected: "ବିକ୍ରେତା RTO ଅନୁରୋଧକୁ ପ୍ରତ୍ୟାଖ୍ୟାନ କରିଛନ୍ତି।",
          rto_approved: "ବିକ୍ରେତା ଏହି ଅର୍ଡର ପାଇଁ RTO ଅନୁମୋଦନ କରିଛନ୍ତି।",
          rto_in_progress: "ଆପଣଙ୍କ ଅର୍ଡର RTO ବାଟରେ ଅଛି।",
          rto_delivered: "RTO ମାଧ୍ୟମରେ ଆପଣଙ୍କ ଅର୍ଡର ବିକ୍ରେତାଙ୍କ ପାଖକୁ ଫେରିଯାଇଛି।",
          rto_verified: "ଆପଣ ଫେରସ୍ତ କରିଥିବା ଅର୍ଡର ବିକ୍ରେତାଙ୍କ ଦ୍ୱାରା ଯାଞ୍ଚ କରାଯାଇଛି।",
          rto_refunded: "RTO ପରେ ଆପଣଙ୍କୁ ଟଙ୍କା ଫେରସ୍ତ କରାଯାଇଛି।"
        }
      },
      forItem: {
        forManager: {
          draft: "ଅର୍ଡରଟି ଡ୍ରାଫ୍ଟ ଅବସ୍ଥାରେ ଅଛି ଏବଂ ଏପର୍ଯ୍ୟନ୍ତ ଦିଆଯାଇ ନାହିଁ।",
          pending: "ପେମେଣ୍ଟ ବାକି ଅଛି।",
          placed: "ଅର୍ଡର ଦିଆଯାଇଛି ଏବଂ ଆପଣଙ୍କ ପକ୍ଷରୁ ନିଶ୍ଚିତକରଣକୁ ଅପେକ୍ଷା କରିଛି।",
          confirmed: "ଆପଣ ଅର୍ଡରଟିକୁ ନିଶ୍ଚିତ କରିଛନ୍ତି।",
          payment_failed: "ପେମେଣ୍ଟ ବିଫଳ ହୋଇଛି।",
          in_process: "ଅର୍ଡରଟି ଆପଣଙ୍କ ଦ୍ୱାରା ପ୍ରକ୍ରିୟାକରଣ କରାଯାଉଛି।",
          ready_to_dispatch: "ଅର୍ଡରଟି ପଠାଯିବା ପାଇଁ ପ୍ରସ୍ତୁତ ଅଛି।",
          shipped: "ଅର୍ଡରଟି ପଠାଯାଇଛି।",
          in_transit: "ଅର୍ଡରଟି ବାଟରେ ଅଛି।",
          delivered: "ଅର୍ଡରଟି ବିତରଣ କରାଯାଇଛି।",
          cancelled: "ଅର୍ଡରଟି ବାତିଲ କରାଯାଇଛି।",
          cancellation_requested: "ଉପଭୋକ୍ତା ବାତିଲ ପାଇଁ ଅନୁରୋଧ କରିଛନ୍ତି।",
          cancellation_rejected: "ଆପଣ ବାତିଲ ଅନୁରୋଧକୁ ପ୍ରତ୍ୟାଖ୍ୟାନ କରିଛନ୍ତି।",
          cancellation_refunded: "ଅର୍ଡରଟି ବାତିଲ ହୋଇଛି ଏବଂ ପେମେଣ୍ଟ ଫେରସ୍ତ କରାଯାଇଛି।",
          return_requested: "ଅର୍ଡରଗୁଡ଼ିକ ପାଇଁ ରିଟର୍ଣ୍ଣ ଅନୁରୋଧ।",
          return_rejected: "ଆପଣ ରିଟର୍ଣ୍ଣ ଅନୁରୋଧକୁ ପ୍ରତ୍ୟାଖ୍ୟାନ କରିଛନ୍ତି।",
          returned: "ଅର୍ଡରଟି ଫେରସ୍ତ କରାଯାଇଛି।",
          return_refunded: "ଫେରସ୍ତ ପରେ ପେମେଣ୍ଟ ଫେରସ୍ତ କରାଯାଇଛି।",
          refunded: "ପେମେଣ୍ଟ ଫେରସ୍ତ କରାଯାଇଛି।",
    
          // New RTO statuses
          rto_requested: "ଆପଣଙ୍କ ଦ୍ୱାରା RTO ପାଇଁ ଅନୁରୋଧ କରାଯାଇଛି।",
          rto_rejected: "ଆପଣ RTO ଅନୁରୋଧକୁ ପ୍ରତ୍ୟାଖ୍ୟାନ କରିଛନ୍ତି।",
          rto_approved: "ଆପଣ RTO ଅନୁରୋଧକୁ ଅନୁମୋଦନ କରିଛନ୍ତି।",
          rto_in_progress: "RTO ପ୍ରକ୍ରିୟା ଚାଲିଛି।",
          rto_delivered: "RTO ମାଧ୍ୟମରେ ଅର୍ଡରଟି ଆପଣଙ୍କୁ ଫେରସ୍ତ କରାଯାଇଛି।",
          rto_verified: "RTO ଆଇଟମଗୁଡ଼ିକ ଆପଣଙ୍କ ଦ୍ୱାରା ଯାଞ୍ଚ କରାଯାଇଛି।",
          rto_refunded: "RTO ପରେ ଗ୍ରାହକଙ୍କୁ ପେମେଣ୍ଟ ଫେରସ୍ତ କରାଯାଇଛି।"
        },
        forUser: {
          draft: "ଆପଣଙ୍କ ଅର୍ଡର ଚେକ୍-ଆଉଟ୍ ରେ ଅଛି କିନ୍ତୁ ଏପର୍ଯ୍ୟନ୍ତ ଦିଆଯାଇ ନାହିଁ।",
          pending: "ପେମେଣ୍ଟ ବାକି ଅଛି। ଦୟାକରି ଆପଣଙ୍କର ପେମେଣ୍ଟ ସମ୍ପୂର୍ଣ୍ଣ କରନ୍ତୁ।",
          placed: "ଆପଣଙ୍କ ଅର୍ଡର ଦିଆଯାଇଛି ଏବଂ ନିଶ୍ଚିତକରଣକୁ ଅପେକ୍ଷା କରିଛି।",
          confirmed: "ଆପଣଙ୍କ ଅର୍ଡର ବିକ୍ରେତାଙ୍କ ଦ୍ୱାରା ନିଶ୍ଚିତ କରାଯାଇଛି।",
          payment_failed: "ପେମେଣ୍ଟ ବିଫଳ ହୋଇଛି। ଦୟାକରି ପୁଣି ଚେଷ୍ଟା କରନ୍ତୁ।",
          in_process: "ଆପଣଙ୍କ ଅର୍ଡର ବିକ୍ରେତାଙ୍କ ଦ୍ୱାରା ପ୍ରକ୍ରିୟାକରଣ କରାଯାଉଛି।",
          ready_to_dispatch: "ଆପଣଙ୍କ ଅର୍ଡର ପଠାଯିବା ପାଇଁ ପ୍ରସ୍ତୁତ ଅଛି।",
          shipped: "ଆପଣଙ୍କ ଅର୍ଡର ପଠାଯାଇଛି।",
          in_transit: "ଆପଣଙ୍କ ଅର୍ଡର ବାଟରେ ଅଛି।",
          delivered: "ଆପଣଙ୍କ ଅର୍ଡର ବିତରଣ କରାଯାଇଛି।",
          cancelled: "ଆପଣଙ୍କ ଅର୍ଡର ବାତିଲ କରାଯାଇଛି।",
          cancellation_requested: "ଆପଣ ଏହି ଅର୍ଡରଟିକୁ ବାତିଲ କରିବାକୁ ଅନୁରୋଧ କରିଛନ୍ତି।",
          cancellation_rejected: "ଆପଣଙ୍କର ବାତିଲ ଅନୁରୋଧ ପ୍ରତ୍ୟାଖ୍ୟାନ କରାଯାଇଛି।",
          cancellation_refunded: "ଆପଣଙ୍କର ବାତିଲ ଗ୍ରହଣ କରାଯାଇଛି ଏବଂ ପେମେଣ୍ଟ ଫେରସ୍ତ କରାଯାଇଛି।",
          return_requested: "ଆପଣଙ୍କ ଅର୍ଡର ପାଇଁ ଏକ ରିଟର୍ଣ୍ଣ ଅନୁରୋଧ ଦାଖଲ କରାଯାଇଛି।",
          return_rejected: "ଆପଣଙ୍କର ରିଟର୍ଣ୍ଣ ଅନୁରୋଧ ପ୍ରତ୍ୟାଖ୍ୟାନ କରାଯାଇଛି।",
          returned: "ଆପଣଙ୍କ ଅର୍ଡର ଫେରସ୍ତ କରାଯାଇଛି।",
          return_refunded: "ଫେରସ୍ତ ପରେ ଆପଣଙ୍କର ପେମେଣ୍ଟ ଫେରସ୍ତ କରାଯାଇଛି।",
          refunded: "ଆପଣଙ୍କର ପେମେଣ୍ଟ ଫେରସ୍ତ କରାଯାଇଛି।",
    
          // New RTO statuses
          rto_requested: "ଅର୍ଡର ପାଇଁ RTO ଅନୁରୋଧ କରାଯାଇଛି।",
          rto_rejected: "ବିକ୍ରେତା RTO ଅନୁରୋଧକୁ ପ୍ରତ୍ୟାଖ୍ୟାନ କରିଛନ୍ତି।",
          rto_approved: "ବିକ୍ରେତା ଏହି ଅର୍ଡର ପାଇଁ RTO ଅନୁମୋଦନ କରିଛନ୍ତି।",
          rto_in_progress: "ଆପଣଙ୍କ ଅର୍ଡର RTO ବାଟରେ ଅଛି।",
          rto_delivered: "RTO ମାଧ୍ୟମରେ ଆପଣଙ୍କ ଅର୍ଡର ବିକ୍ରେତାଙ୍କ ପାଖକୁ ଫେରିଯାଇଛି।",
          rto_verified: "ଆପଣ ଫେରସ୍ତ କରିଥିବା ଅର୍ଡର ବିକ୍ରେତାଙ୍କ ଦ୍ୱାରା ଯାଞ୍ଚ କରାଯାଇଛି।",
          rto_refunded: "RTO ପରେ ଆପଣଙ୍କୁ ଟଙ୍କା ଫେରସ୍ତ କରାଯାଇଛି।"
        }
      }
    },
    statusColors: {
      draft: "var(--secondarytext-color)",
      pending: "var(--warning-color)",
      placed: "var(--info-color)",
      confirmed: "var(--success-color)",
      payment_failed: "var(--danger-color)",
      in_process: "var(--infolight-color)",
      ready_to_dispatch: "purple",
      shipped: "blue",
      in_transit: "var(--primarylight-color)",
      delivered: "var(--successdark-color)",
    
      cancellation_requested: "orange",
      cancelled: "var(--dangerlight-color)",
      cancellation_rejected: "red",
      cancellation_refunded: "var(--success-color)",
    
      return_requested: "var(--secondary-color)",
      returned: "var(--dangerlight-color)",
      return_rejected: "var(--warning-color)",
      return_refunded: "var(--success-color)",
    
      refunded: "var(--success-color)",
    
      // New RTO statuses
      rto_requested: "var(--warningdark-color)",
      rto_rejected: "red",
      rto_approved: "var(--success-color)",
      rto_in_progress: "blueviolet",
      rto_delivered: "var(--info-color)",
      rto_verified: "var(--successdark-color)",
      rto_refunded: "var(--success-color)"
    },
    orderPages: {
      allOrders: {
        title: "ସମସ୍ତ ଅର୍ଡର",
        statuses: ["ALL"]
      },
      pendingOrders: {
        title: "ବାକି ଥିବା ଅର୍ଡର",
        statuses: ["PENDING"]
      },
      newOrders: {
        title: "ନୂଆ ଅର୍ଡର",
        statuses: ["PLACED"]
      },
      confirmedOrders: {
        title: "ନିଶ୍ଚିତ ଅର୍ଡର",
        statuses: ["CONFIRMED"]
      },
      processingOrders: {
        title: "ପ୍ରକ୍ରିୟା ଚାଲିଥିବା ଅର୍ଡର",
        statuses: ["IN_PROCESS"]
      },
      readyToDispatchOrders: {
        title: "ପଠାଇବା ପାଇଁ ପ୍ରସ୍ତୁତ ଅର୍ଡର",
        statuses: ["READY_TO_DISPATCH"]
      },
      onTheWayOrders: {
        title: "ବାଟରେ ଥିବା ଅର୍ଡର",
        statuses: ["SHIPPED", "IN_TRANSIT"]
      },
      deliveredOrders: {
        title: "ବିତରଣ ହୋଇଥିବା ଅର୍ଡର",
        statuses: ["DELIVERED"]
      },
      cancelled: {
        title: "ବାତିଲ ଅର୍ଡର",
        statuses: ["CANCELLED"]
      },
      returns: {
        title: "ରିଟର୍ଣ୍ଣସ୍",
        statuses: ["ALLRETURNS"],
        showOrderStatuses: false
      },
      cancellation_requested: {
        title: "ବାତିଲ ପାଇଁ ଅନୁରୋଧିତ",
        statuses: ["CANCELLATION_REQUESTED"]
      },
      cancellation_rejected: {
        title: "ବାତିଲ ପ୍ରତ୍ୟାଖ୍ୟାତ",
        statuses: ["CANCELLATION_REJECTED"]
      },
      cancellation_refunded: {
        title: "ବାତିଲ ଫେରସ୍ତ ହୋଇଥିବା",
        statuses: ["CANCELLATION_REFUNDED"]
      },
      return_requested: {
        title: "ରିଟର୍ଣ୍ଣ ଅନୁରୋଧିତ",
        statuses: ["RETURN_REQUESTED"]
      },
      returned: {
        title: "ଫେରସ୍ତ ହୋଇଥିବା ଅର୍ଡର",
        statuses: ["RETURNED"]
      },
      return_rejected: {
        title: "ରିଟର୍ଣ୍ଣ ପ୍ରତ୍ୟାଖ୍ୟାତ",
        statuses: ["RETURN_REJECTED"]
      },
      return_refunded: {
        title: "ରିଟର୍ଣ୍ଣ ଫେରସ୍ତ ହୋଇଥିବା",
        statuses: ["RETURN_REFUNDED"]
      },
      rto_requested: {
        title: "RTO ଅନୁରୋଧିତ",
        statuses: ["RTO_REQUESTED"]
      },
      rto_rejected: {
        title: "RTO ପ୍ରତ୍ୟାଖ୍ୟାତ",
        statuses: ["RTO_REJECTED"]
      },
      rto_approved: {
        title: "RTO ଅନୁମୋଦିତ",
        statuses: ["RTO_APPROVED"]
      },
      rto_in_progress: {
        title: "RTO ପ୍ରକ୍ରିୟାଧୀନ",
        statuses: ["RTO_IN_PROGRESS"]
      },
      rto_delivered: {
        title: "RTO ବିତରଣ ହୋଇଥିବା",
        statuses: ["RTO_DELIVERED"]
      },
      rto_verified: {
        title: "RTO ଯାଞ୍ଚ ହୋଇଥିବା",
        statuses: ["RTO_VERIFIED"]
      },
      rto_refunded: {
        title: "RTO ଫେରସ୍ତ ହୋଇଥିବା",
        statuses: ["RTO_REFUNDED"]
      }
    },
    confirmedOrders: "ନିଶ୍ଚିତ ଅର୍ଡର",
    processingOrders: "ପ୍ରକ୍ରିୟା ଚାଲିଥିବା ଅର୍ଡର",
    readyToDispatchOrders: "ପଠାଇବା ପାଇଁ ପ୍ରସ୍ତୁତ ଅର୍ଡର",
    onTheWayOrders: "ବାଟରେ ଥିବା ଅର୍ଡର",
    deliveredOrders: "ବିତରଣ ହୋଇଥିବା ଅର୍ଡର",
    cancelled_orders: "ବାତିଲ ଅର୍ଡର",
    cancellation_requested_orders: "ବାତିଲ ପାଇଁ ଅନୁରୋଧିତ ଅର୍ଡର",
    return_requested_orders: "ରିଟର୍ଣ୍ଣ ପାଇଁ ଅନୁରୋଧିତ ଅର୍ଡର",
    return_refunded_orders: "ରିଟର୍ଣ୍ଣ ଫେରସ୍ତ ହୋଇଥିବା ଅର୍ଡର",
    returns: "ରିଟର୍ଣ୍ଣସ୍",
    returned_orders: "ଫେରସ୍ତ ହୋଇଥିବା ଅର୍ଡର",
    return_rejected_orders: "ରିଟର୍ଣ୍ଣ ପ୍ରତ୍ୟାଖ୍ୟାତ ଅର୍ଡର",
    cancellation_rejected_orders: "ବାତିଲ ପ୍ରତ୍ୟାଖ୍ୟାତ ଅର୍ଡର",
    cancellation_refunded_orders: "ବାତିଲ ଫେରସ୍ତ ହୋଇଥିବା ଅର୍ଡର",
    rto_requested_orders: "RTO ଅନୁରୋଧିତ ଅର୍ଡର",
    rto_rejected_orders: "RTO ପ୍ରତ୍ୟାଖ୍ୟାତ ଅର୍ଡର",
    rto_approved_orders: "RTO ଅନୁମୋଦିତ ଅର୍ଡର",
    rto_in_progress_orders: "RTO ପ୍ରକ୍ରିୟାଧୀନ ଅର୍ଡର",
    rto_delivered_orders: "RTO ବିତରଣ ହୋଇଥିବା ଅର୍ଡର",
    rto_verified_orders: "RTO ଯାଞ୍ଚ ହୋଇଥିବା ଅର୍ଡର",
    rto_refunded_orders: "RTO ଫେରସ୍ତ ହୋଇଥିବା ଅର୍ଡର",
    moreOptions: "ଅଧିକ ବିକଳ୍ପ",
    details: "ବିବରଣୀ",
    viewProductPage: "ଉତ୍ପାଦ ପୃଷ୍ଠା ଦେଖନ୍ତୁ",
    viewSize: "ଆକାର ଦେଖନ୍ତୁ",
    trackStatus: "ସ୍ଥିତି ଟ୍ରାକ୍ କରନ୍ତୁ",
    auditTrail: "ଅଡିଟ୍ ଟ୍ରେଲ୍",
    changedFrom: "ରୁ ପରିବର୍ତ୍ତିତ",
    changedTo: "କୁ ପରିବର୍ତ୍ତିତ",
    entityType: "ଏଣ୍ଟିଟି ପ୍ରକାର",
    entityId: "ଏଣ୍ଟିଟି ଆଇଡି",
    performedBy: "କାହା ଦ୍ୱାରା କରାଗଲା",
    timestamp: "ସମୟ",
    trackingDetails: "ଟ୍ରାକିଂ ବିବରଣୀ",
    noDetailsFound: "କୌଣସି ବିବରଣୀ ମିଳିଲା ନାହିଁ",
    userDetails: 'ଉପଭୋକ୍ତା ବିବରଣୀ',
    followUs: "ଆମକୁ ଫଲୋ କରନ୍ତୁ",
    allRightsReserved: "ସମସ୍ତ ଅଧିକାର ସଂରକ୍ଷିତ",
    fastAndSecured: "ଦ୍ରୁତ ଏବଂ ସୁରକ୍ଷିତ ପେମେଣ୍ଟ ବିକଳ୍ପ ସମୂହ",
    company: "କମ୍ପାନୀ",
    myAccount: "ମୋର ଆକାଉଣ୍ଟ",
    home: "ହୋମ୍",
    account: "ଆକାଉଣ୍ଟ",
    search: "ସନ୍ଧାନ କରନ୍ତୁ",
    cart: "କାର୍ଟ",
    language: "ଭାଷା",
    somethingWentWrong: "କିଛି ତ୍ରୁଟି ଘଟିଲା!",
    note: "ଟିପ୍ପଣୀ",
    notAllowed1: "ଆପଣଙ୍କୁ ଏହି ଆପ୍ଲିକେସନ୍‌ରେ ଲଗ୍ ଇନ୍ କରିବାକୁ ଅନୁମତି ନାହିଁ",
    notAllowed2: "କେବଳ ଆଡମିନ୍ ଏବଂ ମ୍ୟାନେଜରଙ୍କ ପାଖରେ ଏହାର ଆକ୍ସେସ୍ ଅଛି",
    notAllowed3: "ଯଦି ଆପଣ ସେମାନଙ୍କ ମଧ୍ୟରୁ ଜଣେ ଏବଂ ତଥାପି ଆକ୍ସେସ୍ କରିପାରୁନାହାଁନ୍ତି, ତେବେ ଆଡମିନ୍‌ଙ୍କ ସହ ଯୋଗାଯୋଗ କରନ୍ତୁ",
    logOutAndBackToHome: "ଲଗ୍ ଆଉଟ୍ କରନ୍ତୁ ଏବଂ ହୋମ୍ ପେଜ୍ କୁ ଯାଆନ୍ତୁ",
    whatsAppUs: "ଆମକୁ ହ୍ୱାଟସ୍-ଆପ୍ କରନ୍ତୁ",
    ourContactDetails: "ଆମର ଯୋଗାଯୋଗ ବିବରଣୀ",
    workingHours: "କାର୍ଯ୍ୟ ସମୟ",
    instagram: "ଇନଷ୍ଟାଗ୍ରାମ",
    facebook: "ଫେସବୁକ",
    x: "X (Twitter)",
    threads: "ଥ୍ରେଡ୍ସ",
    youtube: "ୟୁଟ୍ୟୁବ୍",
    pinterest: "ପିନଟ୍ରେଷ୍ଟ",
    quotaUsage: "ମେଲ୍/SMS କୋଟା ବ୍ୟବହାର",
    used: "ବ୍ୟବହୃତ",
    remaining: "ବାକି",
    totalQuota: "ମୋଟ କୋଟା",
    sms: "SMS",
    whatsapp: "ହ୍ୱାଟସ୍-ଆପ୍",
    brevo: "Brevo",
    count: "ଗଣନା",
    date: "ତାରିଖ",
    gmail: "Gmail",
    quota: "କୋଟା",
    teamUsers: "ଟିମ୍",
    member: "ସଦସ୍ୟ",
    customer: "ଗ୍ରାହକ",
    profileImage: "ପ୍ରୋଫାଇଲ୍ ଛବି",
    gender: "ଲିଙ୍ଗ",
    role: "ଭୂମିକା (Role)",
    activatedText: "ସକ୍ରିୟ",
    selectRolePlaceholder: "ଭୂମିକା ଚୟନ କରନ୍ତୁ",
    accountActiveLabel: "ଉପଭୋକ୍ତାଙ୍କ ଆକାଉଣ୍ଟ ସକ୍ରିୟ/ନିଷ୍କ୍ରିୟ ହେବା ଉଚିତ କି ନାହିଁ ଚୟନ କରନ୍ତୁ:",
    user: "ଉପଭୋକ୍ତା",
    actions: "କାର୍ଯ୍ୟାନୁଷ୍ଠାନ",
    setAsDiscontinued: "ବନ୍ଦ (Discontinued) ଭାବରେ ସେଟ୍ କରନ୍ତୁ",
    resetToDefaultPassword: "ଡିଫଲ୍ଟ ପାସୱାର୍ଡକୁ ରିସେଟ୍ କରନ୍ତୁ",
    confirmMsg: "ଆପଣ ନିଶ୍ଚିତ କି? ଆପଣ <b>{0}</b> {1} କୁ {2} କରିବାକୁ ଚାହୁଁଛନ୍ତି କି?",
    discontinued: "ବନ୍ଦ ହୋଇଥିବା",
    base: "ବେସ୍ (Base)",
    setActive: "ସକ୍ରିୟ କରନ୍ତୁ",
    refresh: "ରିଫ୍ରେଶ୍",
};

export default or;