const pa = {
    login: "ਲੌਗ ਇਨ ਕਰੋ",
    signup: "ਸਾਈਨ ਅਪ ਕਰੋ",
    forgotPassword: "ਪਾਸਵਰਡ ਭੁੱਲ ਗਏ?",
    welcomeUser: "ਸੁਆਗਤ ਹੈ, ਵਰਤੋਂਕਾਰ!",
    logout: "ਲੌਗ ਆਉਟ",
    requiredField: "ਇਹ ਖੇਤਰ ਲਾਜ਼ਮੀ ਹੈ।",
    invalidEmail: "ਕਿਰਪਾ ਕਰਕੇ ਇੱਕ ਵੈਧ ਈਮੇਲ ਪਤਾ ਦਰਜ ਕਰੋ।",
    name: "ਨਾਮ",
    fullNamePlaceholder: "ਆਪਣਾ ਨਾਮ ਦਰਜ ਕਰੋ",
    firstName: "ਪਹਿਲਾ ਨਾਮ",
    lastName: "ਆਖਰੀ ਨਾਮ",
    mobileOrEmail: "ਈਮੇਲ ਆਈਡੀ ਜਾਂ ਮੋਬਾਈਲ ਨੰਬਰ",
    firstNamePlaceHolder: "ਆਪਣਾ ਪਹਿਲਾ ਨਾਮ ਦਰਜ ਕਰੋ",
    lastNamePlaceHolder: "ਆਪਣਾ ਆਖਰੀ ਨਾਮ ਦਰਜ ਕਰੋ",
    email: "ਈਮੇਲ",
    emailPlaceHolder: "ਆਪਣਾ ਈਮੇਲ ਦਰਜ ਕਰੋ",
    mobile: "ਮੋਬਾਈਲ ਨੰਬਰ",
    mobilePlaceHolder: "ਆਪਣਾ ਮੋਬਾਈਲ ਨੰਬਰ ਦਰਜ ਕਰੋ",
    receiveOTP: "ਤੁਹਾਨੂੰ ਇਹ OTP {0} 'ਤੇ ਪ੍ਰਾਪਤ ਹੋਵੇਗਾ।",
    pleaseWait: "ਕਿਰਪਾ ਕਰਕੇ ਉਡੀਕ ਕਰੋ...",
    fetchingDataFailedTitle: "ਬੇਨਤੀ ਕੀਤਾ ਡਾਟਾ ਪ੍ਰਾਪਤ ਕਰਨ ਵਿੱਚ ਅਸਮਰੱਥ।",
    failureMessage: "ਸਾਡੀ ਬੇਨਤੀ 'ਤੇ ਕਾਰਵਾਈ ਕਰਦੇ ਸਮੇਂ ਇੱਕ ਗਲਤੀ ਆਈ ਹੈ।",
    technicalGlitch: "ਇਹ ਅਸਥਾਈ ਤਕਨੀਕੀ ਖਰਾਬੀ ਕਾਰਨ ਹੋ ਸਕਦਾ ਹੈ। ਕੁਝ ਸਮੇਂ ਬਾਅਦ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
    contactSupport: "ਸੰਪਰਕ ਕਰੋ <a href=\"{supportEmail}\" style=\"text-decoration:none; target=\"_blank\" rel=\"noopener noreferrer\" color: #27c0e0;\">{supportEmail}</a> 'ਤੇ।",
    register: "ਰਜਿਸਟਰ ਕਰੋ",
    registering: "ਰਜਿਸਟਰ ਕੀਤਾ ਜਾ ਰਿਹਾ ਹੈ....",
    submitOTP: "OTP ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ",
    submittingOTP: "OTP ਦੀ ਪੁਸ਼ਟੀ ਕੀਤੀ ਜਾ ਰਹੀ ਹੈ....",
    otp: "ਓਟੀਪੀ (OTP)",
    otpPlaceholder: "OTP ਦਰਜ ਕਰੋ",
    enterOTP: "ਕਿਰਪਾ ਕਰਕੇ ਉਹ OTP ਦਰਜ ਕਰੋ ਜੋ ਤੁਹਾਨੂੰ ({value}) 'ਤੇ ਮਿਲਿਆ ਹੈ।",
    signedUp: "ਤੁਸੀਂ ਸਫਲਤਾਪੂਰਵਕ ਸਾਈਨ ਅਪ ਕਰ ਲਿਆ ਹੈ!",
    failedToSignUp: "ਸਾਈਨ ਅਪ ਕਰਨ ਵਿੱਚ ਅਸਫਲ।",
    loggedIn: "ਤੁਸੀਂ ਸਫਲਤਾਪੂਰਵਕ ਲੌਗ ਇਨ ਕਰ ਲਿਆ ਹੈ!",
    failedToLogIn: "ਲੌਗ ਇਨ ਕਰਨ ਵਿੱਚ ਅਸਫਲ।",
    resendOTP: "OTP ਦੁਬਾਰਾ ਭੇਜੋ",
    resendingOTP: "OTP ਦੁਬਾਰਾ ਭੇਜਿਆ ਜਾ ਰਿਹਾ ਹੈ....",
    password: "ਪਾਸਵਰਡ",
    logingin: "ਲੌਗ ਇਨ ਹੋ ਰਿਹਾ ਹੈ",
    passwordPlaceHolder: "ਆਪਣਾ ਪਾਸਵਰਡ ਦਰਜ ਕਰੋ",
    otpChild1: "OTP ਗਲਤ ਹੋ ਸਕਦਾ ਹੈ",
    otpChild2: "OTP ਦੀ ਮਿਆਦ ਖਤਮ ਹੋ ਗਈ ਹੈ।",
    otpChild3: "ਨੈੱਟਵਰਕ ਵਿੱਚ ਸਮੱਸਿਆ ਹੋ ਸਕਦੀ ਹੈ।",
    otpChild4: "ਸਰਵਰ ਡਾਊਨ ਹੋ ਸਕਦਾ ਹੈ",
    passwordRequirementMsg: "ਆਪਣੇ ਖਾਤੇ ਦੀ ਸੁਰੱਖਿਆ ਲਈ, ਘੱਟੋ-ਘੱਟ ਅੱਠ (8) ਅੱਖਰਾਂ ਦਾ ਪਾਸਵਰਡ ਬਣਾਓ, ਜਿਸ ਵਿੱਚ ਸ਼ਾਮਲ ਹਨ",
    passwordRequireMent: "ਪਾਸਵਰਡ ਦੀਆਂ ਲੋੜਾਂ",
    upperLowerCase: "ਵੱਡੇ ਅਤੇ ਛੋਟੇ ਅੱਖਰ",
    subHeadingIns: "ਮਜ਼ਬੂਤ ਪਾਸਵਰਡ ਲਈ, ਤੁਹਾਡੇ ਪਾਸਵਰਡ ਨੂੰ ਹੇਠ ਲਿਖੇ ਨੁਕਤਿਆਂ ਦੀ ਪਾਲਣਾ ਕਰਨੀ ਚਾਹੀਦੀ ਹੈ",
    minimum8Char: "ਘੱਟੋ-ਘੱਟ 8 ਅੱਖਰ (ਲਾਜ਼ਮੀ)",
    atLeastOneNumericals: "ਘੱਟੋ-ਘੱਟ ਇੱਕ ਅੰਕ (ਲਾਜ਼ਮੀ)",
    numericals: "ਅੰਕ",
    specialChar: "ਖਾਸ ਅੱਖਰ",
    oneUpperCase: "ਘੱਟੋ-ਘੱਟ ਇੱਕ ਵੱਡਾ ਅੱਖਰ (ਲਾਜ਼ਮੀ)",
    oneLowerCase: "ਘੱਟੋ-ਘੱਟ ਇੱਕ ਛੋਟਾ ਅੱਖਰ (ਲਾਜ਼ਮੀ)",
    partnerCompanyName: "ਸਾਥੀ ਕੰਪਨੀ ਦਾ ਨਾਮ",
    atLeastOneSpecialChar: "ਘੱਟੋ-ਘੱਟ ਇੱਕ ਖਾਸ ਅੱਖਰ (ਲਾਜ਼ਮੀ)",
    skip: "ਛੱਡੋ",
    confirmPassword: "ਪਾਸਵਰਡ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ",
    setPassword: "ਪਾਸਵਰਡ ਸੈੱਟ ਕਰੋ",
    accountInstruction: "ਖਾਤੇ ਤੱਕ ਪਹੁੰਚਣ ਅਤੇ ਆਰਡਰਾਂ ਦਾ ਪ੍ਰਬੰਧਨ ਕਰਨ ਲਈ",
    aboutUs: "ਸਾਡੇ ਬਾਰੇ",
    contactUs: "ਸੰਪਰਕ ਕਰੋ",
    profile: "ਪ੍ਰੋਫਾਈਲ",
    orders: "ਆਰਡਰ",
    wishlist: "ਵਿਸ਼ਲਿਸਟ",
    loginSignup: "ਲੌਗ ਇਨ/ਸਾਈਨ ਅਪ",
    welcome: "ਜੀ ਆਇਆਂ ਨੂੰ",
    profileImgUpdated: "ਪ੍ਰੋਫਾਈਲ ਤਸਵੀਰ ਸਫਲਤਾਪੂਰਵਕ ਅੱਪਡੇਟ ਹੋ ਗਈ ਹੈ",
    save: "ਸੇਵ ਕਰੋ",
    cancel: "ਰੱਦ ਕਰੋ",
    adjustImage: "ਤਸਵੀਰ ਐਡਜਸਟ ਕਰੋ",
    dragSqrToChangeImgSizePos: "ਆਕਾਰ ਅਤੇ ਸਥਿਤੀ ਬਦਲਣ ਲਈ ਵਰਗ ਨੂੰ ਖਿੱਚੋ।",
    preview: "ਝਲਕ",
    imageCropped: "ਤਸਵੀਰ ਸਫਲਤਾਪੂਰਵਕ ਕ੍ਰੋਪ ਕੀਤੀ ਗਈ!",
    alternateMobile: "ਵਿਕਲਪਿਕ ਮੋਬਾਈਲ ਨੰਬਰ",
    male: "ਪੁਰਸ਼",
    female: "ਮਹਿਲਾ",
    others: "ਹੋਰ",
    genderLabel: "ਕਿਰਪਾ ਕਰਕੇ ਆਪਣਾ ਲਿੰਗ ਚੁਣੋ:",
    dob: "ਜਨਮ ਤਾਰੀਖ",
    update: "ਅੱਪਡੇਟ ਕਰੋ",
    changePassword: "ਪਾਸਵਰਡ ਬਦਲੋ",
    updatePassword: "ਪਾਸਵਰਡ ਅੱਪਡੇਟ ਕਰੋ",
    updateProfile: "ਪ੍ਰੋਫਾਈਲ ਅੱਪਡੇਟ ਕਰੋ",
    oldPassword: "ਪੁਰਾਣਾ ਪਾਸਵਰਡ",
    confirmPasswordNotMatchPassword: "ਪਾਸਵਰਡ ਪੁਸ਼ਟੀ ਮੇਲ ਨਹੀਂ ਖਾਂਦੀ।",
    passReqNotFulfil: "ਪਾਸਵਰਡ ਦੀਆਂ ਲੋੜਾਂ ਪੂਰੀਆਂ ਨਹੀਂ ਹੋਈਆਂ।",
    passwordUpdated: "ਪਾਸਵਰਡ ਸਫਲਤਾਪੂਰਵਕ ਅੱਪਡੇਟ ਹੋ ਗਿਆ!",
    profileUpdated: "ਪ੍ਰੋਫਾਈਲ ਸਫਲਤਾਪੂਰਵਕ ਅੱਪਡੇਟ ਹੋ ਗਈ!",
    pageNotFound: "ਪੰਨਾ ਨਹੀਂ ਲੱਭਿਆ",
    brokenLinkMsg1: "ਤੁਹਾਡੇ ਦੁਆਰਾ ਕਲਿੱਕ ਕੀਤਾ ਲਿੰਕ ਟੁੱਟਿਆ ਹੋ ਸਕਦਾ ਹੈ ਜਾਂ ਪੰਨਾ ਹਟਾ ਦਿੱਤਾ ਗਿਆ ਹੈ।",
    brokenLinkMsg2: "ਹੋਮ ਪੇਜ 'ਤੇ ਜਾਓ ਜਾਂ ਸਮੱਸਿਆ ਬਾਰੇ ਸਾਡੇ ਨਾਲ ਸੰਪਰਕ ਕਰੋ।",
    backToHome: "ਹੋਮ ਪੇਜ 'ਤੇ ਵਾਪਸ ਜਾਓ",
    dashboard: "ਡੈਸ਼ਬੋਰਡ",
    pages: "ਪੰਨੇ",
    inventory: "ਇਨਵੈਂਟਰੀ",
    customOrders: "ਕਸਟਮ ਆਰਡਰ",
    team: "ਟੀਮ",
    customers: "ਗਾਹਕ",
    settings: "ਸੈਟਿੰਗਾਂ",
    messages: "ਸੁਨੇਹੇ",
    pendingOrders: "ਬਕਾਇਆ ਆਰਡਰ",
    completedOrders: "ਪੂਰੇ ਹੋਏ ਆਰਡਰ",
    offers: "ਪੇਸ਼ਕਸ਼ਾਂ",
    id: "ਆਈਡੀ",
    brand: "ਬ੍ਰਾਂਡ",
    category: "ਸ਼੍ਰੇਣੀ",
    price: "ਕੀਮਤ",
    status: "ਸਥਿਤੀ",
    createdDate: "ਬਣਾਉਣ ਦੀ ਮਿਤੀ",
    updatedDate: "ਆਖਰੀ ਅੱਪਡੇਟ",
    action: "ਕਾਰਵਾਈ",
    productName: "ਉਤਪਾਦ ਦਾ ਨਾਮ",
    size: "ਆਕਾਰ (Size)",
    color: "ਰੰਗ",
    stockQuantity: "ਮਾਤਰਾ",
    products: "ਉਤਪਾਦ",
    description: "ਵੇਰਵਾ",
    parent: "ਮੂਲ (Parent)",
    namePlaceholder: "ਨਾਮ ਦਰਜ ਕਰੋ",
    descriptionPlaceholder: "ਵੇਰਵਾ ਦਰਜ ਕਰੋ",
    categoryPlaceholder: "ਸ਼੍ਰੇਣੀ ਚੁਣੋ",
    categoryLevel: "ਸ਼੍ਰੇਣੀ {0} ਪੱਧਰ",
    at: "ਤੇ",
    modifiedOn: "ਤੇ ਸੋਧਿਆ ਗਿਆ",
    today: "ਅੱਜ",
    edit: "ਸੰਪਾਦਨ ਕਰੋ",
    delete: "ਹਟਾਓ",
    activated: "{entity} ਕਿਰਿਆਸ਼ੀਲ ਹੈ।",
    deactivated: "{entity} ਅਕਿਰਿਆਸ਼ੀਲ ਹੈ।",
    yes: "ਹਾਂ",
    no: "ਨਹੀਂ",
    confirm: "ਪੁਸ਼ਟੀ ਕਰੋ",
    deleteMsg: "ਕੀ ਤੁਸੀਂ ਯਕੀਨੀ ਹੋ ਕਿ ਤੁਸੀਂ <b>{0}</b> {1} ਨੂੰ ਹਟਾਉਣਾ ਚਾਹੁੰਦੇ ਹੋ?",
    childrenOf: "ਦੇ ਬੱਚੇ",
    page: "ਪੰਨਾ",
    add: "ਸ਼ਾਮਲ ਕਰੋ",
    deactivateFirst: "{entity} ਨੂੰ ਪਹਿਲਾਂ ਅਕਿਰਿਆਸ਼ੀਲ ਕਰੋ।",
    activeCantAction: "ਕਿਰਿਆਸ਼ੀਲ {entity} ਨੂੰ {action} ਨਹੀਂ ਕੀਤਾ ਜਾ ਸਕਦਾ।",
    entityIsActive: "<b>{0}</b> {entity} ਕਿਰਿਆਸ਼ੀਲ ਹੈ।",
    searchPlaceHolder: "{entity} ਖੋਜੋ...",
    copy: "ਕਾਪੀ ਕਰੋ",
    deleted: "ਹਟਾਇਆ ਗਿਆ",
    edited: "ਸੰਪਾਦਿਤ",
    product: "ਉਤਪਾਦ",
    title: "ਸਿਰਲੇਖ",
    titlePlaceholder: "ਸਿਰਲੇਖ ਦਰਜ ਕਰੋ",
    image: "ਤਸਵੀਰ",
    material: "ਸਮੱਗਰੀ",
    materialPlaceholder: "ਸਮੱਗਰੀ ਦਰਜ ਕਰੋ",
    colorPlaceholder: "ਰੰਗ ਦਰਜ ਕਰੋ",
    sku: "SKU ਕੋਡ",
    skuPlaceholder: "ਵਿਲੱਖਣ SKU ਕੋਡ ਦਰਜ ਕਰੋ",
    quantity: "ਮਾਤਰਾ",
    type: "ਕਿਸਮ",
    selectProductPlaceholder: "ਉਤਪਾਦ ਚੁਣੋ",
    sizeChart: "ਸਾਈਜ਼ ਚਾਰਟ",
    enterMeasure: "ਆਪਣਾ {0} ਮਾਪ ਦਰਜ ਕਰੋ",
    chest: "ਛਾਤੀ",
    hips: "ਕੁੱਲ੍ਹੇ",
    neck: "ਗਰਦਨ",
    sleeve: "ਬਾਂਹ (Sleeve)",
    arm: "ਬਾਂਹ",
    topLength: "ਉਪਰਲੀ ਲੰਬਾਈ",
    shoulder: "ਮੋਢੇ",
    inseam: "ਇਨਸੀਮ",
    bottomLength: "ਹੇਠਲੀ ਲੰਬਾਈ",
    thigh: "ਪੱਟ",
    waist: "ਕਮਰ",
    topBody: "ਉਪਰਲਾ ਸਰੀਰ",
    bottomBody: "ਹੇਠਲਾ ਸਰੀਰ",
    rank: "ਰੈਂਕ",
    sale: "ਵਿਕਰੀ",
    rental: "ਕਿਰਾਇਆ",
    selectRankPlaceholder: "ਰੈਂਕ ਚੁਣੋ",
    mrp: "ਐਮ.ਆਰ.ਪੀ (MRP)",
    salePrice: "ਵਿਕਰੀ ਮੁੱਲ",
    discount: "ਛੋਟ",
    selectSizePlaceholder: "ਆਕਾਰ ਚੁਣੋ",
    mrpPlaceholder: "ਐਮ.ਆਰ.ਪੀ ਦਰਜ ਕਰੋ (₹)",
    salePricePlaceholder: "ਵਿਕਰੀ ਮੁੱਲ ਦਰਜ ਕਰੋ (₹)",
    discountPlaceholder: "ਛੋਟ ਦਰਜ ਕਰੋ (%)",
    quantityPlaceholder: "ਮਾਤਰਾ ਦਰਜ ਕਰੋ",
    saleOrRentPrice: "ਵਿਕਰੀ/ਕਿਰਾਇਆ ਮੁੱਲ",
    security: "ਸੁਰੱਖਿਆ ਜਮ੍ਹਾਂ",
    securityPlaceholder: "ਵਾਪਸੀ = ਜਮ੍ਹਾਂ - (ਕਿਰਾਇਆ ਮੁੱਲ - ਛੋਟ %)",
    size_Quant_Price: "ਆਕਾਰ - ਮਾਤਰਾ - ਵਿਕਰੀ ਮੁੱਲ",
    view: "ਵੇਖੋ",
    webSettings: "ਵੈੱਬ ਸੈਟਿੰਗਾਂ",
    siteUnderMaintenance: "ਸਾਈਟ ਰੱਖ-ਰਖਾਅ ਅਧੀਨ ਹੈ",
    weWillGetbackShortly: "ਅਸੀਂ ਜਲਦੀ ਵਾਪਸ ਆਵਾਂਗੇ। ਕਿਰਪਾ ਕਰਕੇ ਬਾਅਦ ਵਿੱਚ ਦੁਬਾਰਾ ਜਾਂਚ ਕਰੋ।",
    reload: "ਰੀਲੋਡ ਕਰੋ",
    enableWebsite: "ਵੈੱਬਸਾਈਟ ਨੂੰ ਸਮਰੱਥ/ਅਯੋਗ ਕਰਨ ਲਈ ਕਲਿੱਕ ਕਰੋ।",
    website: "ਵੈੱਬਸਾਈਟ",
    switchOnOffWebsite: "ਵੈੱਬਸਾਈਟ ਚਾਲੂ/ਬੰਦ ਕਰੋ",
    webConfigs: "ਵੈੱਬਸਾਈਟ ਸੰਰਚਨਾ",
    webTrendingBar: "ਵੈੱਬਸਾਈਟ ਟ੍ਰੈਂਡਿੰਗ ਬਾਰ",
    websiteId: "ਵੈੱਬਸਾਈਟ ਆਈਡੀ",
    path: "ਮਾਰਗ (Path)",
    pathPlaceholder: "ਖੋਲ੍ਹਣ ਲਈ ਮਾਰਗ ਦਰਜ ਕਰੋ",
    homePage: "ਹੋਮ ਪੇਜ",
    PageCarousel: "ਹੋਮ ਪੇਜ ਕੈਰੋਜ਼ਲ",
    forPC: "ਪੀਸੀ ਲਈ:",
    forMobile: "ਮੋਬਾਈਲ ਲਈ:",
    reset: "ਰੀਸੈਟ ਕਰੋ",
    customFitting: "ਕਸਟਮ ਫਿਟਿੰਗ",
    customDesigning: "ਕਸਟਮ ਡਿਜ਼ਾਈਨਿੰਗ",
    freeDelivery: "ਮੁਫ਼ਤ ਡਿਲੀਵਰੀ",
    assuredRefunds: "ਯਕੀਨੀ ਰਿਫੰਡ",
    sizes: "ਆਕਾਰ",
    addresses: "ਪਤੇ",
    isTileVisible: "ਕੀ ਟਾਇਲ ਦਿਖਾਈ ਦੇ ਰਹੀ ਹੈ?",
    isTileVisibleGrid: "ਟਾਇਲ ਦਿਖਾਈ ਦੇ ਰਹੀ ਹੈ",
    categories: "ਸ਼੍ਰੇਣੀਆਂ",
    mrpWithDots: "ਐਮ.ਆਰ.ਪੀ",
    rtd: "ਤੁਰੰਤ ਡਿਲੀਵਰੀ",
    inclusiveTax: "ਸਾਰੇ ਟੈਕਸਾਂ ਸਮੇਤ ਕੀਮਤ",
    rentInclusiveTax: "ਕਿਰਾਏ ਵਿੱਚ ਟੈਕਸ ਸ਼ਾਮਲ ਹੈ",
    purchase: "ਖਰੀਦੋ",
    rent: "ਕਿਰਾਇਆ",
    refundableSecurity: "ਵਾਪਸੀਯੋਗ ਸੁਰੱਖਿਆ ਜਮ੍ਹਾਂ",
    securityDeposit: "ਸੁਰੱਖਿਆ ਜਮ੍ਹਾਂ",
    refundSecurity: "ਸਮਾਨ ਵਾਪਸ ਕਰਨ ਤੋਂ ਬਾਅਦ ਤੁਹਾਡੀ ਸੁਰੱਖਿਆ ਜਮ੍ਹਾਂ ਰਕਮ ਵਾਪਸ ਕਰ ਦਿੱਤੀ ਜਾਵੇਗੀ।",
    securityDepositDeduction: "ਤੁਸੀਂ ਡਿਲੀਵਰੀ ਦੇ 5 ਦਿਨਾਂ ਦੇ ਅੰਦਰ ਸਮਾਨ ਵਾਪਸ ਕਰ ਸਕਦੇ ਹੋ। ਇਸ ਤੋਂ ਬਾਅਦ ਹਰ 5 ਦਿਨਾਂ 'ਤੇ ਕਿਰਾਏ ਦੀ ਰਕਮ ਸੁਰੱਖਿਆ ਜਮ੍ਹਾਂ ਤੋਂ ਕੱਟੀ ਜਾਵੇਗੀ।",
    sizeGuide: "ਸਾਈਜ਼ ਗਾਈਡ",
    customSize: "ਕਸਟਮ ਸਾਈਜ਼",
    loginToAddCustomSize: "ਕਸਟਮ ਸਾਈਜ਼ ਜੋੜਨ ਅਤੇ ਦੇਖਣ ਲਈ ਲੌਗਇਨ/ਸਾਈਨ ਅਪ ਕਰੋ",
    yourCustomSizes: "ਤੁਹਾਡੇ ਕਸਟਮ ਸਾਈਜ਼",
    undoWishlistMsg: "ਤੁਸੀਂ <b>{name}</b> ਨੂੰ ਵਿਸ਼ਲਿਸਟ ਤੋਂ ਹਟਾ ਦਿੱਤਾ ਹੈ",
    undo: "ਵਾਪਸ ਲਓ (Undo)",
    textPlaceholder: "{0} ਦਰਜ ਕਰੋ",
    address: "ਪਤਾ",
    fullName: "ਨਾਮ",
    city: "ਸ਼ਹਿਰ",
    country: "ਦੇਸ਼",
    pinCode: "ਪਿੰਨ ਕੋਡ",
    state: "ਰਾਜ",
    landmark: "ਲੈਂਡਮਾਰਕ",
    streetAddress1: "ਫਲੈਟ, ਮਕਾਨ ਨੰਬਰ, ਇਮਾਰਤ, ਕੰਪਨੀ, ਅਪਾਰਟਮੈਂਟ",
    streetAddress2: "ਖੇਤਰ, ਗਲੀ, ਸੈਕਟਰ, ਪਿੰਡ",
    defaultAddress: "ਡਿਫੌਲਟ ਪਤਾ ਸੈੱਟ ਕਰੋ",
    setDefault: "ਡਿਫੌਲਟ ਸੈੱਟ ਕਰੋ",
    default: "ਡਿਫੌਲਟ",
    addToCart: "ਕਾਰਟ ਵਿੱਚ ਪਾਓ",
    buyNow: "ਹੁਣੇ ਖਰੀਦੋ",
    total: "ਕੁੱਲ",
    clearCart: "ਕਾਰਟ ਸਾਫ਼ ਕਰੋ",
    proceedToCheckout: "ਚੈੱਕਆਉਟ ਲਈ ਅੱਗੇ ਵਧੋ",
    shoppingCart: "ਸ਼ਾਪਿੰਗ ਕਾਰਟ",
    loadingCart: "ਕਾਰਟ ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...",
    emptyCart: "ਤੁਹਾਡਾ ਕਾਰਟ ਖਾਲੀ ਹੈ।",
    emptyWishlist: "ਤੁਹਾਡੀ ਵਿਸ਼ਲਿਸਟ ਖਾਲੀ ਹੈ।",
    deSelectAll: "ਸਾਰੀਆਂ ਆਈਟਮਾਂ ਨੂੰ ਅਣ-ਚੁਣਿਆ ਕਰੋ",
    invalidCoupon: "ਅਵੈਧ ਕੂਪਨ ਕੋਡ",
    couponApplied: "ਕੂਪਨ ਲਾਗੂ ਹੋਇਆ: ",
    apply: "ਲਾਗੂ ਕਰੋ",
    freeCaps: "ਮੁਫ਼ਤ",
    deliveryCharges: "ਡਿਲੀਵਰੀ ਖਰਚੇ",
    subTotal: "ਉਪ-ਕੁੱਲ (Sub-Total)",
    changeSize: "ਆਕਾਰ ਬਦਲੋ",
    moveToWishlist: "ਵਿਸ਼ਲਿਸਟ ਵਿੱਚ ਭੇਜੋ",
    share: "ਸਾਂਝਾ ਕਰੋ",
    orderSummary: "ਆਰਡਰ ਦਾ ਸਾਰ",
    coupon: "ਕੂਪਨ",
    itemsForPurchasing: "ਖਰੀਦਦਾਰੀ ਲਈ ਚੁਣੀਆਂ ਗਈਆਂ ਆਈਟਮਾਂ",
    itemsForRenting: "ਕਿਰਾਏ ਲਈ ਚੁਣੀਆਂ ਗਈਆਂ ਆਈਟਮਾਂ",
    itemsSelected: "ਚੁਣੀਆਂ ਆਈਟਮਾਂ",
    applyCoupon: "ਕੂਪਨ ਲਾਗੂ ਕਰੋ",
    undoCartMsg: 'ਕਾਰਟ ਤੋਂ <strong>{name}</strong> ਹਟਾ ਦਿੱਤਾ ਗਿਆ। ',
    itemRestored: "ਆਈਟਮ ਕਾਰਟ ਵਿੱਚ ਵਾਪਸ ਆ ਗਈ",
    selectAll: "ਸਭ ਚੁਣੋ",
    itemMovedToWishlist: "ਆਈਟਮ ਵਿਸ਼ਲਿਸਟ ਵਿੱਚ ਭੇਜੀ ਗਈ।",
    itemRemoved: "ਆਈਟਮ ਹਟਾ ਦਿੱਤੀ ਗਈ",
    addedToCart: "ਆਈਟਮ ਕਾਰਟ ਵਿੱਚ ਜੋੜੀ ਗਈ",
    itemAddedToWishlist: "ਆਈਟਮ ਵਿਸ਼ਲਿਸਟ ਵਿੱਚ ਜੋੜੀ ਗਈ",
    itemRemovedFromWishlist: "ਆਈਟਮ ਵਿਸ਼ਲਿਸਟ ਤੋਂ ਹਟਾ ਦਿੱਤੀ ਗਈ",
    proceedToBuy: "ਖਰੀਦਦਾਰੀ ਲਈ ਅੱਗੇ ਵਧੋ",
    change: "ਬਦਲੋ",
    checkout: "ਚੈੱਕਆਉਟ",
    deliverHere: "ਇੱਥੇ ਡਿਲੀਵਰ ਕਰੋ",
    selectDeliveryAddress: "ਡਿਲੀਵਰੀ ਪਤਾ ਚੁਣੋ",
    selectedDeliveryAddress: "ਚੁਣਿਆ ਗਿਆ ਡਿਲੀਵਰੀ ਪਤਾ",
    inventoryType: "ਇਨਵੈਂਟਰੀ ਦੀ ਕਿਸਮ",
    currentlyDefaultAddress: "ਡਿਫੌਲਟ ਪਤਾ",
    chosenAddressUpdated: "ਚੁਣਿਆ ਪਤਾ ਸਫਲਤਾਪੂਰਵਕ ਅੱਪਡੇਟ ਹੋਇਆ।",
    draftUpdated: "ਆਰਡਰ ਦਾ ਵੇਰਵਾ ਸਫਲਤਾਪੂਰਵਕ ਅੱਪਡੇਟ ਹੋਇਆ।",
    deliveringTo: "ਡਿਲੀਵਰੀ ਲਈ",
    addNew: "ਨਵਾਂ ਜੋੜੋ",
    itemsInOrder: "ਆਰਡਰ ਵਿੱਚ ਆਈਟਮਾਂ",
    shipTogether: "ਸਾਰੀਆਂ ਆਈਟਮਾਂ ਇਕੱਠੀਆਂ ਭੇਜੋ",
    shipAsap: "ਹਰ ਆਈਟਮ ਤਿਆਰ ਹੋਣ 'ਤੇ ਭੇਜੋ",
    shipItems: "ਤੁਸੀਂ ਆਪਣੇ ਆਰਡਰ ਦੀਆਂ ਆਈਟਮਾਂ ਕਦੋਂ ਭੇਜਣਾ ਚਾਹੁੰਦੇ ਹੋ?",
    shipItemsForOrder: "{user} ਆਪਣੇ ਆਰਡਰ ਦੀਆਂ ਆਈਟਮਾਂ ਕਦੋਂ ਭੇਜਣਾ ਚਾਹੁੰਦਾ ਹੈ?",
    orderPlacedTitle: "ਧੰਨਵਾਦ, ਤੁਹਾਡਾ ਆਰਡਰ ਸਫਲਤਾਪੂਰਵਕ ਦਿੱਤਾ ਗਿਆ!",
    orderConfirmationSent: "ਤੁਹਾਡੀ ਈਮੇਲ 'ਤੇ ਪੁਸ਼ਟੀ ਭੇਜ ਦਿੱਤੀ ਗਈ ਹੈ।",
    orderId: "ਆਰਡਰ ਆਈਡੀ",
    itemsInTheOrder: "ਆਰਡਰ ਵਿੱਚ ਆਈਟਮਾਂ",
    viewOrders: "ਆਪਣੇ ਆਰਡਰ ਵੇਖੋ",
    viewAllOrders: "ਸਾਰੇ ਆਰਡਰ ਵੇਖੋ",
    continueShopping: "ਖਰੀਦਦਾਰੀ ਜਾਰੀ ਰੱਖੋ",
    orderDetails: "ਆਰਡਰ ਦਾ ਵੇਰਵਾ",
    appliedCoupon: "ਲਾਗੂ ਕੂਪਨ",
    orderPlacedOn: "ਆਰਡਰ ਦਿੱਤਾ ਗਿਆ",
    shipTo: "ਨੂੰ ਭੇਜੋ",
    noOrdersFound: "ਕੋਈ ਆਰਡਰ ਨਹੀਂ ਮਿਲਿਆ",
    yourOrders: "ਤੁਹਾਡੇ ਆਰਡਰ",
    paymentMode: "ਭੁਗਤਾਨ ਦਾ ਤਰੀਕਾ",
    paymentMethod: "ਭੁਗਤਾਨ ਵਿਧੀ",
    all: "ਸਾਰੇ",
    pending: "ਬਕਾਇਆ",
    shipped: "ਭੇਜਿਆ ਗਿਆ",
    delivered: "ਡਿਲੀਵਰ ਕੀਤਾ ਗਿਆ",
    cancelled: "ਰੱਦ ਕੀਤਾ ਗਿਆ",
    allOrders: "ਸਾਰੇ ਆਰਡਰ",
    newOrders: "ਨਵੇਂ ਆਰਡਰ",
    statusMessages: {
      forOrder: {
        forManager: {
          draft: "ਆਰਡਰ ਡਰਾਫਟ ਸਥਿਤੀ ਵਿੱਚ ਹੈ ਅਤੇ ਅਜੇ ਤੱਕ ਪਲੇਸ ਨਹੀਂ ਕੀਤਾ ਗਿਆ।",
          pending: "ਭੁਗਤਾਨ ਬਕਾਇਆ ਹੈ।",
          placed: "ਆਰਡਰ ਦਿੱਤਾ ਗਿਆ ਹੈ ਅਤੇ ਤੁਹਾਡੀ ਪੁਸ਼ਟੀ ਦੀ ਉਡੀਕ ਹੈ।",
          confirmed: "ਤੁਸੀਂ ਆਰਡਰ ਦੀ ਪੁਸ਼ਟੀ ਕਰ ਦਿੱਤੀ ਹੈ।",
          payment_failed: "ਭੁਗਤਾਨ ਅਸਫਲ ਰਿਹਾ।",
          in_process: "ਆਰਡਰ ਤੁਹਾਡੇ ਦੁਆਰਾ ਪ੍ਰੋਸੈਸ ਕੀਤਾ ਜਾ ਰਿਹਾ ਹੈ।",
          ready_to_dispatch: "ਆਰਡਰ ਡਿਸਪੈਚ ਲਈ ਤਿਆਰ ਹੈ।",
          shipped: "ਆਰਡਰ ਭੇਜ ਦਿੱਤਾ ਗਿਆ ਹੈ।",
          in_transit: "ਆਰਡਰ ਰਸਤੇ ਵਿੱਚ ਹੈ।",
          delivered: "ਆਰਡਰ ਡਿਲੀਵਰ ਕਰ ਦਿੱਤਾ ਗਿਆ ਹੈ।",
          cancelled: "ਆਰਡਰ ਰੱਦ ਕਰ ਦਿੱਤਾ ਗਿਆ ਹੈ।",
          cancellation_requested: "ਵਰਤੋਂਕਾਰ ਨੇ ਆਰਡਰ ਰੱਦ ਕਰਨ ਦੀ ਬੇਨਤੀ ਕੀਤੀ ਹੈ।",
          cancellation_rejected: "ਤੁਸੀਂ ਰੱਦ ਕਰਨ ਦੀ ਬੇਨਤੀ ਨੂੰ ਅਸਵੀਕਾਰ ਕਰ ਦਿੱਤਾ ਹੈ।",
          cancellation_refunded: "ਆਰਡਰ ਰੱਦ ਕਰ ਦਿੱਤਾ ਗਿਆ ਅਤੇ ਭੁਗਤਾਨ ਰਿਫੰਡ ਕੀਤਾ ਗਿਆ।",
          return_requested: "ਵਾਪਸੀ ਲਈ ਬੇਨਤੀ ਕੀਤੀ ਗਈ ਹੈ।",
          return_rejected: "ਵਾਪਸੀ ਦੀ ਬੇਨਤੀ ਅਸਵੀਕਾਰ ਕੀਤੀ ਗਈ।",
          returned: "ਆਰਡਰ ਵਾਪਸ ਕੀਤਾ ਗਿਆ ਹੈ।",
          return_refunded: "ਵਾਪਸੀ ਤੋਂ ਬਾਅਦ ਭੁਗਤਾਨ ਰਿਫੰਡ ਕੀਤਾ ਗਿਆ।",
          refunded: "ਭੁਗਤਾਨ ਰਿਫੰਡ ਕਰ ਦਿੱਤਾ ਗਿਆ।",
          rto_requested: "ਤੁਹਾਡੇ ਦੁਆਰਾ RTO ਦੀ ਬੇਨਤੀ ਕੀਤੀ ਗਈ।",
          rto_rejected: "ਤੁਸੀਂ RTO ਬੇਨਤੀ ਅਸਵੀਕਾਰ ਕੀਤੀ।",
          rto_approved: "ਤੁਸੀਂ RTO ਬੇਨਤੀ ਨੂੰ ਮਨਜ਼ੂਰੀ ਦਿੱਤੀ।",
          rto_in_progress: "RTO ਪ੍ਰਕਿਰਿਆ ਵਿੱਚ ਹੈ।",
          rto_delivered: "RTO ਦੁਆਰਾ ਆਰਡਰ ਤੁਹਾਨੂੰ ਵਾਪਸ ਭੇਜ ਦਿੱਤਾ ਗਿਆ।",
          rto_verified: "RTO ਆਈਟਮ ਦੀ ਤਸਦੀਕ ਕੀਤੀ ਗਈ।",
          rto_refunded: "RTO ਤੋਂ ਬਾਅਦ ਭੁਗਤਾਨ ਰਿਫੰਡ ਕਰ ਦਿੱਤਾ ਗਿਆ।"
        },
        forUser: {
          draft: "ਤੁਹਾਡਾ ਆਰਡਰ ਚੈੱਕਆਉਟ ਵਿੱਚ ਹੈ ਪਰ ਅਜੇ ਤੱਕ ਪਲੇਸ ਨਹੀਂ ਕੀਤਾ ਗਿਆ।",
          pending: "ਭੁਗਤਾਨ ਬਕਾਇਆ ਹੈ। ਕਿਰਪਾ ਕਰਕੇ ਭੁਗਤਾਨ ਪੂਰਾ ਕਰੋ।",
          placed: "ਤੁਹਾਡਾ ਆਰਡਰ ਪਲੇਸ ਕਰ ਦਿੱਤਾ ਗਿਆ ਹੈ ਅਤੇ ਪੁਸ਼ਟੀ ਦੀ ਉਡੀਕ ਹੈ।",
          confirmed: "ਤੁਹਾਡਾ ਆਰਡਰ ਵਿਕਰੇਤਾ ਦੁਆਰਾ ਪੁਸ਼ਟੀ ਕੀਤਾ ਗਿਆ।",
          payment_failed: "ਭੁਗਤਾਨ ਅਸਫਲ ਰਿਹਾ। ਕਿਰਪਾ ਕਰਕੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
          in_process: "ਤੁਹਾਡਾ ਆਰਡਰ ਵਿਕਰੇਤਾ ਦੁਆਰਾ ਪ੍ਰੋਸੈਸ ਕੀਤਾ ਜਾ ਰਿਹਾ ਹੈ।",
          ready_to_dispatch: "ਤੁਹਾਡਾ ਆਰਡਰ ਡਿਸਪੈਚ ਲਈ ਤਿਆਰ ਹੈ।",
          shipped: "ਤੁਹਾਡਾ ਆਰਡਰ ਭੇਜ ਦਿੱਤਾ ਗਿਆ ਹੈ।",
          in_transit: "ਤੁਹਾਡਾ ਆਰਡਰ ਰਸਤੇ ਵਿੱਚ ਹੈ।",
          delivered: "ਤੁਹਾਡਾ ਆਰਡਰ ਡਿਲੀਵਰ ਕਰ ਦਿੱਤਾ ਗਿਆ ਹੈ।",
          cancelled: "ਤੁਹਾਡਾ ਆਰਡਰ ਰੱਦ ਕਰ ਦਿੱਤਾ ਗਿਆ ਹੈ।",
          cancellation_requested: "ਤੁਸੀਂ ਆਰਡਰ ਰੱਦ ਕਰਨ ਦੀ ਬੇਨਤੀ ਕੀਤੀ।",
          cancellation_rejected: "ਤੁਹਾਡੀ ਰੱਦ ਕਰਨ ਦੀ ਬੇਨਤੀ ਅਸਵੀਕਾਰ ਕੀਤੀ ਗਈ।",
          cancellation_refunded: "ਤੁਹਾਡਾ ਆਰਡਰ ਰੱਦ ਕਰ ਦਿੱਤਾ ਗਿਆ ਅਤੇ ਭੁਗਤਾਨ ਰਿਫੰਡ ਕੀਤਾ ਗਿਆ।",
          return_requested: "ਤੁਹਾਡੇ ਆਰਡਰ ਲਈ ਵਾਪਸੀ ਦੀ ਬੇਨਤੀ ਕੀਤੀ ਗਈ।",
          return_rejected: "ਵਾਪਸੀ ਦੀ ਬੇਨਤੀ ਅਸਵੀਕਾਰ ਕੀਤੀ ਗਈ।",
          returned: "ਤੁਹਾਡਾ ਆਰਡਰ ਵਾਪਸ ਕੀਤਾ ਗਿਆ।",
          return_refunded: "ਵਾਪਸੀ ਤੋਂ ਬਾਅਦ ਤੁਹਾਡਾ ਭੁਗਤਾਨ ਰਿਫੰਡ ਕੀਤਾ ਗਿਆ।",
          refunded: "ਭੁਗਤਾਨ ਰਿਫੰਡ ਕਰ ਦਿੱਤਾ ਗਿਆ।",
          rto_requested: "ਤੁਹਾਡੇ ਆਰਡਰ ਲਈ RTO ਦੀ ਬੇਨਤੀ ਕੀਤੀ ਗਈ।",
          rto_rejected: "RTO ਬੇਨਤੀ ਅਸਵੀਕਾਰ ਕੀਤੀ ਗਈ।",
          rto_approved: "RTO ਬੇਨਤੀ ਮਨਜ਼ੂਰ ਕੀਤੀ ਗਈ।",
          rto_in_progress: "RTO ਪ੍ਰਕਿਰਿਆ ਵਿੱਚ ਹੈ।",
          rto_delivered: "RTO ਦੁਆਰਾ ਆਰਡਰ ਵਾਪਸ ਭੇਜ ਦਿੱਤਾ ਗਿਆ।",
          rto_verified: "RTO ਆਈਟਮ ਦੀ ਪੁਸ਼ਟੀ ਕੀਤੀ ਗਈ।",
          rto_refunded: "RTO ਤੋਂ ਬਾਅਦ ਭੁਗਤਾਨ ਰਿਫੰਡ ਕਰ ਦਿੱਤਾ ਗਿਆ।"
        }
      },
      forItem: {
        forManager: {
          draft: "ਆਈਟਮ ਆਰਡਰ ਡਰਾਫਟ ਵਿੱਚ ਸ਼ਾਮਲ ਕੀਤੀ ਗਈ ਹੈ ਅਤੇ ਅਜੇ ਤੱਕ ਪਲੇਸ ਨਹੀਂ ਹੋਈ।",
          pending: "ਇਸ ਆਈਟਮ ਦਾ ਭੁਗਤਾਨ ਬਕਾਇਆ ਹੈ।",
          placed: "ਆਈਟਮ ਪਲੇਸ ਕੀਤੀ ਗਈ ਹੈ ਅਤੇ ਤੁਹਾਡੀ ਪੁਸ਼ਟੀ ਦੀ ਉਡੀਕ ਹੈ।",
          confirmed: "ਤੁਸੀਂ ਆਈਟਮ ਦੀ ਪੁਸ਼ਟੀ ਕਰ ਦਿੱਤੀ ਹੈ।",
          payment_failed: "ਇਸ ਆਈਟਮ ਦਾ ਭੁਗਤਾਨ ਅਸਫਲ ਰਿਹਾ।",
          in_process: "ਆਈਟਮ ਪ੍ਰੋਸੈਸ ਕੀਤੀ ਜਾ ਰਹੀ ਹੈ।",
          ready_to_dispatch: "ਆਈਟਮ ਡਿਸਪੈਚ ਲਈ ਤਿਆਰ ਹੈ।",
          shipped: "ਆਈਟਮ ਭੇਜ ਦਿੱਤੀ ਗਈ।",
          in_transit: "ਆਈਟਮ ਰਸਤੇ ਵਿੱਚ ਹੈ।",
          delivered: "ਆਈਟਮ ਡਿਲੀਵਰ ਕਰ ਦਿੱਤੀ ਗਈ।",
          cancelled: "ਆਈਟਮ ਰੱਦ ਕਰ ਦਿੱਤੀ ਗਈ।",
          cancellation_requested: "ਇਸ ਆਈਟਮ ਲਈ ਵਰਤੋਂਕਾਰ ਨੇ ਰੱਦ ਕਰਨ ਦੀ ਬੇਨਤੀ ਕੀਤੀ।",
          cancellation_rejected: "ਰੱਦ ਕਰਨ ਦੀ ਬੇਨਤੀ ਅਸਵੀਕਾਰ ਕੀਤੀ ਗਈ।",
          cancellation_refunded: "ਭੁਗਤਾਨ ਰਿਫੰਡ ਕਰ ਦਿੱਤਾ ਗਿਆ।",
          return_requested: "ਵਾਪਸੀ ਦੀ ਬੇਨਤੀ ਕੀਤੀ ਗਈ।",
          return_rejected: "ਵਾਪਸੀ ਦੀ ਬੇਨਤੀ ਅਸਵੀਕਾਰ ਕੀਤੀ ਗਈ।",
          returned: "ਆਈਟਮ ਵਾਪਸ ਕੀਤੀ ਗਈ।",
          return_refunded: "ਭੁਗਤਾਨ ਰਿਫੰਡ ਕਰ ਦਿੱਤਾ ਗਿਆ।",
          refunded: "ਭੁਗਤਾਨ ਰਿਫੰਡ ਕਰ ਦਿੱਤਾ ਗਿਆ।",
          rto_requested: "RTO ਦੀ ਬੇਨਤੀ ਕੀਤੀ ਗਈ।",
          rto_rejected: "RTO ਬੇਨਤੀ ਅਸਵੀਕਾਰ ਕੀਤੀ ਗਈ।",
          rto_approved: "RTO ਬੇਨਤੀ ਮਨਜ਼ੂਰ ਕੀਤੀ ਗਈ।",
          rto_in_progress: "RTO ਪ੍ਰਕਿਰਿਆ ਵਿੱਚ ਹੈ।",
          rto_delivered: "RTO ਦੁਆਰਾ ਆਈਟਮ ਵਾਪਸ ਭੇਜ ਦਿੱਤੀ ਗਈ।",
          rto_verified: "RTO ਆਈਟਮ ਦੀ ਪੁਸ਼ਟੀ ਕੀਤੀ ਗਈ।",
          rto_refunded: "RTO ਤੋਂ ਬਾਅਦ ਭੁਗਤਾਨ ਰਿਫੰਡ ਕਰ ਦਿੱਤਾ ਗਿਆ।"
        },
        forUser: {
          draft: "ਇਹ ਆਈਟਮ ਚੈੱਕਆਉਟ ਵਿੱਚ ਹੈ ਪਰ ਅਜੇ ਤੱਕ ਪਲੇਸ ਨਹੀਂ ਹੋਈ।",
          pending: "ਇਸ ਆਈਟਮ ਦਾ ਭੁਗਤਾਨ ਬਕਾਇਆ ਹੈ। ਕਿਰਪਾ ਕਰਕੇ ਪੂਰਾ ਕਰੋ।",
          placed: "ਇਹ ਆਈਟਮ ਪਲੇਸ ਕੀਤੀ ਗਈ ਹੈ ਅਤੇ ਪੁਸ਼ਟੀ ਦੀ ਉਡੀਕ ਹੈ।",
          confirmed: "ਇਹ ਆਈਟਮ ਵਿਕਰੇਤਾ ਦੁਆਰਾ ਪੁਸ਼ਟੀ ਕੀਤੀ ਗਈ।",
          payment_failed: "ਇਸ ਆਈਟਮ ਦਾ ਭੁਗਤਾਨ ਅਸਫਲ ਰਿਹਾ।",
          in_process: "ਆਈਟਮ ਵਿਕਰੇਤਾ ਦੁਆਰਾ ਪ੍ਰੋਸੈਸ ਕੀਤੀ ਜਾ ਰਹੀ ਹੈ।",
          ready_to_dispatch: "ਆਈਟਮ ਡਿਸਪੈਚ ਲਈ ਤਿਆਰ ਹੈ।",
          shipped: "ਆਈਟਮ ਭੇਜ ਦਿੱਤੀ ਗਈ।",
          in_transit: "ਆਈਟਮ ਰਸਤੇ ਵਿੱਚ ਹੈ।",
          delivered: "ਆਈਟਮ ਡਿਲੀਵਰ ਕਰ ਦਿੱਤੀ ਗਈ।",
          cancelled: "ਆਈਟਮ ਰੱਦ ਕਰ ਦਿੱਤੀ ਗਈ।",
          cancellation_requested: "ਤੁਸੀਂ ਇਸ ਆਈਟਮ ਨੂੰ ਰੱਦ ਕਰਨ ਦੀ ਬੇਨਤੀ ਕੀਤੀ।",
          cancellation_rejected: "ਰੱਦ ਕਰਨ ਦੀ ਬੇਨਤੀ ਅਸਵੀਕਾਰ ਕੀਤੀ ਗਈ।",
          cancellation_refunded: "ਭੁਗਤਾਨ ਰਿਫੰਡ ਕਰ ਦਿੱਤਾ ਗਿਆ।",
          return_requested: "ਵਾਪਸੀ ਦੀ ਬੇਨਤੀ ਕੀਤੀ ਗਈ।",
          return_rejected: "ਵਾਪਸੀ ਦੀ ਬੇਨਤੀ ਅਸਵੀਕਾਰ ਕੀਤੀ ਗਈ।",
          returned: "ਆਈਟਮ ਵਾਪਸ ਕੀਤੀ ਗਈ।",
          return_refunded: "ਭੁਗਤਾਨ ਰਿਫੰਡ ਕਰ ਦਿੱਤਾ ਗਿਆ।",
          refunded: "ਭੁਗਤਾਨ ਰਿਫੰਡ ਕਰ ਦਿੱਤਾ ਗਿਆ।",
          rto_requested: "RTO ਦੀ ਬੇਨਤੀ ਕੀਤੀ ਗਈ।",
          rto_rejected: "RTO ਬੇਨਤੀ ਅਸਵੀਕਾਰ ਕੀਤੀ ਗਈ।",
          rto_approved: "RTO ਬੇਨਤੀ ਮਨਜ਼ੂਰ ਕੀਤੀ ਗਈ।",
          rto_in_progress: "RTO ਪ੍ਰਕਿਰਿਆ ਵਿੱਚ ਹੈ।",
          rto_delivered: "RTO ਦੁਆਰਾ ਆਈਟਮ ਵਾਪਸ ਭੇਜ ਦਿੱਤੀ ਗਈ।",
          rto_verified: "RTO ਆਈਟਮ ਦੀ ਪੁਸ਼ਟੀ ਕੀਤੀ ਗਈ।",
          rto_refunded: "RTO ਤੋਂ ਬਾਅਦ ਭੁਗਤਾਨ ਰਿਫੰਡ ਕਰ ਦਿੱਤਾ ਗਿਆ।"
        }
      }
    },
    statusColors: {
      draft: "var(--secondarytext-color)",
      pending: "var(--warning-color)",
      placed: "var(--info-color)",
      confirmed: "var(--success-color)",
      payment_failed: "var(--danger-color)",
      in_process: "var(--infolight-color)",
      ready_to_dispatch: "purple",
      shipped: "blue",
      in_transit: "var(--primarylight-color)",
      delivered: "var(--successdark-color)",
      cancellation_requested: "orange",
      cancelled: "var(--dangerlight-color)",
      cancellation_rejected: "red",
      cancellation_refunded: "var(--success-color)",
      return_requested: "var(--secondary-color)",
      returned: "var(--dangerlight-color)",
      return_rejected: "var(--warning-color)",
      return_refunded: "var(--success-color)",
      refunded: "var(--success-color)",
      rto_requested: "var(--warningdark-color)",
      rto_rejected: "red",
      rto_approved: "var(--success-color)",
      rto_in_progress: "blueviolet",
      rto_delivered: "var(--info-color)",
      rto_verified: "var(--successdark-color)",
      rto_refunded: "var(--success-color)"
    },
    orderPages: {
      allOrders: {
        title: "ਸਾਰੇ ਆਰਡਰ",
        statuses: ["ALL"]
      },
      pendingOrders: {
        title: "ਬਕਾਇਆ ਆਰਡਰ",
        statuses: ["PENDING"]
      },
      newOrders: {
        title: "ਨਵੇਂ ਆਰਡਰ",
        statuses: ["PLACED"]
      },
      confirmedOrders: {
        title: "ਪੁਸ਼ਟੀ ਕੀਤੇ ਆਰਡਰ",
        statuses: ["CONFIRMED"]
      },
      processingOrders: {
        title: "ਪ੍ਰੋਸੈਸਿੰਗ ਆਰਡਰ",
        statuses: ["IN_PROCESS"]
      },
      readyToDispatchOrders: {
        title: "ਡਿਸਪੈਚ ਲਈ ਤਿਆਰ",
        statuses: ["READY_TO_DISPATCH"]
      },
      onTheWayOrders: {
        title: "ਰਸਤੇ ਵਿੱਚ ਆਰਡਰ",
        statuses: ["SHIPPED", "IN_TRANSIT"]
      },
      deliveredOrders: {
        title: "ਡਿਲੀਵਰ ਹੋਏ ਆਰਡਰ",
        statuses: ["DELIVERED"]
      },
      cancelled: {
        title: "ਰੱਦ ਆਰਡਰ",
        statuses: ["CANCELLED"]
      },
      returns: {
        title: "ਰਿਟਰਨ",
        statuses: ["ALLRETURNS"],
        showOrderStatuses: false
      },
      cancellation_requested: {
        title: "ਰੱਦ ਕਰਨ ਦੀ ਬੇਨਤੀ ਕੀਤੀ",
        statuses: ["CANCELLATION_REQUESTED"]
      },
      cancellation_rejected: {
        title: "ਰੱਦ ਕਰਨ ਦੀ ਬੇਨਤੀ ਅਸਵੀਕਾਰ",
        statuses: ["CANCELLATION_REJECTED"]
      },
      cancellation_refunded: {
        title: "ਰੱਦ ਰਿਫੰਡ",
        statuses: ["CANCELLATION_REFUNDED"]
      },
      return_requested: {
        title: "ਵਾਪਸੀ ਦੀ ਬੇਨਤੀ ਕੀਤੀ",
        statuses: ["RETURN_REQUESTED"]
      },
      returned: {
        title: "ਵਾਪਸ ਕੀਤੇ ਆਰਡਰ",
        statuses: ["RETURNED"]
      },
      return_rejected: {
        title: "ਵਾਪਸੀ ਅਸਵੀਕਾਰ",
        statuses: ["RETURN_REJECTED"]
      },
      return_refunded: {
        title: "ਵਾਪਸੀ ਰਿਫੰਡ",
        statuses: ["RETURN_REFUNDED"]
      },
      rto_requested: {
        title: "RTO ਬੇਨਤੀ ਕੀਤੀ",
        statuses: ["RTO_REQUESTED"]
      },
      rto_rejected: {
        title: "RTO ਅਸਵੀਕਾਰ",
        statuses: ["RTO_REJECTED"]
      },
      rto_approved: {
        title: "RTO ਮਨਜ਼ੂਰ",
        statuses: ["RTO_APPROVED"]
      },
      rto_in_progress: {
        title: "RTO ਪ੍ਰਕਿਰਿਆ ਵਿੱਚ",
        statuses: ["RTO_IN_PROGRESS"]
      },
      rto_delivered: {
        title: "RTO ਡਿਲੀਵਰ",
        statuses: ["RTO_DELIVERED"]
      },
      rto_verified: {
        title: "RTO ਤਸਦੀਕਸ਼ੁਦਾ",
        statuses: ["RTO_VERIFIED"]
      },
      rto_refunded: {
        title: "RTO ਰਿਫੰਡ",
        statuses: ["RTO_REFUNDED"]
      }
    },
    confirmedOrders: "ਪੁਸ਼ਟੀ ਕੀਤੇ ਆਰਡਰ",
    processingOrders: "ਪ੍ਰੋਸੈਸਿੰਗ ਆਰਡਰ",
    readyToDispatchOrders: "ਡਿਸਪੈਚ ਲਈ ਤਿਆਰ ਆਰਡਰ",
    onTheWayOrders: "ਰਸਤੇ ਵਿੱਚ ਆਰਡਰ",
    deliveredOrders: "ਡਿਲੀਵਰ ਹੋਏ ਆਰਡਰ",
    cancelled_orders: "ਰੱਦ ਆਰਡਰ",
    cancellation_requested_orders: "ਰੱਦ ਕਰਨ ਦੀ ਬੇਨਤੀ ਕੀਤੇ ਆਰਡਰ",
    return_requested_orders: "ਵਾਪਸੀ ਦੀ ਬੇਨਤੀ ਕੀਤੇ ਆਰਡਰ",
    return_refunded_orders: "ਵਾਪਸੀ ਰਿਫੰਡ ਹੋਏ ਆਰਡਰ",
    returns: "ਰਿਟਰਨ",
    returned_orders: "ਵਾਪਸ ਕੀਤੇ ਆਰਡਰ",
    return_rejected_orders: "ਵਾਪਸੀ ਅਸਵੀਕਾਰ ਹੋਏ ਆਰਡਰ",
    cancellation_rejected_orders: "ਰੱਦ ਕਰਨ ਦੀ ਬੇਨਤੀ ਅਸਵੀਕਾਰ ਹੋਏ ਆਰਡਰ",
    cancellation_refunded_orders: "ਰੱਦ ਕਰਨ ਦੀ ਬੇਨਤੀ ਰਿਫੰਡ ਹੋਏ ਆਰਡਰ",
    rto_requested_orders: "RTO ਬੇਨਤੀ ਕੀਤੇ ਆਰਡਰ",
    rto_rejected_orders: "RTO ਅਸਵੀਕਾਰ ਹੋਏ ਆਰਡਰ",
    rto_approved_orders: "RTO ਮਨਜ਼ੂਰ ਹੋਏ ਆਰਡਰ",
    rto_in_progress_orders: "RTO ਪ੍ਰਕਿਰਿਆ ਵਿੱਚ ਆਰਡਰ",
    rto_delivered_orders: "RTO ਡਿਲੀਵਰ ਹੋਏ ਆਰਡਰ",
    rto_verified_orders: "RTO ਤਸਦੀਕਸ਼ੁਦਾ ਆਰਡਰ",
    rto_refunded_orders: "RTO ਰਿਫੰਡ ਹੋਏ ਆਰਡਰ",
    moreOptions: "ਹੋਰ ਵਿਕਲਪ",
    details: "ਵੇਰਵੇ",
    viewProductPage: "ਉਤਪਾਦ ਪੇਜ ਵੇਖੋ",
    viewSize: "ਸਾਈਜ਼ ਵੇਖੋ",
    trackStatus: "ਸਥਿਤੀ ਟ੍ਰੈਕ ਕਰੋ",
    auditTrail: "ਆਡਿਟ ਟ੍ਰੇਲ",
    changedFrom: "ਤੋਂ ਬਦਲਿਆ",
    changedTo: "ਤੱਕ ਬਦਲਿਆ",
    entityType: "ਇਕਾਈ ਦੀ ਕਿਸਮ",
    entityId: "ਇਕਾਈ ਆਈਡੀ",
    performedBy: "ਦੁਆਰਾ ਕੀਤਾ ਗਿਆ",
    timestamp: "ਟਾਈਮਸਟੈਂਪ",
    trackingDetails: "ਟ੍ਰੈਕਿੰਗ ਵੇਰਵੇ",
    noDetailsFound: "ਕੋਈ ਵੇਰਵਾ ਨਹੀਂ ਮਿਲਿਆ",
    userDetails: "ਵਰਤੋਂਕਾਰ ਵੇਰਵੇ",
    followUs: "ਸਾਨੂੰ ਫਾਲੋ ਕਰੋ",
    allRightsReserved: "ਸਾਰੇ ਅਧਿਕਾਰ ਰਾਖਵੇਂ ਹਨ",
    fastAndSecured: "ਤੇਜ਼ ਅਤੇ ਸੁਰੱਖਿਅਤ ਭੁਗਤਾਨ ਵਿਕਲਪ",
    company: "ਕੰਪਨੀ",
    myAccount: "ਮੇਰਾ ਖਾਤਾ",
    home: "ਮੁੱਖ ਪੰਨਾ",
    account: "ਖਾਤਾ",
    search: "ਖੋਜ ਕਰੋ",
    cart: "ਕਾਰਟ",
    language: "ਭਾਸ਼ਾ",
    somethingWentWrong: "ਕੁਝ ਗਲਤ ਹੋ ਗਿਆ!",
    note: "ਨੋਟ",
    notAllowed1: "ਤੁਹਾਨੂੰ ਇਸ ਐਪਲੀਕੇਸ਼ਨ ਵਿੱਚ ਲੌਗਇਨ ਕਰਨ ਦੀ ਆਗਿਆ ਨਹੀਂ ਹੈ",
    notAllowed2: "ਕੇਵਲ ਐਡਮਿਨ ਅਤੇ ਮੈਨੇਜਰ ਕੋਲ ਹੀ ਇਸ ਦੀ ਪਹੁੰਚ ਹੈ",
    notAllowed3: "ਜੇਕਰ ਤੁਸੀਂ ਇਹਨਾਂ ਵਿੱਚੋਂ ਇੱਕ ਹੋ ਅਤੇ ਫਿਰ ਵੀ ਐਕਸੈਸ ਨਹੀਂ ਕਰ ਪਾ ਰਹੇ ਤਾਂ ਐਡਮਿਨ ਨਾਲ ਸੰਪਰਕ ਕਰੋ",
    logOutAndBackToHome: "ਲੌਗ ਆਉਟ ਕਰੋ ਅਤੇ ਹੋਮ 'ਤੇ ਵਾਪਸ ਜਾਓ",
    whatsAppUs: "ਸਾਨੂੰ ਵਟਸਐਪ ਕਰੋ",
    ourContactDetails: "ਸਾਡੇ ਸੰਪਰਕ ਵੇਰਵੇ",
    workingHours: "ਕੰਮ ਦੇ ਘੰਟੇ",
    instagram: "ਇੰਸਟਾਗ੍ਰਾਮ",
    facebook: "ਫੇਸਬੁੱਕ",
    x: "ਐਕਸ (ਟਵਿੱਟਰ)",
    threads: "ਥ੍ਰੈਡਸ",
    youtube: "ਯੂਟਿਊਬ",
    pinterest: "ਪਿਨਟਰੈਸਟ",
    quotaUsage: "ਮੇਲ/SMS ਕੋਟਾ ਵਰਤੋਂ",
    used: "ਵਰਤਿਆ ਗਿਆ",
    remaining: "ਬਾਕੀ",
    totalQuota: "ਕੁੱਲ ਕੋਟਾ",
    sms: "ਐਸ.ਐਮ.ਐਸ (SMS)",
    whatsapp: "ਵਟਸਐਪ",
    brevo: "ਬ੍ਰੇਵੋ",
    count: "ਗਿਣਤੀ",
    date: "ਤਾਰੀਖ",
    gmail: "ਜੀਮੇਲ",
    quota: "ਕੋਟਾ",
    teamUsers: "ਟੀਮ",
    member: "ਮੈਂਬਰ",
    customer: "ਗਾਹਕ",
    profileImage: "ਪ੍ਰੋਫਾਈਲ ਤਸਵੀਰ",
    gender: "ਲਿੰਗ",
    role: "ਭੂਮਿਕਾ",
    activatedText: "ਕਿਰਿਆਸ਼ੀਲ",
    selectRolePlaceholder: "ਭੂਮਿਕਾ ਚੁਣੋ",
    accountActiveLabel: "ਕਿਰਪਾ ਕਰਕੇ ਚੁਣੋ ਕਿ ਵਰਤੋਂਕਾਰ ਦਾ ਖਾਤਾ ਕਿਰਿਆਸ਼ੀਲ/ਅਕਿਰਿਆਸ਼ੀਲ ਹੋਣਾ ਚਾਹੀਦਾ ਹੈ:",
    user: "ਵਰਤੋਂਕਾਰ",
    actions: "ਕਾਰਵਾਈਆਂ",
    setAsDiscontinued: "ਬੰਦ (Discontinued) ਵਜੋਂ ਸੈੱਟ ਕਰੋ",
    resetToDefaultPassword: "ਡਿਫੌਲਟ ਪਾਸਵਰਡ 'ਤੇ ਰੀਸੈਟ ਕਰੋ",
    confirmMsg: "ਕੀ ਤੁਸੀਂ ਯਕੀਨੀ ਹੋ? ਤੁਸੀਂ <b>{0}</b> {1} ਨੂੰ {2} ਕਰਨਾ ਚਾਹੁੰਦੇ ਹੋ?",
    discontinued: "ਬੰਦ (Discontinued)",
    base: "ਬੇਸ (Base)",
    setActive: "ਕਿਰਿਆਸ਼ੀਲ (Active) ਕਰੋ",
    refresh: "ਰਿਫ੍ਰੈਸ਼"
  };

  export default pa;