const ta = {
    login: "உள்நுழையவும்",
    signup: "பதிவு செய்யவும்",
    forgotPassword: "கடவுச்சொல்லை மறந்துவிட்டீர்களா?",
    welcomeUser: "நல்வரவு, பயனரே!",
    logout: "வெளியேறவும்",
    requiredField: "இப்புலம் கட்டாயமானது.",
    invalidEmail: "சரியான மின்னஞ்சல் முகவரியை உள்ளிடவும்.",
    name: "பெயர்",
    fullNamePlaceholder: "உங்கள் பெயரை உள்ளிடவும்",
    firstName: "முதல் பெயர்",
    lastName: "கடைசி பெயர்",
    mobileOrEmail: "மின்னஞ்சல் ஐடி அல்லது மொபைல் எண்",
    firstNamePlaceHolder: "உங்கள் முதல் பெயரை உள்ளிடவும்",
    lastNamePlaceHolder: "உங்கள் கடைசி பெயரை உள்ளிடவும்",
    email: "மின்னஞ்சல்",
    emailPlaceHolder: "உங்கள் மின்னஞ்சலை உள்ளிடவும்",
    mobile: "மொபைல் எண்",
    mobilePlaceHolder: "உங்கள் மொபைல் எண்ணை உள்ளிடவும்",
    receiveOTP: "இந்த OTP-ஐ {0} இல் பெறுவீர்கள்.",
    pleaseWait: "தயவுசெய்து காத்திருக்கவும்...",
    fetchingDataFailedTitle: "கேட்கப்பட்ட தரவைப் பெற முடியவில்லை.",
    failureMessage: "எங்கள் கோரிக்கையைச் செயல்படுத்தும்போது பிழை ஏற்பட்டது.",
    technicalGlitch: "இது தற்காலிக தொழில்நுட்பக் கோளாறால் இருக்கலாம். சிறிது நேரம் கழித்து மீண்டும் முயற்சிக்கவும்.",
    contactSupport: "<a href=\"{supportEmail}\" style=\"text-decoration:none; target=\"_blank\" rel=\"noopener noreferrer\" color: #27c0e0;\">{supportEmail}</a> இல் தொடர்புகொள்ளவும்.",
    register: "பதிவு செய்யவும்",
    registering: "பதிவு செய்யப்படுகிறது....",
    submitOTP: "OTP-ஐ சரிபார்க்கவும்",
    submittingOTP: "OTP சரிபார்க்கப்படுகிறது....",
    otp: "ஓடிபி (OTP)",
    otpPlaceholder: "OTP-ஐ உள்ளிடவும்",
    enterOTP: "தயவுசெய்து ({value})-இல் பெற்ற OTP-ஐ உள்ளிடவும்.",
    signedUp: "நீங்கள் வெற்றிகரமாகப் பதிவு செய்துள்ளீர்கள்!",
    failedToSignUp: "பதிவு செய்ய முடியவில்லை.",
    loggedIn: "நீங்கள் வெற்றிகரமாக உள்நுழைந்துள்ளீர்கள்!",
    failedToLogIn: "உள்நுைய முடியவில்லை.",
    resendOTP: "OTP-ஐ மீண்டும் அனுப்பவும்",
    resendingOTP: "OTP மீண்டும் அனுப்பப்படுகிறது....",
    password: "கடவுச்சொல்",
    logingin: "உள்நுழைகிறது",
    passwordPlaceHolder: "உங்கள் கடவுச்சொல்லை உள்ளிடவும்",
    otpChild1: "OTP தவறாக இருக்கலாம்",
    otpChild2: "OTP காலாவதியாகிவிட்டது.",
    otpChild3: "நெட்வொர்க்கில் சிக்கல் இருக்கலாம்.",
    otpChild4: "சர்வர் டவுனாக இருக்கலாம்",
    passwordRequirementMsg: "உங்கள் கணக்கைப் பாதுகாக்க, குறைந்தது எட்டு (8) எழுத்துகளைக் கொண்ட கடவுச்சொல்லை உருவாக்கவும், இதில் பின்வருபவை இருக்க வேண்டும்",
    passwordRequireMent: "கடவுச்சொல் தேவைகள்",
    upperLowerCase: "பெரிய மற்றும் சிறிய எழுத்துகள்",
    subHeadingIns: "வலுவான கடவுச்சொல்லுக்கு, உங்கள் கடவுச்சொல் பின்வரும் குறிப்புகளைப் பின்பற்ற வேண்டும்",
    minimum8Char: "குறைந்தது 8 எழுத்துகள் (கட்டாயம்)",
    atLeastOneNumericals: "குறைந்தது ஒரு எண் (கட்டாயம்)",
    numericals: "எண்கள்",
    specialChar: "சிறப்பு எழுத்துகள்",
    oneUpperCase: "குறைந்தது ஒரு பெரிய எழுத்து (கட்டாயம்)",
    oneLowerCase: "குறைந்தது ஒரு சிறிய எழுத்து (கட்டாயம்)",
    partnerCompanyName: "கூட்டாளர் நிறுவனத்தின் பெயர்",
    atLeastOneSpecialChar: "குறைந்தது ஒரு சிறப்பு எழுத்து (கட்டாயம்)",
    skip: "தவிர்",
    confirmPassword: "கடவுச்சொல்லை உறுதிப்படுத்தவும்",
    setPassword: "கடவுச்சொல்லை அமைக்கவும்",
    accountInstruction: "கணக்கை அணுகவும் ஆர்டர்களை நிர்வகிக்கவும்",
    aboutUs: "எங்களைப் பற்றி",
    contactUs: "தொடர்புகொள்ள",
    profile: "சுயவிவரம்",
    orders: "ஆர்டர்கள்",
    wishlist: "விருப்பப்பட்டியல்",
    loginSignup: "உள்நுழை/பதிவு செய்",
    welcome: "நல்வரவு",
    profileImgUpdated: "சுயவிவரப் படம் வெற்றிகரமாகப் புதுப்பிக்கப்பட்டது",
    save: "சேமி",
    cancel: "ரத்துசெய்",
    adjustImage: "படத்தைச் சரிசெய்யவும்",
    dragSqrToChangeImgSizePos: "அளவு மற்றும் நிலையை மாற்ற சதுரத்தை இழுக்கவும்.",
    preview: "முன்னோட்டம்",
    imageCropped: "படம் வெற்றிகரமாக கிராப் செய்யப்பட்டது!",
    alternateMobile: "மாற்று மொபைல் எண்",
    male: "ஆண்",
    female: "பெண்",
    others: "மற்றவை",
    genderLabel: "தயவுசெய்து உங்கள் பாலினத்தைத் தேர்ந்தெடுக்கவும்:",
    dob: "பிறந்த தேதி",
    update: "புதுப்பிக்கவும்",
    changePassword: "கடவுச்சொல்லை மாற்றவும்",
    updatePassword: "கடவுச்சொல்லைப் புதுப்பிக்கவும்",
    updateProfile: "சுயவிவரத்தைப் புதுப்பிக்கவும்",
    oldPassword: "பழைய கடவுச்சொல்",
    confirmPasswordNotMatchPassword: "கடவுச்சொல் உறுதிப்படுத்தல் பொருந்தவில்லை.",
    passReqNotFulfil: "கடவுச்சொல் தேவைகள் பூர்த்தி செய்யப்படவில்லை.",
    passwordUpdated: "கடவுச்சொல் வெற்றிகரமாகப் புதுப்பிக்கப்பட்டது!",
    profileUpdated: "சுயவிவரம் வெற்றிகரமாகப் புதுப்பிக்கப்பட்டது!",
    pageNotFound: "பக்கம் கிடைக்கவில்லை",
    brokenLinkMsg1: "நீங்கள் கிளிக் செய்த இணைப்பு உடைந்திருக்கலாம் அல்லது பக்கம் அகற்றப்பட்டிருக்கலாம்.",
    brokenLinkMsg2: "முகப்புப் பக்கத்திற்குச் செல்லவும் அல்லது சிக்கலைப் பற்றி எங்களைத் தொடர்புகொள்ளவும்.",
    backToHome: "முகப்புப் பக்கத்திற்குத் திரும்பு",
    dashboard: "டாஷ்போர்டு",
    pages: "பக்கங்கள்",
    inventory: "சரக்கு (Inventory)",
    customOrders: "தனிப்பயன் ஆர்டர்கள்",
    team: "குழு",
    customers: "வாடிக்கையாளர்கள்",
    settings: "அமைப்புகள்",
    messages: "செய்திகள்",
    pendingOrders: "நிலுவையில் உள்ள ஆர்டர்கள்",
    completedOrders: "முடிந்த ஆர்டர்கள்",
    offers: "சலுகைகள்",
    id: "ஐடி (ID)",
    brand: "பிராண்ட்",
    category: "வகை",
    price: "விலை",
    status: "நிலை",
    createdDate: "உருவாக்கப்பட்ட தேதி",
    updatedDate: "கடைசிப் புதுப்பிப்பு",
    action: "செயல்",
    productName: "தயாரிப்பு பெயர்",
    size: "அளவு",
    color: "நிறம்",
    stockQuantity: "அளவு (Quantity)",
    products: "தயாரிப்புகள்",
    description: "விளக்கம்",
    parent: "மூலம் (Parent)",
    namePlaceholder: "பெயரை உள்ளிடவும்",
    descriptionPlaceholder: "விளக்கத்தை உள்ளிடவும்",
    categoryPlaceholder: "வகையைத் தேர்ந்தெடுக்கவும்",
    categoryLevel: "வகை {0} நிலை",
    at: "இல்",
    modifiedOn: "இல் மாற்றப்பட்டது",
    today: "இன்று",
    edit: "திருத்து",
    delete: "நீக்கு",
    activated: "{entity} செயலில் உள்ளது.",
    deactivated: "{entity} செயலற்ற நிலையில் உள்ளது.",
    yes: "ஆம்",
    no: "இல்லை",
    confirm: "உறுதி செய்",
    deleteMsg: "நிச்சயமாக <b>{0}</b> {1}-ஐ நீக்க விரும்புகிறீர்களா?",
    childrenOf: "இன் குழந்தைகள்",
    page: "பக்கம்",
    add: "சேர்",
    deactivateFirst: "முதலில் {entity}-ஐ செயலற்றதாக்கவும்.",
    activeCantAction: "செயலில் உள்ள {entity}-ஐ {action} செய்ய முடியாது.",
    entityIsActive: "<b>{0}</b> {entity} செயலில் உள்ளது.",
    searchPlaceHolder: "{entity}-ஐத் தேடு...",
    copy: "நகலெடு",
    deleted: "நீக்கப்பட்டது",
    edited: "திருத்தப்பட்டது",
    product: "தயாரிப்பு",
    title: "தலைப்பு",
    titlePlaceholder: "தலைப்பை உள்ளிடவும்",
    image: "படம்",
    material: "பொருள்",
    materialPlaceholder: "பொருளை உள்ளிடவும்",
    colorPlaceholder: "நிறத்தை உள்ளிடவும்",
    sku: "SKU குறியீடு",
    skuPlaceholder: "தனித்துவமான SKU குறியீட்டை உள்ளிடவும்",
    quantity: "எண்ணிக்கை",
    type: "வகை",
    selectProductPlaceholder: "தயாரிப்பைத் தேர்ந்தெடுக்கவும்",
    sizeChart: "அளவு விளக்கப்படம்",
    enterMeasure: "உங்கள் {0} அளவை உள்ளிடவும்",
    chest: "மார்பு",
    hips: "இடுப்பு",
    neck: "கழுத்து",
    sleeve: "கை (Sleeve)",
    arm: "கை (Arm)",
    topLength: "மேல் நீளம்",
    shoulder: "தோள்பட்டை",
    inseam: "இன்சீம் (Inseam)",
    bottomLength: "கீழ் நீளம்",
    thigh: "தொடை",
    waist: "இடுப்பு",
    topBody: "மேல் உடல்",
    bottomBody: "கீழ் உடல்",
    rank: "ரேங்க்",
    sale: "விற்பனை",
    rental: "வாடகை",
    selectRankPlaceholder: "ரேங்க்கைத் தேர்ந்தெடுக்கவும்",
    mrp: "எம்ஆர்பி (MRP)",
    salePrice: "விற்பனை விலை",
    discount: "தள்ளுபடி",
    selectSizePlaceholder: "அளவைத் தேர்ந்தெடுக்கவும்",
    mrpPlaceholder: "எம்ஆர்பியை உள்ளிடவும் (₹)",
    salePricePlaceholder: "விற்பனை விலையை உள்ளிடவும் (₹)",
    discountPlaceholder: "தள்ளுபடியை உள்ளிடவும் (%)",
    quantityPlaceholder: "எண்ணிக்கையை உள்ளிடவும்",
    saleOrRentPrice: "விற்பனை/வாடகை விலை",
    security: "பாதுகாப்பு வைப்புத்தொகை",
    securityPlaceholder: "திரும்பப் பெறுவது = வைப்புத்தொகை - (வாடகை விலை - தள்ளுபடி %)",
    size_Quant_Price: "அளவு - எண்ணிக்கை - விற்பனை விலை",
    view: "பார்",
    webSettings: "இணையதள அமைப்புகள்",
    siteUnderMaintenance: "தளம் பராமரிப்பில் உள்ளது",
    weWillGetbackShortly: "நாங்கள் விரைவில் திரும்புவோம். தயவுசெய்து சிறிது நேரம் கழித்துச் சரிபார்க்கவும்.",
    reload: "மீண்டும் ஏற்று",
    enableWebsite: "இணையதளத்தை இயக்க/முடக்க கிளிக் செய்யவும்.",
    website: "இணையதளம்",
    switchOnOffWebsite: "இணையதளத்தை ஆன்/ஆஃப் செய்யவும்",
    webConfigs: "இணையதள உள்ளமைவு",
    webTrendingBar: "இணையதள டிரெண்டிங் பார்",
    websiteId: "இணையதள ஐடி",
    path: "பாதை (Path)",
    pathPlaceholder: "திறக்க வேண்டிய பாதையை உள்ளிடவும்",
    homePage: "முகப்புப் பக்கம்",
    PageCarousel: "முகப்புப் பக்க கேலரி",
    forPC: "கணினிக்கு:",
    forMobile: "மொபைலுக்கு:",
    reset: "மீட்டமை",
    customFitting: "தனிப்பயன் பொருத்தம்",
    customDesigning: "தனிப்பயன் வடிவமைப்பு",
    freeDelivery: "இலவச டெலிவரி",
    assuredRefunds: "உறுதியான பணம் திரும்பப் பெறுதல்",
    sizes: "அளவுகள்",
    addresses: "முகவரிகள்",
    isTileVisible: "டைல் தெரிகிறதா?",
    isTileVisibleGrid: "டைல் தெரிகிறது",
    categories: "வகைகள்",
    mrpWithDots: "எம்.ஆர்.பி",
    rtd: "உடனடி டெலிவரி",
    inclusiveTax: "அனைத்து வரிகளும் உட்பட விலை",
    rentInclusiveTax: "வாடகையில் வரி அடங்கும்",
    purchase: "வாங்கு",
    rent: "வாடகை",
    refundableSecurity: "திரும்பப் பெறக்கூடிய பாதுகாப்பு வைப்புத்தொகை",
    securityDeposit: "பாதுகாப்பு வைப்புத்தொகை",
    refundSecurity: "பொருட்களைத் திருப்பியளித்த பிறகு உங்கள் பாதுகாப்பு வைப்புத்தொகை திரும்பப் வழங்கப்படும்.",
    securityDepositDeduction: "டெலிவரி செய்யப்பட்ட 5 நாட்களுக்குள் பொருட்களைத் திருப்பியளிக்கலாம். அதன்பிறகு ஒவ்வொரு 5 நாட்களுக்கும் வாடகைத் தொகை பாதுகாப்பு வைப்புத்தொகையிலிருந்து கழிக்கப்படும்.",
    sizeGuide: "அளவு வழிகாட்டி",
    customSize: "தனிப்பயன் அளவு",
    loginToAddCustomSize: "தனிப்பயன் அளவைச் சேர்க்க மற்றும் பார்க்க உள்நுழையவும்/பதிவு செய்யவும்",
    yourCustomSizes: "உங்கள் தனிப்பயன் அளவுகள்",
    undoWishlistMsg: "விருப்பப்பட்டியலிலிருந்து <b>{name}</b>-ஐ நீக்கிவிட்டீர்கள்",
    undo: "தவிர் (Undo)",
    textPlaceholder: "{0}-ஐ உள்ளிடவும்",
    address: "முகவரி",
    fullName: "பெயர்",
    city: "நகரம்",
    country: "நாடு",
    pinCode: "அஞ்சல் குறியீடு",
    state: "மாநிலம்",
    landmark: "லேண்ட்மார்க்",
    streetAddress1: "பிளாட், வீட்டு எண், கட்டிடம், நிறுவனம், அபார்ட்மெண்ட்",
    streetAddress2: "பகுதி, தெரு, செக்டர், கிராமம்",
    defaultAddress: "இயல்புநிலை முகவரியாக அமை",
    setDefault: "இயல்புநிலையாக அமை",
    default: "இயல்புநிலை",
    addToCart: "கார்ட்டில் சேர்",
    buyNow: "இப்போதே வாங்கு",
    total: "மொத்தம்",
    clearCart: "கார்ட்டைச் சுத்தம் செய்",
    proceedToCheckout: "செக்அவுட்டிற்குச் செல்",
    shoppingCart: "ஷாப்பிங் கார்ட்",
    loadingCart: "கார்ட் ஏற்றப்படுகிறது...",
    emptyCart: "உங்கள் கார்ட் காலியாக உள்ளது.",
    emptyWishlist: "உங்கள் விருப்பப்பட்டியல் காலியாக உள்ளது.",
    deSelectAll: "அனைத்தையும் தேர்வுநீக்கு",
    invalidCoupon: "செல்லாத கூப்பன் குறியீடு",
    couponApplied: "கூப்பன் பயன்படுத்தப்பட்டது: ",
    apply: "பயன்படுத்து",
    freeCaps: "இலவசம்",
    deliveryCharges: "டெலிவரி கட்டணம்",
    subTotal: "கூடுதல் மொத்தம்",
    changeSize: "அளவை மாற்று",
    moveToWishlist: "விருப்பப்பட்டியலுக்கு மாற்று",
    share: "பகிர்",
    orderSummary: "ஆர்டர் சுருக்கம்",
    coupon: "கூப்பன்",
    itemsForPurchasing: "வாங்குவதற்குத் தேர்ந்தெடுக்கப்பட்ட பொருட்கள்",
    itemsForRenting: "வாடகைக்குத் தேர்ந்தெடுக்கப்பட்ட பொருட்கள்",
    itemsSelected: "தேர்ந்தெடுக்கப்பட்ட பொருட்கள்",
    applyCoupon: "கூப்பனைப் பயன்படுத்து",
    undoCartMsg: 'கார்ட்டிலிருந்து <strong>{name}</strong> நீக்கப்பட்டது. ',
    itemRestored: "பொருள் மீண்டும் கார்ட்டில் சேர்க்கப்பட்டது",
    selectAll: "அனைத்தையும் தேர்ந்தெடு",
    itemMovedToWishlist: "பொருள் விருப்பப்பட்டியலுக்கு மாற்றப்பட்டது.",
    itemRemoved: "பொருள் நீக்கப்பட்டது",
    addedToCart: "பொருள் கார்ட்டில் சேர்க்கப்பட்டது",
    itemAddedToWishlist: "பொருள் விருப்பப்பட்டியலில் சேர்க்கப்பட்டது",
    itemRemovedFromWishlist: "பொருள் விருப்பப்பட்டியலிலிருந்து நீக்கப்பட்டது",
    proceedToBuy: "வாங்குவதற்குத் தொடரவும்",
    change: "மாற்று",
    checkout: "செக்அவுட்",
    deliverHere: "இங்கே டெலிவரி செய்யவும்",
    selectDeliveryAddress: "டெலிவரி முகவரியைத் தேர்ந்தெடுக்கவும்",
    selectedDeliveryAddress: "தேர்ந்தெடுக்கப்பட்ட டெலிவரி முகவரி",
    inventoryType: "சரக்கு வகை",
    currentlyDefaultAddress: "இயல்புநிலை முகவரி",
    chosenAddressUpdated: "தேர்ந்தெடுக்கப்பட்ட முகவரி வெற்றிகரமாகப் புதுப்பிக்கப்பட்டது.",
    draftUpdated: "ஆர்டர் விவரங்கள் வெற்றிகரமாகப் புதுப்பிக்கப்பட்டன.",
    deliveringTo: "டெலிவரி செய்யப்படுகிறது",
    addNew: "புதியதைச் சேர்",
    itemsInOrder: "ஆர்டரில் உள்ள பொருட்கள்",
    shipTogether: "அனைத்து பொருட்களையும் ஒன்றாக அனுப்பு",
    shipAsap: "ஒவ்வொரு பொருளும் தயாரானதும் அனுப்பு",
    shipItems: "உங்கள் ஆர்டர் பொருட்களை எப்போது அனுப்ப விரும்புகிறீர்கள்?",
    shipItemsForOrder: "{user} தனது ஆர்டர் பொருட்களை எப்போது அனுப்ப விரும்புகிறார்?",
    orderPlacedTitle: "நன்றி, உங்கள் ஆர்டர் வெற்றிகரமாகச் செய்யப்பட்டது!",
    orderConfirmationSent: "உங்கள் மின்னஞ்சலுக்கு உறுதிப்படுத்தல் அனுப்பப்பட்டுள்ளது.",
    orderId: "ஆர்டர் ஐடி",
    itemsInTheOrder: "ஆர்டரில் உள்ள பொருட்கள்",
    viewOrders: "உங்கள் ஆர்டர்களைப் பார்",
    viewAllOrders: "அனைத்து ஆர்டர்களையும் பார்",
    continueShopping: "ஷாப்பிங்கைத் தொடரவும்",
    orderDetails: "ஆர்டர் விவரங்கள்",
    appliedCoupon: "பயன்படுத்தப்பட்ட கூப்பன்",
    orderPlacedOn: "ஆர்டர் செய்யப்பட்ட தேதி",
    shipTo: "ஷிப் டு",
    noOrdersFound: "ஆர்டர்கள் எதுவும் இல்லை",
    yourOrders: "உங்கள் ஆர்டர்கள்",
    paymentMode: "கட்டண முறை",
    paymentMethod: "கட்டண வழிமுறை",
    all: "அனைத்தும்",
    pending: "நிலுவையில்",
    shipped: "அனுப்பப்பட்டது",
    delivered: "டெலிவரி செய்யப்பட்டது",
    cancelled: "ரத்துசெய்யப்பட்டது",
    allOrders: "அனைத்து ஆர்டர்கள்",
    newOrders: "புதிய ஆர்டர்கள்",
    statusMessages: {
      forOrder: {
        forManager: {
          draft: "ஆர்டர் வரைவு நிலையில் உள்ளது, இன்னும் செய்யப்படவில்லை.",
          pending: "கட்டணம் நிலுவையில் உள்ளது.",
          placed: "ஆர்டர் செய்யப்பட்டுள்ளது மற்றும் உங்கள் உறுதிப்படுத்தலுக்காகக் காத்திருக்கிறது.",
          confirmed: "நீங்கள் ஆர்டரை உறுதிப்படுத்திவிட்டீர்கள்.",
          payment_failed: "கட்டணம் தோல்வியடைந்தது.",
          in_process: "ஆர்டர் உங்களால் செயல்படுத்தப்படுகிறது.",
          ready_to_dispatch: "ஆர்டர் அனுப்பத் தயாராக உள்ளது.",
          shipped: "ஆர்டர் அனுப்பப்பட்டது.",
          in_transit: "ஆர்டர் வழியில் உள்ளது.",
          delivered: "ஆர்டர் டெலிவரி செய்யப்பட்டது.",
          cancelled: "ஆர்டர் ரத்துசெய்யப்பட்டது.",
          cancellation_requested: "பயனர் ஆர்டரை ரத்துசெய்யக் கோரியுள்ளார்.",
          cancellation_rejected: "நீங்கள் ரத்துசெய்தல் கோரிக்கையை நிராகரித்தீர்கள்.",
          cancellation_refunded: "ஆர்டர் ரத்துசெய்யப்பட்டது மற்றும் பணம் திரும்பப் வழங்கப்பட்டது.",
          return_requested: "திருப்பி அனுப்புவதற்கான கோரிக்கை வந்துள்ளது.",
          return_rejected: "திருப்பி அனுப்பும் கோரிக்கை நிராகரிக்கப்பட்டது.",
          returned: "ஆர்டர் திருப்பி அனுப்பப்பட்டது.",
          return_refunded: "திரும்பிய பிறகு பணம் திரும்பப் வழங்கப்பட்டது.",
          refunded: "பணம் திரும்பப் வழங்கப்பட்டது.",
          rto_requested: "உங்களால் RTO கோரப்பட்டது.",
          rto_rejected: "நீங்கள் RTO கோரிக்கையை நிராகரித்தீர்கள்.",
          rto_approved: "நீங்கள் RTO கோரிக்கையை ஏற்றுக்கொண்டீர்கள்.",
          rto_in_progress: "RTO செயல்முறையில் உள்ளது.",
          rto_delivered: "RTO மூலம் ஆர்டர் உங்களுக்குத் திருப்பி அனுப்பப்பட்டது.",
          rto_verified: "RTO பொருள் சரிபார்க்கப்பட்டது.",
          rto_refunded: "RTO-க்குப் பிறகு பணம் திரும்பப் வழங்கப்பட்டது."
        },
        forUser: {
          draft: "உங்கள் ஆர்டர் செக்அவுட்டில் உள்ளது, இன்னும் செய்யப்படவில்லை.",
          pending: "கட்டணம் நிலுவையில் உள்ளது. தயவுசெய்து முடிக்கவும்.",
          placed: "உங்கள் ஆர்டர் செய்யப்பட்டுள்ளது மற்றும் உறுதிப்படுத்தலுக்காகக் காத்திருக்கிறது.",
          confirmed: "உங்கள் ஆர்டர் விற்பனையாளரால் உறுதிப்படுத்தப்பட்டது.",
          payment_failed: "கட்டணம் தோல்வியடைந்தது. மீண்டும் முயற்சிக்கவும்.",
          in_process: "உங்கள் ஆர்டர் விற்பனையாளரால் செயல்படுத்தப்படுகிறது.",
          ready_to_dispatch: "உங்கள் ஆர்டர் அனுப்பத் தயாராக உள்ளது.",
          shipped: "உங்கள் ஆர்டர் அனுப்பப்பட்டது.",
          in_transit: "உங்கள் ஆர்டர் வழியில் உள்ளது.",
          delivered: "உங்கள் ஆர்டர் டெலிவரி செய்யப்பட்டது.",
          cancelled: "உங்கள் ஆர்டர் ரத்துசெய்யப்பட்டது.",
          cancellation_requested: "நீங்கள் ஆர்டரை ரத்துசெய்யக் கோரினீர்கள்.",
          cancellation_rejected: "உங்கள் ரத்துசெய்தல் கோரிக்கை நிராகரிக்கப்பட்டது.",
          cancellation_refunded: "உங்கள் ஆர்டர் ரத்துசெய்யப்பட்டது மற்றும் பணம் திரும்பப் வழங்கப்பட்டது.",
          return_requested: "உங்கள் ஆர்டருக்கான வருவாய் கோரப்பட்டது.",
          return_rejected: "வருவாய் கோரிக்கை நிராகரிக்கப்பட்டது.",
          returned: "உங்கள் ஆர்டர் திருப்பி அனுப்பப்பட்டது.",
          return_refunded: "திரும்பிய பிறகு உங்கள் பணம் திரும்பப் வழங்கப்பட்டது.",
          refunded: "பணம் திரும்பப் வழங்கப்பட்டது.",
          rto_requested: "உங்கள் ஆர்டருக்கு RTO கோரப்பட்டது.",
          rto_rejected: "RTO கோரிக்கை நிராகரிக்கப்பட்டது.",
          rto_approved: "RTO கோரிக்கை ஏற்றுக்கொள்ளப்பட்டது.",
          rto_in_progress: "RTO செயல்முறையில் உள்ளது.",
          rto_delivered: "RTO மூலம் ஆர்டர் திருப்பி அனுப்பப்பட்டது.",
          rto_verified: "RTO பொருள் உறுதிப்படுத்தப்பட்டது.",
          rto_refunded: "RTO-க்குப் பிறகு பணம் திரும்பப் வழங்கப்பட்டது."
        }
      },
      forItem: {
        forManager: {
          draft: "பொருள் ஆர்டர் வரைவில் சேர்க்கப்பட்டுள்ளது, இன்னும் செய்யப்படவில்லை.",
          pending: "இப்பொருளுக்கான கட்டணம் நிலுவையில் உள்ளது.",
          placed: "பொருள் செய்யப்பட்டுள்ளது மற்றும் உங்கள் உறுதிப்படுத்தலுக்காகக் காத்திருக்கிறது.",
          confirmed: "நீங்கள் பொருளை உறுதிப்படுத்திவிட்டீர்கள்.",
          payment_failed: "இப்பொருளுக்கான கட்டணம் தோல்வியடைந்தது.",
          in_process: "பொருள் செயல்படுத்தப்படுகிறது.",
          ready_to_dispatch: "பொருள் அனுப்பத் தயாராக உள்ளது.",
          shipped: "பொருள் அனுப்பப்பட்டது.",
          in_transit: "பொருள் வழியில் உள்ளது.",
          delivered: "பொருள் டெலிவரி செய்யப்பட்டது.",
          cancelled: "பொருள் ரத்துசெய்யப்பட்டது.",
          cancellation_requested: "இப்பொருளுக்கு பயனர் ரத்துசெய்யக் கோரியுள்ளார்.",
          cancellation_rejected: "ரத்துசெய்தல் கோரிக்கை நிராகரிக்கப்பட்டது.",
          cancellation_refunded: "பணம் திரும்பப் வழங்கப்பட்டது.",
          return_requested: "திருப்பி அனுப்பும் கோரிக்கை வந்துள்ளது.",
          return_rejected: "திருப்பி அனுப்பும் கோரிக்கை நிராகரிக்கப்பட்டது.",
          returned: "பொருள் திருப்பி அனுப்பப்பட்டது.",
          return_refunded: "பணம் திரும்பப் வழங்கப்பட்டது.",
          refunded: "பணம் திரும்பப் வழங்கப்பட்டது.",
          rto_requested: "RTO கோரப்பட்டது.",
          rto_rejected: "RTO கோரிக்கை நிராகரிக்கப்பட்டது.",
          rto_approved: "RTO கோரிக்கை ஏற்றுக்கொள்ளப்பட்டது.",
          rto_in_progress: "RTO செயல்முறையில் உள்ளது.",
          rto_delivered: "RTO மூலம் பொருள் திருப்பி அனுப்பப்பட்டது.",
          rto_verified: "RTO பொருள் உறுதிப்படுத்தப்பட்டது.",
          rto_refunded: "RTO-க்குப் பிறகு பணம் திரும்பப் வழங்கப்பட்டது."
        },
        forUser: {
          draft: "இப்பொருள் செக்அவுட்டில் உள்ளது, இன்னும் செய்யப்படவில்லை.",
          pending: "இப்பொருளுக்கான கட்டணம் நிலுவையில் உள்ளது. தயவுசெய்து முடிக்கவும்.",
          placed: "இப்பொருள் செய்யப்பட்டுள்ளது மற்றும் உறுதிப்படுத்தலுக்காகக் காத்திருக்கிறது.",
          confirmed: "இப்பொருள் விற்பனையாளரால் உறுதிப்படுத்தப்பட்டது.",
          payment_failed: "இப்பொருளுக்கான கட்டணம் தோல்வியடைந்தது.",
          in_process: "பொருள் விற்பனையாளரால் செயல்படுத்தப்படுகிறது.",
          ready_to_dispatch: "பொருள் அனுப்பத் தயாராக உள்ளது.",
          shipped: "பொருள் அனுப்பப்பட்டது.",
          in_transit: "பொருள் வழியில் உள்ளது.",
          delivered: "பொருள் டெலிவரி செய்யப்பட்டது.",
          cancelled: "பொருள் ரத்துசெய்யப்பட்டது.",
          cancellation_requested: "நீங்கள் இப்பொருளை ரத்துசெய்யக் கோரினீர்கள்.",
          cancellation_rejected: "ரத்துசெய்தல் கோரிக்கை நிராகரிக்கப்பட்டது.",
          cancellation_refunded: "பணம் திரும்பப் வழங்கப்பட்டது.",
          return_requested: "திருப்பி அனுப்பும் கோரிக்கை கோரப்பட்டது.",
          return_rejected: "திருப்பி அனுப்பும் கோரிக்கை நிராகரிக்கப்பட்டது.",
          returned: "பொருள் திருப்பி அனுப்பப்பட்டது.",
          return_refunded: "பணம் திரும்பப் வழங்கப்பட்டது.",
          refunded: "பணம் திரும்பப் வழங்கப்பட்டது.",
          rto_requested: "RTO கோரப்பட்டது.",
          rto_rejected: "RTO கோரிக்கை நிராகரிக்கப்பட்டது.",
          rto_approved: "RTO கோரிக்கை ஏற்றுக்கொள்ளப்பட்டது.",
          rto_in_progress: "RTO செயல்முறையில் உள்ளது.",
          rto_delivered: "RTO மூலம் பொருள் திருப்பி அனுப்பப்பட்டது.",
          rto_verified: "RTO பொருள் உறுதிப்படுத்தப்பட்டது.",
          rto_refunded: "RTO-க்குப் பிறகு பணம் திரும்பப் வழங்கப்பட்டது."
        }
      }
    },
    statusColors: {
      draft: "var(--secondarytext-color)",
      pending: "var(--warning-color)",
      placed: "var(--info-color)",
      confirmed: "var(--success-color)",
      payment_failed: "var(--danger-color)",
      in_process: "var(--infolight-color)",
      ready_to_dispatch: "purple",
      shipped: "blue",
      in_transit: "var(--primarylight-color)",
      delivered: "var(--successdark-color)",
      cancellation_requested: "orange",
      cancelled: "var(--dangerlight-color)",
      cancellation_rejected: "red",
      cancellation_refunded: "var(--success-color)",
      return_requested: "var(--secondary-color)",
      returned: "var(--dangerlight-color)",
      return_rejected: "var(--warning-color)",
      return_refunded: "var(--success-color)",
      refunded: "var(--success-color)",
      rto_requested: "var(--warningdark-color)",
      rto_rejected: "red",
      rto_approved: "var(--success-color)",
      rto_in_progress: "blueviolet",
      rto_delivered: "var(--info-color)",
      rto_verified: "var(--successdark-color)",
      rto_refunded: "var(--success-color)"
    },
    orderPages: {
      allOrders: {
        title: "அனைத்து ஆர்டர்கள்",
        statuses: ["ALL"]
      },
      pendingOrders: {
        title: "நிலுவையில் உள்ள ஆர்டர்கள்",
        statuses: ["PENDING"]
      },
      newOrders: {
        title: "புதிய ஆர்டர்கள்",
        statuses: ["PLACED"]
      },
      confirmedOrders: {
        title: "உறுதிப்படுத்தப்பட்ட ஆர்டர்கள்",
        statuses: ["CONFIRMED"]
      },
      processingOrders: {
        title: "செயலாக்க ஆர்டர்கள்",
        statuses: ["IN_PROCESS"]
      },
      readyToDispatchOrders: {
        title: "அனுப்பத் தயாராக உள்ளது",
        statuses: ["READY_TO_DISPATCH"]
      },
      onTheWayOrders: {
        title: "வழியில் உள்ள ஆர்டர்கள்",
        statuses: ["SHIPPED", "IN_TRANSIT"]
      },
      deliveredOrders: {
        title: "டெலிவரி செய்யப்பட்ட ஆர்டர்கள்",
        statuses: ["DELIVERED"]
      },
      cancelled: {
        title: "ரத்துசெய்யப்பட்ட ஆர்டர்கள்",
        statuses: ["CANCELLED"]
      },
      returns: {
        title: "ரிட்டர்ன்ஸ்",
        statuses: ["ALLRETURNS"],
        showOrderStatuses: false
      },
      cancellation_requested: {
        title: "ரத்துசெய்தல் கோரப்பட்டது",
        statuses: ["CANCELLATION_REQUESTED"]
      },
      cancellation_rejected: {
        title: "ரத்துசெய்தல் நிராகரிக்கப்பட்டது",
        statuses: ["CANCELLATION_REJECTED"]
      },
      cancellation_refunded: {
        title: "ரத்துசெய்தல் திரும்பப் பெறப்பட்டது",
        statuses: ["CANCELLATION_REFUNDED"]
      },
      return_requested: {
        title: "வருவாய் கோரப்பட்டது",
        statuses: ["RETURN_REQUESTED"]
      },
      returned: {
        title: "திருப்பி அனுப்பப்பட்ட ஆர்டர்கள்",
        statuses: ["RETURNED"]
      },
      return_rejected: {
        title: "வருவாய் நிராகரிக்கப்பட்டது",
        statuses: ["RETURN_REJECTED"]
      },
      return_refunded: {
        title: "வருவாய் திரும்பப் பெறப்பட்டது",
        statuses: ["RETURN_REFUNDED"]
      },
      rto_requested: {
        title: "RTO கோரப்பட்டது",
        statuses: ["RTO_REQUESTED"]
      },
      rto_rejected: {
        title: "RTO நிராகரிக்கப்பட்டது",
        statuses: ["RTO_REJECTED"]
      },
      rto_approved: {
        title: "RTO அங்கீகரிக்கப்பட்டது",
        statuses: ["RTO_APPROVED"]
      },
      rto_in_progress: {
        title: "RTO செயலில் உள்ளது",
        statuses: ["RTO_IN_PROGRESS"]
      },
      rto_delivered: {
        title: "RTO டெலிவரி செய்யப்பட்டது",
        statuses: ["RTO_DELIVERED"]
      },
      rto_verified: {
        title: "RTO சரிபார்க்கப்பட்டது",
        statuses: ["RTO_VERIFIED"]
      },
      rto_refunded: {
        title: "RTO திரும்பப் பெறப்பட்டது",
        statuses: ["RTO_REFUNDED"]
      }
    },
    confirmedOrders: "உறுதிப்படுத்தப்பட்ட ஆர்டர்கள்",
    processingOrders: "செயலாக்க ஆர்டர்கள்",
    readyToDispatchOrders: "அனுப்பத் தயாராக உள்ள ஆர்டர்கள்",
    onTheWayOrders: "வழியில் உள்ள ஆர்டர்கள்",
    deliveredOrders: "டெலிவரி செய்யப்பட்ட ஆர்டர்கள்",
    cancelled_orders: "ரத்துசெய்யப்பட்ட ஆர்டர்கள்",
    cancellation_requested_orders: "ரத்துசெய்யக் கோரப்பட்ட ஆர்டர்கள்",
    return_requested_orders: "வருவாய் கோரப்பட்ட ஆர்டர்கள்",
    return_refunded_orders: "வருவாய் திரும்பப் பெறப்பட்ட ஆர்டர்கள்",
    returns: "ரிட்டர்ன்ஸ்",
    returned_orders: "திருப்பி அனுப்பப்பட்ட ஆர்டர்கள்",
    return_rejected_orders: "வருவாய் நிராகரிக்கப்பட்ட ஆர்டர்கள்",
    cancellation_rejected_orders: "ரத்துசெய்தல் நிராகரிக்கப்பட்ட ஆர்டர்கள்",
    cancellation_refunded_orders: "ரத்துசெய்தல் திரும்பப் பெறப்பட்ட ஆர்டர்கள்",
    rto_requested_orders: "RTO கோரப்பட்ட ஆர்டர்கள்",
    rto_rejected_orders: "RTO நிராகரிக்கப்பட்ட ஆர்டர்கள்",
    rto_approved_orders: "RTO அங்கீகரிக்கப்பட்ட ஆர்டர்கள்",
    rto_in_progress_orders: "RTO செயலில் உள்ள ஆர்டர்கள்",
    rto_delivered_orders: "RTO டெலிவரி செய்யப்பட்ட ஆர்டர்கள்",
    rto_verified_orders: "RTO சரிபார்க்கப்பட்ட ஆர்டர்கள்",
    rto_refunded_orders: "RTO திரும்பப் பெறப்பட்ட ஆர்டர்கள்",
    moreOptions: "கூடுதல் விருப்பங்கள்",
    details: "விவரங்கள்",
    viewProductPage: "தயாரிப்பு பக்கத்தைப் பார்",
    viewSize: "அளவைப் பார்",
    trackStatus: "நிலையைத் தடமறி",
    auditTrail: "தணிக்கை பாதை",
    changedFrom: "இதிலிருந்து மாற்றப்பட்டது",
    changedTo: "இதற்கு மாற்றப்பட்டது",
    entityType: "நிறுவன வகை",
    entityId: "நிறுவன ஐடி",
    performedBy: "செயல்படுத்தியவர்",
    timestamp: "நேர முத்திரை",
    trackingDetails: "தடமறிதல் விவரங்கள்",
    noDetailsFound: "விவரங்கள் எதுவும் இல்லை",
    userDetails: "பயனர் விவரங்கள்",
    followUs: "எங்களைப் பின்தொடரவும்",
    allRightsReserved: "அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை",
    fastAndSecured: "வேகமான மற்றும் பாதுகாப்பான கட்டண விருப்பங்கள்",
    company: "நிறுவனம்",
    myAccount: "என் கணக்கு",
    home: "முகப்புப் பக்கம்",
    account: "கணக்கு",
    search: "தேடு",
    cart: "கார்ட்",
    language: "மொழி",
    somethingWentWrong: "ஏதோ தவறு நடந்துவிட்டது!",
    note: "குறிப்பு",
    notAllowed1: "இந்த செயலியில் உள்நுழைய உங்களுக்கு அனுமதி இல்லை",
    notAllowed2: "நிர்வாகி (Admin) மற்றும் மேலாளருக்கு (Manager) மட்டுமே அணுகல் உள்ளது",
    notAllowed3: "நீங்கள் இவர்களில் ஒருவராக இருந்தும் அணுக முடியவில்லை என்றால் நிர்வாகியைத் தொடர்புகொள்ளவும்",
    logOutAndBackToHome: "வெளியேறி முகப்புக்குச் செல்",
    whatsAppUs: "வாட்ஸ்அப் செய்யவும்",
    ourContactDetails: "எங்கள் தொடர்பு விவரங்கள்",
    workingHours: "வேலை நேரம்",
    instagram: "இன்ஸ்டாகிராம்",
    facebook: "பேஸ்புக்",
    x: "எக்ஸ் (ட்விட்டர்)",
    threads: "த்ரெட்ஸ்",
    youtube: "யூடியூப்",
    pinterest: "பின்ட்ரெஸ்ட்",
    quotaUsage: "மெயில்/எஸ்எம்எஸ் ஒதுக்கீட்டுப் பயன்பாடு",
    used: "பயன்படுத்தப்பட்டது",
    remaining: "மீதமுள்ளது",
    totalQuota: "மொத்த ஒதுக்கீடு",
    sms: "எஸ்எம்எஸ் (SMS)",
    whatsapp: "வாட்ஸ்அப்",
    brevo: "ப்ரெவோ (Brevo)",
    count: "எண்ணிக்கை",
    date: "தேதி",
    gmail: "ஜிமெயில்",
    quota: "ஒதுக்கீடு",
    teamUsers: "குழு",
    member: "உறுப்பினர்",
    customer: "வாடிக்கையாளர்",
    profileImage: "சுயவிவரப் படம்",
    gender: "பாலினம்",
    role: "பங்கு (Role)",
    activatedText: "செயலில்",
    selectRolePlaceholder: "பங்கைத் தேர்ந்தெடுக்கவும்",
    accountActiveLabel: "பயனர் கணக்கு செயலில்/செயலற்ற நிலையில் இருக்க வேண்டுமா என்பதைத் தேர்ந்தெடுக்கவும்:",
    user: "பயனர்",
    actions: "செயல்கள்",
    setAsDiscontinued: "நிறுத்தப்பட்டதாக (Discontinued) அமை",
    resetToDefaultPassword: "இயல்புநிலை கடவுச்சொல்லுக்கு மீட்டமை",
    confirmMsg: "நிச்சயமாகவா? <b>{0}</b> {1}-ஐ {2} செய்ய விரும்புகிறீர்களா?",
    discontinued: "நிறுத்தப்பட்டது (Discontinued)",
    base: "அடித்தளம் (Base)",
    setActive: "செயல்படுத்து (Active)",
    refresh: "புதுப்பி",
    about: "என்னை பற்றி",
    resume: "ரெஸ்யூம்",
    portfolio: "போர்ட்ஃபோலியோ",
    services: "சேவைகள்",
    contact: "தொடர்பு",
    contactMe: "என்னை தொடர்பு கொள்ளுங்கள்",
    birthday: "பிறந்தநாள்",
    age: "வயது",
    degree: "பட்டம்",
    freelance: "ஃப்ரீலான்ஸ்",
    available: "கிடைக்கும்",
    education: "கல்வி",
    projects: "திட்டங்கள்",
    languages: "மொழிகள்",
    accountInstruction1: "உங்கள் விவரங்களை நிர்வகிக்கவும்",
    aboutDesc: "என்னை பற்றி மேலும் அறிக",
    resumeDesc: "என் தொழில்முறை அனுபவம் மற்றும் கல்வி காலவரிசை:",
    summary: "சுருக்கம்",
    professionalExperience: "தொழில்முறை அனுபவம்",
    servicesDesc: "நான் வழங்கும் தொழில்நுட்ப சேவைகள்:",
    skillsDesc: "என் தொழில்நுட்ப திறன்கள்:",
    portfolioDesc: "என் சமீபத்திய திட்டங்கள்:",
    app: "அப்",
    web: "வலை",
    branding: "பிராண்டிங்",
    books: "புத்தகங்கள்",
    contactDesc: "ஒத்துழைப்பிற்காக தொடர்பு கொள்ளவும்",
    callUs: "எங்களை அழைக்கவும்",
    emailUs: "எங்களுக்கு மின்னஞ்சல் செய்யவும்",
    yourName: "உங்கள் பெயர்",
    yourEmail: "உங்கள் மின்னஞ்சல்",
    subject: "பொருள்",
    message: "செய்தி",
    sendMessage: "செய்தி அனுப்பு",
    messageSent: "உங்கள் செய்தி அனுப்பப்பட்டது. நன்றி!",
    dobShort: "பி.தேதி",
    toolsTitle: "நான் பயன்படுத்தும் கருவிகள் மற்றும் தொழில்நுட்பங்கள்",
    iM: "நான்",
    viewDetails: "விவரங்கள் பார்க்க",
    zoom: "ஜூம்",
    sendingMessage: "செய்தி அனுப்பப்படுகிறது...",
    messageFailed: "செய்தியை அனுப்ப முடியவில்லை. தயவுசெய்து பின்னர் முயற்சிக்கவும்.",
    networkError: "நெட்வொர்க் பிழை ஏற்பட்டது. உங்கள் இணைப்பை சரிபார்க்கவும்.",
    sending: "அனுப்பப்படுகிறது..."
  

  };

export default ta;