const te = {
    login: "లాగిన్",
    signup: "సైన్ అప్",
    forgotPassword: "పాస్‌వర్డ్ మర్చిపోయారా?",
    welcome: "స్వాగతం, వినియోగదారు!",
    logout: "లాగ్ అవుట్",
    requiredField: "ఈ ఫీల్డ్ తప్పనిసరి.",
    invalidEmail: "దయచేసి సరైన ఇమెయిల్ చిరునామాను నమోదు చేయండి.",
    name: "పేరు",
    fullNamePlaceholder: "మీ పేరును నమోదు చేయండి",
    firstName: "మొదటి పేరు",
    lastName: "చివరి పేరు",
    mobileOrEmail: "ఇమెయిల్ ఐడి లేదా మొబైల్ నంబర్",
    firstNamePlaceHolder: "మీ మొదటి పేరును నమోదు చేయండి",
    lastNamePlaceHolder: "మీ చివరి పేరును నమోదు చేయండి",
    email: "ఇమెయిల్",
    emailPlaceHolder: "మీ ఇమెయిల్ నమోదు చేయండి",
    mobile: "మొబైల్ నంబర్",
    mobilePlaceHolder: "మీ మొబైల్ నంబర్ నమోదు చేయండి",
    receiveOTP: "మీరు {0} పై OTP ని అందుకుంటారు.",
    pleaseWait: "దయచేసి వేచి ఉండండి...",
    fetchingDataFailedTitle: "అభ్యర్థించిన డేటాను పొందడం సాధ్యం కాలేదు.",
    failureMessage: "మీ అభ్యర్థనను ప్రాసెస్ చేస్తున్నప్పుడు లోపం ఏర్పడింది.",
    technicalGlitch: "ఇది తాత్కాలిక సాంకేతిక సమస్య వల్ల కావచ్చు. కొంత సమయం తర్వాత మళ్ళీ ప్రయత్నించండి.",
    contactSupport: "<a href=\"{supportEmail}\" style=\"text-decoration:none; target=\"_blank\" rel=\"noopener noreferrer\" color: #27c0e0;\">{supportEmail}</a> వద్ద మద్దతు బృందాన్ని సంప్రదించండి.",
    register: "రిజిస్టర్",
    registering: "రిజిస్టర్ అవుతోంది....",
    submitOTP: "OTP ని ధృవీకరించండి",
    submittingOTP: "OTP ధృవీకరించబడుతోంది....",
    otp: "OTP",
    otpPlaceholder: "OTP ని నమోదు చేయండి",
    enterOTP: "దయచేసి ({value}) పై మీరు అందుకున్న OTP ని నమోదు చేయండి.",
    signedUp: "మీరు విజయవంతంగా సైన్ అప్ అయ్యారు!",
    failedToSignUp: "సైన్ అప్ చేయడం విఫలమైంది.",
    loggedIn: "మీరు విజయవంతంగా లాగిన్ అయ్యారు!",
    failedToLogIn: "లాగిన్ చేయడం విఫలమైంది.",
    resendOTP: "OTP ని మళ్ళీ పంపండి",
    resendingOTP: "OTP ని మళ్ళీ పంపుతున్నాము....",
    password: "పాస్‌వర్డ్",
    logingin: "లాగిన్ అవుతోంది",
    passwordPlaceHolder: "మీ పాస్‌వర్డ్ నమోదు చేయండి",
    otpChild1: "OTP తప్పు కావచ్చు",
    otpChild2: "OTP గడువు ముగిసి ఉండవచ్చు.",
    otpChild3: "నెట్‌వర్క్ సమస్య ఉండవచ్చు.",
    otpChild4: "సర్వర్ డౌన్ అయి ఉండవచ్చు",
    passwordRequirementMsg: "మీ ఖాతాను భద్రపరచడానికి, కనీసం ఎనిమిది (8) అక్షరాలతో కూడిన పాస్‌వర్డ్‌ను సృష్టించండి, ఇందులో ఇవి ఉండాలి:",
    passwordRequireMent: "పాస్‌వర్డ్ ఆవశ్యకతలు",
    upperLowerCase: "అప్పర్ & లోయర్ కేస్ (పెద్ద & చిన్న అక్షరాలు)",
    subHeadingIns: "బలమైన పాస్‌వర్డ్ కోసం, మీ పాస్‌వర్డ్ కింది అంశాలను పాటించాలి",
    minimum8Char: "కనీసం 8 అక్షరాలు (తప్పనిసరి)",
    atLeastOneNumericals: "కనీసం ఒక అంకె (తప్పనిసరి)",
    numericals: "అంకెలు",
    specialChar: "ప్రత్యేక అక్షరాలు (Special Characters)",
    oneUpperCase: "కనీసం ఒక పెద్ద అక్షరం (తప్పనిసరి)",
    oneLowerCase: "కనీసం ఒక చిన్న అక్షరం (తప్పనిసరి)",
    partnerCompanyName: "భాగస్వామి కంపెనీ పేరు",
    atLeastOneSpecialChar: "కనీసం ఒక ప్రత్యేక అక్షరం (తప్పనిసరి)",
    skip: "దాటవేయి",
    confirmPassword: "పాస్‌వర్డ్ నిర్ధారించండి",
    setPassword: "పాస్‌వర్డ్ సెట్ చేయండి",
    accountInstruction: "ఖాతాను యాక్సెస్ చేయడానికి మరియు ఆర్డర్‌లను నిర్వహించడానికి",
    aboutUs: "మా గురించి",
    contactUs: "మమ్మల్ని సంప్రదించండి",
    profile: "ప్రొఫైల్",
    orders: "ఆర్డర్లు",
    wishlist: "విష్ లిస్ట్",
    loginSignup: "లాగిన్/సైన్ అప్",
    welcome: "స్వాగతం",
    profileImgUpdated: "ప్రొఫైల్ చిత్రం విజయవంతంగా అప్‌డేట్ చేయబడింది",
    save: "సేవ్",
    cancel: "రద్దు",
    adjustImage: "చిత్రాన్ని సర్దుబాటు చేయండి",
    dragSqrToChangeImgSizePos: "పరిమాణం మరియు స్థానాన్ని మార్చడానికి చతురస్రాన్ని లాగండి.",
    preview: "ప్రివ్యూ",
    imageCropped: "క్రాప్ చేసిన చిత్రం విజయవంతంగా సేవ్ చేయబడింది!",
    alternateMobile: "ప్రత్యామ్నాయ మొబైల్ నంబర్",
    male: "పురుషుడు",
    female: "స్త్రీ",
    others: "ఇతరులు",
    genderLabel: "దయచేసి మీ లింగాన్ని ఎంచుకోండి:",
    dob: "పుట్టిన తేదీ",
    update: "అప్‌డేట్",
    changePassword: "పాస్‌వర్డ్ మార్చండి",
    updatePassword: "పాస్‌వర్డ్ అప్‌డేట్ చేయండి",
    updateProfile: "ప్రొఫైల్ అప్‌డేట్ చేయండి",
    oldPassword: "పాత పాస్‌వర్డ్",
    confirmPasswordNotMatchPassword: "నిర్ధారించిన పాస్‌వర్డ్ అసలు పాస్‌వర్డ్‌తో సరిపోలలేదు.",
    passReqNotFulfil: "పాస్‌వర్డ్ నిబంధనలు నెరవేరలేదు.",
    passwordUpdated: "పాస్‌వర్డ్ విజయవంతంగా అప్‌డేట్ చేయబడింది!",
    profileUpdated: "ప్రొఫైల్ విజయవంతంగా అప్‌డేట్ చేయబడింది!",
    pageNotFound: "పేజీ కనుగొనబడలేదు",
    brokenLinkMsg1: "మీరు క్లిక్ చేసిన లింక్ విరిగిపోయి ఉండవచ్చు లేదా పేజీ తొలగించబడి ఉండవచ్చు.",
    brokenLinkMsg2: "హోమ్ పేజీని సందర్శించండి లేదా సమస్య గురించి మమ్మల్ని సంప్రదించండి.",
    backToHome: "హోమ్ పేజీకి తిరిగి వెళ్ళండి",
    dashboard: "డ్యాష్‌బోర్డ్",
    pages: "పేజీలు",
    inventory: "ఇన్వెంటరీ",
    customOrders: "కస్టమ్ ఆర్డర్లు",
    team: "టీమ్",
    customers: "కస్టమర్లు",
    settings: "సెట్టింగులు",
    messages: "సందేశాలు",
    pendingOrders: "పెండింగ్ ఆర్డర్లు",
    completedOrders: "పూర్తయిన ఆర్డర్లు",
    offers: "ఆఫర్లు",
    id: "ఐడి",
    name: "పేరు",
    brand: "బ్రాండ్",
    category: "వర్గం",
    price: "ధర",
    status: "స్థితి",
    createdDate: "సృష్టించిన తేదీ",
    updatedDate: "చివరిగా అప్‌డేట్ చేసిన తేదీ",
    action: "చర్య",
    productName: "ఉత్పత్తి పేరు",
    size: "సైజు",
    color: "రంగు",
    sku: "SKU",
    stockQuantity: "పరిమాణం",
    products: "ఉత్పత్తులు",
    description: "వివరణ",
    parent: "పేరెంట్",
    namePlaceholder: "పేరు నమోదు చేయండి",
    descriptionPlaceholder: "వివరణ నమోదు చేయండి",
    categoryPlaceholder: "ఒక వర్గాన్ని ఎంచుకోండి",
    categoryLevel: "వర్గం {0} స్థాయి ",
    at: "వద్ద",
    modifiedOn: "సవరించిన తేదీ",
    today: "ఈ రోజు",
    edit: "సవరించు",
    delete: "తొలగించు",
    activated: "{entity} యాక్టివేట్ చేయబడింది.",
    deactivated: "{entity} డీయాక్టివేట్ చేయబడింది.",
    yes: "అవును",
    no: "కాదు",
    confirm: "ధృవీకరించండి",
    deleteMsg: "మీరు ఖచ్చితంగా <b>{0}</b> {1}ని తొలగించాలనుకుంటున్నారా?",
    childrenOf: "యొక్క చిల్డ్రన్ ",
    page: "పేజీ",
    add: "జోడించు",
    deactivateFirst: "ముందుగా {entity}ని డీయాక్టివేట్ చేయండి.",
    activeCantAction: "యాక్టివ్ {entity}పై {action} చేయలేరు.",
    entityIsActive: "<b>{0}</b> {entity} యాక్టివ్‌గా ఉంది.",
    searchPlaceHolder: "{entity} కోసం వెతకండి...",
    copy: "కాపీ",
    deleted: "తొలగించబడింది",
    edited: "సవరించబడింది",
    product: "ఉత్పత్తి",
    title: "శీర్షిక",
    titlePlaceholder: "శీర్షిక నమోదు చేయండి",
    image: "చిత్రం",
    material: "మెటీరియల్",
    materialPlaceholder: "మెటీరియల్ నమోదు చేయండి",
    colorPlaceholder: "రంగు నమోదు చేయండి",
    sku: "SKU కోడ్",
    skuPlaceholder: "ప్రత్యేకమైన SKU కోడ్‌ని నమోదు చేయండి",
    quantity: "పరిమాణం",
    type: "రకం",
    productName: "ఉత్పత్తి పేరు",
    selectProductPlaceholder: "ఉత్పత్తిని ఎంచుకోండి",
    sizeChart: "సైజ్ చార్ట్",
    enterMeasure: "మీ {0} కొలతను నమోదు చేయండి",
    chest: "ఛాతి",
    hips: "హిప్స్",
    neck: "మెడ",
    sleeve: "చేతులు (స్లీవ్)",
    arm: "భుజం",
    topLength: "పై భాగం పొడవు",
    shoulder: "భుజం",
    inseam: "ఇన్సీమ్",
    bottomLength: "కింది భాగం పొడవు",
    thigh: "తొడ",
    waist: "నడుము",
    topBody: "పై శరీరం",
    bottomBody: "కింది శరీరం",
    rank: "ర్యాంక్",
    sale: "అమ్మకం",
    rental: "అద్దె",
    selectRankPlaceholder: "ర్యాంక్ ఎంచుకోండి",
    mrp: "MRP",
    salePrice: "అమ్మకపు ధర",
    discount: "తగ్గింపు",
    selectSizePlaceholder: "సైజు ఎంచుకోండి",
    mrpPlaceholder: "MRPని నమోదు చేయండి (₹)",
    salePricePlaceholder: "అమ్మకపు ధర నమోదు చేయండి (₹)",
    discountPlaceholder: "తగ్గింపును నమోదు చేయండి (%)",
    quantityPlaceholder: "పరిమాణాన్ని నమోదు చేయండి",
    saleOrRentPrice: "అమ్మకం/అద్దె ధర",
    security: "సెక్యూరిటీ డిపాజిట్",
    securityPlaceholder: "రీఫండబుల్ = డిపాజిట్ - (అద్దె ధర - తగ్గింపు %)",
    size_Quant_Price: "సైజ్ - పరిమాణం - అమ్మకపు ధర",
    view: "చూడండి",
    webSettings: "వెబ్ సెట్టింగులు",
    siteUnderMaintenance: "సైట్ నిర్వహణలో ఉంది",
    weWillGetbackShortly: "మేము త్వరలో తిరిగి వస్తాము. దయచేసి మళ్ళీ ప్రయత్నించండి.",
    reload: "రీలోడ్",
    enableWebsite: "వెబ్‌సైట్‌ను ప్రారంభించడానికి లేదా నిలిపివేయడానికి క్లిక్ చేయండి.",
    website: "వెబ్‌సైట్",
    switchOnOffWebsite: "వెబ్‌సైట్ ఆన్/ఆఫ్ చేయండి",
    webConfigs: "వెబ్‌సైట్ కాన్ఫిగరేషన్లు",
    webTrendingBar: "వెబ్‌సైట్ ట్రెండింగ్ బార్",
    websiteId: "వెబ్‌సైట్ ఐడి",
    path: "పాత్",
    pathPlaceholder: "తెరవవలసిన పాత్‌ను నమోదు చేయండి",
    homePage: "హోమ్ పేజీ",
    homePageCarousel: "హోమ్ పేజీ క్యారౌసెల్",
    forPC: "PC కోసం:",
    forMobile: "మొబైల్ కోసం:",
    reset: "రీసెట్",
    customFitting: "కస్టమ్ ఫిట్టింగ్",
    customDesigning: "కస్టమ్ డిజైనింగ్",
    freeDelivery: "ఉచిత డెలివరీ",
    assuredRefunds: "ఖచ్చితమైన రీఫండ్",
    sizes: "సైజులు",
    addresses: "చిరునామాలు",
    isTileVisible: "టైల్ కనిపిస్తోందా?",
    isTileVisibleGrid: "టైల్ కనిపిస్తోంది",
    categories: "వర్గాలు",
    mrpWithDots: "M.R.P",
    rtd: "డిస్పాచ్‌కి సిద్ధంగా ఉంది",
    inclusiveTax: "అన్ని పన్నులతో కలిపి ధర",
    rentInclusiveTax: "అన్ని పన్నులతో కలిపి అద్దె",
    purchase: "కొనుగోలు",
    rent: "అద్దె",
    refundableSecurity: "తిరిగి ఇచ్చే సెక్యూరిటీ డిపాజిట్",
    securityDeposit: "సెక్యూరిటీ డిపాజిట్",
    refundSecurity: "వస్తువును తిరిగి ఇచ్చిన తర్వాత, మీ సెక్యూరిటీ డిపాజిట్ రీఫండ్ చేయబడుతుంది.",
    securityDepositDeduction: "మీరు డెలివరీ అయిన 5 రోజులలోపు వస్తువును తిరిగి ఇవ్వవచ్చు. ఆ తర్వాత ప్రతి 5 రోజులకు మీ సెక్యూరిటీ డిపాజిట్ నుండి అద్దె మొత్తం తీసివేయబడుతుంది.",
    sizeGuide: "సైజ్ గైడ్",
    customSize: "కస్టమ్ సైజ్",
    loginToAddCustomSize: "కస్టమ్ సైజ్‌ని జోడించడానికి & చూడటానికి లాగిన్/సైన్ అప్ చేయండి",
    yourCustomSizes: "మీ కస్టమ్ సైజులు",
    undoWishlistMsg: "మీరు విష్ లిస్ట్ నుండి <b>{name}</b>ని తొలగించారు",
    undo: "అన్డూ (Undo)",
    textPlaceholder: "{0}ని నమోదు చేయండి",
    address: "చిరునామా",
    fullName: "పేరు",
    city: "నగరం",
    country: "దేశం",
    pinCode: "పిన్ కోడ్",
    state: "రాష్ట్రం",
    landmark: "ల్యాండ్‌మార్క్",
    streetAddress1: "ఫ్లాట్, హౌస్ నెం, బిల్డింగ్, కంపెనీ, అపార్ట్‌మెంట్",
    streetAddress2: "ఏరియా, వీధి, సెక్టార్, గ్రామం",
    defaultAddress: "డిఫాల్ట్ చిరునామాగా సెట్ చేయండి",
    setDefault: "డిఫాల్ట్‌గా సెట్ చేయండి",
    default: "డిఫాల్ట్",
    addToCart: "కార్ట్‌కు జోడించు",
    buyNow: "ఇప్పుడే కొనండి",
    total: "మొత్తం",
    clearCart: "కార్ట్‌ను ఖాళీ చేయండి",
    proceedToCheckout: "చెక్అవుట్‌కు వెళ్లండి",
    shoppingCart: "షాపింగ్ కార్ట్",
    loadingCart: "కార్ట్ లోడ్ అవుతోంది...",
    emptyCart: "మీ కార్ట్ ఖాళీగా ఉంది.",
    emptyWishlist: "మీ విష్ లిస్ట్ ఖాళీగా ఉంది.",
    deSelectAll: "అన్ని ఐటెమ్‌లను అన్ సెలెక్ట్ చేయండి",
    invalidCoupon: "చెల్లని కూపన్ కోడ్",
    couponApplied: "కూపన్ వర్తింపజేయబడింది: ",
    apply: "వర్తింపజేయి",
    freeCaps: "ఉచితం",
    deliveryCharges: "డెలివరీ ఛార్జీలు",
    subTotal: "సబ్ టోటల్",
    changeSize: "సైజు మార్చండి",
    moveToWishlist: "విష్ లిస్ట్‌కు తరలించండి",
    share: "షేర్ చేయండి",
    orderSummary: "ఆర్డర్ సారాంశం",
    coupon: "కూపన్",
    itemsForPurchasing: "కొనుగోలు కోసం ఎంచుకున్న ఐటెమ్‌లు",
    itemsForRenting: "అద్దె కోసం ఎంచుకున్న ఐటెమ్‌లు",
    itemsSelected: "ఎంచుకున్న ఐటెమ్‌లు",
    applyCoupon: "కూపన్ వర్తింపజేయి",
    undoCartMsg: 'కార్ట్ నుండి <strong>{name}</strong> తొలగించబడింది. ',
    itemRestored: "ఐటెమ్ మళ్ళీ కార్ట్‌లోకి చేర్చబడింది",
    selectAll: "అన్నీ ఎంచుకోండి",
    itemMovedToWishlist: "ఐటెమ్ విష్ లిస్ట్‌కు తరలించబడింది.",
    itemRemoved: "కార్ట్ నుండి ఐటెమ్ తొలగించబడింది",
    addedToCart: "కార్ట్‌కు ఐటెమ్ జోడించబడింది",
    itemAddedToWishlist: "విష్ లిస్ట్‌కు ఐటెమ్ జోడించబడింది",
    itemRemovedFromWishlist: "విష్ లిస్ట్ నుండి ఐటెమ్ తొలగించబడింది",
    proceedToBuy: "కొనుగోలుకు వెళ్లండి",
    change: "మార్చండి",
    checkout: "చెక్అవుట్",
    deliverHere: "ఇక్కడ డెలివరీ చేయండి",
    selectDeliveryAddress: "డెలివరీ చిరునామాను ఎంచుకోండి",
    selectedDeliveryAddress: "ఎంచుకున్న డెలివరీ చిరునామా",
    inventoryType: "ఇన్వెంటరీ రకం",
    currentlyDefaultAddress: "డిఫాల్ట్ చిరునామా",
    chosenAddressUpdated: "ఎంచుకున్న చిరునామా విజయవంతంగా అప్‌డేట్ చేయబడింది.",
    draftUpdated: "ఆర్డర్ వివరాలు విజయవంతంగా అప్‌డేట్ చేయబడ్డాయి.",
    proceedToCheckout: "చెక్అవుట్‌కు వెళ్లారు.",
    deliveringTo: "డెలివరీ చేస్తున్న చిరునామా",
    addNew: "కొత్తది జోడించు",
    itemsInOrder: "ఆర్డర్‌లోని ఐటెమ్‌లు",
    shipTogether: "అన్ని ఐటెమ్‌లను కలిపి షిప్ చేయండి",
    shipAsap: "ప్రతి ఐటెమ్ సిద్ధమైన వెంటనే షిప్ చేయండి",
    shipItems: "మీ ఆర్డర్ ఎప్పుడు షిప్ చేయబడాలని కోరుకుంటున్నారు?",
    shipItemsForOrder: "{user} ఆర్డర్ ఎప్పుడు షిప్ చేయబడాలని కోరుకుంటున్నారు?",
    orderPlacedTitle: "ధన్యవాదాలు, మీ ఆర్డర్ విజయవంతంగా పూర్తయింది!",
    orderConfirmationSent:  "మీ ఇమెయిల్‌కు నిర్ధారణ సందేశం పంపబడింది.",
    orderId: "ఆర్డర్ ఐడి",
    itemsInTheOrder: "ఆర్డర్‌లోని ఐటెమ్‌లు",
    viewOrders: "మీ ఆర్డర్‌లను చూడండి",
    viewAllOrders: "అన్ని ఆర్డర్‌లను చూడండి",
    continueShopping: "షాపింగ్ కొనసాగించండి",
    orderDetails: "ఆర్డర్ వివరాలు",
    appliedCoupon: "వర్తింపజేసిన కూపన్",
    orderPlacedOn: "ఆర్డర్ చేసిన తేదీ",
    shipTo: "షిప్ చేయవలసిన చిరునామా",
    noOrdersFound: "ఆర్డర్‌లు ఏవీ కనుగొనబడలేదు",
    yourOrders: "మీ ఆర్డర్లు",
    paymentMode: "చెల్లింపు మోడ్",
    paymentMethod: "చెల్లింపు పద్ధతి",
    all: "అన్నీ",
    pending: "పెండింగ్",
    shipped: "షిప్ చేయబడింది",
    delivered: "డెలివరీ చేయబడింది",
    cancelled: "రద్దు చేయబడింది",
    allOrders: "అన్ని ఆర్డర్లు",
    newOrders: "కొత్త ఆర్డర్లు",
    statusMessages: {
      forOrder: {
        forManager: {
          draft: "ఆర్డర్ డ్రాఫ్ట్ స్థితిలో ఉంది, ఇంకా ఆర్డర్ చేయబడలేదు.",
          pending: "చెల్లింపు పెండింగ్‌లో ఉంది.",
          placed: "ఆర్డర్ చేయబడింది, మీ వైపు నుండి నిర్ధారణ కోసం వేచి ఉంది.",
          confirmed: "మీరు ఆర్డర్‌ను ధృవీకరించారు.",
          payment_failed: "చెల్లింపు విఫలమైంది.",
          in_process: "ఆర్డర్ మీ ద్వారా ప్రాసెస్ చేయబడుతోంది.",
          ready_to_dispatch: "ఆర్డర్ డిస్పాచ్ చేయడానికి సిద్ధంగా ఉంది.",
          shipped: "ఆర్డర్ షిప్ చేయబడింది.",
          in_transit: "ఆర్డర్ మార్గంలో ఉంది.",
          delivered: "ఆర్డర్ డెలివరీ చేయబడింది.",
          cancelled: "ఆర్డర్ రద్దు చేయబడింది.",
          cancellation_requested: "వినియోగదారు రద్దు కోసం అభ్యర్థించారు.",
          cancellation_rejected: "మీరు రద్దు అభ్యర్థనను తిరస్కరించారు.",
          cancellation_refunded: "ఆర్డర్ రద్దు చేయబడింది మరియు చెల్లింపు రీఫండ్ చేయబడింది.",
          return_requested: "ఆర్డర్ల కోసం రిటర్న్ అభ్యర్థనలు.",
          return_rejected: "మీరు రిటర్న్ అభ్యర్థనను తిరస్కరించారు.",
          returned: "ఆర్డర్ తిరిగి వచ్చింది.",
          return_refunded: "రిటర్న్ తర్వాత చెల్లింపు రీఫండ్ చేయబడింది.",
          refunded: "చెల్లింపు రీఫండ్ చేయబడింది.",
    
          // New RTO statuses
          rto_requested: "మీ ద్వారా RTO అభ్యర్థించబడింది.",
          rto_rejected: "మీరు RTO అభ్యర్థనను తిరస్కరించారు.",
          rto_approved: "మీరు RTO అభ్యర్థనను ఆమోదించారు.",
          rto_in_progress: "RTO పురోగతిలో ఉంది.",
          rto_delivered: "RTO ద్వారా ఆర్డర్ మీకు తిరిగి వచ్చింది.",
          rto_verified: "RTO ఐటెమ్‌లను మీరు ధృవీకరించారు.",
          rto_refunded: "RTO తర్వాత కస్టమర్‌కు చెల్లింపు రీఫండ్ చేయబడింది."
        },
        forUser: {
          draft: "మీ ఆర్డర్ చెక్అవుట్‌లో ఉంది, ఇంకా ఆర్డర్ కాలేదు.",
          pending: "చెల్లింపు పెండింగ్‌లో ఉంది. దయచేసి చెల్లింపు పూర్తి చేయండి.",
          placed: "మీ ఆర్డర్ చేయబడింది, నిర్ధారణ కోసం వేచి ఉంది.",
          confirmed: "మీ ఆర్డర్ విక్రేత ద్వారా ధృవీకరించబడింది.",
          payment_failed: "చెల్లింపు విఫలమైంది. దయచేసి మళ్ళీ ప్రయత్నించండి.",
          in_process: "మీ ఆర్డర్ విక్రేత ద్వారా ప్రాసెస్ చేయబడుతోంది.",
          ready_to_dispatch: "మీ ఆర్డర్ డిస్పాచ్‌కి సిద్ధంగా ఉంది.",
          shipped: "మీ ఆర్డర్ షిప్ చేయబడింది.",
          in_transit: "మీ ఆర్డర్ మార్గంలో ఉంది.",
          delivered: "మీ ఆర్డర్ డెలివరీ చేయబడింది.",
          cancelled: "మీ ఆర్డర్ రద్దు చేయబడింది.",
          cancellation_requested: "మీరు ఈ ఆర్డర్‌ను రద్దు చేయమని అభ్యర్థించారు.",
          cancellation_rejected: "మీ రద్దు అభ్యర్థన తిరస్కరించబడింది.",
          cancellation_refunded: "మీ రద్దు అంగీకరించబడింది మరియు చెల్లింపు రీఫండ్ చేయబడింది.",
          return_requested: "మీ ఆర్డర్ కోసం రిటర్న్ అభ్యర్థన సమర్పించబడింది.",
          return_rejected: "మీ రిటర్న్ అభ్యర్థన తిరస్కరించబడింది.",
          returned: "మీ ఆర్డర్ తిరిగి పంపబడింది.",
          return_refunded: "రిటర్న్ తర్వాత మీ చెల్లింపు రీఫండ్ చేయబడింది.",
          refunded: "మీ చెల్లింపు రీఫండ్ చేయబడింది.",
    
          // New RTO statuses
          rto_requested: "ఆర్డర్ కోసం RTO అభ్యర్థించబడింది.",
          rto_rejected: "విక్రేత RTO అభ్యర్థనను తిరస్కరించారు.",
          rto_approved: "విక్రేత ఈ ఆర్డర్ కోసం RTOని ఆమోదించారు.",
          rto_in_progress: "మీ ఆర్డర్ RTO మార్గంలో ఉంది.",
          rto_delivered: "మీ ఆర్డర్ RTO ద్వారా విక్రేతకు తిరిగి చేరింది.",
          rto_verified: "మీరు తిరిగి పంపిన ఆర్డర్ విక్రేత ద్వారా ధృవీకరించబడింది.",
          rto_refunded: "RTO తర్వాత మీకు రీఫండ్ చేయబడింది."
        }
      },
      forItem: {
        forManager: {
          draft: "ఐటెమ్ ఆర్డర్ డ్రాఫ్ట్‌లో జోడించబడింది, ఇంకా ఆర్డర్ చేయబడలేదు.",
          pending: "ఈ ఐటెమ్ చెల్లింపు పెండింగ్‌లో ఉంది.",
          placed: "ఐటెమ్ ఆర్డర్ చేయబడింది, మీ నిర్ధారణ కోసం వేచి ఉంది.",
          confirmed: "మీరు ఈ ఐటెమ్‌ను ధృవీకరించారు.",
          payment_failed: "ఈ ఐటెమ్ చెల్లింపు విఫలమైంది.",
          in_process: "ఐటెమ్ మీ ద్వారా ప్రాసెస్ చేయబడుతోంది.",
          ready_to_dispatch: "ఐటెమ్ డిస్పాచ్ చేయడానికి సిద్ధంగా ఉంది.",
          shipped: "ఐటెమ్ షిప్ చేయబడింది.",
          in_transit: "ఐటెమ్ మార్గంలో ఉంది.",
          delivered: "ఐటెమ్ డెలివరీ చేయబడింది.",
          cancelled: "ఈ ఐటెమ్ రద్దు చేయబడింది.",
          cancellation_requested: "వినియోగదారు ఈ ఐటెమ్ రద్దు కోసం అభ్యర్థించారు.",
          cancellation_rejected: "మీరు ఈ ఐటెమ్ రద్దు అభ్యర్థనను తిరస్కరించారు.",
          cancellation_refunded: "ఈ ఐటెమ్ రద్దు చేయబడింది మరియు చెల్లింపు రీఫండ్ చేయబడింది.",
          return_requested: "వినియోగదారు ఈ ఐటెమ్ రిటర్న్ కోసం అభ్యర్థించారు.",
          return_rejected: "మీరు ఈ ఐటెమ్ రిటర్న్ అభ్యర్థనను తిరస్కరించారు.",
          returned: "ఐటెమ్ తిరిగి వచ్చింది.",
          return_refunded: "తిరిగి వచ్చిన ఐటెమ్ కోసం చెల్లింపు రీఫండ్ చేయబడింది.",
          refunded: "ఈ ఐటెమ్ కోసం చెల్లింపు రీఫండ్ చేయబడింది.",
    
          // New RTO statuses
          rto_requested: "ఈ ఐటెమ్ కోసం RTO అభ్యర్థించబడింది.",
          rto_rejected: "మీరు ఈ ఐటెమ్ RTO అభ్యర్థనను తిరస్కరించారు.",
          rto_approved: "మీరు ఈ ఐటెమ్ RTO అభ్యర్థనను ఆమోదించారు.",
          rto_in_progress: "ఈ ఐటెమ్ RTO పురోగతిలో ఉంది.",
          rto_delivered: "ఈ ఐటెమ్ మీకు తిరిగి వచ్చింది.",
          rto_verified: "తిరిగి వచ్చిన ఐటెమ్ ధృవీకరించబడింది.",
          rto_refunded: "RTO తర్వాత ఈ ఐటెమ్ కోసం చెల్లింపు రీఫండ్ చేయబడింది."
        },
        forUser: {
          draft: "ఈ ఐటెమ్ చెక్అవుట్‌లో ఉంది, ఇంకా ఆర్డర్ కాలేదు.",
          pending: "ఈ ఐటెమ్ చెల్లింపు పెండింగ్‌లో ఉంది. దయచేసి చెల్లింపు పూర్తి చేయండి.",
          placed: "ఈ ఐటెమ్ ఆర్డర్ చేయబడింది, నిర్ధారణ కోసం వేచి ఉంది.",
          confirmed: "ఈ ఐటెమ్ విక్రేత ద్వారా ధృవీకరించబడింది.",
          payment_failed: "ఈ ఐటెమ్ చెల్లింపు విఫలమైంది. దయచేసి మళ్ళీ ప్రయత్నించండి.",
          in_process: "ఈ ఐటెమ్ విక్రేత ద్వారా ప్రాసెస్ చేయబడుతోంది.",
          ready_to_dispatch: "ఈ ఐటెమ్ డిస్పాచ్‌కి సిద్ధంగా ఉంది.",
          shipped: "ఈ ఐటెమ్ షిప్ చేయబడింది.",
          in_transit: "ఈ ఐటెమ్ మార్గంలో ఉంది.",
          delivered: "ఈ ఐటెమ్ డెలివరీ చేయబడింది.",
          cancelled: "ఈ ఐటెమ్ రద్దు చేయబడింది.",
          cancellation_requested: "మీరు ఈ ఐటెమ్‌ను రద్దు చేయమని అభ్యర్థించారు.",
          cancellation_rejected: "ఈ ఐటెమ్ రద్దు అభ్యర్థన తిరస్కరించబడింది.",
          cancellation_refunded: "ఈ ఐటెమ్ రద్దు అంగీకరించబడింది మరియు చెల్లింపు రీఫండ్ చేయబడింది.",
          return_requested: "ఈ ఐటెమ్ కోసం రిటర్న్ అభ్యర్థన సమర్పించబడింది.",
          return_rejected: "ఈ ఐటెమ్ రిటర్న్ అభ్యర్థన తిరస్కరించబడింది.",
          returned: "ఈ ఐటెమ్ తిరిగి పంపబడింది.",
          return_refunded: "ఈ ఐటెమ్ రిటర్న్ తర్వాత మీ చెల్లింపు రీఫండ్ చేయబడింది.",
          refunded: "ఈ ఐటెమ్ కోసం మీ చెల్లింపు రీఫండ్ చేయబడింది.",
    
          // New RTO statuses
          rto_requested: "ఈ ఐటెమ్ కోసం RTO అభ్యర్థించబడింది.",
          rto_rejected: "విక్రేత ఈ ఐటెమ్ RTO అభ్యర్థనను తిరస్కరించారు.",
          rto_approved: "విక్రేత ఈ ఐటెమ్ RTOని ఆమోదించారు.",
          rto_in_progress: "ఈ ఐటెమ్ RTO మార్గంలో ఉంది.",
          rto_delivered: "ఈ ఐటెమ్ విక్రేతకు తిరిగి చేరింది.",
          rto_verified: "మీరు తిరిగి పంపిన ఐటెమ్ విక్రేత ద్వారా ధృవీకరించబడింది.",
          rto_refunded: "RTO తర్వాత ఈ ఐటెమ్ కోసం మీకు రీఫండ్ చేయబడింది."
        }
      }
    },
    statusColors: {
      draft: "var(--secondarytext-color)",
      pending: "var(--warning-color)",
      placed: "var(--info-color)",
      confirmed: "var(--success-color)",
      payment_failed: "var(--danger-color)",
      in_process: "var(--infolight-color)",
      ready_to_dispatch: "purple",
      shipped: "blue",
      in_transit: "var(--primarylight-color)",
      delivered: "var(--successdark-color)",
    
      cancellation_requested: "orange",
      cancelled: "var(--dangerlight-color)",
      cancellation_rejected: "red",
      cancellation_refunded: "var(--success-color)",
    
      return_requested: "var(--secondary-color)",
      returned: "var(--dangerlight-color)",
      return_rejected: "var(--warning-color)",
      return_refunded: "var(--success-color)",
    
      refunded: "var(--success-color)",
    
      // New RTO statuses
      rto_requested: "var(--warningdark-color)",
      rto_rejected: "red",
      rto_approved: "var(--success-color)",
      rto_in_progress: "blueviolet",
      rto_delivered: "var(--info-color)",
      rto_verified: "var(--successdark-color)",
      rto_refunded: "var(--success-color)"
    },
    orderPages: {
      allOrders: {
        title: "అన్ని ఆర్డర్లు",
        statuses: ["ALL"]
      },
      pendingOrders: {
        title: "పెండింగ్ ఆర్డర్లు",
        statuses: ["PENDING"]
      },
      newOrders: {
        title: "కొత్త ఆర్డర్లు",
        statuses: ["PLACED"]
      },
      confirmedOrders: {
        title: "ధృవీకరించబడిన ఆర్డర్లు",
        statuses: ["CONFIRMED"]
      },
      processingOrders: {
        title: "ప్రాసెసింగ్ ఆర్డర్లు",
        statuses: ["IN_PROCESS"]
      },
      readyToDispatchOrders: {
        title: "డిస్పాచ్‌కి సిద్ధంగా ఉన్న ఆర్డర్లు",
        statuses: ["READY_TO_DISPATCH"]
      },
      onTheWayOrders: {
        title: "మార్గంలో ఉన్న ఆర్డర్లు",
        statuses: ["SHIPPED", "IN_TRANSIT"]
      },
      deliveredOrders: {
        title: "డెలివరీ అయిన ఆర్డర్లు",
        statuses: ["DELIVERED"]
      },
    
      // After-sale statuses
      cancelled: {
        title: "రద్దు చేయబడిన ఆర్డర్లు",
        statuses: ["CANCELLED"]
      },
      returns: {
        title: "రిటర్న్స్",
        statuses: ["ALLRETURNS"],
        showOrderStatuses: false
      },  
      cancellation_requested: {
        title: "రద్దు అభ్యర్థించిన ఆర్డర్లు",
        statuses: ["CANCELLATION_REQUESTED"]
      },
      cancellation_rejected: {
        title: "రద్దు తిరస్కరించిన ఆర్డర్లు",
        statuses: ["CANCELLATION_REJECTED"]
      },
      cancellation_refunded: {
        title: "రద్దు రీఫండ్ అయిన ఆర్డర్లు",
        statuses: ["CANCELLATION_REFUNDED"]
      },
      return_requested: {
        title: "రిటర్న్ అభ్యర్థించిన ఆర్డర్లు",
        statuses: ["RETURN_REQUESTED"]
      },
      returned: {
        title: "తిరిగి వచ్చిన ఆర్డర్లు",
        statuses: ["RETURNED"]
      },
      return_rejected: {
        title: "రిటర్న్ తిరస్కరించిన ఆర్డర్లు",
        statuses: ["RETURN_REJECTED"]
      },
      return_refunded: {
        title: "రిటర్న్ రీఫండ్ అయిన ఆర్డర్లు",
        statuses: ["RETURN_REFUNDED"]
      },
    
      // New RTO pages
      rto_requested: {
        title: "RTO అభ్యర్థించిన ఆర్డర్లు",
        statuses: ["RTO_REQUESTED"]
      },
      rto_rejected: {
        title: "RTO తిరస్కరించిన ఆర్డర్లు",
        statuses: ["RTO_REJECTED"]
      },
      rto_approved: {
        title: "RTO ఆమోదించబడిన ఆర్డర్లు",
        statuses: ["RTO_APPROVED"]
      },
      rto_in_progress: {
        title: "RTO పురోగతిలో ఉన్న ఆర్డర్లు",
        statuses: ["RTO_IN_PROGRESS"]
      },
      rto_delivered: {
        title: "RTO డెలివరీ అయిన ఆర్డర్లు",
        statuses: ["RTO_DELIVERED"]
      },
      rto_verified: {
        title: "RTO ధృవీకరించబడిన ఆర్డర్లు",
        statuses: ["RTO_VERIFIED"]
      },
      rto_refunded: {
        title: "RTO రీఫండ్ అయిన ఆర్డర్లు",
        statuses: ["RTO_REFUNDED"]
      }
    },  
    confirmedOrders: "ధృవీకరించబడిన ఆర్డర్లు",
    processingOrders: "ప్రాసెసింగ్ ఆర్డర్లు",
    readyToDispatchOrders: "డిస్పాచ్‌కి సిద్ధంగా ఉన్న ఆర్డర్లు",
    onTheWayOrders: "మార్గంలో ఉన్న ఆర్డర్లు",
    deliveredOrders: "డెలివరీ అయిన ఆర్డర్లు",
    cancelled_orders: "రద్దు చేయబడిన ఆర్డర్లు",
    cancellation_requested_orders: "రద్దు అభ్యర్థించిన ఆర్డర్లు",
    return_requested_orders: "రిటర్న్ అభ్యర్థించిన ఆర్డర్లు",
    return_refunded_orders: "రిటర్న్ రీఫండ్ అయిన ఆర్డర్లు",
    returns: "రిటర్న్స్",
    returned_orders: "తిరిగి వచ్చిన ఆర్డర్లు",
    return_rejected_orders: "రిటర్న్ తిరస్కరించిన ఆర్డర్లు",
    cancellation_rejected_orders: "రద్దు తిరస్కరించిన ఆర్డర్లు",
    cancellation_refunded_orders: "రద్దు రీఫండ్ అయిన ఆర్డర్లు",
    rto_requested_orders: "RTO అభ్యర్థించిన ఆర్డర్లు",
    rto_rejected_orders: "RTO తిరస్కరించిన ఆర్డర్లు",
    rto_approved_orders: "RTO ఆమోదించబడిన ఆర్డర్లు",
    rto_in_progress_orders: "RTO పురోగతిలో ఉన్న ఆర్డర్లు",
    rto_delivered_orders: "RTO డెలివరీ అయిన ఆర్డర్లు",
    rto_verified_orders: "RTO ధృవీకరించబడిన ఆర్డర్లు",
    rto_refunded_orders: "RTO రీఫండ్ అయిన ఆర్డర్లు",
    moreOptions: "మరిన్ని ఎంపికలు",
    details: "వివరాలు",
    viewProductPage: "ఉత్పత్తి పేజీని చూడండి",
    viewSize: "సైజు చూడండి",
    trackStatus: "స్థితిని ట్రాక్ చేయండి",
    auditTrail: "ఆడిట్ ట్రయల్",
    changedFrom: "నుండి మార్చబడింది",
    changedTo: "కి మార్చబడింది",
    entityType: "ఎంటిటీ రకం",
    entityId: "ఎంటిటీ ఐడి",
    performedBy: "చేసిన వారు",
    timestamp: "టైమ్ స్టాంప్",
    trackingDetails: "ట్రాకింగ్ వివరాలు",
    noDetailsFound: "వివరాలు ఏవీ కనుగొనబడలేదు",
    userDetails: 'వినియోగదారు వివరాలు',
    followUs: "మమ్మల్ని అనుసరించండి",
    allRightsReserved: "అన్ని హక్కులు రిజర్వ్ చేయబడ్డాయి",
    fastAndSecured: "వేగవంతమైన మరియు సురక్షితమైన చెల్లింపు ఎంపికలు",
    company: "కంపెనీ",
    myAccount: "నా ఖాతా",
    home: "హోమ్",
    account: "ఖాతా",
    search: "వెతుకు",
    cart: "కార్ట్",
    language: "భాష",
    somethingWentWrong: "ఏదో తప్పు జరిగింది!",
    note: "గమనిక",
    notAllowed1: "మీరు ఈ అప్లికేషన్‌లో లాగిన్ అవ్వడానికి అనుమతి లేదు",
    notAllowed2: "కేవలం అడ్మిన్ మరియు మేనేజర్‌కు మాత్రమే దీనికి యాక్సెస్ ఉంది",
    notAllowed3: "మీరు వీరిలో ఒకరై ఉండి కూడా యాక్సెస్ చేయలేకపోతే అడ్మిన్‌ను సంప్రదించండి",
    logOutAndBackToHome: "లాగ్ అవుట్ అయ్యి హోమ్ పేజీకి వెళ్ళండి",
    whatsAppUs: "మాకు వాట్సాప్ చేయండి",
    ourContactDetails: "మా సంప్రదింపు వివరాలు",
    workingHours: "పని వేళలు",
    instagram: "ఇన్‌స్టాగ్రామ్",
    facebook: "ఫేస్‌బుక్",
    x: "X (ట్విట్టర్)",
    threads: "థ్రెడ్స్",
    youtube: "యూట్యూబ్",
    pinterest: "పింట్రెస్ట్",
    quotaUsage: "మెయిల్/SMS కోటా వినియోగం",
    used: "ఉపయోగించినవి",
    remaining: "మిగిలినవి",
    totalQuota: "మొత్తం కోటా",
    sms: "SMS",
    whatsapp: "వాట్సాప్",
    brevo: "Brevo",
    count: "సంఖ్య",
    date: "తేదీ",
    gmail: "Gmail",
    quota: "కోటా",
    teamUsers: "టీమ్",
    member: "సభ్యుడు",
    customer: "కస్టమర్",
    customers: "కస్టమర్లు",
    profileImage: "ప్రొఫైల్ చిత్రం",
    gender: "లింగం",
    role: "పాత్ర (Role)",
    activatedText: "యాక్టివేట్ చేయబడింది",
    selectRolePlaceholder: "పాత్రను ఎంచుకోండి",
    accountActiveLabel: "వినియోగదారు ఖాతా యాక్టివ్‌గా/ఇనాక్టివ్‌గా ఉండాలో ఎంచుకోండి:",
    user: "వినియోగదారు",
    actions: "చర్యలు",
    setAsDiscontinued: "నిలిపివేసినట్లుగా సెట్ చేయండి",
    resetToDefaultPassword: "డిఫాల్ట్ పాస్‌వర్డ్‌కు రీసెట్ చేయండి",
    confirmMsg: "మీరు ఖచ్చితంగా <b>{0}</b> {1}ని {2} చేయాలనుకుంటున్నారా?",
    discontinued: "నిలిపివేయబడింది",
    base: "బేస్",
    setActive: "యాక్టివ్‌గా సెట్ చేయి",
    refresh: "రిఫ్రెష్",
    
  };
  
  export default te;