const ur = {
    login: "لاگ ان کریں",
    signup: "سائن اپ کریں",
    forgotPassword: "پاس ورڈ بھول گئے؟",
    welcomeUser: "خوش آمدید، صارف!",
    logout: "لاگ آؤٹ",
    requiredField: "یہ خانہ پُر کرنا ضروری ہے۔",
    invalidEmail: "براہ کرم ایک درست ای میل پتہ درج کریں۔",
    name: "نام",
    fullNamePlaceholder: "اپنا نام درج کریں",
    firstName: "پہلا نام",
    lastName: "آخری نام",
    mobileOrEmail: "ای میل آئی ڈی یا موبائل نمبر",
    firstNamePlaceHolder: "اپنا پہلا نام درج کریں",
    lastNamePlaceHolder: "اپنا آخری نام درج کریں",
    email: "ای میل",
    emailPlaceHolder: "اپنا ای میل درج کریں",
    mobile: "موبائل نمبر",
    mobilePlaceHolder: "اپنا موبائل نمبر درج کریں",
    receiveOTP: "آپ کو اس {0} پر ایک OTP موصول ہوگا۔",
    pleaseWait: "براہ کرم انتظار کریں...",
    fetchingDataFailedTitle: "درخواست کردہ ڈیٹا لانے سے قاصر۔",
    failureMessage: "آپ کی درخواست پر کارروائی کرتے وقت ہمیں ایک خرابی کا سامنا کرنا پڑا۔",
    technicalGlitch: "یہ عارضی تکنیکی خرابی کی وجہ سے ہو سکتا ہے۔ کچھ دیر بعد دوبارہ کوشش کریں۔",
    contactSupport: "سپورٹ سے رابطہ کریں <a href=\"{supportEmail}\" style=\"text-decoration:none; target=\"_blank\" rel=\"noopener noreferrer\" color: #27c0e0;\">{supportEmail}</a> پر۔",
    register: "رجسٹر کریں",
    registering: "رجسٹریشن ہو رہی ہے....",
    submitOTP: "OTP کی تصدیق کریں",
    submittingOTP: "OTP کی تصدیق ہو رہی ہے....",
    otp: "OTP",
    otpPlaceholder: "OTP درج کریں",
    enterOTP: "براہ کرم وہ OTP درج کریں جو آپ کو ({value}) پر موصول ہوا ہے۔",
    signedUp: "آپ نے کامیابی کے ساتھ سائن اپ کر لیا ہے!",
    failedToSignUp: "سائن اپ کرنے میں ناکام۔",
    loggedIn: "آپ کامیابی کے ساتھ لاگ ان ہو گئے ہیں!",
    failedToLogIn: "لاگ ان کرنے میں ناکام۔",
    resendOTP: "OTP دوبارہ بھیجیں",
    resendingOTP: "OTP دوبارہ بھیجا جا رہا ہے....",
    password: "پاس ورڈ",
    logingin: "لاگ ان ہو رہا ہے",
    passwordPlaceHolder: "اپنا پاس ورڈ درج کریں",
    otpChild1: "OTP غلط ہو سکتا ہے",
    otpChild2: "OTP کی میعاد ختم ہو سکتی ہے۔",
    otpChild3: "نیٹ ورک کا مسئلہ ہو سکتا ہے۔",
    otpChild4: "سرور ڈاؤن ہو سکتا ہے",
    passwordRequirementMsg: "اپنے اکاؤنٹ کی حفاظت کے لیے، کم از کم آٹھ (8) حروف کا پاس ورڈ بنائیں، جس میں شامل ہوں:",
    passwordRequireMent: "پاس ورڈ کی ضروریات",
    upperLowerCase: "بڑے اور چھوٹے حروف (Upper & Lower Case)",
    subHeadingIns: "مضبوط پاس ورڈ کے لیے، آپ کا پاس ورڈ درج ذیل نکات کے مطابق ہونا چاہیے",
    minimum8Char: "کم از کم 8 حروف (لازمی)",
    atLeastOneNumericals: "کم از کم ایک ہندسہ (لازمی)",
    numericals: "ہندسے",
    specialChar: "خصوصی حروف",
    oneUpperCase: "کم از کم ایک بڑا حرف (لازمی)",
    oneLowerCase: "کم از کم ایک چھوٹا حرف (لازمی)",
    partnerCompanyName: "پارٹنر کمپنی کا نام",
    atLeastOneSpecialChar: "کم از کم ایک خصوصی حرف (لازمی)",
    skip: "چھوڑیں",
    confirmPassword: "پاس ورڈ کی تصدیق کریں",
    setPassword: "پاس ورڈ سیٹ کریں",
    accountInstruction: "اکاؤنٹ تک رسائی اور آرڈرز کا انتظام کرنے کے لیے",
    aboutUs: "ہمارے بارے میں",
    contactUs: "رابطہ کریں",
    profile: "پروفائل",
    orders: "آرڈرز",
    wishlist: "پسندیدہ فہرست (Wishlist)",
    loginSignup: "لاگ ان/سائن اپ",
    welcome: "خوش آمدید",
    profileImgUpdated: "پروفائل تصویر کامیابی سے اپ ڈیٹ ہو گئی",
    save: "محفوظ کریں",
    cancel: "منسوخ کریں",
    adjustImage: "تصویر کو ایڈجسٹ کریں",
    dragSqrToChangeImgSizePos: "سائز اور پوزیشن تبدیل کرنے کے لیے مربع کو گھسیٹیں۔",
    preview: "پیش نظارہ",
    imageCropped: "کراپ شدہ تصویر کامیابی سے محفوظ ہو گئی!",
    alternateMobile: "متبادل موبائل نمبر",
    male: "مرد",
    female: "عورت",
    others: "دیگر",
    genderLabel: "براہ کرم اپنی جنس منتخب کریں:",
    dob: "تاریخ پیدائش",
    update: "اپ ڈیٹ کریں",
    changePassword: "پاس ورڈ تبدیل کریں",
    updatePassword: "پاس ورڈ اپ ڈیٹ کریں",
    updateProfile: "پروفائل اپ ڈیٹ کریں",
    oldPassword: "پرانا پاس ورڈ",
    confirmPasswordNotMatchPassword: "تصدیقی پاس ورڈ اصل پاس ورڈ سے مماثل نہیں ہے۔",
    passReqNotFulfil: "پاس ورڈ کی ضرورت پوری نہیں ہوئی۔",
    passwordUpdated: "پاس ورڈ کامیابی سے اپ ڈیٹ ہو گیا!",
    profileUpdated: "پروفائل کامیابی سے اپ ڈیٹ ہو گئی!",
    pageNotFound: "صفحہ نہیں ملا",
    brokenLinkMsg1: "آپ نے جس لنک پر کلک کیا وہ ٹوٹا ہوا ہو سکتا ہے یا صفحہ ہٹا دیا گیا ہے۔",
    brokenLinkMsg2: "ہوم پیج پر جائیں یا مسئلے کے بارے میں ہم سے رابطہ کریں۔",
    backToHome: "ہوم پیج پر واپس جائیں",
    dashboard: "ڈیش بورڈ",
    pages: "صفحات",
    inventory: "انوینٹری",
    customOrders: "کسٹم آرڈرز",
    team: "ٹیم",
    customers: "صارفین",
    settings: "سیٹنگز",
    messages: "پیغامات",
    pendingOrders: "زیر التواء آرڈرز",
    completedOrders: "مکمل شدہ آرڈرز",
    offers: "پیشکشیں (Offers)",
    id: "آئی ڈی",
    brand: "برانڈ",
    category: "زمرہ (Category)",
    price: "قیمت",
    status: "حیثیت (Status)",
    createdDate: "تخلیق کی تاریخ",
    updatedDate: "آخری بار اپ ڈیٹ کیا گیا",
    action: "عمل (Action)",
    productName: "پروڈکٹ کا نام",
    size: "سائز",
    color: "رنگ",
    stockQuantity: "مقدار",
    products: "مصنوعات",
    description: "تفصیل",
    parent: "پیرنٹ",
    namePlaceholder: "نام درج کریں",
    descriptionPlaceholder: "تفصیل درج کریں",
    categoryPlaceholder: "ایک زمرہ منتخب کریں",
    categoryLevel: "زمرہ {0} لیول ",
    at: "پر",
    modifiedOn: "تبدیل شدہ تاریخ",
    today: "آج",
    edit: "ترمیم کریں",
    delete: "حذف کریں",
    activated: "{entity} کو فعال کر دیا گیا ہے۔",
    deactivated: "{entity} کو غیر فعال کر دیا گیا ہے۔",
    yes: "ہاں",
    no: "نہیں",
    confirm: "تصدیق کریں",
    deleteMsg: "کیا آپ کو یقین ہے؟ آپ <b>{0}</b> {1} کو حذف کرنا چاہتے ہیں؟",
    childrenOf: "کے ذیلی (Children of) ",
    page: "صفحہ",
    add: "شامل کریں",
    deactivateFirst: "پہلے {entity} کو غیر فعال کریں۔",
    activeCantAction: "فعال {entity} پر {action} نہیں کیا جا سکتا۔",
    entityIsActive: "<b>{0}</b> {entity} فعال ہے۔",
    searchPlaceHolder: "{entity} تلاش کریں...",
    copy: "کاپی کریں",
    deleted: "حذف شدہ",
    edited: "ترمیم شدہ",
    product: "پروڈکٹ",
    title: "عنوان",
    titlePlaceholder: "عنوان درج کریں",
    image: "تصویر",
    material: "مواد (Material)",
    materialPlaceholder: "مواد درج کریں",
    colorPlaceholder: "رنگ درج کریں",
    sku: "SKU کوڈ",
    skuPlaceholder: "ایک منفرد SKU کوڈ درج کریں",
    quantity: "مقدار",
    type: "قسم",
    selectProductPlaceholder: "پروڈکٹ منتخب کریں",
    sizeChart: "سائز چارٹ",
    enterMeasure: "اپنی {0} پیمائش درج کریں",
    chest: "چھاتی",
    hips: "ہپس",
    neck: "گردن",
    sleeve: "آستین",
    arm: "بازو",
    topLength: "اوپری لمبائی",
    shoulder: "کندھا",
    inseam: "انسیئم (Inseam)",
    bottomLength: "نیچے کی لمبائی",
    thigh: "ران",
    waist: "کمر",
    topBody: "اوپری جسم",
    bottomBody: "نچلا جسم",
    rank: "رینک",
    sale: "فروخت",
    rental: "کرایہ",
    selectRankPlaceholder: "رینک منتخب کریں",
    mrp: "MRP",
    salePrice: "فروخت کی قیمت",
    discount: "رعایت",
    selectSizePlaceholder: "سائز منتخب کریں",
    mrpPlaceholder: "MRP درج کریں (₹)",
    salePricePlaceholder: "فروخت کی قیمت درج کریں (₹)",
    discountPlaceholder: "رعایت درج کریں (%)",
    quantityPlaceholder: "مقدار درج کریں",
    saleOrRentPrice: "فروخت/کرایہ کی قیمت",
    security: "سیکیورٹی ڈپازٹ",
    securityPlaceholder: "واپسی کے قابل = ڈپازٹ - (کرایہ کی قیمت - رعایت %)",
    size_Quant_Price: "سائز - مقدار - فروخت کی قیمت",
    view: "دیکھیں",
    webSettings: "ویب سیٹنگز",
    siteUnderMaintenance: "سائٹ کی دیکھ بھال جاری ہے",
    weWillGetbackShortly: "ہم جلد ہی واپس آئیں گے۔ براہ کرم کچھ دیر بعد دوبارہ چیک کریں۔",
    reload: "دوبارہ لوڈ کریں",
    enableWebsite: "ویب سائٹ کو فعال یا غیر فعال کرنے کے لیے کلک کریں۔",
    website: "ویب سائٹ",
    switchOnOffWebsite: "ویب سائٹ آن/آف کریں",
    webConfigs: "ویب سائٹ کنفیگریشنز",
    webTrendingBar: "ویب سائٹ ٹرینڈنگ بار",
    websiteId: "ویب سائٹ آئی ڈی",
    path: "پاتھ (Path)",
    pathPlaceholder: "کھولنے کے لیے پاتھ درج کریں",
    homePage: "ہوم پیج",
    homePageCarousel: "ہوم پیج کیروسل",
    forPC: "PC کے لیے:",
    forMobile: "موبائل کے لیے:",
    reset: "ری سیٹ کریں",
    customFitting: "کسٹم فٹنگ",
    customDesigning: "کسٹم ڈیزائننگ",
    freeDelivery: "مفت ڈیلیوری",
    assuredRefunds: "یقینی ریفنڈز",
    sizes: "سائز",
    addresses: "پتے",
    isTileVisible: "کیا ٹائل نظر آ رہی ہے؟",
    isTileVisibleGrid: "ٹائل نظر آ رہی ہے",
    categories: "زمرہ جات",
    mrpWithDots: "M.R.P",
    rtd: "بھیجنے کے لیے تیار (Ready to Dispatch)",
    inclusiveTax: "تمام ٹیکس سمیت قیمت",
    rentInclusiveTax: "تمام ٹیکس سمیت کرایہ",
    purchase: "خریدیں",
    rent: "کرایہ",
    refundableSecurity: "واپسی کے قابل سیکیورٹی ڈپازٹ",
    securityDeposit: "سیکیورٹی ڈپازٹ",
    refundSecurity: "آئٹم واپس کرنے کے بعد، آپ کی سیکیورٹی ڈپازٹ واپس کر دی جائے گی۔",
    securityDepositDeduction: "آپ ڈیلیوری کے 5 دن کے اندر آئٹم واپس کر سکتے ہیں۔ اس کے بعد ہر 5 دن کے لیے کرایے کی رقم آپ کی سیکیورٹی ڈپازٹ سے کاٹی جائے گی۔",
    sizeGuide: "سائز گائیڈ",
    customSize: "کسٹم سائز",
    loginToAddCustomSize: "کسٹم سائز شامل کرنے اور دیکھنے کے لیے لاگ ان/سائن اپ کریں",
    yourCustomSizes: "آپ کے کسٹم سائز",
    undoWishlistMsg: "آپ نے <b>{name}</b> کو خواہش کی فہرست سے ہٹا دیا ہے",
    undo: "واپس کریں (Undo)",
    textPlaceholder: "{0} درج کریں",
    address: "پتہ",
    fullName: "نام",
    city: "شہر",
    country: "ملک",
    pinCode: "پن کوڈ",
    state: "ریاست",
    landmark: "لینڈ مارک",
    streetAddress1: "فلیٹ، مکان نمبر، عمارت، کمپنی، اپارٹمنٹ",
    streetAddress2: "علاقہ، گلی، سیکٹر، گاؤں",
    defaultAddress: "بطور ڈیفالٹ پتہ سیٹ کریں",
    setDefault: "ڈیفالٹ سیٹ کریں",
    default: "ڈیفالٹ",
    addToCart: "کارٹ میں شامل کریں",
    buyNow: "ابھی خریدیں",
    total: "کل",
    clearCart: "کارٹ صاف کریں",
    proceedToCheckout: "چیک آؤٹ کے لیے آگے بڑھیں",
    shoppingCart: "شاپنگ کارٹ",
    loadingCart: "کارٹ لوڈ ہو رہا ہے...",
    emptyCart: "آپ کا کارٹ خالی ہے۔",
    emptyWishlist: "آپ کی خواہش کی فہرست خالی ہے۔",
    deSelectAll: "تمام آئٹمز کو غیر منتخب کریں",
    invalidCoupon: "غلط کوپن کوڈ",
    couponApplied: "کوپن لاگو ہوا: ",
    apply: "لاگو کریں",
    freeCaps: "مفت",
    deliveryCharges: "ڈیلیوری چارجز",
    subTotal: "سب ٹوٹل",
    changeSize: "سائز تبدیل کریں",
    moveToWishlist: "خواہش کی فہرست میں منتقل کریں",
    share: "شیئر کریں",
    orderSummary: "آرڈر کا خلاصہ",
    coupon: "کوپن",
    itemsForPurchasing: "خریداری کے لیے منتخب کردہ اشیاء",
    itemsForRenting: "کرائے کے لیے منتخب کردہ اشیاء",
    itemsSelected: "منتخب کردہ اشیاء",
    applyCoupon: "کوپن لاگو کریں",
    undoCartMsg: 'کارٹ سے <strong>{name}</strong> ہٹا دیا گیا۔ ',
    itemRestored: "آئٹم کارٹ میں بحال ہو گیا",
    selectAll: "سب منتخب کریں",
    itemMovedToWishlist: "آئٹم خواہش کی فہرست میں منتقل ہو گیا۔",
    itemRemoved: "آئٹم کارٹ سے ہٹا دیا گیا",
    addedToCart: "آئٹم کارٹ میں شامل کر دیا گیا",
    itemAddedToWishlist: "آئٹم خواہش کی فہرست میں شامل کر دیا گیا",
    itemRemovedFromWishlist: "آئٹم خواہش کی فہرست سے ہٹا دیا گیا",
    proceedToBuy: "خریداری کے لیے آگے بڑھیں",
    change: "تبدیل کریں",
    checkout: "چیک آؤٹ",
    deliverHere: "یہاں ڈیلیور کریں",
    selectDeliveryAddress: "ڈیلیوری کا پتہ منتخب کریں",
    selectedDeliveryAddress: "منتخب شدہ ڈیلیوری کا پتہ",
    inventoryType: "انوینٹری کی قسم",
    currentlyDefaultAddress: "ڈیفالٹ پتہ",
    chosenAddressUpdated: "منتخب پتہ کامیابی سے اپ ڈیٹ ہو گیا۔",
    draftUpdated: "آرڈر کی تفصیلات کامیابی سے اپ ڈیٹ ہو گئیں۔",
    deliveringTo: "ڈیلیوری برائے",
    addNew: "نیا شامل کریں",
    itemsInOrder: "آرڈر میں اشیاء",
    shipTogether: "تمام اشیاء ایک ساتھ بھیجیں",
    shipAsap: "ہر آئٹم تیار ہونے پر بھیجیں",
    shipItems: "آپ اپنا آرڈر کب بھیجنا چاہتے ہیں؟",
    shipItemsForOrder: "{user} آرڈر کب بھیجنا چاہتا ہے؟",
    orderPlacedTitle: "شکریہ، آپ کا آرڈر دے دیا گیا ہے!",
    orderConfirmationSent: "ایک تصدیق آپ کے ای میل پر بھیج دی گئی ہے۔",
    orderId: "آرڈر آئی ڈی",
    itemsInTheOrder: "آرڈر میں اشیاء",
    viewOrders: "اپنے آرڈرز دیکھیں",
    viewAllOrders: "تمام آرڈرز دیکھیں",
    continueShopping: "خریداری جاری رکھیں",
    orderDetails: "آرڈر کی تفصیلات",
    appliedCoupon: "لاگو کوپن",
    orderPlacedOn: "آرڈر کی تاریخ",
    shipTo: "بھیجیں برائے",
    noOrdersFound: "کوئی آرڈر نہیں ملا",
    yourOrders: "آپ کے آرڈرز",
    paymentMode: "ادائیگی کا طریقہ",
    paymentMethod: "ادائیگی کا طریقہ کار",
    all: "تمام",
    pending: "زیر التواء",
    shipped: "بھیج دیا گیا",
    delivered: "پہنچا دیا گیا",
    cancelled: "منسوخ شدہ",
    allOrders: "تمام آرڈرز",
    newOrders: "نئے آرڈرز",
    statusMessages: {
        forOrder: {
            forManager: {
                draft: "آرڈر ڈرافٹ حالت میں ہے اور ابھی تک پلیس نہیں کیا گیا ہے۔",
                pending: "ادائیگی زیر التواء ہے۔",
                placed: "آرڈر دیا گیا ہے اور آپ کی طرف سے تصدیق کا منتظر ہے۔",
                confirmed: "آپ نے آرڈر کی تصدیق کر دی ہے۔",
                payment_failed: "ادائیگی ناکام ہو گئی۔",
                in_process: "آرڈر آپ کے ذریعہ پروسیس کیا جا رہا ہے۔",
                ready_to_dispatch: "آرڈر ڈسپیچ کے لیے تیار ہے۔",
                shipped: "آرڈر بھیج دیا گیا ہے۔",
                in_transit: "آرڈر راستے میں ہے۔",
                delivered: "آرڈر پہنچا دیا گیا ہے۔",
                cancelled: "آرڈر منسوخ کر دیا گیا ہے۔",
                cancellation_requested: "صارف نے منسوخی کی درخواست کی ہے۔",
                cancellation_rejected: "آپ نے منسوخی کی درخواست مسترد کر دی ہے۔",
                cancellation_refunded: "آرڈر منسوخ کر دیا گیا اور ادائیگی واپس کر دی گئی۔",
                return_requested: "آرڈرز کے لیے واپسی کی درخواستیں۔",
                return_rejected: "آپ نے واپسی کی درخواست مسترد کر دی ہے۔",
                returned: "آرڈر واپس کر دیا گیا ہے۔",
                return_refunded: "واپسی کے بعد ادائیگی واپس کر دی گئی۔",
                refunded: "ادائیگی واپس کر دی گئی۔",
                rto_requested: "آپ کی طرف سے RTO کی درخواست کی گئی ہے۔",
                rto_rejected: "آپ نے RTO کی درخواست مسترد کر دی۔",
                rto_approved: "آپ نے RTO کی درخواست منظور کر لی۔",
                rto_in_progress: "RTO جاری ہے۔",
                rto_delivered: "آرڈر RTO کے ذریعے آپ کو واپس کر دیا گیا ہے۔",
                rto_verified: "RTO اشیاء کی آپ نے تصدیق کر لی ہے۔",
                rto_refunded: "RTO کے بعد کسٹمر کو ادائیگی واپس کر دی گئی۔"
            },
            forUser: {
                draft: "آپ کا آرڈر چیک آؤٹ میں ہے لیکن ابھی تک پلیس نہیں ہوا ہے۔",
                pending: "ادائیگی زیر التواء ہے۔ براہ کرم اپنی ادائیگی مکمل کریں۔",
                placed: "آپ کا آرڈر دے دیا گیا ہے اور تصدیق کا منتظر ہے۔",
                confirmed: "آپ کے آرڈر کی بیچنے والے نے تصدیق کر دی ہے۔",
                payment_failed: "ادائیگی ناکام ہو گئی۔ براہ کرم دوبارہ کوشش کریں۔",
                in_process: "آپ کا آرڈر بیچنے والے کے ذریعہ پروسیس کیا جا رہا ہے۔",
                ready_to_dispatch: "آپ کا آرڈر ڈسپیچ کے لیے تیار ہے۔",
                shipped: "آپ کا آرڈر بھیج دیا گیا ہے۔",
                in_transit: "آپ کا آرڈر راستے میں ہے۔",
                delivered: "آپ کا آرڈر پہنچا دیا گیا ہے۔",
                cancelled: "آپ کا آرڈر منسوخ کر دیا گیا ہے۔",
                cancellation_requested: "آپ نے اس آرڈر کو منسوخ کرنے کی درخواست کی ہے۔",
                cancellation_rejected: "آپ کی منسوخی کی درخواست مسترد کر دی گئی ہے۔",
                cancellation_refunded: "آپ کی منسوخی قبول کر لی گئی ہے اور ادائیگی واپس کر دی گئی ہے۔",
                return_requested: "آپ کے آرڈر کے لیے واپسی کی درخواست جمع کر دی گئی ہے۔",
                return_rejected: "آپ کی واپسی کی درخواست مسترد کر دی گئی ہے۔",
                returned: "آپ کا آرڈر واپس کر دیا گیا ہے۔",
                return_refunded: "واپسی کے بعد آپ کی ادائیگی واپس کر دی گئی ہے۔",
                refunded: "آپ کی ادائیگی واپس کر دی گئی ہے۔",
                rto_requested: "آپ/بیچنے والے نے آرڈر کے لیے RTO کی درخواست کی ہے۔",
                rto_rejected: "بیچنے والے نے RTO کی درخواست مسترد کر دی۔",
                rto_approved: "بیچنے والے نے اس آرڈر کے لیے RTO منظور کر لیا ہے۔",
                rto_in_progress: "آپ کا آرڈر RTO کے راستے پر ہے۔",
                rto_delivered: "آپ کا آرڈر RTO کے ذریعے بیچنے والے کو واپس کر دیا گیا ہے۔",
                rto_verified: "آپ کا واپس کردہ آرڈر بیچنے والے نے تصدیق کر لیا ہے۔",
                rto_refunded: "RTO کے بعد آپ کو رقم واپس کر دی گئی ہے۔"
            }
        },
        forItem: {
            forManager: {
                draft: "آئٹم آرڈر ڈرافٹ میں شامل کر دیا گیا ہے اور ابھی تک پلیس نہیں ہوا ہے۔",
                pending: "اس آئٹم کی ادائیگی زیر التواء ہے۔",
                placed: "آئٹم پلیس کر دیا گیا ہے اور آپ کی طرف سے تصدیق کا منتظر ہے۔",
                confirmed: "آپ نے اس آئٹم کی تصدیق کر دی ہے۔",
                payment_failed: "اس آئٹم کی ادائیگی ناکام ہو گئی۔",
                in_process: "آئٹم آپ کے ذریعہ پروسیس کیا جا رہا ہے۔",
                ready_to_dispatch: "آئٹم ڈسپیچ کے لیے تیار ہے۔",
                shipped: "آئٹم بھیج دیا گیا ہے۔",
                in_transit: "آئٹم راستے میں ہے۔",
                delivered: "آئٹم پہنچا دیا گیا ہے۔",
                cancelled: "یہ آئٹم منسوخ کر دیا گیا ہے۔",
                cancellation_requested: "صارف نے اس آئٹم کے لیے منسوخی کی درخواست کی ہے۔",
                cancellation_rejected: "آپ نے اس آئٹم کے لیے منسوخی کی درخواست مسترد کر دی۔",
                cancellation_refunded: "یہ آئٹم منسوخ کر دیا گیا ہے اور ادائیگی واپس کر دی گئی ہے۔",
                return_requested: "صارف نے اس آئٹم کے لیے واپسی کی درخواست کی ہے۔",
                return_rejected: "آپ نے اس آئٹم کے لیے واپسی کی درخواست مسترد کر دی۔",
                returned: "آئٹم واپس کر دیا گیا ہے۔",
                return_refunded: "اس واپس کردہ آئٹم کے لیے ادائیگی واپس کر دی گئی ہے۔",
                refunded: "اس آئٹم کے لیے ادائیگی واپس کر دی گئی ہے۔",
                rto_requested: "اس آئٹم کے لیے RTO کی درخواست کی گئی ہے۔",
                rto_rejected: "آپ نے اس آئٹم کے لیے RTO کی درخواست مسترد کر دی۔",
                rto_approved: "آپ نے اس آئٹم کے لیے RTO کی درخواست منظور کر لی۔",
                rto_in_progress: "اس آئٹم کے لیے RTO جاری ہے۔",
                rto_delivered: "یہ آئٹم آپ کو واپس کر دیا گیا ہے۔",
                rto_verified: "اس اصل پر واپس کردہ آئٹم کی تصدیق کر لی گئی ہے۔",
                rto_refunded: "RTO کے بعد اس آئٹم کے لیے ادائیگی واپس کر دی گئی ہے۔"
            },
            forUser: {
                draft: "یہ آئٹم چیک آؤٹ میں ہے لیکن ابھی تک پلیس نہیں ہوا ہے۔",
                pending: "اس آئٹم کی ادائیگی زیر التواء ہے۔ براہ کرم اپنی ادائیگی مکمل کریں۔",
                placed: "یہ آئٹم پلیس کر دیا گیا ہے اور تصدیق کا منتظر ہے۔",
                confirmed: "اس آئٹم کی بیچنے والے نے تصدیق کر دی ہے۔",
                payment_failed: "اس آئٹم کی ادائیگی ناکام ہو گئی۔ براہ کرم دوبارہ کوشش کریں۔",
                in_process: "یہ آئٹم بیچنے والے کے ذریعہ پروسیس کیا جا رہا ہے۔",
                ready_to_dispatch: "یہ آئٹم ڈسپیچ کے لیے تیار ہے۔",
                shipped: "یہ آئٹم بھیج دیا گیا ہے۔",
                in_transit: "یہ آئٹم راستے میں ہے۔",
                delivered: "یہ آئٹم پہنچا دیا گیا ہے۔",
                cancelled: "یہ آئٹم منسوخ کر دیا گیا ہے۔",
                cancellation_requested: "آپ نے اس آئٹم کو منسوخ کرنے کی درخواست کی ہے۔",
                cancellation_rejected: "اس آئٹم کے لیے آپ کی منسوخی کی درخواست مسترد کر دی گئی ہے۔",
                cancellation_refunded: "اس آئٹم کے لیے آپ کی منسوخی قبول کر لی گئی ہے اور ادائیگی واپس کر دی گئی ہے۔",
                return_requested: "اس آئٹم کے لیے واپسی کی درخواست جمع کر دی گئی ہے۔",
                return_rejected: "اس آئٹم کے لیے آپ کی واپسی کی درخواست مسترد کر دی گئی ہے۔",
                returned: "یہ آئٹم واپس کر دیا گیا ہے۔",
                return_refunded: "یہ آئٹم واپس کرنے کے بعد آپ کی ادائیگی واپس کر دی گئی ہے۔",
                refunded: "اس آئٹم کے لیے آپ کی ادائیگی واپس کر دی گئی ہے۔",
                rto_requested: "آپ/بیچنے والے نے اس آئٹم کے لیے RTO کی درخواست کی ہے۔",
                rto_rejected: "بیچنے والے نے اس آئٹم کے لیے RTO کی درخواست مسترد کر دی۔",
                rto_approved: "بیچنے والے نے اس آئٹم کے لیے RTO منظور کر لیا ہے۔",
                rto_in_progress: "یہ آئٹم RTO ہو رہا ہے۔",
                rto_delivered: "یہ آئٹم بیچنے والے کو واپس کر دیا گیا ہے۔",
                rto_verified: "یہ آئٹم واپس آنے کے بعد بیچنے والے نے تصدیق کر لیا ہے۔",
                rto_refunded: "RTO کے بعد اس آئٹم کے لیے آپ کی ادائیگی واپس کر دی گئی ہے۔"
            }
        }
    },
    statusColors: {
        draft: "var(--secondarytext-color)",
        pending: "var(--warning-color)",
        placed: "var(--info-color)",
        confirmed: "var(--success-color)",
        payment_failed: "var(--danger-color)",
        in_process: "var(--infolight-color)",
        ready_to_dispatch: "purple",
        shipped: "blue",
        in_transit: "var(--primarylight-color)",
        delivered: "var(--successdark-color)",
        cancellation_requested: "orange",
        cancelled: "var(--dangerlight-color)",
        cancellation_rejected: "red",
        cancellation_refunded: "var(--success-color)",
        return_requested: "var(--secondary-color)",
        returned: "var(--dangerlight-color)",
        return_rejected: "var(--warning-color)",
        return_refunded: "var(--success-color)",
        refunded: "var(--success-color)",
        rto_requested: "var(--warningdark-color)",
        rto_rejected: "red",
        rto_approved: "var(--success-color)",
        rto_in_progress: "blueviolet",
        rto_delivered: "var(--info-color)",
        rto_verified: "var(--successdark-color)",
        rto_refunded: "var(--success-color)"
    },
    orderPages: {
        allOrders: {
            title: "تمام آرڈرز",
            statuses: ["ALL"]
        },
        pendingOrders: {
            title: "زیر التواء آرڈرز",
            statuses: ["PENDING"]
        },
        newOrders: {
            title: "نئے آرڈرز",
            statuses: ["PLACED"]
        },
        confirmedOrders: {
            title: "تصدیق شدہ آرڈرز",
            statuses: ["CONFIRMED"]
        },
        processingOrders: {
            title: "پروسیسنگ آرڈرز",
            statuses: ["IN_PROCESS"]
        },
        readyToDispatchOrders: {
            title: "ڈسپیچ کے لیے تیار آرڈرز",
            statuses: ["READY_TO_DISPATCH"]
        },
        onTheWayOrders: {
            title: "راستے میں موجود آرڈرز",
            statuses: ["SHIPPED", "IN_TRANSIT"]
        },
        deliveredOrders: {
            title: "ڈیلیور شدہ آرڈرز",
            statuses: ["DELIVERED"]
        },
        cancelled: {
            title: "منسوخ شدہ آرڈرز",
            statuses: ["CANCELLED"]
        },
        returns: {
            title: "واپسی (Returns)",
            statuses: ["ALLRETURNS"],
            showOrderStatuses: false
        },
        cancellation_requested: {
            title: "منسوخی کی درخواست کردہ آرڈرز",
            statuses: ["CANCELLATION_REQUESTED"]
        },
        cancellation_rejected: {
            title: "منسوخی مسترد شدہ آرڈرز",
            statuses: ["CANCELLATION_REJECTED"]
        },
        cancellation_refunded: {
            title: "منسوخی ریفنڈ شدہ آرڈرز",
            statuses: ["CANCELLATION_REFUNDED"]
        },
        return_requested: {
            title: "واپسی کی درخواست کردہ آرڈرز",
            statuses: ["RETURN_REQUESTED"]
        },
        returned: {
            title: "واپس کردہ آرڈرز",
            statuses: ["RETURNED"]
        },
        return_rejected: {
            title: "واپسی مسترد شدہ آرڈرز",
            statuses: ["RETURN_REJECTED"]
        },
        return_refunded: {
            title: "واپسی ریفنڈ شدہ آرڈرز",
            statuses: ["RETURN_REFUNDED"]
        },
        rto_requested: {
            title: "RTO درخواست کردہ آرڈرز",
            statuses: ["RTO_REQUESTED"]
        },
        rto_rejected: {
            title: "RTO مسترد شدہ آرڈرز",
            statuses: ["RTO_REJECTED"]
        },
        rto_approved: {
            title: "RTO منظور شدہ آرڈرز",
            statuses: ["RTO_APPROVED"]
        },
        rto_in_progress: {
            title: "RTO جاری آرڈرز",
            statuses: ["RTO_IN_PROGRESS"]
        },
        rto_delivered: {
            title: "RTO ڈیلیور شدہ آرڈرز",
            statuses: ["RTO_DELIVERED"]
        },
        rto_verified: {
            title: "RTO تصدیق شدہ آرڈرز",
            statuses: ["RTO_VERIFIED"]
        },
        rto_refunded: {
            title: "RTO ریفنڈ شدہ آرڈرز",
            statuses: ["RTO_REFUNDED"]
        }
    },
    confirmedOrders: "تصدیق شدہ آرڈرز",
    processingOrders: "پروسیسنگ آرڈرز",
    readyToDispatchOrders: "ڈسپیچ کے لیے تیار آرڈرز",
    onTheWayOrders: "راستے میں موجود آرڈرز",
    deliveredOrders: "ڈیلیور شدہ آرڈرز",
    cancelled_orders: "منسوخ شدہ آرڈرز",
    cancellation_requested_orders: "منسوخی کی درخواست کردہ آرڈرز",
    return_requested_orders: "واپسی کی درخواست کردہ آرڈرز",
    return_refunded_orders: "واپسی ریفنڈ شدہ آرڈرز",
    returns: "واپسی (Returns)",
    returned_orders: "واپس کردہ آرڈرز",
    return_rejected_orders: "واپسی مسترد شدہ آرڈرز",
    cancellation_rejected_orders: "منسوخی مسترد شدہ آرڈرز",
    cancellation_refunded_orders: "منسوخی ریفنڈ شدہ آرڈرز",
    rto_requested_orders: "RTO درخواست کردہ آرڈرز",
    rto_rejected_orders: "RTO مسترد شدہ آرڈرز",
    rto_approved_orders: "RTO منظور شدہ آرڈرز",
    rto_in_progress_orders: "RTO جاری آرڈرز",
    rto_delivered_orders: "RTO ڈیلیور شدہ آرڈرز",
    rto_verified_orders: "RTO تصدیق شدہ آرڈرز",
    rto_refunded_orders: "RTO ریفنڈ شدہ آرڈرز",
    moreOptions: "مزید اختیارات",
    details: "تفصیلات",
    viewProductPage: "پروڈکٹ کا صفحہ دیکھیں",
    viewSize: "سائز دیکھیں",
    trackStatus: "اسٹیٹس ٹریک کریں",
    auditTrail: "آڈٹ ٹریل (Audit Trail)",
    changedFrom: "سے تبدیل ہوا",
    changedTo: "میں تبدیل ہوا",
    entityType: "اینٹیٹی کی قسم",
    entityId: "اینٹیٹی آئی ڈی",
    performedBy: "کس نے کیا",
    timestamp: "ٹائم اسٹیمپ",
    trackingDetails: "ٹریکنگ کی تفصیلات",
    noDetailsFound: "کوئی تفصیلات نہیں ملیں",
    userDetails: 'صارف کی تفصیلات',
    followUs: "ہمیں فالو کریں",
    allRightsReserved: "جملہ حقوق محفوظ ہیں",
    fastAndSecured: "تیز اور محفوظ ادائیگی کے اختیارات",
    company: "کمپنی",
    myAccount: "میرا اکاؤنٹ",
    home: "ہوم",
    account: "اکاؤنٹ",
    search: "تلاش کریں",
    cart: "کارٹ",
    language: "زبان",
    somethingWentWrong: "کچھ غلط ہو گیا!",
    note: "نوٹ",
    notAllowed1: "آپ کو اس ایپلیکیشن میں لاگ ان کرنے کی اجازت نہیں ہے",
    notAllowed2: "صرف ایڈمن اور مینیجر کو اس تک رسائی حاصل ہے",
    notAllowed3: "اگر آپ ان میں سے ایک ہیں اور پھر بھی رسائی حاصل نہیں کر پا رہے ہیں تو ایڈمن سے رابطہ کریں",
    logOutAndBackToHome: "لاگ آؤٹ کریں اور ہوم پر واپس جائیں",
    whatsAppUs: "ہمیں واٹس ایپ کریں",
    ourContactDetails: "ہماری رابطہ کی تفصیلات",
    workingHours: "کام کے اوقات",
    instagram: "انسٹاگرام",
    facebook: "فیس بک",
    x: "ایکس (ٹویٹر)",
    threads: "تھریڈز",
    youtube: "یوٹیوب",
    pinterest: "پنٹرسٹ",
    quotaUsage: "میل/ایس ایم ایس کوٹہ کا استعمال",
    used: "استعمال شدہ",
    remaining: "باقی",
    totalQuota: "کل کوٹہ",
    sms: "ایس ایم ایس",
    whatsapp: "واٹس ایپ",
    brevo: "بریوو (Brevo)",
    count: "تعداد",
    date: "تاریخ",
    gmail: "جی میل",
    quota: "کوٹہ",
    teamUsers: "ٹیم",
    member: "رکن",
    customer: "کسٹمر",
    profileImage: "پروفائل تصویر",
    gender: "جنس",
    role: "کردار (Role)",
    activatedText: "فعال",
    selectRolePlaceholder: "کردار منتخب کریں",
    accountActiveLabel: "براہ کرم منتخب کریں کہ آیا صارف کا اکاؤنٹ فعال/غیر فعال ہونا چاہیے:",
    user: "صارف",
    actions: "افعال (Actions)",
    setAsDiscontinued: "بند (Discontinued) کے طور پر سیٹ کریں",
    resetToDefaultPassword: "ڈیفالٹ پاس ورڈ پر ری سیٹ کریں",
    confirmMsg: "کیا آپ کو یقین ہے؟ آپ <b>{0}</b> {1} کو {2} کرنا چاہتے ہیں؟",
    discontinued: "بند کر دیا گیا (Discontinued)",
    base: "بیس (Base)",
    setActive: "فعال سیٹ کریں",
    refresh: "ریفریش",
    about: "تعارف",
    resume: "ریزیومے",
    portfolio: "پورٹ فولیو",
    services: "خدمات",
    contact: "رابطہ",
    contactMe: "مجھ سے رابطہ کریں",
    birthday: "سالگرہ",
    age: "عمر",
    degree: "ڈگری",
    freelance: "فری لانس",
    available: "دستیاب",
    education: "تعلیم",
    projects: "پروجیکٹس",
    languages: "زبانیں",
    accountInstruction1: "اپنی تفصیلات منظم کریں",
    aboutDesc: "میرے بارے میں مزید جانیں",
    resumeDesc: "میرے پیشہ ورانہ تجربے اور تعلیم کی ٹائم لائن:",
    summary: "خلاصہ",
    professionalExperience: "پیشہ ورانہ تجربہ",
    servicesDesc: "میں جو تکنیکی خدمات فراہم کرتا ہوں:",
    skillsDesc: "میری تکنیکی مہارتیں:",
    portfolioDesc: "میرے حالیہ پروجیکٹس کی نمائش:",
    app: "ایپ",
    web: "ویب",
    branding: "برانڈنگ",
    books: "کتابیں",
    contactDesc: "تعاون یا مواقع کے لیے رابطہ کریں",
    callUs: "ہمیں کال کریں",
    emailUs: "ہمیں ای میل کریں",
    yourName: "آپ کا نام",
    yourEmail: "آپ کا ای میل",
    subject: "موضوع",
    message: "پیغام",
    sendMessage: "پیغام بھیجیں",
    messageSent: "آپ کا پیغام بھیج دیا گیا ہے۔ شکریہ!",
    dobShort: "تاریخ پیدائش",
    toolsTitle: "میرے استعمال کردہ ٹولز اور ٹیکنالوجیز",
    iM: "میں ہوں",
    viewDetails: "تفصیلات دیکھیں",
    zoom: "زوم",
    sendingMessage: "پیغام بھیجا جا رہا ہے...",
    messageFailed: "پیغام بھیجنے میں ناکامی۔ براہ کرم بعد میں دوبارہ کوشش کریں۔",
    networkError: "نیٹ ورک کی خرابی پیش آئی ہے۔ براہ کرم اپنا کنکشن چیک کریں۔",
    sending: "بھیجا جا رہا ہے..."
  
};

export default ur;